/**
 * NOTYA-ULKE-KLINIK-01 — Uzbekistan: the CLINIC ACCOUNTS catalogue, in the three forms of the application:
 *
 *   uz-Latn   Uzbek, Latin script       uz-Cyrl   Uzbek, Cyrillic script       ru   Russian
 *
 *   kabuk      the links in the navigation            konum     the name of each position
 *   yetkiTuru  the name of each permission            yetkiAciklama   what it lets the member do
 *   giris      create a clinic, or join with a code   klinik    members, positions, removing, leaving
 *   davet      invitations                            takvim    the clinic's schedule
 *   yetki      "who can help with my patients"        kayit     the record of what was done
 *   paylasilan what was shared with the account       onBuro    the front-desk workspace
 *
 * ────────────────────────────────────────────────────────────────────────────────────────────────────────────
 * MACHINE-WRITTEN. AWAITS NATIVE REVIEW. Nobody who speaks Uzbek or Russian as a first language has read this
 * text yet (docs/COUNTRY-PACK-UZBEKISTAN.md, "Clinic accounts"; checklist E11, J3).
 * THE UZBEK CYRILLIC FORM IS NOT WRITTEN HERE: it is DERIVED FROM THE LATIN TEXT BY RULE (scripts/uz-kiril.mjs) and
 * stored in ./klinikMetinleriKiril.ts. To change a sentence, change the Latin text here and make the Cyrillic file
 * again; countries/uz/uygulama/araclar/kiril.test.ts holds the two together.
 * THE NAMES OF THE POSITIONS ("Klinika egasi", "Registrator" …) are everyday words chosen by a machine, not the
 * official names of posts in Uzbekistan: the local clinical lead confirms them (checklist J3).
 * ────────────────────────────────────────────────────────────────────────────────────────────────────────────
 *
 * `yetkiAciklama['on-buro-portal']` SAYS PLAINLY that the member will see the patient's link and PIN: whoever hands
 * them to a patient has seen them. The doctor reads it before giving that permission.
 *
 * The shape is the kit's type (KlinikMetni), so a missing key in any form is a type error and fails the build.
 * Written fresh for Uzbekistan — there is no Turkish source. Uzbek Latin uses U+02BB (ʻ) in oʻ / gʻ and U+02BC (ʼ)
 * for the tutuq belgisi. PLACEHOLDERS: '%' one value; '%1' and '%2' two (each key of the type says which).
 */
import type { KlinikMetni } from '@/lib/ulke/arayuz/metinTipleri'
import type { UzUygulamaDili } from './metinler'
import { UZ_KLINIK_KIRIL } from './klinikMetinleriKiril'

export const UZ_KLINIK_LATN: KlinikMetni = {
  kabuk: { klinik: 'Klinika', onBuro: 'Qabulxona' },
  konum: { sahip: 'Klinika egasi', yonetici: 'Administrator', hekim: 'Shifokor', muttefik: 'Klinika mutaxassisi', 'on-buro': 'Registrator' },
  yetkiTuru: {
    'on-buro-randevu': 'Qabullarni yuritish',
    'on-buro-hasta': 'Bemor qoʻshish',
    'on-buro-portal': 'Bemor sahifasi havolasini berish',
    paylasim: 'Bir bemorning qaydlarini ulashish',
    vekalet: 'Oʻrinbosarlik',
  },
  yetkiAciklama: {
    'on-buro-randevu': 'Registrator sizning qabullaringizni koʻradi va yuritadi: qabulga yozadi, vaqtini oʻzgartiradi, «keldi», «kelmadi» yoki «bekor qilindi» deb belgilaydi. Bemorni ismi yoki telefoni boʻyicha topadi va faqat ismini, tugʻilgan sanasini va telefonini koʻradi. Qaydlar, koʻrik yozuvlari, soʻrovnoma javoblari va qabul sababi unga koʻrsatilmaydi.',
    'on-buro-hasta': 'Registrator sizning nomingizga yangi bemor qoʻshadi: ismi, tugʻilgan sanasi, jinsi, telefoni va tili. Bemor sizniki boʻladi. Shaxsiy raqam bu yerda kiritilmaydi.',
    'on-buro-portal': 'Registrator bemorga sahifa havolasi va PIN-kodni beradi hamda soʻrovnomani toʻldirishni soʻraydi. DIQQAT: havola va PIN-kodni bemorga bergan kishi ularni oʻzi ham koʻradi, yaʼni registrator ular bilan bemor sahifasini ocha oladi. Har bir berilgan havola kim tomonidan berilgani bilan qayd etiladi, bemor sahifasiga har bir kirish esa bemor kartasida koʻrinadi.',
    paylasim: 'Tanlangan klinika mutaxassisi faqat shu bir bemorning tasdiqlangan qaydlarini oʻqiydi. Hech narsani oʻzgartira olmaydi; qoralamalar, koʻrik yozuvi va bemorning telefoni unga koʻrsatilmaydi.',
    vekalet: 'Tanlangan shifokor koʻrsatilgan muddat davomida bemorlaringizni ismi boʻyicha topadi, ularning tasdiqlangan qaydlarini va sizning qabullaringizni oʻqiydi. Hech narsani oʻzgartira olmaydi va sizning bemoringizga koʻrik yoza olmaydi. Muddat tugagach, ruxsat oʻzi toʻxtaydi.',
  },
  giris: {
    baslik: 'Klinika',
    aciklama: 'Siz hali hech bir klinikada emassiz. Taklif kodi bilan klinikaga qoʻshiling yoki oʻz klinikangizni yarating. Bir hisob faqat bitta klinikada boʻla oladi.',
    kurBaslik: 'Klinika yaratish',
    kurAciklama: 'Klinikani yaratgan hisob uning egasi boʻladi va boshqalarni taklif kodi bilan chaqiradi.',
    ad: 'Klinika nomi',
    kur: 'Klinikani yaratish',
    katilBaslik: 'Taklif kodi bilan klinikaga qoʻshilish',
    katilAciklama: 'Kodni klinika egasi yoki administratori beradi. Kod bir marta ishlaydi.',
    kod: 'Taklif kodi',
    katil: 'Qoʻshilish',
    bekliyor: 'Kuting…',
    adGerekli: 'Klinika nomini kiriting.',
    kodGecersiz: 'Kod notoʻgʻri, ishlatilgan yoki muddati oʻtgan.',
    zatenUye: 'Siz allaqachon klinika aʼzosisiz.',
    yapilamadi: 'Bajarib boʻlmadi. Qayta urinib koʻring.',
  },
  klinik: {
    konumunuz: 'Sizning lavozimingiz: %',
    konumAciklama: 'Lavozim hech bir bemorni ochmaydi. Boshqa shifokorning bemoriga faqat oʻsha shifokor bergan ruxsat orqali kiriladi, va har bir kirish qayd etiladi.',
    uyeler: 'Aʼzolar',
    siz: '(siz)',
    rolYok: 'Yoʻnalish tanlanmagan',
    konumDegistir: 'Lavozim',
    konumUyari: 'Lavozim oʻzgartirilsa, oʻsha aʼzoga berilgan va u bergan barcha ruxsatlar darhol toʻxtaydi.',
    cikar: 'Klinikadan chiqarish',
    cikarOnay: '% klinikadan chiqarilsinmi? Unga berilgan va u bergan barcha ruxsatlar darhol toʻxtaydi.',
    ayril: 'Klinikadan chiqish',
    ayrilOnay: 'Klinikadan chiqasizmi? Sizga berilgan va siz bergan barcha ruxsatlar darhol toʻxtaydi. Bemorlaringiz oʻzingizda qoladi.',
    evet: 'Ha',
    vazgec: 'Bekor qilish',
    degistirildi: 'Lavozim oʻzgartirildi.',
    cikarildi: 'Bajarildi.',
    yetkiYok: 'Bu amalni bajarishga ruxsatingiz yoʻq.',
    yapilamadi: 'Bajarib boʻlmadi. Qayta urinib koʻring.',
    yetkilerBaglanti: 'Bemorlarimga kim yordam beradi',
    paylasilanBaglanti: 'Menga ulashilganlar',
    onBuroBaglanti: 'Qabulxona ish joyi',
    geri: 'Klinikaga qaytish',
  },
  davet: {
    baslik: 'Takliflar',
    aciklama: 'Taklif kodi bir marta ishlaydi va muddati oʻtgach oʻzi toʻxtaydi. Kodni olgan kishi tizimga kirib, «Klinika» boʻlimida uni kiritadi.',
    konum: 'Lavozim',
    olustur: 'Taklif kodini yaratish',
    birKez: 'Kod faqat hozir koʻrsatiladi. Nusxalab oling: qayta koʻrsatib boʻlmaydi.',
    kod: 'Taklif kodi',
    kopyala: 'Nusxalash',
    kopyalandi: 'Nusxalandi.',
    kopyalanamadi: 'Nusxalab boʻlmadi.',
    sonGecerlilik: '% gacha amal qiladi',
    liste: 'Berilgan takliflar',
    listeBos: 'Hozircha takliflar yoʻq.',
    durum: { acik: 'Kutilmoqda', kullanildi: 'Ishlatilgan', iptal: 'Bekor qilingan', 'suresi-doldu': 'Muddati oʻtgan' },
    geriAl: 'Bekor qilish',
    geriAlindi: 'Taklif bekor qilindi.',
    yetkiYok: 'Bu lavozimga taklif berishga ruxsatingiz yoʻq.',
    yapilamadi: 'Bajarib boʻlmadi. Qayta urinib koʻring.',
  },
  takvim: {
    baslik: 'Klinika jadvali',
    aciklama: 'Kim qachon band ekani koʻrinadi. Bemorning ismi, qabul sababi va boshqa hech qanday maʼlumoti bu yerda koʻrsatilmaydi.',
    bos: 'Bu kunda qabullar yoʻq.',
  },
  yetki: {
    baslik: 'Bemorlarimga kim yordam beradi',
    aciklama: 'Bemorlaringiz faqat sizniki. Klinika aʼzosiga har bir ruxsatni alohida berasiz va istalgan paytda qaytarib olasiz: qaytarib olingan ruxsat shu zahoti ishlamaydi.',
    verilen: 'Men bergan ruxsatlar',
    verilenBos: 'Siz hali hech kimga ruxsat bermagansiz.',
    ver: 'Ruxsat berish',
    uye: 'Klinika aʼzosi',
    uyeSec: 'Aʼzoni tanlang',
    uyeYok: 'Klinikada ruxsat berish mumkin boʻlgan aʼzo hozircha yoʻq.',
    tur: 'Ruxsat',
    turSec: 'Ruxsatni tanlang',
    hasta: 'Bemor',
    hastaAra: 'Qidirish',
    hastaSec: 'Bemorni tanlang',
    hastaYok: 'Bemor topilmadi.',
    bitisGun: 'Oʻrinbosarlikning oxirgi kuni',
    bitisIpucu: 'Koʻpi bilan % kun.',
    gonder: 'Ruxsat berish',
    bekliyor: 'Kuting…',
    verildi: 'Ruxsat berildi.',
    zatenVar: 'Bu ruxsat allaqachon berilgan.',
    geriAl: 'Qaytarib olish',
    geriAlindi: 'Ruxsat toʻxtatildi.',
    durumGecerli: 'Amalda',
    durumBitti: 'Toʻxtagan',
    donem: '%1 – %2',
    hastaIcin: 'Bemor: %',
    hataKonum: 'Bu ruxsat bunday lavozimdagi aʼzoga berilmaydi.',
    hataRol: 'Bu aʼzoning yoʻnalishi bunday ruxsatni olishga mos emas.',
    hataTur: 'Bu ruxsat hozircha yoqilmagan.',
    hataGecersiz: 'Maʼlumotlarni tekshiring: kun bugundan oldin boʻlmasligi va ruxsat etilgan muddatdan oshmasligi kerak.',
    hataBulunamadi: 'Aʼzo yoki bemor topilmadi.',
    yapilamadi: 'Bajarib boʻlmadi. Qayta urinib koʻring.',
    alinan: 'Menga berilgan ruxsatlar',
    alinanBos: 'Sizga hozircha ruxsat berilmagan.',
    hekimden: 'Shifokor: %',
    birak: 'Voz kechish',
  },
  kayit: {
    baslik: 'Qaydnoma',
    aciklama: 'Bemorlaringiz boʻyicha ruxsat orqali qilingan har bir ish shu yerda: kim, nima qildi, qaysi bemor, qachon. Bu roʻyxatni faqat siz koʻrasiz.',
    bos: 'Hozircha yozuvlar yoʻq.',
    olay: { verildi: 'ruxsat berildi: %1 — %2', 'geri-alindi': 'ruxsat toʻxtatildi: %1 — %2', bitti: 'ruxsat tugadi: %1 — %2' },
    ne: {
      'randevu-listesi': 'qabullar roʻyxatini koʻrdi',
      'hasta-arama': 'bemor qidirdi',
      'hasta-karti': 'bemor kartasini koʻrdi',
      'hasta-olusturma': 'bemor qoʻshdi',
      'randevu-olusturma': 'qabulga yozdi',
      'randevu-degisiklik': 'qabulni oʻzgartirdi',
      'portal-baglantisi': 'bemor sahifasi havolasi va PIN-kodni berdi',
      'form-istegi': 'soʻrovnomani toʻldirishni soʻradi',
      'not-listesi': 'tasdiqlangan qaydlarni oʻqidi',
    },
    hasta: 'Bemor: %',
  },
  paylasilan: {
    baslik: 'Menga ulashilganlar',
    aciklama: 'Shifokor siz bilan ulashgan bemorlar va siz oʻrinbosarlik qilayotgan shifokorlar. Har bir ochish oʻsha shifokorning qaydnomasiga yoziladi.',
    bos: 'Sizga hozircha hech narsa ulashilmagan.',
    hekim: 'Shifokor: %',
    bitis: '% gacha',
    ac: 'Ochish',
    saltOkunur: 'Faqat oʻqish uchun. Bu yerda faqat tasdiqlangan qaydlar koʻrsatiladi; hech narsani oʻzgartirib boʻlmaydi.',
    notlar: 'Tasdiqlangan qaydlar',
    notYok: 'Tasdiqlangan qaydlar yoʻq.',
    notTarihi: 'Koʻrik: %1 · tasdiqlangan: %2',
    dogum: 'Tugʻilgan sana: %',
    hastaAra: 'Bemorni ismi boʻyicha qidirish',
    ara: 'Qidirish',
    aramaKisa: 'Kamida ikkita belgi kiriting.',
    sonucYok: 'Hech narsa topilmadi.',
    randevular: 'Shifokorning qabullari',
    randevuYok: 'Bu kunda qabullar yoʻq.',
    okunamadi: 'Ochib boʻlmadi: ruxsat toʻxtatilgan yoki muddati tugagan boʻlishi mumkin.',
    geri: 'Roʻyxatga qaytish',
  },
  onBuro: {
    baslik: 'Qabulxona',
    aciklama: 'Sizga ruxsat bergan shifokorlar uchun qabullarni yuritasiz. Har bir shifokor nimaga ruxsat berganini oʻzi belgilaydi.',
    hekimYok: 'Hozircha hech bir shifokor sizga ruxsat bermagan. Shifokor «Klinika» boʻlimida ruxsat bergach, uning qabullari shu yerda koʻrinadi.',
    hekim: 'Shifokor',
    gordugunuz: 'Siz bemorning ismini, tugʻilgan sanasini va telefonini koʻrasiz. Kartaning boshqa hech bir qismi bu yerda koʻrsatilmaydi. Har bir ishingiz shifokorning qaydnomasiga yoziladi.',
    randevular: 'Qabullar',
    randevuYok: 'Bu kunda qabullar yoʻq.',
    hastaAra: 'Bemorni ismi yoki telefoni boʻyicha qidirish',
    ara: 'Qidirish',
    aramaKisa: 'Kamida ikkita belgi kiriting.',
    sonucYok: 'Hech narsa topilmadi.',
    sec: 'Tanlash',
    dogum: 'Tugʻilgan sana: %',
    telefonYok: 'Telefon koʻrsatilmagan',
    randevuAl: 'Qabulga yozish',
    gun: 'Kun',
    alindi: 'Qabulga yozildi.',
    degistirildi: 'Qabul oʻzgartirildi.',
    yeniHasta: 'Yangi bemor',
    hastaKaydedildi: 'Bemor qoʻshildi.',
    portalVer: 'Sahifa havolasi va PIN-kod berish',
    portalBirKez: 'Havola va PIN-kod faqat hozir koʻrsatiladi. Ularni bemorga bering: qayta koʻrsatib boʻlmaydi. Oldingi havola endi ishlamaydi.',
    baglanti: 'Havola',
    pin: 'PIN-kod',
    kopyala: 'Nusxalash',
    kopyalandi: 'Nusxalandi.',
    kopyalanamadi: 'Nusxalab boʻlmadi.',
    formIste: 'Soʻrovnomani soʻrash',
    formIstendi: 'Soʻrovnoma soʻraldi. Bemor uni oʻz sahifasida toʻldiradi.',
    yetkiYok: 'Shifokor bu ishga ruxsat bermagan yoki ruxsat toʻxtatilgan.',
    yapilamadi: 'Bajarib boʻlmadi. Qayta urinib koʻring.',
    bekliyor: 'Kuting…',
    kapat: 'Yopish',
  },
}

export const UZ_KLINIK_RU: KlinikMetni = {
  kabuk: { klinik: 'Клиника', onBuro: 'Регистратура' },
  konum: { sahip: 'Владелец клиники', yonetici: 'Администратор', hekim: 'Врач', muttefik: 'Специалист клиники', 'on-buro': 'Регистратор' },
  yetkiTuru: {
    'on-buro-randevu': 'Ведение записи на приём',
    'on-buro-hasta': 'Добавление пациента',
    'on-buro-portal': 'Выдача ссылки на страницу пациента',
    paylasim: 'Доступ к записям одного пациента',
    vekalet: 'Замещение',
  },
  yetkiAciklama: {
    'on-buro-randevu': 'Регистратор видит и ведёт вашу запись на приём: записывает, переносит, отмечает «пришёл», «не пришёл» или «отменён». Он находит пациента по имени или телефону и видит только имя, дату рождения и телефон. Записи врача, расшифровки приёмов, ответы анкеты и причина приёма ему не показываются.',
    'on-buro-hasta': 'Регистратор добавляет нового пациента от вашего имени: имя, дата рождения, пол, телефон и язык. Пациент становится вашим. Личный номер здесь не вводится.',
    'on-buro-portal': 'Регистратор выдаёт пациенту ссылку на страницу и PIN-код и просит заполнить анкету. ВНИМАНИЕ: тот, кто передаёт пациенту ссылку и PIN-код, сам их видит, то есть регистратор может открыть с ними страницу пациента. Каждая выданная ссылка записывается вместе с тем, кто её выдал, а каждый вход на страницу пациента виден в карте пациента.',
    paylasim: 'Выбранный специалист клиники читает подтверждённые записи только этого одного пациента. Он ничего не может изменить; черновики, расшифровка приёма и телефон пациента ему не показываются.',
    vekalet: 'Выбранный врач в течение указанного срока находит ваших пациентов по имени, читает их подтверждённые записи и вашу запись на приём. Он ничего не может изменить и не может записать приём вашему пациенту. По окончании срока доступ прекращается сам.',
  },
  giris: {
    baslik: 'Клиника',
    aciklama: 'Вы пока не состоите ни в одной клинике. Присоединитесь к клинике по коду приглашения или создайте свою. Одна учётная запись может состоять только в одной клинике.',
    kurBaslik: 'Создать клинику',
    kurAciklama: 'Учётная запись, создавшая клинику, становится её владельцем и приглашает остальных по коду.',
    ad: 'Название клиники',
    kur: 'Создать клинику',
    katilBaslik: 'Присоединиться к клинике по коду приглашения',
    katilAciklama: 'Код выдаёт владелец или администратор клиники. Код действует один раз.',
    kod: 'Код приглашения',
    katil: 'Присоединиться',
    bekliyor: 'Подождите…',
    adGerekli: 'Введите название клиники.',
    kodGecersiz: 'Код неверный, уже использован или срок его действия истёк.',
    zatenUye: 'Вы уже состоите в клинике.',
    yapilamadi: 'Не удалось выполнить. Попробуйте ещё раз.',
  },
  klinik: {
    konumunuz: 'Ваша должность: %',
    konumAciklama: 'Должность не открывает ни одного пациента. К пациенту другого врача можно попасть только по разрешению, которое дал этот врач, и каждое обращение записывается.',
    uyeler: 'Участники',
    siz: '(вы)',
    rolYok: 'Направление не выбрано',
    konumDegistir: 'Должность',
    konumUyari: 'При смене должности все разрешения, выданные этому участнику и выданные им, сразу прекращаются.',
    cikar: 'Исключить из клиники',
    cikarOnay: 'Исключить из клиники: %? Все разрешения, выданные этому участнику и выданные им, сразу прекратятся.',
    ayril: 'Выйти из клиники',
    ayrilOnay: 'Выйти из клиники? Все разрешения, выданные вам и выданные вами, сразу прекратятся. Ваши пациенты останутся у вас.',
    evet: 'Да',
    vazgec: 'Отмена',
    degistirildi: 'Должность изменена.',
    cikarildi: 'Выполнено.',
    yetkiYok: 'У вас нет права на это действие.',
    yapilamadi: 'Не удалось выполнить. Попробуйте ещё раз.',
    yetkilerBaglanti: 'Кто помогает с моими пациентами',
    paylasilanBaglanti: 'Мне открыт доступ',
    onBuroBaglanti: 'Рабочее место регистратуры',
    geri: 'Вернуться к клинике',
  },
  davet: {
    baslik: 'Приглашения',
    aciklama: 'Код приглашения действует один раз и прекращает действовать по истечении срока. Получивший код входит в систему и вводит его в разделе «Клиника».',
    konum: 'Должность',
    olustur: 'Создать код приглашения',
    birKez: 'Код показывается только сейчас. Скопируйте его: показать повторно нельзя.',
    kod: 'Код приглашения',
    kopyala: 'Копировать',
    kopyalandi: 'Скопировано.',
    kopyalanamadi: 'Не удалось скопировать.',
    sonGecerlilik: 'Действует до %',
    liste: 'Выданные приглашения',
    listeBos: 'Приглашений пока нет.',
    durum: { acik: 'Ожидает', kullanildi: 'Использовано', iptal: 'Отменено', 'suresi-doldu': 'Срок истёк' },
    geriAl: 'Отменить',
    geriAlindi: 'Приглашение отменено.',
    yetkiYok: 'У вас нет права приглашать на эту должность.',
    yapilamadi: 'Не удалось выполнить. Попробуйте ещё раз.',
  },
  takvim: {
    baslik: 'Расписание клиники',
    aciklama: 'Видно, кто и когда занят. Имя пациента, причина приёма и любые другие сведения о пациенте здесь не показываются.',
    bos: 'На этот день приёмов нет.',
  },
  yetki: {
    baslik: 'Кто помогает с моими пациентами',
    aciklama: 'Ваши пациенты — только ваши. Каждое разрешение вы даёте участнику клиники отдельно и можете отозвать в любой момент: отозванное разрешение перестаёт действовать сразу.',
    verilen: 'Разрешения, которые я выдал',
    verilenBos: 'Вы пока никому не выдали разрешений.',
    ver: 'Выдать разрешение',
    uye: 'Участник клиники',
    uyeSec: 'Выберите участника',
    uyeYok: 'В клинике пока нет участника, которому можно выдать разрешение.',
    tur: 'Разрешение',
    turSec: 'Выберите разрешение',
    hasta: 'Пациент',
    hastaAra: 'Найти',
    hastaSec: 'Выберите пациента',
    hastaYok: 'Пациент не найден.',
    bitisGun: 'Последний день замещения',
    bitisIpucu: 'Не более % дней.',
    gonder: 'Выдать разрешение',
    bekliyor: 'Подождите…',
    verildi: 'Разрешение выдано.',
    zatenVar: 'Это разрешение уже выдано.',
    geriAl: 'Отозвать',
    geriAlindi: 'Разрешение прекращено.',
    durumGecerli: 'Действует',
    durumBitti: 'Прекращено',
    donem: '%1 – %2',
    hastaIcin: 'Пациент: %',
    hataKonum: 'Такое разрешение не выдаётся участнику в этой должности.',
    hataRol: 'Направление этого участника не позволяет получить такое разрешение.',
    hataTur: 'Это разрешение пока не включено.',
    hataGecersiz: 'Проверьте данные: день не может быть раньше сегодняшнего, а срок — длиннее допустимого.',
    hataBulunamadi: 'Участник или пациент не найден.',
    yapilamadi: 'Не удалось выполнить. Попробуйте ещё раз.',
    alinan: 'Разрешения, выданные мне',
    alinanBos: 'Вам пока не выдано разрешений.',
    hekimden: 'Врач: %',
    birak: 'Отказаться',
  },
  kayit: {
    baslik: 'Журнал доступа',
    aciklama: 'Здесь всё, что было сделано с вашими пациентами по разрешению: кто, что сделал, какой пациент, когда. Этот список видите только вы.',
    bos: 'Записей пока нет.',
    olay: { verildi: 'разрешение выдано: %1 — %2', 'geri-alindi': 'разрешение прекращено: %1 — %2', bitti: 'разрешение закончилось: %1 — %2' },
    ne: {
      'randevu-listesi': 'просмотрел список приёмов',
      'hasta-arama': 'искал пациента',
      'hasta-karti': 'открыл карточку пациента',
      'hasta-olusturma': 'добавил пациента',
      'randevu-olusturma': 'записал на приём',
      'randevu-degisiklik': 'изменил приём',
      'portal-baglantisi': 'выдал ссылку на страницу пациента и PIN-код',
      'form-istegi': 'попросил заполнить анкету',
      'not-listesi': 'прочитал подтверждённые записи',
    },
    hasta: 'Пациент: %',
  },
  paylasilan: {
    baslik: 'Мне открыт доступ',
    aciklama: 'Пациенты, к которым врач открыл вам доступ, и врачи, которых вы замещаете. Каждое открытие записывается в журнал этого врача.',
    bos: 'Вам пока ничего не открыто.',
    hekim: 'Врач: %',
    bitis: 'до %',
    ac: 'Открыть',
    saltOkunur: 'Только для чтения. Здесь показываются только подтверждённые записи; изменить ничего нельзя.',
    notlar: 'Подтверждённые записи',
    notYok: 'Подтверждённых записей нет.',
    notTarihi: 'Приём: %1 · подтверждено: %2',
    dogum: 'Дата рождения: %',
    hastaAra: 'Поиск пациента по имени',
    ara: 'Найти',
    aramaKisa: 'Введите не менее двух символов.',
    sonucYok: 'Ничего не найдено.',
    randevular: 'Приёмы врача',
    randevuYok: 'На этот день приёмов нет.',
    okunamadi: 'Не удалось открыть: возможно, разрешение отозвано или его срок истёк.',
    geri: 'Вернуться к списку',
  },
  onBuro: {
    baslik: 'Регистратура',
    aciklama: 'Вы ведёте запись на приём для врачей, которые дали вам разрешение. Каждый врач сам решает, что вам разрешено.',
    hekimYok: 'Пока ни один врач не дал вам разрешения. Когда врач выдаст его в разделе «Клиника», его приёмы появятся здесь.',
    hekim: 'Врач',
    gordugunuz: 'Вы видите имя пациента, дату рождения и телефон. Никакая другая часть карты здесь не показывается. Каждое ваше действие записывается в журнал врача.',
    randevular: 'Приёмы',
    randevuYok: 'На этот день приёмов нет.',
    hastaAra: 'Поиск пациента по имени или телефону',
    ara: 'Найти',
    aramaKisa: 'Введите не менее двух символов.',
    sonucYok: 'Ничего не найдено.',
    sec: 'Выбрать',
    dogum: 'Дата рождения: %',
    telefonYok: 'Телефон не указан',
    randevuAl: 'Записать на приём',
    gun: 'День',
    alindi: 'Пациент записан на приём.',
    degistirildi: 'Приём изменён.',
    yeniHasta: 'Новый пациент',
    hastaKaydedildi: 'Пациент добавлен.',
    portalVer: 'Выдать ссылку на страницу и PIN-код',
    portalBirKez: 'Ссылка и PIN-код показываются только сейчас. Передайте их пациенту: показать повторно нельзя. Прежняя ссылка больше не работает.',
    baglanti: 'Ссылка',
    pin: 'PIN-код',
    kopyala: 'Копировать',
    kopyalandi: 'Скопировано.',
    kopyalanamadi: 'Не удалось скопировать.',
    formIste: 'Попросить заполнить анкету',
    formIstendi: 'Анкета запрошена. Пациент заполнит её на своей странице.',
    yetkiYok: 'Врач не дал разрешения на это действие, или разрешение отозвано.',
    yapilamadi: 'Не удалось выполнить. Попробуйте ещё раз.',
    bekliyor: 'Подождите…',
    kapat: 'Закрыть',
  },
}

export const UZ_KLINIK_METINLERI: Readonly<Record<UzUygulamaDili, KlinikMetni>> = {
  'uz-Latn': UZ_KLINIK_LATN,
  'uz-Cyrl': UZ_KLINIK_KIRIL,
  ru: UZ_KLINIK_RU,
}
