/**
 * NOTYA-UZ-MUAYENE-01 — Uzbekistan: every sentence of the signed-in application (first-login language question,
 * settings, home, patients, visit, note), in the three forms an account can choose:
 *
 *   uz-Latn   Uzbek, Latin script       uz-Cyrl   Uzbek, Cyrillic script       ru   Russian
 *
 * ────────────────────────────────────────────────────────────────────────────────────────────────────────────
 * MACHINE-WRITTEN. AWAITS NATIVE REVIEW. Nobody who speaks Uzbek or Russian as a first language, and no
 * clinician, has read this text yet. It must be read and corrected before a real doctor uses the application
 * (docs/COUNTRY-PACK-CHECKLIST.md E4, E11). The Cyrillic form was written by hand, line by line — it is not a
 * transliteration at run time — and needs the same review.
 * ────────────────────────────────────────────────────────────────────────────────────────────────────────────
 *
 * Written fresh for Uzbekistan: there is no Turkish source for these screens. The shape is defined once by the
 * Uzbek Latin catalogue; the other two forms are typed against it, so a missing or misspelled key in any form is
 * a type error and fails the build (same guarantee as lib/ulke/tipler.ts gives the core surfaces).
 *
 * Uzbek Latin uses U+02BB (ʻ) in oʻ / gʻ and U+02BC (ʼ) for the tutuq belgisi.
 *
 * CONSENT WORDING (`muayene.riza`, in all three forms) is marked "NOT REVIEWED BY A LAWYER" where it is written;
 * a test fails if the mark is removed while the pack still says no lawyer has reviewed it.
 */

const UZ_LATN = {
  kabuk: {
    bugun: 'Bugun',
    hastalar: 'Bemorlar',
    ayarlar: 'Sozlamalar',
    cikis: 'Chiqish',
    menu: 'Asosiy menyu',
    yukleniyor: 'Yuklanmoqda…',
    hata: 'Xatolik yuz berdi. Qaytadan urinib koʻring.',
    baglanti: 'Ulanib boʻlmadi. Internet aloqasini tekshiring.',
    geri: 'Orqaga',
  },
  diller: {
    uz: 'Oʻzbekcha',
    ru: 'Ruscha',
    latin: 'Lotin yozuvi',
    kiril: 'Kirill yozuvi',
  },
  baslangic: {
    baslik: 'Qaysi tilda ishlaysiz?',
    aciklama: 'Interfeys va koʻrik qaydlari shu tilda boʻladi. Keyin Sozlamalar boʻlimida oʻzgartirishingiz mumkin.',
    dil: 'Til',
    yazi: 'Yozuv',
    devam: 'Davom etish',
    kaydediliyor: 'Saqlanmoqda…',
    kaydedilemedi: 'Saqlab boʻlmadi. Qaytadan urinib koʻring.',
  },
  ayarlar: {
    baslik: 'Sozlamalar',
    dilBolumu: 'Til',
    arayuzDili: 'Interfeys tili',
    notDili: 'Koʻrik qaydlari tili',
    yazi: 'Oʻzbek yozuvi',
    yaziIzoh: 'Oʻzbek tilidagi interfeys va qaydlar uchun.',
    kaydet: 'Saqlash',
    kaydediliyor: 'Saqlanmoqda…',
    kaydedildi: 'Saqlandi.',
    kaydedilemedi: 'Saqlab boʻlmadi. Qaytadan urinib koʻring.',
  },
  arama: {
    etiket: 'Bemorni qidirish',
    ornek: 'Familiya, ism yoki telefon',
    dugme: 'Qidirish',
    sonucYok: 'Hech narsa topilmadi.',
  },
  durum: {
    taslak: 'Qoralama',
    onayli: 'Tasdiqlangan',
  },
  bugun: {
    selam: 'Assalomu alaykum',
    baslik: 'Bugungi koʻriklar',
    bos: 'Bugun hali koʻrik oʻtkazilmagan.',
    yeniHasta: 'Yangi bemor',
    muayeneBaslat: 'Koʻrikni boshlash',
    hastasiz: 'Bemor koʻrsatilmagan',
    tumHastalar: 'Barcha bemorlar',
  },
  hastalar: {
    baslik: 'Bemorlar',
    bos: 'Hali bemor qoʻshilmagan.',
    dosya: 'Varaqani ochish',
  },
  yeniHasta: {
    baslik: 'Yangi bemor',
    ad: 'Familiyasi va ismi',
    otaIsmi: 'Otasining ismi',
    istegeBagli: 'ixtiyoriy',
    dogumTarihi: 'Tugʻilgan sana',
    cinsiyet: 'Jinsi',
    erkek: 'Erkak',
    kadin: 'Ayol',
    telefon: 'Telefon',
    dil: 'Bemorning tili',
    ulusalKimlik: 'JSHSHIR',
    kaydet: 'Bemorni saqlash',
    kaydediliyor: 'Saqlanmoqda…',
    iptal: 'Bekor qilish',
    adGerekli: 'Familiya va ismni kiriting.',
    dogumGecersiz: 'Tugʻilgan sana notoʻgʻri.',
    dilGerekli: 'Bemorning tilini tanlang.',
    kaydedilemedi: 'Bemorni saqlab boʻlmadi. Qaytadan urinib koʻring.',
  },
  hasta: {
    baslik: 'Bemor varaqasi',
    yas: 'Yoshi',
    ay: 'oy',
    bulunamadi: 'Bemor topilmadi.',
    notlar: 'Tasdiqlangan qaydlar',
    notYok: 'Hali tasdiqlangan qayd yoʻq.',
    taslaklar: 'Tasdiqlanmagan qoralamalar',
    notsuzlar: 'Qayd yozilmagan koʻriklar',
    notsuz: 'Suhbat matni',
    ac: 'Ochish',
  },
  muayene: {
    baslik: 'Koʻrik',
    hasta: 'Bemor',
    sablon: 'Qayd shabloni',
    sablonGenel: 'Umumiy',
    sablonPediatri: 'Pediatriya',
    // NOT REVIEWED BY A LAWYER — recording-consent wording (docs/COUNTRY-PACK-CHECKLIST.md A3, I1). Shown beside the
    // tick-box that unlocks recording. The version stamped on every visit is `riza.surum` in ../klinik/index.ts:
    // change both together when a reviewed wording arrives.
    riza: 'Bemor yoki uning qonuniy vakili suhbatni yozib olishga rozilik berdi.',
    rizaGerekli: 'Yozishni boshlash uchun rozilikni belgilang.',
    kayitBaslat: 'Yozishni boshlash',
    kayitDurdur: 'Toʻxtatish va qaydni tayyorlash',
    kaydediliyor: 'Yozib olinmoqda',
    vazgec: 'Yozuvni bekor qilish',
    mikrofonYok: 'Mikrofonga ruxsat berilmadi. Brauzer sozlamalarini tekshiring.',
    yukleniyor: 'Yozuv yuklanmoqda…',
    isleniyor: 'Yozuv matnga aylantirilmoqda va qayd tayyorlanmoqda. Bu bir necha daqiqa olishi mumkin.',
    kisaKayit: 'Yozuvda yetarli nutq topilmadi. Qaytadan yozib koʻring.',
    sesOkunamadi: 'Yozuvni qayta ishlab boʻlmadi. Qaytadan urinib koʻring.',
    notYazilamadi: 'Qaydni tayyorlab boʻlmadi. Suhbat matni saqlandi.',
    yenidenDene: 'Qaydni qaytadan tayyorlash',
    limit: 'Bugungi qayd limiti tugadi. Ertaga qaytadan urinib koʻring.',
    hazirDegil: 'Ovozni matnga aylantirish hozircha sozlanmagan.',
    taninanDil: 'Koʻrik tili',
    dilUz: 'oʻzbekcha',
    dilRu: 'ruscha',
    dilKarma: 'aniqlanmadi (aralash boʻlishi mumkin)',
    dilBaska: 'boshqa til',
    ikinciGecis: 'Aniqlik past boʻlgani uchun yozuv ikkinchi marta qayta ishlandi.',
    dusukGuven: 'Yozuv sifati yoki tili sababli matn notoʻgʻri tanilgan boʻlishi mumkin. Qaydni diqqat bilan tekshiring.',
    metinKaydedildi: 'Suhbat matni saqlandi.',
    bulunamadi: 'Koʻrik topilmadi.',
    yeniHasta: 'Yangi bemor qoʻshish',
    notHazirla: 'Qaydni tayyorlash',
    notYaziliyor: 'Qayd tayyorlanmoqda…',
    notuAc: 'Koʻrik qaydini ochish',
    hastaSec: 'Avval bemorni tanlang.',
  },
  not: {
    baslik: 'Koʻrik qaydi',
    uyari: 'Qaydni sunʼiy intellekt tayyorladi. Tasdiqlashdan oldin oʻqib chiqing va kerakli joylarini tuzating.',
    s: 'Shikoyatlar va anamnez',
    o: 'Obyektiv koʻrik',
    a: 'Tashxis va baholash',
    p: 'Reja',
    notDili: 'Qayd tili',
    cevirRu: 'Rus tilida qayta yozish',
    cevirUz: 'Oʻzbek tilida qayta yozish',
    cevriliyor: 'Qayta yozilmoqda…',
    cevrilemedi: 'Qayta yozib boʻlmadi. Qayd oʻzgarmadi.',
    kaydet: 'Qoralamani saqlash',
    kaydedildi: 'Qoralama saqlandi.',
    onayla: 'Tasdiqlash va varaqaga saqlash',
    onaylaniyor: 'Tasdiqlanmoqda…',
    onaylandi: 'Qayd tasdiqlandi va bemor varaqasiga saqlandi.',
    bosNot: 'Boʻsh qaydni tasdiqlab boʻlmaydi.',
    transkript: 'Suhbat matni',
    dosyayaDon: 'Bemor varaqasiga oʻtish',
    bulunamadi: 'Qayd topilmadi.',
    kaydedilemedi: 'Qoralamani saqlab boʻlmadi. Qaytadan urinib koʻring.',
    onaylanamadi: 'Tasdiqlab boʻlmadi. Qaytadan urinib koʻring.',
    zatenOnayli: 'Bu qayd allaqachon tasdiqlangan. Tasdiqlangan qayd oʻzgartirilmaydi.',
    ikinciTaslak: 'Bu ikkinchi qoralama. Birinchi qoralama oʻzgarmagan: tasdiqlash uchun ulardan birini tanlang.',
  },
}

/** Same keys, any text. */
type Bicim<T> = { readonly [K in keyof T]: T[K] extends string ? string : Bicim<T[K]> }
export type UygulamaMetni = Bicim<typeof UZ_LATN>

const UZ_CYRL: UygulamaMetni = {
  kabuk: {
    bugun: 'Бугун',
    hastalar: 'Беморлар',
    ayarlar: 'Созламалар',
    cikis: 'Чиқиш',
    menu: 'Асосий меню',
    yukleniyor: 'Юкланмоқда…',
    hata: 'Хатолик юз берди. Қайтадан уриниб кўринг.',
    baglanti: 'Уланиб бўлмади. Интернет алоқасини текширинг.',
    geri: 'Орқага',
  },
  diller: {
    uz: 'Ўзбекча',
    ru: 'Русча',
    latin: 'Лотин ёзуви',
    kiril: 'Кирилл ёзуви',
  },
  baslangic: {
    baslik: 'Қайси тилда ишлайсиз?',
    aciklama: 'Интерфейс ва кўрик қайдлари шу тилда бўлади. Кейин Созламалар бўлимида ўзгартиришингиз мумкин.',
    dil: 'Тил',
    yazi: 'Ёзув',
    devam: 'Давом этиш',
    kaydediliyor: 'Сақланмоқда…',
    kaydedilemedi: 'Сақлаб бўлмади. Қайтадан уриниб кўринг.',
  },
  ayarlar: {
    baslik: 'Созламалар',
    dilBolumu: 'Тил',
    arayuzDili: 'Интерфейс тили',
    notDili: 'Кўрик қайдлари тили',
    yazi: 'Ўзбек ёзуви',
    yaziIzoh: 'Ўзбек тилидаги интерфейс ва қайдлар учун.',
    kaydet: 'Сақлаш',
    kaydediliyor: 'Сақланмоқда…',
    kaydedildi: 'Сақланди.',
    kaydedilemedi: 'Сақлаб бўлмади. Қайтадан уриниб кўринг.',
  },
  arama: {
    etiket: 'Беморни қидириш',
    ornek: 'Фамилия, исм ёки телефон',
    dugme: 'Қидириш',
    sonucYok: 'Ҳеч нарса топилмади.',
  },
  durum: {
    taslak: 'Қоралама',
    onayli: 'Тасдиқланган',
  },
  bugun: {
    selam: 'Ассалому алайкум',
    baslik: 'Бугунги кўриклар',
    bos: 'Бугун ҳали кўрик ўтказилмаган.',
    yeniHasta: 'Янги бемор',
    muayeneBaslat: 'Кўрикни бошлаш',
    hastasiz: 'Бемор кўрсатилмаган',
    tumHastalar: 'Барча беморлар',
  },
  hastalar: {
    baslik: 'Беморлар',
    bos: 'Ҳали бемор қўшилмаган.',
    dosya: 'Варақани очиш',
  },
  yeniHasta: {
    baslik: 'Янги бемор',
    ad: 'Фамилияси ва исми',
    otaIsmi: 'Отасининг исми',
    istegeBagli: 'ихтиёрий',
    dogumTarihi: 'Туғилган сана',
    cinsiyet: 'Жинси',
    erkek: 'Эркак',
    kadin: 'Аёл',
    telefon: 'Телефон',
    dil: 'Беморнинг тили',
    ulusalKimlik: 'ЖШШИР',
    kaydet: 'Беморни сақлаш',
    kaydediliyor: 'Сақланмоқда…',
    iptal: 'Бекор қилиш',
    adGerekli: 'Фамилия ва исмни киритинг.',
    dogumGecersiz: 'Туғилган сана нотўғри.',
    dilGerekli: 'Беморнинг тилини танланг.',
    kaydedilemedi: 'Беморни сақлаб бўлмади. Қайтадан уриниб кўринг.',
  },
  hasta: {
    baslik: 'Бемор варақаси',
    yas: 'Ёши',
    ay: 'ой',
    bulunamadi: 'Бемор топилмади.',
    notlar: 'Тасдиқланган қайдлар',
    notYok: 'Ҳали тасдиқланган қайд йўқ.',
    taslaklar: 'Тасдиқланмаган қораламалар',
    notsuzlar: 'Қайд ёзилмаган кўриклар',
    notsuz: 'Суҳбат матни',
    ac: 'Очиш',
  },
  muayene: {
    baslik: 'Кўрик',
    hasta: 'Бемор',
    sablon: 'Қайд шаблони',
    sablonGenel: 'Умумий',
    sablonPediatri: 'Педиатрия',
    // NOT REVIEWED BY A LAWYER — recording-consent wording (docs/COUNTRY-PACK-CHECKLIST.md A3, I1). Shown beside the
    // tick-box that unlocks recording. The version stamped on every visit is `riza.surum` in ../klinik/index.ts:
    // change both together when a reviewed wording arrives.
    riza: 'Бемор ёки унинг қонуний вакили суҳбатни ёзиб олишга розилик берди.',
    rizaGerekli: 'Ёзишни бошлаш учун розиликни белгиланг.',
    kayitBaslat: 'Ёзишни бошлаш',
    kayitDurdur: 'Тўхтатиш ва қайдни тайёрлаш',
    kaydediliyor: 'Ёзиб олинмоқда',
    vazgec: 'Ёзувни бекор қилиш',
    mikrofonYok: 'Микрофонга рухсат берилмади. Браузер созламаларини текширинг.',
    yukleniyor: 'Ёзув юкланмоқда…',
    isleniyor: 'Ёзув матнга айлантирилмоқда ва қайд тайёрланмоқда. Бу бир неча дақиқа олиши мумкин.',
    kisaKayit: 'Ёзувда етарли нутқ топилмади. Қайтадан ёзиб кўринг.',
    sesOkunamadi: 'Ёзувни қайта ишлаб бўлмади. Қайтадан уриниб кўринг.',
    notYazilamadi: 'Қайдни тайёрлаб бўлмади. Суҳбат матни сақланди.',
    yenidenDene: 'Қайдни қайтадан тайёрлаш',
    limit: 'Бугунги қайд лимити тугади. Эртага қайтадан уриниб кўринг.',
    hazirDegil: 'Овозни матнга айлантириш ҳозирча созланмаган.',
    taninanDil: 'Кўрик тили',
    dilUz: 'ўзбекча',
    dilRu: 'русча',
    dilKarma: 'аниқланмади (аралаш бўлиши мумкин)',
    dilBaska: 'бошқа тил',
    ikinciGecis: 'Аниқлик паст бўлгани учун ёзув иккинчи марта қайта ишланди.',
    dusukGuven: 'Ёзув сифати ёки тили сабабли матн нотўғри танилган бўлиши мумкин. Қайдни диққат билан текширинг.',
    metinKaydedildi: 'Суҳбат матни сақланди.',
    bulunamadi: 'Кўрик топилмади.',
    yeniHasta: 'Янги бемор қўшиш',
    notHazirla: 'Қайдни тайёрлаш',
    notYaziliyor: 'Қайд тайёрланмоқда…',
    notuAc: 'Кўрик қайдини очиш',
    hastaSec: 'Аввал беморни танланг.',
  },
  not: {
    baslik: 'Кўрик қайди',
    uyari: 'Қайдни сунъий интеллект тайёрлади. Тасдиқлашдан олдин ўқиб чиқинг ва керакли жойларини тузатинг.',
    s: 'Шикоятлар ва анамнез',
    o: 'Объектив кўрик',
    a: 'Ташхис ва баҳолаш',
    p: 'Режа',
    notDili: 'Қайд тили',
    cevirRu: 'Рус тилида қайта ёзиш',
    cevirUz: 'Ўзбек тилида қайта ёзиш',
    cevriliyor: 'Қайта ёзилмоқда…',
    cevrilemedi: 'Қайта ёзиб бўлмади. Қайд ўзгармади.',
    kaydet: 'Қораламани сақлаш',
    kaydedildi: 'Қоралама сақланди.',
    onayla: 'Тасдиқлаш ва варақага сақлаш',
    onaylaniyor: 'Тасдиқланмоқда…',
    onaylandi: 'Қайд тасдиқланди ва бемор варақасига сақланди.',
    bosNot: 'Бўш қайдни тасдиқлаб бўлмайди.',
    transkript: 'Суҳбат матни',
    dosyayaDon: 'Бемор варақасига ўтиш',
    bulunamadi: 'Қайд топилмади.',
    kaydedilemedi: 'Қораламани сақлаб бўлмади. Қайтадан уриниб кўринг.',
    onaylanamadi: 'Тасдиқлаб бўлмади. Қайтадан уриниб кўринг.',
    zatenOnayli: 'Бу қайд аллақачон тасдиқланган. Тасдиқланган қайд ўзгартирилмайди.',
    ikinciTaslak: 'Бу иккинчи қоралама. Биринчи қоралама ўзгармаган: тасдиқлаш учун улардан бирини танланг.',
  },
}

const RU: UygulamaMetni = {
  kabuk: {
    bugun: 'Сегодня',
    hastalar: 'Пациенты',
    ayarlar: 'Настройки',
    cikis: 'Выйти',
    menu: 'Главное меню',
    yukleniyor: 'Загрузка…',
    hata: 'Произошла ошибка. Попробуйте ещё раз.',
    baglanti: 'Нет соединения. Проверьте интернет.',
    geri: 'Назад',
  },
  diller: {
    uz: 'Узбекский',
    ru: 'Русский',
    latin: 'Латиница',
    kiril: 'Кириллица',
  },
  baslangic: {
    baslik: 'На каком языке вы работаете?',
    aciklama: 'На этом языке будут интерфейс и записи приёмов. Позже это можно изменить в разделе «Настройки».',
    dil: 'Язык',
    yazi: 'Письменность',
    devam: 'Продолжить',
    kaydediliyor: 'Сохраняем…',
    kaydedilemedi: 'Не удалось сохранить. Попробуйте ещё раз.',
  },
  ayarlar: {
    baslik: 'Настройки',
    dilBolumu: 'Язык',
    arayuzDili: 'Язык интерфейса',
    notDili: 'Язык записей приёма',
    yazi: 'Узбекская письменность',
    yaziIzoh: 'Для интерфейса и записей на узбекском языке.',
    kaydet: 'Сохранить',
    kaydediliyor: 'Сохраняем…',
    kaydedildi: 'Сохранено.',
    kaydedilemedi: 'Не удалось сохранить. Попробуйте ещё раз.',
  },
  arama: {
    etiket: 'Поиск пациента',
    ornek: 'Фамилия, имя или телефон',
    dugme: 'Найти',
    sonucYok: 'Ничего не найдено.',
  },
  durum: {
    taslak: 'Черновик',
    onayli: 'Утверждено',
  },
  bugun: {
    selam: 'Здравствуйте',
    baslik: 'Приёмы за сегодня',
    bos: 'Сегодня приёмов ещё не было.',
    yeniHasta: 'Новый пациент',
    muayeneBaslat: 'Начать приём',
    hastasiz: 'Пациент не указан',
    tumHastalar: 'Все пациенты',
  },
  hastalar: {
    baslik: 'Пациенты',
    bos: 'Пациентов пока нет.',
    dosya: 'Открыть карту',
  },
  yeniHasta: {
    baslik: 'Новый пациент',
    ad: 'Фамилия и имя',
    otaIsmi: 'Отчество',
    istegeBagli: 'необязательно',
    dogumTarihi: 'Дата рождения',
    cinsiyet: 'Пол',
    erkek: 'Мужской',
    kadin: 'Женский',
    telefon: 'Телефон',
    dil: 'Язык пациента',
    ulusalKimlik: 'ПИНФЛ',
    kaydet: 'Сохранить пациента',
    kaydediliyor: 'Сохраняем…',
    iptal: 'Отмена',
    adGerekli: 'Введите фамилию и имя.',
    dogumGecersiz: 'Неверная дата рождения.',
    dilGerekli: 'Выберите язык пациента.',
    kaydedilemedi: 'Не удалось сохранить пациента. Попробуйте ещё раз.',
  },
  hasta: {
    baslik: 'Карта пациента',
    yas: 'Возраст',
    ay: 'мес.',
    bulunamadi: 'Пациент не найден.',
    notlar: 'Утверждённые записи',
    notYok: 'Утверждённых записей пока нет.',
    taslaklar: 'Неутверждённые черновики',
    notsuzlar: 'Приёмы без записи',
    notsuz: 'Текст беседы',
    ac: 'Открыть',
  },
  muayene: {
    baslik: 'Приём',
    hasta: 'Пациент',
    sablon: 'Шаблон записи',
    sablonGenel: 'Общий',
    sablonPediatri: 'Педиатрия',
    // NOT REVIEWED BY A LAWYER — recording-consent wording (docs/COUNTRY-PACK-CHECKLIST.md A3, I1). Shown beside the
    // tick-box that unlocks recording. The version stamped on every visit is `riza.surum` in ../klinik/index.ts:
    // change both together when a reviewed wording arrives.
    riza: 'Пациент или его законный представитель дал согласие на запись беседы.',
    rizaGerekli: 'Чтобы начать запись, отметьте согласие.',
    kayitBaslat: 'Начать запись',
    kayitDurdur: 'Остановить и подготовить запись приёма',
    kaydediliyor: 'Идёт запись',
    vazgec: 'Отменить запись',
    mikrofonYok: 'Нет доступа к микрофону. Проверьте настройки браузера.',
    yukleniyor: 'Загружаем запись…',
    isleniyor: 'Запись расшифровывается, готовится текст приёма. Это может занять несколько минут.',
    kisaKayit: 'В записи недостаточно речи. Попробуйте записать ещё раз.',
    sesOkunamadi: 'Не удалось обработать запись. Попробуйте ещё раз.',
    notYazilamadi: 'Не удалось подготовить запись приёма. Текст беседы сохранён.',
    yenidenDene: 'Подготовить запись ещё раз',
    limit: 'Дневной лимит записей исчерпан. Попробуйте завтра.',
    hazirDegil: 'Распознавание речи пока не настроено.',
    taninanDil: 'Язык приёма',
    dilUz: 'узбекский',
    dilRu: 'русский',
    dilKarma: 'не определён (возможно, смешанный)',
    dilBaska: 'другой язык',
    ikinciGecis: 'Из-за низкой уверенности распознавания запись была обработана повторно.',
    dusukGuven: 'Из-за качества или языка записи текст мог быть распознан неточно. Внимательно проверьте запись приёма.',
    metinKaydedildi: 'Текст беседы сохранён.',
    bulunamadi: 'Приём не найден.',
    yeniHasta: 'Добавить нового пациента',
    notHazirla: 'Подготовить запись приёма',
    notYaziliyor: 'Готовим запись приёма…',
    notuAc: 'Открыть запись приёма',
    hastaSec: 'Сначала выберите пациента.',
  },
  not: {
    baslik: 'Запись приёма',
    uyari: 'Запись подготовлена искусственным интеллектом. Перед утверждением прочитайте её и при необходимости исправьте.',
    s: 'Жалобы и анамнез',
    o: 'Объективный осмотр',
    a: 'Диагноз и оценка',
    p: 'План',
    notDili: 'Язык записи',
    cevirRu: 'Переписать на русском',
    cevirUz: 'Переписать на узбекском',
    cevriliyor: 'Переписываем…',
    cevrilemedi: 'Не удалось переписать. Запись не изменена.',
    kaydet: 'Сохранить черновик',
    kaydedildi: 'Черновик сохранён.',
    onayla: 'Утвердить и сохранить в карту',
    onaylaniyor: 'Утверждаем…',
    onaylandi: 'Запись утверждена и сохранена в карте пациента.',
    bosNot: 'Пустую запись утвердить нельзя.',
    transkript: 'Текст беседы',
    dosyayaDon: 'Перейти в карту пациента',
    bulunamadi: 'Запись не найдена.',
    kaydedilemedi: 'Не удалось сохранить черновик. Попробуйте ещё раз.',
    onaylanamadi: 'Не удалось утвердить. Попробуйте ещё раз.',
    zatenOnayli: 'Эта запись уже утверждена. Утверждённая запись не изменяется.',
    ikinciTaslak: 'Это второй черновик. Первый черновик не изменён: для утверждения выберите один из них.',
  },
}

/** The three forms an account of this country can choose. Same list as the pack's `uygulamaDilleri`. */
export const UZ_UYGULAMA_DILLERI = ['uz-Latn', 'uz-Cyrl', 'ru'] as const
export type UzUygulamaDili = (typeof UZ_UYGULAMA_DILLERI)[number]

export const UZ_UYGULAMA_METINLERI: Readonly<Record<UzUygulamaDili, UygulamaMetni>> = {
  'uz-Latn': UZ_LATN,
  'uz-Cyrl': UZ_CYRL,
  ru: RU,
}

/** Narrowing for a value that came from the server or the address bar. Anything else is Uzbek in Latin script. */
export function uzUygulamaDili(ham: unknown): UzUygulamaDili {
  return (UZ_UYGULAMA_DILLERI as readonly unknown[]).includes(ham) ? (ham as UzUygulamaDili) : 'uz-Latn'
}

export function uygulamaMetni(dil: unknown): UygulamaMetni {
  return UZ_UYGULAMA_METINLERI[uzUygulamaDili(dil)]
}

/** Language and script as two questions: 'uz' + 'Latn' | 'Cyrl', or 'ru'. */
export type TemelDil = 'uz' | 'ru'
export type Yazi = 'Latn' | 'Cyrl'
export const temelDil = (dil: UzUygulamaDili): TemelDil => (dil === 'ru' ? 'ru' : 'uz')
export const yaziSec = (dil: UzUygulamaDili): Yazi => (dil === 'uz-Cyrl' ? 'Cyrl' : 'Latn')
export const dilBirlestir = (temel: TemelDil, yazi: Yazi): UzUygulamaDili => (temel === 'ru' ? 'ru' : yazi === 'Cyrl' ? 'uz-Cyrl' : 'uz-Latn')
