/**
 * NOTYA-ULKE-PORTAL-01 — Uzbekistan: every sentence of the PATIENT PORTAL, in the three forms of the application:
 *
 *   uz-Latn   Uzbek, Latin script       uz-Cyrl   Uzbek, Cyrillic script       ru   Russian
 *
 *   erisim, ozet, istek   the doctor's controls (the patient's file, an approved note, the calendar)
 *   giris, sayfa          what the PATIENT reads: the PIN page and their own page
 *
 * ────────────────────────────────────────────────────────────────────────────────────────────────────────────
 * MACHINE-WRITTEN. AWAITS NATIVE REVIEW. Nobody who speaks Uzbek or Russian as a first language has read this
 * text yet. `giris` and `sayfa` are PATIENT-FACING: a patient reads them on their own phone, with nobody beside
 * them to explain. They come first for the native reader, and must be read and corrected before a real doctor
 * gives a patient a link (docs/COUNTRY-PACK-UZBEKISTAN.md, "The patient portal"; checklist E8, E11).
 * `sayfa.acilNumara` is the sentence that carries the ambulance number. The NUMBER is not in this file: it is a setting
 * of the pack (../index.ts, `uygulama.portal.acilNumara`), unverified today, to be confirmed by a local source.
 * The Cyrillic form was written by hand, line by line — it is not a transliteration at run time.
 * ────────────────────────────────────────────────────────────────────────────────────────────────────────────
 *
 * Same rules as the other catalogues of this folder: the shape is the kit's type (PortalMetni), so a missing key
 * in any form is a type error and fails the build. Written fresh for Uzbekistan — there is no Turkish source.
 * Uzbek Latin uses U+02BB (ʻ) in oʻ / gʻ and U+02BC (ʼ) for the tutuq belgisi. The Cyrillic and Russian forms carry
 * no Latin letter (so the product's name is not written in a sentence, and the code is «ПИН-код»).
 *
 * PLACEHOLDERS: '%' one value; '%1' and '%2' two (each key of the type says which).
 */
import type { PortalMetni } from '@/lib/ulke/arayuz/metinTipleri'
import type { UzUygulamaDili } from './metinler'

const UZ_LATN: PortalMetni = {
  erisim: {
    baslik: 'Bemor sahifasi',
    aciklama: 'Bemor havola va PIN-kod orqali oʻz sahifasini ochadi: unda qabullari va siz ulashgan xulosalar koʻrinadi. Koʻrik qaydi bemorga hech qachon koʻrsatilmaydi.',
    durumYok: 'Bu bemorga hali kirish berilmagan.',
    durumAcik: 'Kirish ochiq. Havola % gacha ishlaydi.',
    durumKilitli: 'Havola yopilgan: PIN-kod juda koʻp marta notoʻgʻri kiritildi. Yangi havola bering.',
    durumBitti: 'Havolaning muddati tugagan. Yangi havola bering.',
    sonGiris: 'Oxirgi kirish: %',
    sonGirisYok: 'Bemor hali kirmagan.',
    ver: 'Kirish berish',
    yenile: 'Yangi havola va PIN-kod',
    yenileUyari: 'Eski havola shu zahoti ishlamay qoladi.',
    iptal: 'Kirishni bekor qilish',
    iptalEdildi: 'Kirish bekor qilindi. Havola endi ishlamaydi.',
    bekliyor: 'Kuting…',
    yapilamadi: 'Bajarib boʻlmadi. Qaytadan urinib koʻring.',
    birKez: 'Havola va PIN-kod faqat hozir koʻrsatiladi. Ularni nusxalab oling: qayta koʻrsatib boʻlmaydi.',
    baglanti: 'Havola',
    pin: 'PIN-kod',
    kopyala: 'Nusxalash',
    kopyalandi: 'Nusxalandi.',
    kopyalanamadi: 'Nusxalab boʻlmadi. Matnni belgilab, qoʻlda nusxalang.',
    nasil: 'Havola va PIN-kodni bemorga oʻzingiz bering, imkoni boʻlsa ikki xil yoʻl bilan. Tizim bemorga hech narsa yubormaydi.',
    kayitlar: 'Tarix',
    kayitYok: 'Hozircha hech narsa yoʻq.',
    olay: {
      erisim: 'Kirish berildi',
      iptal: 'Kirish bekor qilindi',
      giris: 'Bemor kirdi',
      kilit: 'Havola yopildi: PIN-kod koʻp marta notoʻgʻri kiritildi',
      paylasim: 'Xulosa ulashildi',
      geriAlma: 'Xulosa qaytarib olindi',
    },
  },
  ozet: {
    baslik: 'Bemor uchun xulosa',
    aciklama: 'Tasdiqlangan qayd asosida sodda tilda yozilgan qisqa matn. Bemor uni faqat siz ulashganingizdan keyin koʻradi. Qaydning oʻzi bemorga koʻrsatilmaydi.',
    dil: 'Xulosa tili: %',
    yaz: 'Qoralama yozdirish',
    yenidenYaz: 'Qaytadan yozdirish',
    yaziliyor: 'Yozilmoqda…',
    yazilamadi: 'Xulosani yozib boʻlmadi. Qaytadan urinib koʻring.',
    makine: 'Qoralamani sunʼiy intellekt tayyorladi. Ulashishdan oldin oʻqib chiqing va kerakli joylarini tuzating.',
    etiket: 'Xulosa matni',
    kaydet: 'Saqlash',
    kaydedildi: 'Saqlandi.',
    kaydedilemedi: 'Saqlab boʻlmadi. Qaytadan urinib koʻring.',
    bos: 'Xulosa boʻsh.',
    paylas: 'Bemor bilan ulashish',
    paylasildi: 'Bemor bilan ulashilgan: %',
    paylasilmadi: 'Ulashilmagan. Bemor buni koʻrmaydi.',
    geriAl: 'Qaytarib olish',
    geriAlindi: 'Qaytarib olindi. Bemor endi buni koʻrmaydi.',
    degistirmekIcin: 'Ulashilgan xulosani oʻzgartirish uchun avval uni qaytarib oling.',
    yapilamadi: 'Bajarib boʻlmadi. Qaytadan urinib koʻring.',
    erisimIpucu: 'Bemor xulosani oʻz sahifasida oʻqiydi. Kirish bemor varaqasida beriladi.',
  },
  istek: {
    baslik: 'Qabulga yozilish soʻrovlari',
    gunler: 'Qulay kunlar',
    neden: 'Sababi',
    sec: 'Vaqt tanlash',
    reddet: 'Rad etish',
    reddedildi: 'Soʻrov rad etildi.',
    formBaslik: 'Soʻrovga javob',
    kabul: 'Qabulga yozish',
    cevaplandi: 'Bu soʻrovga allaqachon javob berilgan.',
    yapilamadi: 'Bajarib boʻlmadi. Qaytadan urinib koʻring.',
    istekTarihi: 'Yuborilgan: %',
  },
  // PATIENT-FACING from here on.
  giris: {
    baslik: 'Sizning sahifangiz',
    aciklama: 'Shifokoringiz bergan PIN-kodni kiriting.',
    pin: 'PIN-kod',
    gonder: 'Ochish',
    gonderiliyor: 'Tekshirilmoqda…',
    pinBicimi: 'PIN-kod % ta raqamdan iborat.',
    pinYanlis: 'PIN-kod notoʻgʻri. Qolgan urinishlar: %',
    kilitli: 'PIN-kod juda koʻp marta notoʻgʻri kiritildi, bu havola yopildi. Shifokoringizdan yangi havola soʻrang.',
    yavas: 'Juda tez. Bir necha soniya kutib, qaytadan urinib koʻring.',
    gecersiz: 'Bu havola ishlamaydi yoki muddati tugagan. Shifokoringizdan yangi havola soʻrang.',
    hata: 'Xatolik yuz berdi. Qaytadan urinib koʻring.',
    baglanti: 'Ulanib boʻlmadi. Internet aloqasini tekshiring.',
    gizlilik: 'Havola va PIN-kodni boshqa hech kimga bermang.',
    yukleniyor: 'Yuklanmoqda…',
  },
  sayfa: {
    selam: 'Assalomu alaykum, %',
    hekim: 'Shifokoringiz',
    cikis: 'Chiqish',
    oturumBitti: 'Xavfsizligingiz uchun sahifa yopildi. PIN-kodni qaytadan kiriting.',
    randevular: 'Qabullaringiz',
    randevuYok: 'Yaqin kunlarda qabulga yozilmagansiz.',
    ozetler: 'Shifokoringizdan',
    ozetYok: 'Shifokoringiz hali hech narsa ulashmagan.',
    muayene: '% kungi koʻrik',
    istekBaslik: 'Qabulga yozilishni soʻrash',
    istekAciklama: 'Oʻzingizga qulay kunlarni tanlang (koʻpi bilan % ta). Vaqtni shifokoringiz belgilaydi.',
    istekNeden: 'Sababi (qisqacha, ixtiyoriy)',
    istekGonder: 'Soʻrov yuborish',
    istekGonderiliyor: 'Yuborilmoqda…',
    istekGunGerekli: 'Kamida bitta kunni tanlang.',
    istekCokGun: 'Koʻpi bilan % ta kun tanlang.',
    istekGonderilemedi: 'Soʻrovni yuborib boʻlmadi. Qaytadan urinib koʻring.',
    istekBekliyor: 'Soʻrovingiz yuborildi. Shifokoringiz hali javob bermadi.',
    istekGunler: 'Siz soʻragan kunlar: %',
    istekKabul: 'Shifokoringiz sizni qabulga yozdi: %1, soat %2.',
    istekRed: 'Shifokoringiz bu kunlarda qabul qila olmaydi. Yangi soʻrov yuborishingiz mumkin.',
    acil: 'Bu sahifa shoshilinch holatlar uchun emas.',
    acilNumara: 'Ahvolingiz ogʻir boʻlsa, tez yordam chaqiring: %.',
    yalniz: 'Bu yerda faqat shifokoringiz siz bilan ulashgan narsalar koʻrsatiladi.',
  },
}

/** Same keys, any text. */

const UZ_CYRL: PortalMetni = {
  erisim: {
    baslik: 'Бемор саҳифаси',
    aciklama: 'Бемор ҳавола ва ПИН-код орқали ўз саҳифасини очади: унда қабуллари ва сиз улашган хулосалар кўринади. Кўрик қайди беморга ҳеч қачон кўрсатилмайди.',
    durumYok: 'Бу беморга ҳали кириш берилмаган.',
    durumAcik: 'Кириш очиқ. Ҳавола % гача ишлайди.',
    durumKilitli: 'Ҳавола ёпилган: ПИН-код жуда кўп марта нотўғри киритилди. Янги ҳавола беринг.',
    durumBitti: 'Ҳаволанинг муддати тугаган. Янги ҳавола беринг.',
    sonGiris: 'Охирги кириш: %',
    sonGirisYok: 'Бемор ҳали кирмаган.',
    ver: 'Кириш бериш',
    yenile: 'Янги ҳавола ва ПИН-код',
    yenileUyari: 'Эски ҳавола шу заҳоти ишламай қолади.',
    iptal: 'Киришни бекор қилиш',
    iptalEdildi: 'Кириш бекор қилинди. Ҳавола энди ишламайди.',
    bekliyor: 'Кутинг…',
    yapilamadi: 'Бажариб бўлмади. Қайтадан уриниб кўринг.',
    birKez: 'Ҳавола ва ПИН-код фақат ҳозир кўрсатилади. Уларни нусхалаб олинг: қайта кўрсатиб бўлмайди.',
    baglanti: 'Ҳавола',
    pin: 'ПИН-код',
    kopyala: 'Нусхалаш',
    kopyalandi: 'Нусхаланди.',
    kopyalanamadi: 'Нусхалаб бўлмади. Матнни белгилаб, қўлда нусхаланг.',
    nasil: 'Ҳавола ва ПИН-кодни беморга ўзингиз беринг, имкони бўлса икки хил йўл билан. Тизим беморга ҳеч нарса юбормайди.',
    kayitlar: 'Тарих',
    kayitYok: 'Ҳозирча ҳеч нарса йўқ.',
    olay: {
      erisim: 'Кириш берилди',
      iptal: 'Кириш бекор қилинди',
      giris: 'Бемор кирди',
      kilit: 'Ҳавола ёпилди: ПИН-код кўп марта нотўғри киритилди',
      paylasim: 'Хулоса улашилди',
      geriAlma: 'Хулоса қайтариб олинди',
    },
  },
  ozet: {
    baslik: 'Бемор учун хулоса',
    aciklama: 'Тасдиқланган қайд асосида содда тилда ёзилган қисқа матн. Бемор уни фақат сиз улашганингиздан кейин кўради. Қайднинг ўзи беморга кўрсатилмайди.',
    dil: 'Хулоса тили: %',
    yaz: 'Қоралама ёздириш',
    yenidenYaz: 'Қайтадан ёздириш',
    yaziliyor: 'Ёзилмоқда…',
    yazilamadi: 'Хулосани ёзиб бўлмади. Қайтадан уриниб кўринг.',
    makine: 'Қораламани сунъий интеллект тайёрлади. Улашишдан олдин ўқиб чиқинг ва керакли жойларини тузатинг.',
    etiket: 'Хулоса матни',
    kaydet: 'Сақлаш',
    kaydedildi: 'Сақланди.',
    kaydedilemedi: 'Сақлаб бўлмади. Қайтадан уриниб кўринг.',
    bos: 'Хулоса бўш.',
    paylas: 'Бемор билан улашиш',
    paylasildi: 'Бемор билан улашилган: %',
    paylasilmadi: 'Улашилмаган. Бемор буни кўрмайди.',
    geriAl: 'Қайтариб олиш',
    geriAlindi: 'Қайтариб олинди. Бемор энди буни кўрмайди.',
    degistirmekIcin: 'Улашилган хулосани ўзгартириш учун аввал уни қайтариб олинг.',
    yapilamadi: 'Бажариб бўлмади. Қайтадан уриниб кўринг.',
    erisimIpucu: 'Бемор хулосани ўз саҳифасида ўқийди. Кириш бемор варақасида берилади.',
  },
  istek: {
    baslik: 'Қабулга ёзилиш сўровлари',
    gunler: 'Қулай кунлар',
    neden: 'Сабаби',
    sec: 'Вақт танлаш',
    reddet: 'Рад этиш',
    reddedildi: 'Сўров рад этилди.',
    formBaslik: 'Сўровга жавоб',
    kabul: 'Қабулга ёзиш',
    cevaplandi: 'Бу сўровга аллақачон жавоб берилган.',
    yapilamadi: 'Бажариб бўлмади. Қайтадан уриниб кўринг.',
    istekTarihi: 'Юборилган: %',
  },
  // PATIENT-FACING from here on.
  giris: {
    baslik: 'Сизнинг саҳифангиз',
    aciklama: 'Шифокорингиз берган ПИН-кодни киритинг.',
    pin: 'ПИН-код',
    gonder: 'Очиш',
    gonderiliyor: 'Текширилмоқда…',
    pinBicimi: 'ПИН-код % та рақамдан иборат.',
    pinYanlis: 'ПИН-код нотўғри. Қолган уринишлар: %',
    kilitli: 'ПИН-код жуда кўп марта нотўғри киритилди, бу ҳавола ёпилди. Шифокорингиздан янги ҳавола сўранг.',
    yavas: 'Жуда тез. Бир неча сония кутиб, қайтадан уриниб кўринг.',
    gecersiz: 'Бу ҳавола ишламайди ёки муддати тугаган. Шифокорингиздан янги ҳавола сўранг.',
    hata: 'Хатолик юз берди. Қайтадан уриниб кўринг.',
    baglanti: 'Уланиб бўлмади. Интернет алоқасини текширинг.',
    gizlilik: 'Ҳавола ва ПИН-кодни бошқа ҳеч кимга берманг.',
    yukleniyor: 'Юкланмоқда…',
  },
  sayfa: {
    selam: 'Ассалому алайкум, %',
    hekim: 'Шифокорингиз',
    cikis: 'Чиқиш',
    oturumBitti: 'Хавфсизлигингиз учун саҳифа ёпилди. ПИН-кодни қайтадан киритинг.',
    randevular: 'Қабулларингиз',
    randevuYok: 'Яқин кунларда қабулга ёзилмагансиз.',
    ozetler: 'Шифокорингиздан',
    ozetYok: 'Шифокорингиз ҳали ҳеч нарса улашмаган.',
    muayene: '% кунги кўрик',
    istekBaslik: 'Қабулга ёзилишни сўраш',
    istekAciklama: 'Ўзингизга қулай кунларни танланг (кўпи билан % та). Вақтни шифокорингиз белгилайди.',
    istekNeden: 'Сабаби (қисқача, ихтиёрий)',
    istekGonder: 'Сўров юбориш',
    istekGonderiliyor: 'Юборилмоқда…',
    istekGunGerekli: 'Камида битта кунни танланг.',
    istekCokGun: 'Кўпи билан % та кун танланг.',
    istekGonderilemedi: 'Сўровни юбориб бўлмади. Қайтадан уриниб кўринг.',
    istekBekliyor: 'Сўровингиз юборилди. Шифокорингиз ҳали жавоб бермади.',
    istekGunler: 'Сиз сўраган кунлар: %',
    istekKabul: 'Шифокорингиз сизни қабулга ёзди: %1, соат %2.',
    istekRed: 'Шифокорингиз бу кунларда қабул қила олмайди. Янги сўров юборишингиз мумкин.',
    acil: 'Бу саҳифа шошилинч ҳолатлар учун эмас.',
    acilNumara: 'Аҳволингиз оғир бўлса, тез ёрдам чақиринг: %.',
    yalniz: 'Бу ерда фақат шифокорингиз сиз билан улашган нарсалар кўрсатилади.',
  },
}

const RU: PortalMetni = {
  erisim: {
    baslik: 'Страница пациента',
    aciklama: 'По ссылке и ПИН-коду пациент открывает свою страницу: там видны его приёмы и резюме, которыми вы поделились. Запись приёма пациенту никогда не показывается.',
    durumYok: 'Этому пациенту доступ ещё не выдан.',
    durumAcik: 'Доступ открыт. Ссылка действует до %.',
    durumKilitli: 'Ссылка закрыта: ПИН-код слишком много раз введён неверно. Выдайте новую ссылку.',
    durumBitti: 'Срок действия ссылки истёк. Выдайте новую ссылку.',
    sonGiris: 'Последний вход: %',
    sonGirisYok: 'Пациент ещё не входил.',
    ver: 'Выдать доступ',
    yenile: 'Новая ссылка и ПИН-код',
    yenileUyari: 'Старая ссылка сразу перестанет работать.',
    iptal: 'Отозвать доступ',
    iptalEdildi: 'Доступ отозван. Ссылка больше не работает.',
    bekliyor: 'Подождите…',
    yapilamadi: 'Не удалось выполнить. Попробуйте ещё раз.',
    birKez: 'Ссылка и ПИН-код показываются только сейчас. Скопируйте их: показать их снова нельзя.',
    baglanti: 'Ссылка',
    pin: 'ПИН-код',
    kopyala: 'Скопировать',
    kopyalandi: 'Скопировано.',
    kopyalanamadi: 'Не удалось скопировать. Выделите текст и скопируйте вручную.',
    nasil: 'Передайте ссылку и ПИН-код пациенту сами, по возможности двумя разными способами. Система ничего не отправляет пациенту.',
    kayitlar: 'История',
    kayitYok: 'Пока ничего нет.',
    olay: {
      erisim: 'Доступ выдан',
      iptal: 'Доступ отозван',
      giris: 'Пациент вошёл',
      kilit: 'Ссылка закрыта: ПИН-код много раз введён неверно',
      paylasim: 'Резюме отправлено пациенту',
      geriAlma: 'Резюме отозвано',
    },
  },
  ozet: {
    baslik: 'Резюме для пациента',
    aciklama: 'Короткий текст простым языком на основе утверждённой записи. Пациент увидит его только после того, как вы им поделитесь. Сама запись пациенту не показывается.',
    dil: 'Язык резюме: %',
    yaz: 'Подготовить черновик',
    yenidenYaz: 'Подготовить заново',
    yaziliyor: 'Готовим текст…',
    yazilamadi: 'Не удалось подготовить резюме. Попробуйте ещё раз.',
    makine: 'Черновик подготовлен искусственным интеллектом. Прежде чем поделиться, прочитайте его и при необходимости исправьте.',
    etiket: 'Текст резюме',
    kaydet: 'Сохранить',
    kaydedildi: 'Сохранено.',
    kaydedilemedi: 'Не удалось сохранить. Попробуйте ещё раз.',
    bos: 'Резюме пустое.',
    paylas: 'Поделиться с пациентом',
    paylasildi: 'Пациент видит это резюме с %',
    paylasilmadi: 'Не отправлено. Пациент этого не видит.',
    geriAl: 'Отозвать',
    geriAlindi: 'Отозвано. Пациент больше этого не видит.',
    degistirmekIcin: 'Чтобы изменить отправленное резюме, сначала отзовите его.',
    yapilamadi: 'Не удалось выполнить. Попробуйте ещё раз.',
    erisimIpucu: 'Пациент читает резюме на своей странице. Доступ выдаётся в карте пациента.',
  },
  istek: {
    baslik: 'Запросы на приём',
    gunler: 'Удобные дни',
    neden: 'Причина',
    sec: 'Выбрать время',
    reddet: 'Отклонить',
    reddedildi: 'Запрос отклонён.',
    formBaslik: 'Ответ на запрос',
    kabul: 'Записать на приём',
    cevaplandi: 'На этот запрос уже дан ответ.',
    yapilamadi: 'Не удалось выполнить. Попробуйте ещё раз.',
    istekTarihi: 'Отправлен: %',
  },
  // PATIENT-FACING from here on.
  giris: {
    baslik: 'Ваша страница',
    aciklama: 'Введите ПИН-код, который дал вам врач.',
    pin: 'ПИН-код',
    gonder: 'Открыть',
    gonderiliyor: 'Проверяем…',
    pinBicimi: 'ПИН-код состоит из % цифр.',
    pinYanlis: 'Неверный ПИН-код. Осталось попыток: %',
    kilitli: 'ПИН-код слишком много раз введён неверно, эта ссылка закрыта. Попросите у врача новую ссылку.',
    yavas: 'Слишком быстро. Подождите несколько секунд и попробуйте ещё раз.',
    gecersiz: 'Эта ссылка не работает или срок её действия истёк. Попросите у врача новую ссылку.',
    hata: 'Произошла ошибка. Попробуйте ещё раз.',
    baglanti: 'Нет соединения. Проверьте интернет.',
    gizlilik: 'Никому не передавайте ссылку и ПИН-код.',
    yukleniyor: 'Загрузка…',
  },
  sayfa: {
    selam: 'Здравствуйте, %',
    hekim: 'Ваш врач',
    cikis: 'Выйти',
    oturumBitti: 'Ради вашей безопасности страница закрыта. Введите ПИН-код ещё раз.',
    randevular: 'Ваши приёмы',
    randevuYok: 'В ближайшие дни вы не записаны на приём.',
    ozetler: 'От вашего врача',
    ozetYok: 'Врач пока ничем с вами не поделился.',
    muayene: 'Приём %',
    istekBaslik: 'Попросить о приёме',
    istekAciklama: 'Выберите удобные вам дни (не больше %). Время назначит врач.',
    istekNeden: 'Причина (коротко, необязательно)',
    istekGonder: 'Отправить запрос',
    istekGonderiliyor: 'Отправляем…',
    istekGunGerekli: 'Выберите хотя бы один день.',
    istekCokGun: 'Выберите не больше % дней.',
    istekGonderilemedi: 'Не удалось отправить запрос. Попробуйте ещё раз.',
    istekBekliyor: 'Ваш запрос отправлен. Врач ещё не ответил.',
    istekGunler: 'Дни, о которых вы просили: %',
    istekKabul: 'Врач записал вас на приём: %1, %2.',
    istekRed: 'Врач не может принять вас в эти дни. Вы можете отправить новый запрос.',
    acil: 'Эта страница не для экстренных случаев.',
    acilNumara: 'Если вам очень плохо, вызовите скорую помощь: %.',
    yalniz: 'Здесь показано только то, чем с вами поделился врач.',
  },
}

export const UZ_PORTAL_METINLERI: Readonly<Record<UzUygulamaDili, PortalMetni>> = {
  'uz-Latn': UZ_LATN,
  'uz-Cyrl': UZ_CYRL,
  ru: RU,
}
