-- BASELINE OF A NEW, EMPTY COUNTRY DATABASE. Migrations 129 to 135, as one file.
--
-- GENERATED by scripts/ulke-temel-uret.mjs from lib/db/ulke/gocler.json. DO NOT EDIT BY HAND: change or add a
-- migration, add it to that list, and run the script again. The commented source of every statement below is the
-- migration file named above it.
--
-- WHAT IT IS FOR. One database per country. A new country's own database is created empty, and this file is run on
-- it ONCE. It creates every table, rule, function and the recordings bucket a country build needs, and the ledger
-- that records which migrations the database holds (129 to 135, one row each). Migrations written after this
-- file was generated are then run one by one, as files.
--
-- WHERE IT MAY RUN. On a database whose `public` schema holds no table at all. It checks that itself, first, and
-- refuses with an error otherwise: it cannot be run twice, and it cannot be run on a database that is in use.
-- It is one transaction: it is applied completely or not at all.
--
-- It expects what every new project of the database provider brings: the roles anon, authenticated and service_role,
-- the sign-in tables and functions (auth.users, auth.uid(), auth.jwt()) and the storage tables (storage.buckets,
-- storage.objects, storage.foldername()).

begin;
set local lock_timeout = '4s';

do $$
declare n integer;
begin
  select count(*) into n
    from pg_class c join pg_namespace s on s.oid = c.relnamespace
   where s.nspname = 'public' and c.relkind in ('r', 'p', 'v', 'm', 'f');
  if n > 0 then
    raise exception 'baseline refused: the public schema of this database already holds % table(s). This file is for a NEW, EMPTY country database and is run once.', n;
  end if;
end $$;

-- ── the ledger (lib/db/ulke/defter.sql) ──
create table if not exists public.schema_migrations (
  version text primary key,
  filename text not null,
  checksum text,
  applied_at timestamptz,
  backfilled boolean not null default false,
  note text
);

alter table public.schema_migrations enable row level security;
revoke all on table public.schema_migrations from anon, authenticated;

-- ── 129_davet_kodlari.sql ──
create table if not exists public.davet_kodlari (
  kod_hash text primary key check (kod_hash ~ '^[0-9a-f]{64}$'),
  ulke text not null check (ulke ~ '^[a-z]{2}$'),
  azami_kullanim integer not null default 1 check (azami_kullanim > 0),
  kullanim integer not null default 0 check (kullanim >= 0),
  son_gecerlilik timestamptz,
  aciklama text,
  created_at timestamptz not null default now(),
  son_kullanim_at timestamptz,
  constraint davet_kodlari_kullanim_siniri check (kullanim <= azami_kullanim)
);

alter table public.davet_kodlari enable row level security;
revoke all on table public.davet_kodlari from anon, authenticated;

create or replace function public.davet_kodu_kullan(p_hash text, p_ulke text)
returns boolean language plpgsql security definer set search_path = public as $$
declare
  n integer;
begin
  update public.davet_kodlari
     set kullanim = kullanim + 1, son_kullanim_at = now()
   where kod_hash = p_hash
     and ulke = p_ulke
     and kullanim < azami_kullanim
     and (son_gecerlilik is null or son_gecerlilik > now());
  get diagnostics n = row_count;
  return n = 1;
end $$;

create or replace function public.davet_kodu_iade(p_hash text, p_ulke text)
returns void language sql security definer set search_path = public as $$
  update public.davet_kodlari set kullanim = greatest(kullanim - 1, 0) where kod_hash = p_hash and ulke = p_ulke;
$$;

revoke execute on function public.davet_kodu_kullan(text, text) from public, anon, authenticated;
revoke execute on function public.davet_kodu_iade(text, text) from public, anon, authenticated;
do $$
begin
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    grant execute on function public.davet_kodu_kullan(text, text) to service_role;
    grant execute on function public.davet_kodu_iade(text, text) to service_role;
  end if;
end $$;

insert into schema_migrations (version, filename, checksum, applied_at, backfilled, note)
values ('129', '129_davet_kodlari.sql', null, now(), false,
  'NOTYA-ULKE-01: invitation codes (hash only, one country each) for countries whose sign-up is not open yet; atomic use / give-back functions bound to the country')
on conflict (version) do nothing;

-- ── 130_hekim_dil_tercihleri.sql ──
create or replace function public.ulke_oturum_ulkesi() returns text
language sql stable set search_path = public as $$
  select coalesce(auth.jwt() -> 'app_metadata' ->> 'country', '')
$$;

create table if not exists public.ulke_hesaplari (
  id uuid primary key references auth.users(id) on delete cascade,
  ulke text not null check (ulke ~ '^[a-z]{2}$'),
  full_name text not null default '',
  ui_language text not null check (ui_language ~ '^[a-z]{2,3}(-[A-Z][a-z]{3})?(-[A-Z]{2})?$'),
  saat_dilimi text check (saat_dilimi is null or (char_length(saat_dilimi) <= 64 and saat_dilimi ~ '^[A-Za-z0-9_+-]+(/[A-Za-z0-9_+-]+)*$')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ulke_hesaplari_ulke_id_tekil unique (ulke, id)
);

create or replace function public.ulke_hesaplari_ulke_kilidi() returns trigger
language plpgsql as $$
begin
  if new.ulke is distinct from old.ulke then
    raise exception 'ulke_hesaplari.ulke is set when the account is created and never changes' using errcode = '23514';
  end if;
  return new;
end $$;

create trigger ulke_hesaplari_ulke_kilidi
  before update of ulke on public.ulke_hesaplari
  for each row execute function public.ulke_hesaplari_ulke_kilidi();

alter table public.ulke_hesaplari enable row level security;

create policy "ulke hesabi kendi satiri" on public.ulke_hesaplari
  for select to authenticated using (id = auth.uid() and ulke = public.ulke_oturum_ulkesi());

revoke all on table public.ulke_hesaplari from anon, authenticated;
grant select on table public.ulke_hesaplari to authenticated;

create table if not exists public.hekim_dil_tercihleri (
  doctor_id uuid primary key,
  ulke text not null check (ulke ~ '^[a-z]{2}$'),
  not_dili text not null check (not_dili ~ '^[a-z]{2,3}(-[A-Z][a-z]{3})?(-[A-Z]{2})?$'),
  soruldu_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint hekim_dil_tercihleri_hesap_fk foreign key (ulke, doctor_id) references public.ulke_hesaplari (ulke, id) on delete cascade
);

alter table public.hekim_dil_tercihleri enable row level security;

create policy "hekim kendi dil tercihi" on public.hekim_dil_tercihleri
  for select to authenticated using (doctor_id = auth.uid() and ulke = public.ulke_oturum_ulkesi());

revoke all on table public.hekim_dil_tercihleri from anon, authenticated;
grant select on table public.hekim_dil_tercihleri to authenticated;

insert into schema_migrations (version, filename, checksum, applied_at, backfilled, note)
values ('130', '130_hekim_dil_tercihleri.sql', null, now(), false,
  'NOTYA-ULKE-SABLON-01: country accounts (ulke_hesaplari: one country per account, never changes) + per-account note language (new tables, country in every key, owner-and-country-only)')
on conflict (version) do nothing;

-- ── 131_hasta_ulke_bilgisi.sql ──
create table if not exists public.ulke_hastalar (
  id uuid primary key default gen_random_uuid(),
  ulke text not null check (ulke ~ '^[a-z]{2}$'),
  doctor_id uuid not null,
  name_encrypted text,
  dob_encrypted text,
  gender_encrypted text,
  phone_encrypted text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ulke_hastalar_hesap_fk foreign key (ulke, doctor_id) references public.ulke_hesaplari (ulke, id) on delete cascade,
  constraint ulke_hastalar_sahip_tekil unique (ulke, doctor_id, id)
);

create index if not exists ulke_hastalar_doctor_idx on public.ulke_hastalar (ulke, doctor_id, created_at desc);

alter table public.ulke_hastalar enable row level security;

create policy "hasta_izolasyon_kendi_satiri" on public.ulke_hastalar
  for select to authenticated using (doctor_id = auth.uid() and ulke = public.ulke_oturum_ulkesi());

revoke all on table public.ulke_hastalar from anon, authenticated;
grant select on table public.ulke_hastalar to authenticated;

create table if not exists public.hasta_ulke_bilgisi (
  patient_id uuid primary key,
  ulke text not null check (ulke ~ '^[a-z]{2}$'),
  doctor_id uuid not null,
  ota_ismi_encrypted text,
  dil text not null check (dil ~ '^[a-z]{2,3}$'),
  ulusal_kimlik_encrypted text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint hasta_ulke_bilgisi_hasta_fk foreign key (ulke, doctor_id, patient_id) references public.ulke_hastalar (ulke, doctor_id, id) on delete cascade
);

create index if not exists hasta_ulke_bilgisi_doctor_idx on public.hasta_ulke_bilgisi (ulke, doctor_id);

alter table public.hasta_ulke_bilgisi enable row level security;

create policy "hasta_izolasyon_kendi_satiri" on public.hasta_ulke_bilgisi
  for select to authenticated using (doctor_id = auth.uid() and ulke = public.ulke_oturum_ulkesi());

create policy "hasta_izolasyon_hasta_sahipligi" on public.hasta_ulke_bilgisi as restrictive for all to authenticated, anon
  using (exists (select 1 from public.ulke_hastalar p where p.id = patient_id and p.doctor_id = auth.uid() and p.ulke = public.ulke_oturum_ulkesi()))
  with check (exists (select 1 from public.ulke_hastalar p where p.id = patient_id and p.doctor_id = auth.uid() and p.ulke = public.ulke_oturum_ulkesi()));

revoke all on table public.hasta_ulke_bilgisi from anon, authenticated;
grant select on table public.hasta_ulke_bilgisi to authenticated;

insert into schema_migrations (version, filename, checksum, applied_at, backfilled, note)
values ('131', '131_hasta_ulke_bilgisi.sql', null, now(), false,
  'NOTYA-ULKE-SABLON-01: country patients (ulke_hastalar) + per-patient patronymic, language and optional identity number (new tables, country and doctor in every key, owner-and-country-only, restrictive patient ownership)')
on conflict (version) do nothing;

-- ── 132_muayene_dil_kaydi.sql ──
create table if not exists public.ulke_muayeneler (
  id uuid primary key default gen_random_uuid(),
  ulke text not null check (ulke ~ '^[a-z]{2}$'),
  doctor_id uuid not null,
  patient_id uuid not null,
  patient_consent_given boolean not null default false,
  patient_consent_at timestamptz,
  duration_seconds integer check (duration_seconds is null or duration_seconds >= 0),
  specialty text,
  session_type text,
  status text,
  transcript_cleaned text,
  started_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint ulke_muayeneler_hasta_fk foreign key (ulke, doctor_id, patient_id) references public.ulke_hastalar (ulke, doctor_id, id) on delete cascade,
  constraint ulke_muayeneler_sahip_tekil unique (ulke, doctor_id, id)
);

create index if not exists ulke_muayeneler_doctor_idx on public.ulke_muayeneler (ulke, doctor_id, started_at desc);
create index if not exists ulke_muayeneler_patient_idx on public.ulke_muayeneler (ulke, doctor_id, patient_id, started_at desc);

alter table public.ulke_muayeneler enable row level security;

create policy "hasta_izolasyon_kendi_satiri" on public.ulke_muayeneler
  for select to authenticated using (doctor_id = auth.uid() and ulke = public.ulke_oturum_ulkesi());

create policy "hasta_izolasyon_hasta_sahipligi" on public.ulke_muayeneler as restrictive for all to authenticated, anon
  using (exists (select 1 from public.ulke_hastalar p where p.id = patient_id and p.doctor_id = auth.uid() and p.ulke = public.ulke_oturum_ulkesi()))
  with check (exists (select 1 from public.ulke_hastalar p where p.id = patient_id and p.doctor_id = auth.uid() and p.ulke = public.ulke_oturum_ulkesi()));

revoke all on table public.ulke_muayeneler from anon, authenticated;
grant select on table public.ulke_muayeneler to authenticated;

create table if not exists public.muayene_dil_kaydi (
  session_id uuid primary key,
  ulke text not null check (ulke ~ '^[a-z]{2}$'),
  doctor_id uuid not null,
  patient_id uuid not null,
  riza_at timestamptz not null,
  riza_surumu text not null,
  stt_model text not null,
  taninan_dil text,
  dil_olasiligi numeric check (dil_olasiligi is null or (dil_olasiligi >= 0 and dil_olasiligi <= 1)),
  ortalama_log_olasilik numeric,
  ikinci_gecis boolean not null default false,
  ikinci_gecis_dili text,
  secilen_gecis smallint not null default 1 check (secilen_gecis in (1, 2)),
  gecis_sayisi smallint not null default 1 check (gecis_sayisi in (1, 2)),
  dusuk_guven boolean not null default false,
  ses_suresi_sn numeric,
  not_dili text not null check (not_dili ~ '^[a-z]{2,3}(-[A-Z][a-z]{3})?(-[A-Z]{2})?$'),
  sablon text not null,
  created_at timestamptz not null default now(),
  constraint muayene_dil_kaydi_muayene_fk foreign key (ulke, doctor_id, session_id) references public.ulke_muayeneler (ulke, doctor_id, id) on delete cascade,
  constraint muayene_dil_kaydi_hasta_fk foreign key (ulke, doctor_id, patient_id) references public.ulke_hastalar (ulke, doctor_id, id) on delete cascade
);

create index if not exists muayene_dil_kaydi_doctor_idx on public.muayene_dil_kaydi (ulke, doctor_id, created_at desc);

alter table public.muayene_dil_kaydi enable row level security;

create policy "hasta_izolasyon_kendi_satiri" on public.muayene_dil_kaydi
  for select to authenticated using (doctor_id = auth.uid() and ulke = public.ulke_oturum_ulkesi());

create policy "hasta_izolasyon_hasta_sahipligi" on public.muayene_dil_kaydi as restrictive for all to authenticated, anon
  using (exists (select 1 from public.ulke_hastalar p where p.id = patient_id and p.doctor_id = auth.uid() and p.ulke = public.ulke_oturum_ulkesi()))
  with check (exists (select 1 from public.ulke_hastalar p where p.id = patient_id and p.doctor_id = auth.uid() and p.ulke = public.ulke_oturum_ulkesi()));

revoke all on table public.muayene_dil_kaydi from anon, authenticated;
grant select on table public.muayene_dil_kaydi to authenticated;

create table if not exists public.ulke_kullanim (
  ulke text not null check (ulke ~ '^[a-z]{2}$'),
  doctor_id uuid not null,
  gun date not null,
  kova text not null,
  sayac integer not null default 0 check (sayac >= 0),
  primary key (ulke, doctor_id, gun, kova),
  constraint ulke_kullanim_hesap_fk foreign key (ulke, doctor_id) references public.ulke_hesaplari (ulke, id) on delete cascade
);

alter table public.ulke_kullanim enable row level security;
revoke all on table public.ulke_kullanim from anon, authenticated;

insert into storage.buckets (id, name, public)
values ('muayene-sesleri', 'muayene-sesleri', false)
on conflict (id) do nothing;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'storage' and tablename = 'objects' and policyname = 'muayene_sesleri_ulke_ve_kendi_klasorune_yukle') then
    create policy "muayene_sesleri_ulke_ve_kendi_klasorune_yukle" on storage.objects
      for insert to authenticated
      with check (
        bucket_id = 'muayene-sesleri'
        and public.ulke_oturum_ulkesi() <> ''
        and (storage.foldername(name))[1] = public.ulke_oturum_ulkesi()
        and (storage.foldername(name))[2] = auth.uid()::text
        and array_length(storage.foldername(name), 1) = 2
      );
  end if;
end $$;

insert into schema_migrations (version, filename, checksum, applied_at, backfilled, note)
values ('132', '132_muayene_dil_kaydi.sql', null, now(), false,
  'NOTYA-ULKE-SABLON-01: country visits (ulke_muayeneler) + consent and speech record + daily counter (new tables, country and doctor in every key) + private bucket muayene-sesleri with an upload rule per country folder and own folder')
on conflict (version) do nothing;

-- ── 133_not_dil_kaydi.sql ──
create table if not exists public.ulke_notlar (
  id uuid primary key default gen_random_uuid(),
  ulke text not null check (ulke ~ '^[a-z]{2}$'),
  doctor_id uuid not null,
  session_id uuid not null,
  note_type text not null default 'soap',
  content_subjektif text,
  content_objektif text,
  content_degerlendirme text,
  content_plan text,
  ai_model text,
  approved_at timestamptz,
  approved_by uuid,
  created_at timestamptz not null default now(),
  constraint ulke_notlar_muayene_fk foreign key (ulke, doctor_id, session_id) references public.ulke_muayeneler (ulke, doctor_id, id) on delete cascade,
  constraint ulke_notlar_sahip_tekil unique (ulke, doctor_id, id),
  constraint ulke_notlar_onaylayan check (approved_by is null or approved_by = doctor_id)
);

create index if not exists ulke_notlar_session_idx on public.ulke_notlar (ulke, doctor_id, session_id);

alter table public.ulke_notlar enable row level security;

create policy "hasta_izolasyon_kendi_satiri" on public.ulke_notlar
  for select to authenticated using (doctor_id = auth.uid() and ulke = public.ulke_oturum_ulkesi());

revoke all on table public.ulke_notlar from anon, authenticated;
grant select on table public.ulke_notlar to authenticated;

create table if not exists public.not_dil_kaydi (
  note_id uuid primary key,
  ulke text not null check (ulke ~ '^[a-z]{2}$'),
  doctor_id uuid not null,
  patient_id uuid not null,
  not_dili text not null check (not_dili ~ '^[a-z]{2,3}(-[A-Z][a-z]{3})?(-[A-Z]{2})?$'),
  ikinci_dil text check (ikinci_dil is null or ikinci_dil ~ '^[a-z]{2,3}(-[A-Z][a-z]{3})?(-[A-Z]{2})?$'),
  ikinci_s text,
  ikinci_o text,
  ikinci_a text,
  ikinci_p text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ikinci_dil is null or ikinci_dil <> not_dili),
  constraint not_dil_kaydi_not_fk foreign key (ulke, doctor_id, note_id) references public.ulke_notlar (ulke, doctor_id, id) on delete cascade,
  constraint not_dil_kaydi_hasta_fk foreign key (ulke, doctor_id, patient_id) references public.ulke_hastalar (ulke, doctor_id, id) on delete cascade
);

create index if not exists not_dil_kaydi_doctor_idx on public.not_dil_kaydi (ulke, doctor_id);

alter table public.not_dil_kaydi enable row level security;

create policy "hasta_izolasyon_kendi_satiri" on public.not_dil_kaydi
  for select to authenticated using (doctor_id = auth.uid() and ulke = public.ulke_oturum_ulkesi());

create policy "hasta_izolasyon_hasta_sahipligi" on public.not_dil_kaydi as restrictive for all to authenticated, anon
  using (exists (select 1 from public.ulke_hastalar p where p.id = patient_id and p.doctor_id = auth.uid() and p.ulke = public.ulke_oturum_ulkesi()))
  with check (exists (select 1 from public.ulke_hastalar p where p.id = patient_id and p.doctor_id = auth.uid() and p.ulke = public.ulke_oturum_ulkesi()));

revoke all on table public.not_dil_kaydi from anon, authenticated;
grant select on table public.not_dil_kaydi to authenticated;

insert into schema_migrations (version, filename, checksum, applied_at, backfilled, note)
values ('133', '133_not_dil_kaydi.sql', null, now(), false,
  'NOTYA-ULKE-SABLON-01: country notes (ulke_notlar) + per-note language and second-language draft (new tables, country and doctor in every key, owner-and-country-only, restrictive patient ownership)')
on conflict (version) do nothing;

-- ── 134_hekim_rolu.sql ──
create table if not exists public.hekim_rolu (
  doctor_id uuid primary key,
  ulke text not null check (ulke ~ '^[a-z]{2}$'),
  rol text not null check (rol ~ '^[a-z]+(-[a-z]+)*$' and char_length(rol) <= 60),
  secildi_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint hekim_rolu_hesap_fk foreign key (ulke, doctor_id) references public.ulke_hesaplari (ulke, id) on delete cascade
);

alter table public.hekim_rolu enable row level security;

create policy "hekim kendi rolu" on public.hekim_rolu
  for select to authenticated using (doctor_id = auth.uid() and ulke = public.ulke_oturum_ulkesi());

revoke all on table public.hekim_rolu from anon, authenticated;
grant select on table public.hekim_rolu to authenticated;

alter table public.not_dil_kaydi
  add column if not exists alanlar jsonb check (alanlar is null or jsonb_typeof(alanlar) = 'object'),
  add column if not exists ikinci_alanlar jsonb check (ikinci_alanlar is null or jsonb_typeof(ikinci_alanlar) = 'object');

insert into schema_migrations (version, filename, checksum, applied_at, backfilled, note)
values ('134', '134_hekim_rolu.sql', null, now(), false,
  'NOTYA-ULKE-SABLON-01: per-account role (new table, country in the key, owner-and-country-only) + role-specific note fields on not_dil_kaydi (country table)')
on conflict (version) do nothing;

-- ── 135_ulke_randevu.sql ──
create extension if not exists btree_gist;

create table if not exists public.hekim_calisma_duzeni (
  doctor_id uuid primary key,
  ulke text not null check (ulke ~ '^[a-z]{2}$'),
  gunler smallint[] not null check (gunler <@ array[1,2,3,4,5,6,7]::smallint[] and cardinality(gunler) between 1 and 7),
  baslangic_dk smallint not null check (baslangic_dk between 0 and 1439),
  bitis_dk smallint not null check (bitis_dk between 1 and 1440),
  sure_dk smallint not null check (sure_dk between 5 and 240),
  molalar jsonb not null default '[]'::jsonb check (jsonb_typeof(molalar) = 'array'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (bitis_dk > baslangic_dk),
  constraint hekim_calisma_duzeni_hesap_fk foreign key (ulke, doctor_id) references public.ulke_hesaplari (ulke, id) on delete cascade
);

alter table public.hekim_calisma_duzeni enable row level security;

create policy "hekim kendi calisma duzeni" on public.hekim_calisma_duzeni
  for select to authenticated using (doctor_id = auth.uid() and ulke = public.ulke_oturum_ulkesi());

revoke all on table public.hekim_calisma_duzeni from anon, authenticated;
grant select on table public.hekim_calisma_duzeni to authenticated;

create table if not exists public.ulke_randevulari (
  id uuid primary key default gen_random_uuid(),
  ulke text not null check (ulke ~ '^[a-z]{2}$'),
  doctor_id uuid not null,
  patient_id uuid not null,
  baslangic timestamptz not null,
  bitis timestamptz not null,
  neden_encrypted text,
  durum text not null default 'planlandi' check (durum in ('planlandi', 'geldi', 'tamamlandi', 'gelmedi', 'iptal')),
  mesai_disi boolean not null default false,
  session_id uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (bitis > baslangic),
  check (bitis <= baslangic + interval '8 hours'),
  constraint ulke_randevulari_hasta_fk foreign key (ulke, doctor_id, patient_id) references public.ulke_hastalar (ulke, doctor_id, id) on delete cascade,
  constraint ulke_randevulari_muayene_fk foreign key (ulke, doctor_id, session_id) references public.ulke_muayeneler (ulke, doctor_id, id)
);

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'ulke_randevulari_cakisma_yok') then
    alter table public.ulke_randevulari add constraint ulke_randevulari_cakisma_yok
      exclude using gist (doctor_id with =, tstzrange(baslangic, bitis, '[)') with &&)
      where (durum in ('planlandi', 'geldi', 'tamamlandi'));
  end if;
end $$;

create index if not exists ulke_randevulari_doctor_idx on public.ulke_randevulari (ulke, doctor_id, baslangic);
create index if not exists ulke_randevulari_patient_idx on public.ulke_randevulari (ulke, doctor_id, patient_id, baslangic);
create unique index if not exists ulke_randevulari_session_idx on public.ulke_randevulari (session_id) where session_id is not null;

alter table public.ulke_randevulari enable row level security;

create policy "hasta_izolasyon_kendi_satiri" on public.ulke_randevulari
  for select to authenticated using (doctor_id = auth.uid() and ulke = public.ulke_oturum_ulkesi());

create policy "hasta_izolasyon_hasta_sahipligi" on public.ulke_randevulari as restrictive for all to authenticated, anon
  using (exists (select 1 from public.ulke_hastalar p where p.id = patient_id and p.doctor_id = auth.uid() and p.ulke = public.ulke_oturum_ulkesi()))
  with check (exists (select 1 from public.ulke_hastalar p where p.id = patient_id and p.doctor_id = auth.uid() and p.ulke = public.ulke_oturum_ulkesi()));

revoke all on table public.ulke_randevulari from anon, authenticated;
grant select on table public.ulke_randevulari to authenticated;

create or replace function public.ulke_not_onayla(
  p_ulke text,
  p_note_id uuid,
  p_doctor_id uuid,
  p_onay_ani timestamptz,
  p_s text,
  p_o text,
  p_a text,
  p_p text,
  p_dil_kaydi jsonb default null
) returns text
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_session uuid;
  v_onayli timestamptz;
begin
  -- The row is locked, so a second approval or a late save of the same note waits for this one to finish.
  select n.session_id, n.approved_at into v_session, v_onayli
    from public.ulke_notlar n
   where n.id = p_note_id and n.doctor_id = p_doctor_id and n.ulke = p_ulke
     for update;
  if not found then
    return 'NOT_FOUND';
  end if;
  if v_onayli is not null then
    return 'ONAYLI';
  end if;

  update public.ulke_notlar
     set content_subjektif = p_s,
         content_objektif = p_o,
         content_degerlendirme = p_a,
         content_plan = p_p,
         approved_at = p_onay_ani,
         approved_by = p_doctor_id
   where id = p_note_id and doctor_id = p_doctor_id and ulke = p_ulke and approved_at is null;

  if p_dil_kaydi is not null then
    update public.not_dil_kaydi d
       set alanlar        = case when p_dil_kaydi ? 'alanlar' then nullif(p_dil_kaydi -> 'alanlar', 'null'::jsonb) else d.alanlar end,
           ikinci_alanlar = case when p_dil_kaydi ? 'ikinci_alanlar' then nullif(p_dil_kaydi -> 'ikinci_alanlar', 'null'::jsonb) else d.ikinci_alanlar end,
           not_dili       = case when p_dil_kaydi ? 'not_dili' then p_dil_kaydi ->> 'not_dili' else d.not_dili end,
           ikinci_dil     = case when p_dil_kaydi ? 'ikinci_dil' then p_dil_kaydi ->> 'ikinci_dil' else d.ikinci_dil end,
           ikinci_s       = case when p_dil_kaydi ? 'ikinci_s' then p_dil_kaydi ->> 'ikinci_s' else d.ikinci_s end,
           ikinci_o       = case when p_dil_kaydi ? 'ikinci_o' then p_dil_kaydi ->> 'ikinci_o' else d.ikinci_o end,
           ikinci_a       = case when p_dil_kaydi ? 'ikinci_a' then p_dil_kaydi ->> 'ikinci_a' else d.ikinci_a end,
           ikinci_p       = case when p_dil_kaydi ? 'ikinci_p' then p_dil_kaydi ->> 'ikinci_p' else d.ikinci_p end,
           updated_at     = p_onay_ani
     where d.note_id = p_note_id and d.doctor_id = p_doctor_id and d.ulke = p_ulke;
    if not found then
      -- A note of this application always has its language record. Without it nothing is approved.
      raise exception 'ulke_not_onayla: not_dil_kaydi row missing' using errcode = 'P0002';
    end if;
  end if;

  -- The appointment this visit was started from is done. Only an appointment that still holds its time changes
  -- (planned or arrived), so this statement can never run into the no-double-booking constraint.
  update public.ulke_randevulari
     set durum = 'tamamlandi', updated_at = p_onay_ani
   where session_id = v_session and doctor_id = p_doctor_id and ulke = p_ulke and durum in ('planlandi', 'geldi');

  return 'TAMAM';
end $$;

revoke all on function public.ulke_not_onayla(text, uuid, uuid, timestamptz, text, text, text, text, jsonb) from public, anon, authenticated;
do $$
begin
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    grant execute on function public.ulke_not_onayla(text, uuid, uuid, timestamptz, text, text, text, text, jsonb) to service_role;
  end if;
end $$;

insert into schema_migrations (version, filename, checksum, applied_at, backfilled, note)
values ('135', '135_ulke_randevu.sql', null, now(), false,
  'NOTYA-ULKE-SABLON-01: per-account working pattern + country appointments (new tables, country and doctor in every key, exclusion constraint against double booking) + ulke_not_onayla (note approval in one transaction, bound to the country)')
on conflict (version) do nothing;

commit;
