/**
 * Analjezik / antipiretik / NSAİİ / kas gevşetici. Every entry read from the molecule's own TİTCK
 * KÜB (kaynak.url is the PDF that was opened); numbers not stated there are left empty.
 *
 * NSAİİ cross-allergy is modelled once, in `alerjiSinifi: ['nsaii']` + `siniflar` — the KÜBs all say
 * the same thing ("aspirin veya diğer NSAİİ'lere karşı astım/rinit/ürtiker geliştiren hastalarda
 * kontrendikedir"), and writing it per pair is how a table drifts.
 */
import { kub } from '../kaynak'
import type { TürkishDrug } from '../tipler'

const NSAII_SINIF = ['NSAİİ', 'NSAID', 'Nonsteroid antiinflamatuvar', 'Analjezik', 'Antipiretik'] as const

/** The interaction set every oral NSAİİ's §4.5 states, written once. */
const NSAII_ETKILESIM = [
  { ile: 'Varfarin', siddet: 'ciddi' as const, not: 'NSAİİ antikoagülan etkiyi artırır; GİS kanama riski sinerjik. INR takibi, mümkünse kaçının.' },
  { ile: 'Antikoagülan', siddet: 'ciddi' as const, not: 'Birlikte kullanımda ciddi gastrointestinal kanama riski belirgin artar (KÜB §4.5).' },
  { ile: 'Metotreksat', siddet: 'ciddi' as const, not: 'NSAİİ metotreksatın renal klerensini azaltır; hematolojik toksisite riski. Yüksek doz MTX ile birlikte verilmez.' },
  { ile: 'Lityum', siddet: 'ciddi' as const, not: 'Renal lityum klerensi azalır, plazma lityumu toksik düzeye çıkabilir. Lityum düzeyi izlenmeli.' },
  { ile: 'ACE inhibitörü', siddet: 'orta' as const, not: 'Antihipertansif etki azalır; diüretikle üçlü kullanımda akut böbrek yetmezliği riski.' },
  { ile: 'Anjiyotensin II reseptör blokeri', siddet: 'orta' as const, not: 'Antihipertansif etki azalır; hipovolemik/yaşlı hastada böbrek fonksiyonu bozulabilir.' },
  { ile: 'Diüretik', siddet: 'orta' as const, not: 'Natriüretik etki azalır; birlikte nefrotoksisite riski artar (KÜB §4.5).' },
  { ile: 'Kortikosteroid', siddet: 'ciddi' as const, not: 'GİS ülserasyon ve kanama riski artar; birlikte kullanımda gastroproteksiyon düşünülmeli.' },
  { ile: 'SSRI', siddet: 'ciddi' as const, not: 'Trombosit fonksiyonu üzerine sinerjik etki — gastrointestinal kanama riski artar.' },
  { ile: 'NSAİİ', siddet: 'ciddi' as const, not: 'İki NSAİİ birlikte kullanılmaz: yarar artmaz, ülser ve kanama riski artar (KÜB §4.5).' },
  { ile: 'Siklosporin', siddet: 'ciddi' as const, not: 'Renal prostaglandin inhibisyonu nedeniyle nefrotoksisite riski artar.' },
] as const

const NSAII_KONTRA = [
  'Aktif peptik ülser veya GİS kanama öyküsü',
  'Aspirin / NSAİİ alerjisi (astım, rinit, ürtiker, anjiyoödem)',
  'Şiddetli böbrek yetmezliği',
  'Şiddetli karaciğer yetmezliği',
  'Şiddetli kalp yetmezliği',
  'Gebeliğin 3. trimesteri',
]

export const ANALJEZIK: Record<string, TürkishDrug> = {
  parasetamol: {
    name: 'Parasetamol',
    brand: ['Parol', 'Minoset', 'Calpol', 'Tylol', 'Termalgine', 'Panadol', 'Vermidon', 'Geralgine-P'],
    dose: 'Yetişkin: 500–1000 mg, 4–6 saatte bir. Günlük maksimum 4 g (alkol kullanan hastada 2 g).',
    pediatricDose: '10–15 mg/kg/doz, 6 saatte bir (günlük maksimum 60 mg/kg)',
    pediatrik: {
      min: 10, max: 15, birim: 'mg/kg/doz', gunlukBolum: 4,
      maxMgKgGun: 60, mutlakMaxMgGun: 2000, mutlakMaxMgDoz: 500,
      metin: "KÜB §4.2: 6 saatte bir 10–15 mg/kg/doz; günlük maksimum 60 mg/kg. 30 kg üstü çocukta tek doz en fazla 500 mg, günlük en fazla 2 g. Doz aralığı en az 4 saat, günde 4 defadan fazla verilmez.",
    },
    form: 'Tablet, şurup, süspansiyon, supozituvar, IV',
    sgkCovered: true,
    category: 'Analjezik/Antipiretik',
    siniflar: ['Analjezik', 'Antipiretik', 'Anilid', 'Parasetamol'],
    contraindications: ['Parasetamol aşırı duyarlılığı', 'Şiddetli karaciğer yetmezliği (Child-Pugh >9)', 'Şiddetli böbrek yetmezliği (GFR <60 mL/dk)'],
    interactions: ['Varfarin (yüksek doz, uzun süre)', 'Flukloksasilin', 'Kloramfenikol', 'Zidovudin', 'Alkol'],
    etkilesimler: [
      { ile: 'Varfarin', siddet: 'orta', not: 'Uzun süreli yüksek doz parasetamol INR artışına ve kanama riskine yol açabilir; kısa süreli kullanım güvenli kabul edilir.' },
      { ile: 'Kloramfenikol', siddet: 'orta', not: 'Kloramfenikolün yarılanma ömrü uzayabilir, toksisite riski artar (KÜB §4.5).' },
      { ile: 'Zidovudin', siddet: 'ciddi', not: 'Nötropeni eğilimi artar; tıbbi tavsiye olmadıkça birlikte alınmamalıdır (KÜB §4.5).' },
      { ile: 'Flukloksasilin', siddet: 'orta', not: 'Yüksek anyon açıklı metabolik asidoz riski — birlikte kullanımda dikkat (KÜB §4.5).' },
    ],
    gebelik: { kategori: 'B', metin: 'Terapötik dozda kısa süreli kullanım insanda teratojenik etkiyle ilişkili bulunmamıştır (KÜB §4.6).' },
    emzirme: 'Anne sütüne geçer; önerilen dozlarda klinik olarak anlamlı düzeyde değildir, emzirme için kontrendikasyon yoktur.',
    bobrekDozUyarisi: true,
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: "Türkiye'de en yaygın antipiretik. Doz aşımı karaciğer nakli/ölümle sonuçlanabilen hepatotoksisite yapar — birden fazla kombine soğuk algınlığı preparatında birlikte bulunabilir.",
    kaynak: kub('TYLOL 6 PLUS 250 MG/5 ML SÜSPANSİYON (onay 12/09/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/TTCKOnaylKBTYLOL6PLUS_7a97996a-9ac9-4d61-8a23-5dfd238a6a83.pdf'),
  },

  ibuprofen: {
    name: 'İbuprofen',
    brand: ['Brufen', 'Dolven', 'Nurofen', 'Advil', 'Profen', 'Suprafen', 'Arfen'],
    dose: 'Yetişkin: 400–800 mg, günde 3–4 kez. Günlük maksimum 2400 mg.',
    pediatricDose: '20–30 mg/kg/gün, 3–4 doza bölünmüş (6 ay ve >7 kg üstü)',
    pediatrik: {
      min: 20, max: 30, birim: 'mg/kg/gün', gunlukBolum: 3,
      maxMgKgGun: 30, mutlakMaxMgGun: 2400, enAzAy: 6,
      metin: 'KÜB §4.2: 6 ay–12 yaş ve >7 kg çocukta bölünmüş dozlar halinde 20–30 mg/kg/gün; dozlar 6 saatte bir, günde en fazla 4 defa. 6 aylıktan küçük veya 7 kg altındaki çocuklarda kullanılmaz.',
    },
    form: 'Tablet, film tablet, pediatrik şurup, süspansiyon',
    sgkCovered: true,
    category: 'NSAİİ',
    siniflar: [...NSAII_SINIF, 'Propiyonik asit türevi', 'Siklooksijenaz inhibitörü'],
    alerjiSinifi: ['nsaii'],
    yasKontrendikasyonAy: 6,
    contraindications: [...NSAII_KONTRA, '6 ay altı bebek', '7 kg altı çocuk', 'Şiddetli kalp yetmezliği (NYHA IV)'],
    interactions: ['Varfarin', 'Metotreksat', 'Lityum', 'ACE inhibitörleri', 'Aspirin', 'Diüretikler', 'Kortikosteroidler', 'SSRI', 'Aminoglikozidler', 'Zidovudin'],
    etkilesimler: [
      ...NSAII_ETKILESIM,
      { ile: 'Asetilsalisilik asit', siddet: 'orta', not: 'İbuprofen düşük doz aspirinin kardiyoprotektif antiagregan etkisini azaltabilir (KÜB §4.5).' },
      { ile: 'Aminoglikozid', siddet: 'orta', not: 'NSAİİ aminoglikozitlerin atılımını azaltır; nefrotoksisite/ototoksisite riski artar.' },
      { ile: 'Zidovudin', siddet: 'orta', not: 'Hematolojik toksisite riski artar; hemofili hastalarında hemartroz bildirilmiştir (KÜB §4.5).' },
      { ile: 'Digoksin', siddet: 'orta', not: 'NSAİİ glomerüler filtrasyonu azaltır, plazma digoksin düzeyi yükselebilir.' },
    ],
    gebelik: { kategori: 'C', metin: '3. trimesterde kontrendike (duktus arteriosusun erken kapanması). Erken gebelikte düşük ve malformasyon riskinde artış bildirilmiştir (KÜB §4.6).' },
    emzirme: 'Anne sütüne çok düşük düzeyde geçer; kısa süreli kullanımda genellikle uyumlu kabul edilir.',
    bobrekDozUyarisi: true,
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    kaynak: kub('DOLVEN 100 MG/5 ML PEDİATRİK ŞURUP (onay 15/05/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/DolvenKBONAY_18_05_2026.pdf'),
  },

  naproksen: {
    name: 'Naproksen',
    brand: ['Apranax', 'Naprosyn', 'Flamaks', 'Naproks', 'Xenar', 'Aleve'],
    dose: 'Yetişkin: başlangıç 500–1000 mg/gün, 12 saat arayla 2 doza bölünmüş. İdame 500–1000 mg/gün.',
    form: 'Tablet, fort tablet, jel',
    sgkCovered: true,
    category: 'NSAİİ',
    siniflar: [...NSAII_SINIF, 'Propiyonik asit türevi', 'Siklooksijenaz inhibitörü'],
    alerjiSinifi: ['nsaii'],
    contraindications: [...NSAII_KONTRA, '16 yaş altı çocuklarda güvenlilik/etkililik gösterilmemiştir', 'Koroner arter bypass greft cerrahisi perioperatif dönemi'],
    interactions: ['Varfarin', 'Metotreksat', 'Lityum', 'Probenesid', 'Siklosporin', 'Beta blokörler', 'ACE inhibitörleri', 'Kortikosteroidler', 'Sülfonilüre', 'Takrolimus'],
    etkilesimler: [
      ...NSAII_ETKILESIM,
      { ile: 'Probenesid', siddet: 'orta', not: 'Naproksen plazma konsantrasyonu ve yarı ömrü artar (KÜB §4.5).' },
      { ile: 'Beta blokör', siddet: 'orta', not: 'Beta blokörlerin antihipertansif etkisi azalır (KÜB §4.5).' },
      { ile: 'Sülfonilüre', siddet: 'orta', not: 'Hipoglisemik etki güçlenebilir; doz ayarı gerekebilir.' },
      { ile: 'Takrolimus', siddet: 'orta', not: 'Nefrotoksisite riski artar.' },
    ],
    gebelik: { kategori: 'C', metin: '3. trimesterde kontrendike; 1. ve 2. trimesterde yeterli veri yok, gerekli olmadıkça kullanılmaz (KÜB §4.6).' },
    emzirme: 'Anne sütünde plazma konsantrasyonunun ~%1\'i bulunur; yenidoğanda prostaglandin inhibisyonu riski nedeniyle tercih edilmez.',
    bobrekDozUyarisi: true,
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    kaynak: kub('FLAMAKS FORT 500 MG TABLET (onay 23/07/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/xEkEk41311kubtemizkopya_24_07_2026.pdf'),
  },

  diklofenak: {
    name: 'Diklofenak',
    brand: ['Voltaren', 'Dicloflam', 'Dikloron', 'Cataflam', 'Voltfast', 'Miyadren'],
    dose: 'Yetişkin: başlangıç 100–150 mg/gün, 2–3 doza bölünmüş. Maksimum günlük doz 150 mg, aşılmamalıdır.',
    form: 'Tablet, kaplı tablet, IM ampul, jel, supozituvar',
    sgkCovered: true,
    category: 'NSAİİ',
    siniflar: [...NSAII_SINIF, 'Asetik asit türevi', 'Siklooksijenaz inhibitörü'],
    alerjiSinifi: ['nsaii'],
    yasKontrendikasyonAy: 168,
    contraindications: [...NSAII_KONTRA, '14 yaş altı çocuklarda önerilmez', 'Konjestif kalp yetmezliği (NYHA II-IV)', 'İskemik kalp hastalığı', 'Periferik arter hastalığı', 'Serebrovasküler hastalık'],
    interactions: ['Varfarin', 'Lityum', 'Digoksin', 'Metotreksat', 'Siklosporin', 'Takrolimus', 'Kinolonlar', 'Diüretikler', 'ACE inhibitörleri', 'Kortikosteroidler', 'Vorikonazol'],
    etkilesimler: [
      ...NSAII_ETKILESIM,
      { ile: 'Digoksin', siddet: 'orta', not: 'Diklofenak digoksinin plazma konsantrasyonunu yükseltebilir (KÜB §4.5).' },
      { ile: 'Kinolon', siddet: 'orta', not: 'Birlikte kullanımda çok ender konvülsiyon bildirilmiştir; epilepsi öyküsünde dikkat (KÜB §4.5).' },
      { ile: 'Takrolimus', siddet: 'orta', not: 'Nefrotoksisite riskinde artış.' },
      { ile: 'Vorikonazol', siddet: 'orta', not: 'Güçlü CYP2C9 inhibitörü — diklofenak maruziyeti artar, doz azaltımı gerekebilir.' },
    ],
    gebelik: { kategori: 'C', metin: '3. trimesterde kontrendike. Kadın fertilitesini olumsuz etkiler; gebe kalmaya çalışan kadınlarda önerilmez (KÜB §4.4/4.6).' },
    emzirme: 'Anne sütüne az miktarda geçer; uzun süreli kullanım önerilmez.',
    bobrekDozUyarisi: true,
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    kaynak: kub('DİCLOFLAM 50 MG KAPLI TABLET (onay 30/03/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/ek3kubtemizkopya_01_04_2026.pdf'),
  },

  deksketoprofen: {
    name: 'Deksketoprofen',
    brand: ['Arveles', 'Dexofen', 'Deksalgin', 'Ketesse'],
    dose: 'Yetişkin: 4–6 saatte bir 12,5 mg veya 8 saatte bir 25 mg. Günlük toplam doz 75 mg\'ı geçmemelidir.',
    form: 'Film kaplı tablet, granül, ampul',
    sgkCovered: true,
    category: 'NSAİİ',
    siniflar: [...NSAII_SINIF, 'Propiyonik asit türevi', 'Siklooksijenaz inhibitörü'],
    alerjiSinifi: ['nsaii'],
    yasKontrendikasyonAy: 216,
    contraindications: [...NSAII_KONTRA, '18 yaş altı çocuk ve adolesanlarda çalışma yoktur, kullanılmaz', 'Ketoprofen veya fibratlarla fotoalerjik/fototoksik reaksiyon öyküsü', 'Crohn hastalığı / ülseratif kolit'],
    interactions: ['Varfarin', 'Heparin', 'Metotreksat', 'Lityum', 'Diüretikler', 'ACE inhibitörleri', 'Aminoglikozidler', 'Aspirin', 'Kortikosteroidler', 'SSRI'],
    etkilesimler: [...NSAII_ETKILESIM, { ile: 'Heparin', siddet: 'ciddi', not: 'Trombosit fonksiyonu inhibisyonu + mukoza hasarı — hemoraji riski artar (KÜB §4.5).' }],
    gebelik: { kategori: 'C', metin: '3. trimesterde kontrendike (KÜB §4.3/4.6).' },
    emzirme: 'Anne sütüne geçip geçmediği bilinmiyor; emzirme döneminde kontrendikedir.',
    bobrekDozUyarisi: true,
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Hafif böbrek yetmezliğinde (KrKl 60–89) günlük doz 50 mg\'a indirilir; orta/şiddetli böbrek yetmezliğinde kullanılmaz.',
    kaynak: kub('ARVELES 25 MG FİLM KAPLI TABLET (onay 24/02/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/UYGUNKBARVELESTABLET2_24_02_2026.pdf'),
  },

  metamizol: {
    name: 'Metamizol sodyum',
    brand: ['Novalgin', 'Geralgine-M', 'Adepiron', 'Andolor'],
    dose: 'Yetişkin ve ≥15 yaş (>53 kg): tek doz 500–1000 mg, günde en fazla 4 kez (6–8 saat arayla). Günlük maksimum 4000 mg.',
    pediatricDose: 'Tek doz 8–16 mg/kg; ateşte genellikle 10 mg/kg yeterli (3 aylıktan itibaren)',
    pediatrik: {
      min: 8, max: 16, birim: 'mg/kg/doz', gunlukBolum: 4,
      maxMgKgGun: 64, mutlakMaxMgGun: 4000, enAzAy: 3,
      metin: 'KÜB §4.2: 14 yaşına kadar çocuklarda tek doz 8–16 mg/kg; ateşte genellikle 10 mg/kg yeterlidir. Tek doz günde 4 kez, 6–8 saat arayla (günlük tavan tek dozun 4 katı). 3 aylıktan küçük bebeklere uygulanmaz.',
    },
    form: 'Tablet, şurup, ampul',
    sgkCovered: true,
    category: 'Pirazolon analjezik',
    siniflar: ['Analjezik', 'Antipiretik', 'Pirazolon', 'Nonopioid analjezik'],
    yasKontrendikasyonAy: 3,
    contraindications: [
      'Metamizol / pirazolon / pirazolidin aşırı duyarlılığı',
      'Pirazolonlara bağlı agranülositoz öyküsü',
      'Kemik iliği fonksiyon bozukluğu veya hematopoietik sistem hastalığı',
      'Analjezik astım sendromu veya ürtiker-anjiyoödem analjezik intoleransı',
      'Akut hepatik porfiri',
      'G6PD eksikliği',
      '3 ay altı bebek',
    ],
    interactions: ['Siklosporin', 'Klorpromazin', 'Asetilsalisilik asit (düşük doz)', 'Metotreksat', 'Bupropion'],
    etkilesimler: [
      { ile: 'Siklosporin', siddet: 'ciddi', not: 'Metamizol CYP3A4 indüksiyonu ile siklosporin düzeyini düşürür; düzey takibi zorunlu (KÜB §4.5).' },
      { ile: 'Klorpromazin', siddet: 'ciddi', not: 'Birlikte kullanımda ağır hipotermi gelişebilir — kombinasyondan kaçınılmalıdır (KÜB §4.5).' },
      { ile: 'Asetilsalisilik asit', siddet: 'orta', not: 'Düşük doz aspirinin antiagregan (kardiyoprotektif) etkisini azaltabilir (KÜB §4.5).' },
      { ile: 'Metotreksat', siddet: 'ciddi', not: 'Hematotoksisite riski artar; özellikle yaşlılarda birlikte kullanımdan kaçınılmalıdır.' },
    ],
    gebelik: { metin: '1. ve 2. trimesterde gerekli olmadıkça kullanılmaz; 3. trimesterde kontrendike (duktus arteriosus kapanması, KÜB §4.6).' },
    emzirme: 'Metabolitleri anne sütüne geçer; alımdan sonra 48 saat emzirmeye ara verilmelidir.',
    renkliRecete: 'normal',
    notes: "Agranülositoz riski nedeniyle birçok ülkede ruhsatı yoktur; Türkiye'de ruhsatlıdır. Ateş/boğaz ağrısı/ağız ülseri gelişirse ilaç kesilip tam kan sayımı istenmelidir.",
    kaynak: kub('GERALGİNE-M 250 MG/5 ML ŞURUP (onay 01/09/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/kubGERALGNEM250mg5mlurup_b5bf9e25-6db4-405a-80c6-c0108c09f5f2.pdf'),
  },

  asetilsalisilikAsit: {
    name: 'Asetilsalisilik asit',
    brand: ['Aspirin', 'Coraspin', 'Ecopirin', 'Dispril', 'Opirin'],
    dose: 'Analjezik/antipiretik (≥16 yaş): 4–8 saatte bir 500–1000 mg, günlük maksimum 4 g. Antiagregan: 75–100 mg 1x1.',
    form: 'Tablet, efervesan tablet, enterik kaplı tablet',
    sgkCovered: true,
    category: 'Salisilat / antiagregan',
    siniflar: ['NSAİİ', 'Salisilat', 'Antiagregan', 'Trombosit agregasyon inhibitörü', 'Analjezik', 'Antipiretik'],
    alerjiSinifi: ['nsaii', 'aspirin'],
    yasKontrendikasyonAy: 192,
    contraindications: [
      'Asetilsalisilik asit / salisilat aşırı duyarlılığı',
      'NSAİİ ile tetiklenen astım öyküsü',
      'Akut gastrointestinal ülser',
      'Hemorajik diyatez',
      'Şiddetli karaciğer yetmezliği',
      'Şiddetli böbrek yetmezliği',
      'Şiddetli kalp yetmezliği',
      '≥15 mg/hafta metotreksat ile birlikte kullanım',
      'Gebeliğin son trimesteri',
      '16 yaş altı çocuklarda doktor tavsiyesi olmadan kullanılmaz (Reye sendromu)',
    ],
    interactions: ['Metotreksat', 'Varfarin', 'Heparin', 'NSAİİ', 'SSRI', 'Trombolitikler', 'Kortikosteroidler', 'Asetazolamid', 'Probenesid'],
    etkilesimler: [
      { ile: 'Metotreksat', siddet: 'ciddi', not: '≥15 mg/hafta metotreksat ile birlikte kullanım KONTRENDİKE: renal klerens azalır, salisilat MTX\'i proteinden ayırır (KÜB §4.3/4.5).' },
      { ile: 'Varfarin', siddet: 'ciddi', not: 'Kanama riski belirgin artar; kombinasyon ancak açık endikasyonla ve yakın INR takibiyle.' },
      { ile: 'Antikoagülan', siddet: 'ciddi', not: 'Antiagregan + antikoagülan: majör kanama riski artar (KÜB §4.5).' },
      { ile: 'NSAİİ', siddet: 'ciddi', not: 'Yüksek doz ASA + NSAİİ: GİS ülser ve kanama riskinde artış.' },
      { ile: 'SSRI', siddet: 'ciddi', not: 'Sinerjik trombosit etkisi — gastrointestinal kanama riski artar (KÜB §4.5).' },
      { ile: 'Kortikosteroid', siddet: 'ciddi', not: 'GİS ülser/kanama riski artar.' },
      { ile: 'Trombolitik', siddet: 'ciddi', not: 'Trombolitik tedaviden önce alındığında kanama riski artar (KÜB §4.5).' },
      { ile: 'İbuprofen', siddet: 'orta', not: 'İbuprofen düşük doz aspirinin kardiyoprotektif etkisini azaltabilir; aspirinden 2 saat sonra alınmalı.' },
    ],
    gebelik: { kategori: 'B', metin: 'Son trimesterde kontrendike. Erken gebelikte düşük ve malformasyon riskinde artış bildirilmiştir (KÜB §4.6). Preeklampsi profilaksisinde düşük doz kullanımı ayrı endikasyondur.' },
    emzirme: 'Anne sütüne geçer; analjezik dozlarda düzenli kullanım önerilmez.',
    bobrekDozUyarisi: true,
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Çocukta viral enfeksiyon sırasında Reye sendromu riski — pediatride antipiretik olarak kullanılmaz.',
    kaynak: kub('ASPİRİN 500 MG TABLET (onay 27/11/2025)', 'https://titck.gov.tr/storage/Archive/2025/kubKtAttachments/onaylkb_01_12_2025.pdf'),
  },

  flurbiprofen: {
    name: 'Flurbiprofen',
    brand: ['Majezik', 'Flurflex', 'Maxaljin', 'Ansaid'],
    dose: 'Yetişkin: 150–200 mg/gün bölünmüş dozlar halinde; gerekirse 300 mg/gün. Maksimum günlük doz 300 mg.',
    form: 'Film tablet, supozituvar, boğaz pastili',
    sgkCovered: true,
    category: 'NSAİİ',
    siniflar: [...NSAII_SINIF, 'Propiyonik asit türevi', 'Siklooksijenaz inhibitörü'],
    alerjiSinifi: ['nsaii'],
    contraindications: [...NSAII_KONTRA, 'Aspirin triadı (astım + nazal polip + NSAİİ intoleransı)'],
    interactions: ['Varfarin', 'Lityum', 'Metotreksat', 'ACE inhibitörleri', 'ARB', 'Beta blokörler', 'Diüretikler', 'Aspirin', 'Kortikosteroidler'],
    etkilesimler: [...NSAII_ETKILESIM, { ile: 'Propranolol', siddet: 'orta', not: 'Flurbiprofen propranololün hipotansif etkisini azaltır (atenololde bu etki gözlenmemiştir, KÜB §4.5).' }],
    gebelik: { metin: '3. trimesterde kullanılmaz (duktus arteriosusun erken kapanması). Erken gebelikte düşük/malformasyon riskinde artış (KÜB §4.6).' },
    emzirme: 'Anne sütüne geçer; emzirme döneminde önerilmez.',
    bobrekDozUyarisi: true,
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    kaynak: kub('FLURFLEX 100 MG FİLM TABLET (onay 10/09/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/UygunbulunanKBmetni38_304fe278-305c-4eb0-a420-cf4c4105476d.pdf'),
  },

  meloksikam: {
    name: 'Meloksikam',
    brand: ['Melox', 'Zeloxim', 'Runomex', 'Mobic', 'Exen'],
    dose: 'Osteoartrit alevlenmesi: 7,5 mg/gün (gerekirse 15 mg/gün). Romatoid artrit / ankilozan spondilit: 15 mg/gün.',
    form: 'Tablet, ampul, supozituvar',
    sgkCovered: true,
    category: 'NSAİİ',
    siniflar: [...NSAII_SINIF, 'Oksikam', 'Siklooksijenaz inhibitörü'],
    alerjiSinifi: ['nsaii'],
    yasKontrendikasyonAy: 192,
    contraindications: [...NSAII_KONTRA, '16 yaş altı çocuk ve adolesanlarda kullanılmaz', 'Koroner arter bypass greft cerrahisi perioperatif dönemi'],
    interactions: ['Varfarin', 'Heparin', 'Metotreksat', 'Lityum', 'Diüretikler', 'ACE inhibitörleri', 'ARB', 'Kortikosteroidler', 'SSRI', 'SNRI', 'Siklosporin'],
    etkilesimler: [
      ...NSAII_ETKILESIM,
      { ile: 'Heparin', siddet: 'ciddi', not: 'Küratif dozda heparin ile birlikte kullanım önerilmez — kanama riski (KÜB §4.5).' },
      { ile: 'SNRI', siddet: 'ciddi', not: 'Gastrointestinal kanama riski artar (KÜB §4.5).' },
    ],
    gebelik: { kategori: 'C', metin: 'Gebeliğin ileri dönemlerinde kaçınılmalıdır (duktus arteriosusun erken kapanması). Gebe kalmayı planlayan kadınlarda önerilmez (KÜB §4.4/4.6).' },
    emzirme: 'Anne sütüne geçer; emzirme döneminde önerilmez.',
    bobrekDozUyarisi: true,
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Ağır böbrek yetmezliği olan diyaliz hastasında günlük doz 7,5 mg\'ı geçmemelidir.',
    kaynak: kub('RUNOMEX FORT 15 MG TABLET (onay 12/08/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/RUNOMEXFORT15mgtabletKUB_5f1449c8-8b26-4834-8dae-080152514367.pdf'),
  },

  etodolak: {
    name: 'Etodolak',
    brand: ['Lodine', 'Edolar', 'Tadolak'],
    dose: 'Yetişkin: 300–1200 mg/gün, günde 2 doza bölünmüş. Maksimum günlük doz 1200 mg.',
    form: 'Film tablet, SR tablet',
    sgkCovered: true,
    category: 'NSAİİ',
    siniflar: [...NSAII_SINIF, 'Asetik asit türevi', 'Siklooksijenaz inhibitörü'],
    alerjiSinifi: ['nsaii'],
    yasKontrendikasyonAy: 216,
    contraindications: [...NSAII_KONTRA, '18 yaş altı çocuklarda kullanımı önerilmez', 'By-pass/kalp ameliyatı öncesi veya hemen sonrası'],
    interactions: ['Varfarin', 'Lityum', 'Metotreksat', 'ACE inhibitörleri', 'Diüretikler', 'Aspirin', 'Digoksin', 'SSRI', 'Probenesid', 'Fenilbutazon'],
    etkilesimler: [
      ...NSAII_ETKILESIM,
      { ile: 'Digoksin', siddet: 'orta', not: 'Kalp yetmezliği şiddetlenebilir, GFR azalır, plazma glikozid düzeyi yükselebilir (KÜB §4.5).' },
      { ile: 'Probenesid', siddet: 'orta', not: 'Etodolakın yan etki riskini artırır (KÜB §4.5).' },
    ],
    gebelik: { metin: 'NSAİİ sınıf etkisi: doğumda gecikme ve distosi; ileri gebelikte kullanılmaz (KÜB §4.6).' },
    emzirme: 'Anne sütüne geçişi bilinmiyor; emzirme döneminde önerilmez.',
    bobrekDozUyarisi: true,
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    kaynak: kub('LODİNE 300 MG FİLM TABLET (onay 07/12/2025)', 'https://titck.gov.tr/storage/Archive/2025/kubKtAttachments/LODNKB_10_12_2025.pdf'),
  },

  tiyokolsikosid: {
    name: 'Tiyokolşikosid',
    brand: ['Muscoflex', 'Adeleks', 'Miyokol', 'Tiyoson', 'Coltis'],
    dose: 'Yetişkin: 12 saatte bir 8 mg (günde 2 kez). Günlük maksimum 16 mg. Tedavi süresi ardışık 7 günü geçmemelidir.',
    form: 'Tablet, kapsül, ampul, pomat',
    sgkCovered: true,
    category: 'Kas gevşetici',
    siniflar: ['Kas gevşetici', 'Miyorelaksan', 'Santral etkili kas gevşetici'],
    yasKontrendikasyonAy: 192,
    contraindications: [
      'Tiyokolşikosid aşırı duyarlılığı',
      'Gevşek paralizi, kas hipotonisi',
      'Gebelik',
      'Emzirme',
      '16 yaş altı çocuklar',
      'Etkili doğum kontrolü kullanmayan çocuk doğurma potansiyeli olan kadınlar',
    ],
    interactions: ['Diğer kas gevşeticiler', 'NSAİİ'],
    etkilesimler: [{ ile: 'Kas gevşetici', siddet: 'orta', not: 'Diğer kas gevşeticilerle birlikte alınması etkileri karşılıklı artırabilir; önerilmez (KÜB §4.5).' }],
    gebelik: { kategori: 'X', metin: 'Gebelikte KONTRENDİKE — hayvan çalışmalarında teratojenik etki dahil üreme toksisitesi (KÜB §4.3/4.6).' },
    emzirme: 'Anne sütüne geçtiği için emzirme döneminde kontrendikedir.',
    renkliRecete: 'normal',
    notes: 'Tedaviden sonra kadınlarda 1 ay, erkeklerde 3 ay etkili kontrasepsiyon şartı KÜB\'de kontrendikasyon olarak yazılıdır.',
    kaynak: kub('ADELEKS 4 MG TABLET (onay 20/01/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/adeleks4yaynlanacakkb_30_01_2026.pdf'),
  },

  tramadol: {
    name: 'Tramadol',
    brand: ['Contramal', 'Tramosel', 'Tramadolor', 'Ultram'],
    dose: 'Yetişkin ve >12 yaş: 4–6 saatte bir 50–100 mg. Günlük doz 400 mg\'ı aşmamalıdır.',
    form: 'Kapsül, SR tablet, damla, ampul',
    sgkCovered: true,
    sgkRestriction: 'Kontrole tabi ilaç — yeşil reçete ile düzenlenir (TİTCK 20.02.2016).',
    category: 'Opioid analjezik',
    siniflar: ['Opioid', 'Opioid analjezik', 'Zayıf opioid', 'Analjezik', 'SSS depresanı'],
    yasKontrendikasyonAy: 144,
    contraindications: [
      'Tramadol aşırı duyarlılığı',
      'Alkol / hipnotik / analjezik / opioid / psikotrop madde ile akut intoksikasyon',
      'MAO inhibitörü kullanımı (son 14 gün)',
      'Kontrol edilemeyen epilepsi',
      '12 yaş altı çocuklar',
      '18 yaş altı tonsil/adenoid cerrahisi sonrası ağrı',
    ],
    interactions: ['MAO inhibitörleri', 'SSRI', 'SNRI', 'Triptanlar', 'Varfarin', 'Karbamazepin', 'Benzodiazepinler', 'Ketokonazol', 'Eritromisin'],
    etkilesimler: [
      { ile: 'MAO inhibitörü', siddet: 'ciddi', not: 'KONTRENDİKE — son 14 gün içinde MAOI alan hastada birlikte kullanılmaz (KÜB §4.3).' },
      { ile: 'SSRI', siddet: 'ciddi', not: 'Serotonin sendromu riski (ajitasyon, terleme, klonus, hipertermi). Birlikte başlanırsa yakın izlem (KÜB §4.5).' },
      { ile: 'SNRI', siddet: 'ciddi', not: 'Serotonin sendromu riski; ayrıca nöbet eşiğini birlikte düşürürler.' },
      { ile: 'Triptan', siddet: 'ciddi', not: 'Serotonerjik yük artar — serotonin sendromu riski.' },
      { ile: 'Benzodiazepin', siddet: 'ciddi', not: 'Ek SSS depresyonu: sedasyon, solunum depresyonu, koma ve ölüm riski artar (KÜB §4.5).' },
      { ile: 'Varfarin', siddet: 'ciddi', not: 'INR artışı ile majör kanama ve ekimoz bildirilmiştir; INR takibi (KÜB §4.5).' },
      { ile: 'Karbamazepin', siddet: 'orta', not: 'Enzim indüksiyonu ile tramadolün analjezik etkisi azalır ve süresi kısalır.' },
    ],
    gebelik: { kategori: 'C', metin: 'İnsanda gebelikte güvenlilik verisi çok az; gebe kadınlarda kullanılmamalıdır (KÜB §4.6).' },
    emzirme: 'Anne sütüne geçer; emzirme döneminde tek doz dışında önerilmez.',
    renkliRecete: 'yesil',
    notes: 'Nöbet eşiğini düşürür. CYP2D6 ultrahızlı metabolize edicilerde solunum depresyonu riski.',
    kaynak: kub('CONTRAMAL 100 MG/ML DAMLA, ÇÖZELTİ (onay 06/03/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/TTCKOnaylKBCONTRAMAL_17_03_2026.pdf'),
  },
}
