/**
 * Kinolonlar, üriner antiseptikler, antitüberküloz, antifungaller, antiviraller.
 *
 * Two class facts carry most of this file's safety weight and are therefore written as class labels
 * (`siniflar`) rather than pair by pair:
 *   • florokinolonlar — tendon rüptürü, nöbet eşiğini düşürme, QT uzatma, katyonlarla şelasyon;
 *   • azol antifungaller — güçlü CYP3A4 inhibisyonu, QT uzatma.
 * Both let `ilacUyari.ts` fire on a class the KÜB names ("QT uzatan ilaçlar") without a second table.
 */
import { kub } from '../kaynak'
import type { TürkishDrug } from '../tipler'

const KINOLON_ETKILESIM = [
  { ile: 'Demir', siddet: 'orta' as const, not: 'İki/üç değerlikli katyonlar kinolon emilimini belirgin azaltır; kinolon 1–2 saat önce veya 4 saat sonra alınmalı (KÜB §4.5).' },
  { ile: 'Antiasit', siddet: 'orta' as const, not: 'Magnezyum/alüminyum içeren antiasit emilimi düşürür; saat ayrımı şart (KÜB §4.5).' },
  { ile: 'Kalsiyum', siddet: 'orta' as const, not: 'Süt ürünleri ve mineral katkılı içecekler emilimi azaltır; birlikte alınmamalı.' },
  { ile: 'Çinko', siddet: 'orta' as const, not: 'Çinko içeren multivitaminler oral emilimi azaltır (KÜB §4.5).' },
  { ile: 'Sukralfat', siddet: 'orta' as const, not: 'Biyoyararlanımı önemli ölçüde düşürür; sukralfat kinolondan en az 2 saat sonra verilmeli.' },
  { ile: 'Varfarin', siddet: 'ciddi' as const, not: 'PT/INR ve kanamada şiddetli olabilen artışlar bildirilmiştir; INR sık izlenmeli (KÜB §4.5).' },
  { ile: 'Teofilin', siddet: 'ciddi' as const, not: 'Teofilin serum düzeyi yükselir, konvülsiyon riski; düzey izlenmeli ve doz azaltılmalı (KÜB §4.5).' },
  { ile: 'NSAİİ', siddet: 'orta' as const, not: 'Kinolonla birlikte konvülsiyon eşiği daha da düşer; epilepsi öyküsünde dikkat (KÜB §4.5).' },
  { ile: 'Kortikosteroid', siddet: 'ciddi' as const, not: 'Tendinit ve tendon rüptürü riski belirgin artar, özellikle 60 yaş üstünde.' },
  { ile: 'QT uzatan ilaç', siddet: 'ciddi' as const, not: 'Kinolonlar QT\'yi uzatır; Sınıf IA/III antiaritmik, trisiklik, makrolid veya antipsikotikle birlikte aritmi riski artar (KÜB §4.5).' },
  { ile: 'Metotreksat', siddet: 'ciddi' as const, not: 'Renal tübüler taşınma yarışması ile MTX düzeyi yükselir; toksik reaksiyon riski (KÜB §4.5).' },
  { ile: 'Siklosporin', siddet: 'orta' as const, not: 'Serum kreatinin artışı bildirilmiştir; böbrek fonksiyonu izlenmeli.' },
] as const

const KINOLON_KONTRA = [
  'Kinolon grubu antibiyotiklere aşırı duyarlılık',
  'Florokinolon kullanımına bağlı tendon hastalığı/hasarı öyküsü',
  'Miyastenia gravis',
]

export const ANTIINFEKTIF: Record<string, TürkishDrug> = {
  siprofloksasin: {
    name: 'Siprofloksasin',
    brand: ['Cipro', 'Cipronatin', 'Siprosan', 'Ciproxin', 'Cifloks'],
    dose: 'Yetişkin: 12 saatte bir 250–750 mg (endikasyona göre). Komplike olmayan sistit: 12 saatte bir 250–500 mg, 3 gün.',
    pediatricDose: 'Yalnız seçilmiş endikasyonlarda (kistik fibroz, komplike ÜSE/piyelonefrit): 10–20 mg/kg, günde iki kez',
    pediatrik: {
      min: 10, max: 20, birim: 'mg/kg/doz', gunlukBolum: 2,
      mutlakMaxMgDoz: 750,
      metin: 'KÜB §4.2: pediatride yalnızca seçilmiş endikasyonlarda — kistik fibrozda günde iki kez 10 mg/kg (doz başına en fazla 750 mg), komplike ÜSE/piyelonefritte günde iki kez 10–20 mg/kg. Genel pediatrik kullanım kıkırdak hasarı riski nedeniyle önerilmez.',
    },
    form: 'Film kaplı tablet, IV infüzyon, göz/kulak damlası',
    sgkCovered: true,
    category: 'Florokinolon antibiyotik',
    siniflar: ['Kinolon', 'Florokinolon', 'Antibiyotik', 'QT uzatan ilaç'],
    alerjiSinifi: ['kinolon'],
    contraindications: [...KINOLON_KONTRA, 'Tizanidin ile birlikte kullanım'],
    interactions: ['Tizanidin', 'Teofilin', 'Varfarin', 'Metotreksat', 'Demir', 'Antiasitler', 'Sukralfat', 'Süt ürünleri', 'NSAİİ', 'Kortikosteroidler', 'QT uzatan ilaçlar'],
    etkilesimler: [
      ...KINOLON_ETKILESIM,
      { ile: 'Tizanidin', siddet: 'ciddi', not: 'KONTRENDİKE — tizanidin serum düzeyi 7–10 kat artar; ciddi hipotansiyon ve sedasyon (KÜB §4.3/4.5).' },
      { ile: 'Omeprazol', siddet: 'orta', not: 'Siprofloksasinin Cmaks ve EAA değerlerinde hafif düşüş (KÜB §4.5).' },
    ],
    gebelik: { kategori: 'C', metin: 'İnsan verisinde malformasyon gösterilmemiştir, ancak immatür organizmada artiküler kıkırdak hasarı olasılığı dışlanamaz (KÜB §4.6).' },
    emzirme: 'Anne sütüne geçer; kısa kürlerde genellikle kabul edilir, uzun kullanımda önerilmez.',
    bobrekDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Tendinit/tendon rüptürü ilk haftalarda görülebilir; 60 yaş üstü ve kortikosteroid kullananlarda risk yüksektir.',
    kaynak: kub('CİPRONATİN 250 MG FİLM KAPLI TABLET (onay 30/07/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/Ekek41311kubtemiz_31_07_2026.pdf'),
  },

  levofloksasin: {
    name: 'Levofloksasin',
    brand: ['Tavanic', 'Levonat', 'Levoflox', 'Cravit'],
    dose: 'Yetişkin (KrKl >50): endikasyona göre günde bir veya iki kez 500 mg. Toplum kökenli pnömonide 500 mg 1–2x1, 7–14 gün.',
    form: 'Film kaplı tablet, IV infüzyon, göz damlası',
    sgkCovered: true,
    category: 'Florokinolon antibiyotik',
    siniflar: ['Kinolon', 'Florokinolon', 'Antibiyotik', 'QT uzatan ilaç'],
    alerjiSinifi: ['kinolon'],
    yasKontrendikasyonAy: 216,
    contraindications: [
      ...KINOLON_KONTRA,
      'Epilepsi',
      'Çocuklar ve büyümesi devam eden ergenler',
      'Gebelik',
      'Emzirme',
    ],
    interactions: ['Demir', 'Antiasitler', 'Sukralfat', 'Çinko', 'Teofilin', 'Varfarin', 'NSAİİ', 'Siklosporin', 'Kortikosteroidler', 'QT uzatan ilaçlar'],
    etkilesimler: KINOLON_ETKILESIM,
    gebelik: { kategori: 'C', metin: 'Gebelikte KONTRENDİKE — büyüyen organizmanın ağırlık taşıyan kıkırdağına zarar verme riski (KÜB §4.3/4.6).' },
    emzirme: 'Emzirme döneminde kontrendikedir (KÜB §4.3).',
    bobrekDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Karaciğerde önemli ölçüde metabolize olmaz — karaciğer yetmezliğinde doz ayarı gerekmez, böbrek yetmezliğinde gerekir.',
    kaynak: kub('LEVONAT 500 MG FİLM KAPLI TABLET (onay 31/03/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/LEVONAT500mgfilmkapltabletkub_01_04_2026.pdf'),
  },

  moksifloksasin: {
    name: 'Moksifloksasin',
    brand: ['Avelox', 'Moxadent', 'Vigamox'],
    dose: 'Yetişkin: tüm endikasyonlarda günde bir kez 400 mg; bu doz aşılmamalıdır.',
    form: 'Film kaplı tablet, IV infüzyon, göz damlası',
    sgkCovered: true,
    category: 'Florokinolon antibiyotik',
    siniflar: ['Kinolon', 'Florokinolon', 'Antibiyotik', 'QT uzatan ilaç'],
    alerjiSinifi: ['kinolon'],
    yasKontrendikasyonAy: 216,
    contraindications: [
      ...KINOLON_KONTRA,
      'Gebelik ve emzirme',
      '18 yaş altı hastalar',
      'Doğuştan veya kazanılmış QT uzaması',
      'Elektrolit bozukluğu (özellikle hipokalemi)',
      'Klinik olarak anlamlı bradikardi',
      'Sınıf IA ve Sınıf III antiaritmiklerle birlikte kullanım',
    ],
    interactions: ['Sınıf IA antiaritmikler', 'Sınıf III antiaritmikler', 'Aktif kömür', 'Varfarin', 'Demir', 'Antiasitler', 'Glibenklamid', 'QT uzatan ilaçlar'],
    etkilesimler: [
      ...KINOLON_ETKILESIM,
      { ile: 'Amiodaron', siddet: 'ciddi', not: 'KONTRENDİKE — Sınıf III antiaritmikle birlikte QT uzaması ve ventriküler aritmi riski (KÜB §4.3).' },
      { ile: 'Aktif kömür', siddet: 'orta', not: 'Sistemik yararlanımı %80\'den fazla azaltır; birlikte uygulanmamalı (KÜB §4.5).' },
    ],
    gebelik: { kategori: 'C', metin: 'Gebelikte KONTRENDİKE; hayvan çalışmalarında üreme toksisitesi (KÜB §4.3/4.6).' },
    emzirme: 'Emzirme döneminde kontrendikedir.',
    renkliRecete: 'normal',
    notes: 'Sınıfın en belirgin QT uzatanı — hipokalemi ve bradikardi düzeltilmeden başlanmamalıdır.',
    kaynak: kub('AVELOX 400 MG FİLM KAPLI TABLET (onay 26/08/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/AVELOX400mgfilmkapltabletkub_26_08_2026.pdf'),
  },

  metronidazol: {
    name: 'Metronidazol',
    brand: ['Flagyl', 'Nidazol', 'Metrazol', 'Metronidazol'],
    dose: 'Amebiyaz: 1,5 g/gün, 3 doza bölünmüş, 7 gün. Trikomoniyaz: tek doz 2 g (eş de tedavi edilir). Giardiyaz: 750 mg/gün.',
    pediatricDose: 'Amebiyaz 30–40 mg/kg/gün, giardiyaz 20–30 mg/kg/gün, 3 doza bölünmüş',
    pediatrik: {
      min: 20, max: 40, birim: 'mg/kg/gün', gunlukBolum: 3,
      maxMgKgGun: 40, mutlakMaxMgGun: 2250,
      metin: 'KÜB §4.2: amebiyazda çocuklarda 30–40 mg/kg/gün, giardiyazda 20–30 mg/kg/gün, üç doza bölünerek. (Film tablet formu farmasötik nedenle 6 yaş altında uygun değildir — süspansiyon formu kullanılmalıdır.)',
    },
    form: 'Film kaplı tablet, oral süspansiyon, IV infüzyon, vajinal ovül, topikal jel',
    sgkCovered: true,
    category: 'Nitroimidazol antibiyotik',
    siniflar: ['Nitroimidazol', 'Antibiyotik', 'Antiprotozoal', 'QT uzatan ilaç'],
    contraindications: [
      'İmidazol türevlerine aşırı duyarlılık',
      'Gebeliğin 1. trimesteri',
      'Buğday alerjisi (çölyak dışı)',
      '6 yaş altı çocuklarda tablet formu',
    ],
    interactions: ['Alkol', 'Varfarin', 'Lityum', 'Busulfan', 'Disülfiram', 'Fenitoin', 'QT uzatan ilaçlar'],
    etkilesimler: [
      { ile: 'Alkol', siddet: 'ciddi', not: 'Disülfiram benzeri (antabüz) reaksiyon — bulantı, kusma, kızarma, taşikardi. Tedavi boyunca ve sonrasında 48 saat alkol alınmamalı (KÜB §4.5).' },
      { ile: 'Varfarin', siddet: 'ciddi', not: 'Antikoagülan etkiyi belirgin artırır; INR izlenmeli ve doz ayarlanmalı (KÜB §4.5).' },
      { ile: 'Disülfiram', siddet: 'ciddi', not: 'Akut psikotik epizod ve konfüzyon riski; birlikte kullanılmamalı (KÜB §4.5).' },
      { ile: 'Lityum', siddet: 'ciddi', not: 'Lityum düzeyi ve toksisite riski artar; düzey izlenmeli.' },
      { ile: 'Busulfan', siddet: 'ciddi', not: 'Busulfan plazma düzeyini yükseltir; toksisite riski (KÜB §4.5).' },
      { ile: 'QT uzatan ilaç', siddet: 'ciddi', not: 'Metronidazol QT aralığını uzatabilir; birlikte kullanımda EKG izlemi (KÜB §4.5).' },
    ],
    gebelik: { kategori: 'X', metin: '1. trimesterde kontrendike (KÜB §4.3). Sonraki trimesterlerde yarar/risk değerlendirmesiyle kullanılabilir.' },
    emzirme: 'Anne sütüne geçer; tek yüksek dozdan sonra 12–24 saat emzirmeye ara verilmesi önerilir.',
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    kaynak: kub('FLAGYL 500 MG FİLM KAPLI TABLET (onay 10/03/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/flagy500ek2kub_15_04_2026.pdf'),
  },

  nitrofurantoin: {
    name: 'Nitrofurantoin',
    brand: ['Piyeloseptyl', 'Üriseptil', 'Üvamin', 'Ürineks'],
    dose: 'Komplike olmayan akut ÜSE: 7 gün, günde 2 kez 100 mg. Uzun dönem baskılama: günde 1 kez 50–100 mg.',
    pediatricDose: 'Akut ÜSE: 3 mg/kg/gün, 4 doza bölünmüş. Baskılama: 1 mg/kg/gün',
    pediatrik: {
      min: 3, max: 3, birim: 'mg/kg/gün', gunlukBolum: 4,
      maxMgKgGun: 3, mutlakMaxMgGun: 400,
      metin: 'KÜB §4.2: akut idrar yolu enfeksiyonunda 7 gün boyunca 4 bölünmüş doz olarak günlük 3 mg/kg; baskılama tedavisinde günde 1 kez 1 mg/kg. 25 kg altındaki çocuklarda oral süspansiyon formu tercih edilmelidir.',
    },
    form: 'Tablet, kapsül, oral süspansiyon',
    sgkCovered: true,
    category: 'Üriner antiseptik',
    siniflar: ['Nitrofuran', 'Üriner antiseptik', 'Antibiyotik'],
    contraindications: [
      'Nitrofurantoin veya diğer nitrofuranlara aşırı duyarlılık',
      'Böbrek fonksiyon bozukluğu (KrKl <60 mL/dk)',
      'G6PD eksikliği',
      'Akut porfiri',
      'Term gebelik (doğuma yakın dönem — neonatal hemoliz)',
      'Eritrositlerde enzim sisteminin immatür olduğu durumlar (yenidoğan)',
    ],
    interactions: ['Magnezyum trisilikat', 'Probenesid', 'Sülfinpirazon', 'Karbonik anhidraz inhibitörleri', 'Oral kontraseptifler'],
    etkilesimler: [
      { ile: 'Probenesid', siddet: 'orta', not: 'Renal atılımı azaltır; idrar konsantrasyonu düşer, etkinlik azalır ve sistemik toksisite artar (KÜB §4.5).' },
      { ile: 'Asetazolamid', siddet: 'orta', not: 'Karbonik anhidraz inhibitörleri idrarı alkalileştirerek antibakteriyel etkinliği azaltır (KÜB §4.5).' },
      { ile: 'Antiasit', siddet: 'orta', not: 'Magnezyum trisilikat emilimi azaltır (KÜB §4.5).' },
      { ile: 'Oral kontraseptif', siddet: 'orta', not: 'Östrojen reabsorbsiyonunu etkileyerek kontraseptif etkinliği azaltabilir (KÜB §4.5).' },
    ],
    gebelik: { kategori: 'B', metin: '1. ve 2. trimesterde kullanılabilir; term döneme yakın (38. haftadan sonra) neonatal hemoliz riski nedeniyle KONTRENDİKE (KÜB §4.3/4.6).' },
    emzirme: 'Anne sütüne az geçer; G6PD eksikliği olan bebekte hemoliz için yeterlidir — o durumda kullanılmaz.',
    bobrekDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Yemekle alınması GİS irritasyonunu azaltır ve emilimi artırır. Uzun kullanımda pulmoner fibrozis ve periferik nöropati izlenmeli.',
    kaynak: kub('ÜRİNEKS 100 MG TABLET (onay 21/04/2023)', 'https://titck.gov.tr/storage/Archive/2023/kubKtAttachments/ek3onerilenkub_6650cd47-a967-4a72-94a5-7b9d0587f3c9.pdf'),
  },

  fosfomisin: {
    name: 'Fosfomisin trometamol',
    brand: ['Monurol', 'Uroday', 'Fosfosin'],
    dose: 'Yetişkin kadın ve ≥12 yaş adolesan kız, akut komplike olmayan sistit: TEK DOZ 3 g. Transrektal prostat biyopsisi profilaksisi: işlemden 3 saat önce 3 g + 24 saat sonra 3 g.',
    form: 'Granül içeren saşe',
    sgkCovered: true,
    category: 'Fosfonik asit türevi antibiyotik',
    siniflar: ['Fosfomisin', 'Üriner antiseptik', 'Antibiyotik'],
    yasKontrendikasyonAy: 144,
    contraindications: [
      'Fosfomisine aşırı duyarlılık',
      'Ciddi böbrek yetmezliği (KrKl <10 mL/dk) ve hemodiyaliz',
      'Kalıtımsal fruktoz intoleransı, glukoz-galaktoz malabsorpsiyonu, sükroz-izomaltaz yetmezliği',
      '12 yaş ve altı çocuklarda önerilmez',
    ],
    interactions: ['Metoklopramid', 'Yiyecekler'],
    etkilesimler: [
      { ile: 'Metoklopramid', siddet: 'orta', not: 'Fosfomisinin serum ve idrar konsantrasyonlarını düşürür; birlikte kullanılmamalıdır (KÜB §4.5).' },
    ],
    gebelik: { kategori: 'B', metin: 'İlk trimester verisi sınırlıdır (n=152), teratojenite sinyali yoktur; yalnızca gerekli görüldüğünde kullanılır (KÜB §4.6).' },
    emzirme: 'Anne sütüne az miktarda geçer; tek doz kullanımda uyumlu kabul edilir.',
    bobrekDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Aç karnına, tercihen gece yatmadan önce mesane boşaltıldıktan sonra alınmalıdır.',
    kaynak: kub('URODAY 3 G GRANÜL İÇEREN SAŞE (onay 27/12/2024)', 'https://titck.gov.tr/storage/Archive/2024/kubKtAttachments/urodaykubtemizkopya_27_12_2024.pdf'),
  },

  rifampisin: {
    name: 'Rifampisin',
    brand: ['Rifadin', 'Rif', 'Rifex', 'Rifcap'],
    dose: 'Tüberküloz (yetişkin): günde tek doz 8–12 mg/kg — <50 kg: 450 mg, ≥50 kg: 600 mg. Lepra: ayda bir 600 mg.',
    pediatricDose: 'Tüberküloz: 8–12 mg/kg/gün tek doz (600 mg aşılmaz). H. influenzae/meningokok profilaksisi: 10–20 mg/kg',
    pediatrik: {
      min: 8, max: 12, birim: 'mg/kg/gün', gunlukBolum: 1,
      maxMgKgGun: 12, mutlakMaxMgGun: 600, enAzAy: 1,
      metin: 'KÜB §4.2: tüberkülozda günlük doz tüm yaş gruplarında 600 mg\'ı aşmamak koşuluyla 8–12 mg/kg. Meningokok profilaksisinde 2 gün süreyle günde 2 kez 10 mg/kg (1 aylıktan küçükte 5 mg/kg). H. influenzae profilaksisinde 4 gün süreyle 20 mg/kg (günde 600 mg aşılmaz); yenidoğanda (1 aylıktan itibaren) 4 gün süreyle günde 1 kez 10 mg/kg.',
    },
    form: 'Kapsül, oral süspansiyon, IV',
    sgkCovered: true,
    category: 'Antitüberküloz antibiyotik',
    siniflar: ['Rifamisin', 'Antitüberküloz', 'Antibiyotik', 'CYP3A4 indükleyicisi'],
    contraindications: ['Rifamisinlere aşırı duyarlılık', 'Sarılık', 'Sakinavir/ritonavir kombinasyonu ile birlikte kullanım'],
    interactions: ['Oral kontraseptifler', 'Varfarin', 'Statinler', 'Ketokonazol', 'Enalapril', 'İzoniazid', 'Halotan', 'Antiasitler', 'Siklosporin', 'Sakinavir/ritonavir'],
    etkilesimler: [
      { ile: 'Oral kontraseptif', siddet: 'ciddi', not: 'Güçlü CYP3A4 indüksiyonu ile kontraseptif etkinlik kaybolur; alternatif/ek korunma ZORUNLUDUR (KÜB §4.5).' },
      { ile: 'Varfarin', siddet: 'ciddi', not: 'Varfarin metabolizmasını hızlandırır, INR düşer ve tromboz riski artar; doz artırımı ve sık INR takibi.' },
      { ile: 'Simvastatin', siddet: 'orta', not: 'CYP3A4 ile metabolize olan statinlerin etkinliği azalır (KÜB §4.5).' },
      { ile: 'Siklosporin', siddet: 'ciddi', not: 'Siklosporin düzeyi belirgin düşer; rejeksiyon riski, düzey takibi zorunlu.' },
      { ile: 'İzoniazid', siddet: 'ciddi', not: 'Birlikte hepatotoksisite potansiyeli artar; hastalar yakından izlenmelidir (KÜB §4.5).' },
      { ile: 'Ketokonazol', siddet: 'orta', not: 'Her iki ilacın serum konsantrasyonu düşer (KÜB §4.5).' },
      { ile: 'Antiasit', siddet: 'orta', not: 'Rifampisin emilimini azaltır; en az 1 saat ara verilmeli.' },
    ],
    gebelik: { kategori: 'C', metin: 'Yüksek dozda hayvan çalışmalarında teratojenik etki; plasentayı geçer, gebede kontrollü araştırma yoktur (KÜB §4.6).' },
    emzirme: 'Anne sütüne geçer; genellikle uyumlu kabul edilir.',
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'İdrar, ter, gözyaşı ve kontakt lensleri turuncu-kırmızı boyar (zararsız). Güçlü enzim indükleyicisi — hastanın TÜM ilaç listesi gözden geçirilmelidir.',
    kaynak: kub('RİFEX 150 MG KAPSÜL (onay 06/05/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/RFEX150mgKB_07_05_2026.pdf'),
  },

  izoniazid: {
    name: 'İzoniazid',
    brand: ['INH', 'İzonyazid', 'Izoniazid'],
    dose: 'Tüberküloz tedavisi (yetişkin): 5 mg/kg/gün tek doz, günlük toplam 300 mg aşılmaz. Koruyucu tedavi: 300 mg/gün tek doz.',
    pediatricDose: '10–15 mg/kg/gün tek doz (günlük toplam 300 mg aşılmaz)',
    pediatrik: {
      min: 10, max: 15, birim: 'mg/kg/gün', gunlukBolum: 1,
      maxMgKgGun: 15, mutlakMaxMgGun: 300,
      metin: 'KÜB §4.2: tüberküloz tedavisinde çocuklarda tavsiye edilen doz 10–15 mg/kg/gün, tek dozda; günlük toplam doz 300 mg\'ı aşmamalıdır.',
    },
    form: 'Tablet (100 mg, 300 mg)',
    sgkCovered: true,
    category: 'Antitüberküloz',
    siniflar: ['Antitüberküloz', 'Hidrazid', 'MAO inhibitörü'],
    contraindications: ['İzoniazide aşırı duyarlılık', 'İlaca bağlı karaciğer hastalığı öyküsü', 'Akut karaciğer hastalığı'],
    interactions: ['Rifampisin', 'Fenitoin', 'Karbamazepin', 'Benzodiazepinler', 'Levodopa', 'İtrakonazol', 'Ketokonazol', 'Stavudin', 'Alkol'],
    etkilesimler: [
      { ile: 'Rifampisin', siddet: 'ciddi', not: 'Birlikte karaciğer hasarı riski artar; transaminazlar izlenmelidir (KÜB §4.5).' },
      { ile: 'Diazepam', siddet: 'orta', not: 'Benzodiazepin toksisite riski artar (KÜB §4.5).' },
      { ile: 'Levodopa', siddet: 'orta', not: 'İzoniazid levodopanın terapötik etkisini azaltabilir (KÜB §4.5).' },
      { ile: 'İtrakonazol', siddet: 'orta', not: 'İtrakonazol serum konsantrasyonu düşer; birlikte kullanım önerilmez (KÜB §4.5).' },
      { ile: 'Fenitoin', siddet: 'ciddi', not: 'Fenitoin metabolizması inhibe olur, toksik düzeye çıkabilir; düzey izlenmeli.' },
      { ile: 'Karbamazepin', siddet: 'ciddi', not: 'Karbamazepin düzeyi yükselir ve hepatotoksisite riski artar.' },
    ],
    gebelik: { kategori: 'C', metin: 'Plasentadan geçer; yalnızca yararı fetüse olası riskin üzerindeyse kullanılır (KÜB §4.6).' },
    emzirme: 'Anne sütüne geçer; bebekte piridoksin desteği düşünülmelidir.',
    bobrekDozUyarisi: true,
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Malnütrisyonu olan ve nöropatiye yatkın hastalarda piridoksin (B6) eklenmelidir. MAO ve DAO inhibitörüdür — tiramin/histamin içeren gıdalarla reaksiyon bildirilmiştir.',
    kaynak: kub('INH 300 MG TABLET (onay 10/09/2020)', 'https://titck.gov.tr/storage/Archive/2020/kubKtAttachments/kubtemiz_57bb5114-f421-4076-87dc-ac89615795b8.pdf'),
  },

  flukonazol: {
    name: 'Flukonazol',
    brand: ['Diflucan', 'Fungan', 'Flucan', 'Zolax', 'Triflucan'],
    dose: 'Vajinal kandidiyaz: tek doz 150 mg. Orofarengeal kandidiyaz: 50–100 mg/gün, 7–14 gün. Kriptokokal menenjit: 400 mg/gün.',
    pediatricDose: 'Mukozal kandidiyaz 3 mg/kg/gün; invazif kandidiyaz 6–12 mg/kg/gün (400 mg aşılmaz)',
    pediatrik: {
      min: 3, max: 12, birim: 'mg/kg/gün', gunlukBolum: 1,
      maxMgKgGun: 12, mutlakMaxMgGun: 400, enAzAy: 3,
      metin: 'KÜB §4.2: pediatrik dozlar 3, 6 ve 12 mg/kg/gün (endikasyona göre); kriptokok enfeksiyonunda 6–12 mg/kg/gün. 3 ay ve üzerinde invazif kandidiyazda ilk gün 25 mg/kg yükleme (800 mg aşılmaz), ardından günde bir kez 12 mg/kg (400 mg aşılmaz). Pediyatrik popülasyonda günlük maksimum doz 400 mg\'ı aşmamalıdır.',
    },
    form: 'Kapsül, şurup, IV infüzyon',
    sgkCovered: true,
    category: 'Azol antifungal',
    siniflar: ['Azol antifungal', 'Antifungal', 'Triazol', 'CYP3A4 inhibitörü', 'CYP2C9 inhibitörü', 'QT uzatan ilaç'],
    contraindications: [
      'Flukonazol veya benzer azol bileşiklerine aşırı duyarlılık',
      'Terfenadin ile birlikte (≥400 mg/gün flukonazol dozunda)',
      'Sisaprid, astemizol, eritromisin, pimozid, kinidin ile birlikte kullanım',
    ],
    interactions: ['Sisaprid', 'Astemizol', 'Pimozid', 'Kinidin', 'Eritromisin', 'Terfenadin', 'Varfarin', 'Fenitoin', 'Sülfonilüre', 'Siklosporin', 'Simvastatin', 'Rifampisin'],
    etkilesimler: [
      { ile: 'Sisaprid', siddet: 'ciddi', not: 'KONTRENDİKE — Torsade de Pointes bildirilmiştir (KÜB §4.3/4.5).' },
      { ile: 'Pimozid', siddet: 'ciddi', not: 'KONTRENDİKE — QT uzaması ve ventriküler aritmi (KÜB §4.3).' },
      { ile: 'Eritromisin', siddet: 'ciddi', not: 'KONTRENDİKE — kardiyotoksisite, uzamış QT ve ani kalp ölümü riski (KÜB §4.3/4.5).' },
      { ile: 'Varfarin', siddet: 'ciddi', not: 'CYP2C9 inhibisyonu ile INR belirgin yükselir; kanama riski, INR sık takip edilmeli.' },
      { ile: 'Simvastatin', siddet: 'ciddi', not: 'Statin düzeyi yükselir; miyopati/rabdomiyoliz riski.' },
      { ile: 'Fenitoin', siddet: 'ciddi', not: 'Fenitoin düzeyi yükselir; düzey izlenmeli.' },
      { ile: 'Sülfonilüre', siddet: 'ciddi', not: 'Hipoglisemik ajanların yarı ömrü uzar; hipoglisemi riski, kan şekeri izlenmeli.' },
      { ile: 'Siklosporin', siddet: 'ciddi', not: 'Siklosporin düzeyi yükselir; düzey takibi zorunlu.' },
      { ile: 'Terbinafin', siddet: 'orta', not: 'Flukonazol terbinafinin Cmaks ve EAA değerlerini %52 ve %69 artırır (KÜB §4.5).' },
      { ile: 'QT uzatan ilaç', siddet: 'ciddi', not: 'Flukonazol QT\'yi uzatır; birlikte aritmi riski artar.' },
    ],
    gebelik: { kategori: 'D', metin: '1./2. trimesterde spontan abortus riskinde artış bildirilmiştir; yüksek doz uzun süreli kullanımda konjenital anomali. Tek doz 150 mg dışında gebelikte kaçınılır (KÜB §4.6).' },
    emzirme: 'Anne sütüne geçer; tek doz kullanımda genellikle uyumlu kabul edilir.',
    bobrekDozUyarisi: true,
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    kaynak: kub('FLUCAN 5 MG/ML ŞURUP (onay 28/10/2025)', 'https://titck.gov.tr/storage/Archive/2025/kubKtAttachments/flucanurupkub_25_11_2025.pdf'),
  },

  terbinafin: {
    name: 'Terbinafin',
    brand: ['Lamisil', 'Terbisil', 'Fungoral', 'Mikosil'],
    dose: 'Yetişkin: günde tek doz 250 mg. Onikomikozda el tırnağı 6 hafta, ayak tırnağı 12 hafta.',
    pediatricDose: '20–40 kg: 125 mg/gün; >40 kg: 250 mg/gün (2 yaş / 12 kg altında veri yok)',
    pediatrik: {
      min: 125, max: 250, birim: 'mg/kg/gün', gunlukBolum: 1, enAzAy: 24,
      metin: 'KÜB §4.2 (kiloya göre sabit doz, mg/kg değil): 20–40 kg arası çocukta günde tek doz 125 mg; 40 kg üzerinde günde tek doz 250 mg. İki yaşın altındaki (genellikle <12 kg) çocuklarda kullanım verisi yoktur.',
    },
    form: 'Tablet, krem, sprey',
    sgkCovered: true,
    sgkRestriction: 'SUT: onikomikozda mikolojik doğrulama arandığı durumlar için ilgili SUT maddesine bakınız.',
    category: 'Allilamin antifungal',
    siniflar: ['Allilamin', 'Antifungal', 'CYP2D6 inhibitörü'],
    contraindications: ['Terbinafine aşırı duyarlılık', 'Ciddi böbrek yetmezliği (KrKl <30 mL/dk)', 'Ciddi karaciğer yetmezliği'],
    interactions: ['Rifampisin', 'Simetidin', 'Flukonazol', 'Amiodaron', 'Varfarin', 'Desipramin', 'Trisiklik antidepresanlar', 'Metoprolol', 'Kafein'],
    etkilesimler: [
      { ile: 'Rifampisin', siddet: 'orta', not: 'Terbinafin klerensini %100 artırır, etkinlik azalır (KÜB §4.5).' },
      { ile: 'Simetidin', siddet: 'orta', not: 'Terbinafin klerensini %33 azaltır (KÜB §4.5).' },
      { ile: 'Flukonazol', siddet: 'orta', not: 'CYP2C9 + CYP3A4 inhibisyonu ile terbinafin maruziyeti belirgin artar (KÜB §4.5).' },
      { ile: 'Varfarin', siddet: 'orta', not: 'Varfarinin etkisini artırabilir; INR izlenmeli (KÜB §4.5).' },
      { ile: 'Metoprolol', siddet: 'ciddi', not: 'CYP2D6 inhibisyonu — beta blokör düzeyi yükselir, bradikardi/hipotansiyon riski (KÜB §4.5).' },
      { ile: 'Trisiklik antidepresan', siddet: 'ciddi', not: 'Terbinafin desipramin klerensini %82 azaltır; CYP2D6 substratlarında doz azaltımı gerekebilir (KÜB §4.5).' },
    ],
    gebelik: { kategori: 'B', metin: 'Gebelikte klinik veri sınırlıdır; gebelik sırasında kullanılmamalıdır (KÜB §4.6).' },
    emzirme: 'Anne sütüne geçer; emzirme döneminde kullanılmamalıdır.',
    bobrekDozUyarisi: true,
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Tedavi öncesi ve 4–6. haftada karaciğer enzimleri kontrol edilmelidir. Tat kaybı bildirilmiştir.',
    kaynak: kub('TERBİSİL 250 MG TABLET (onay 29/04/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/Terbisil250mgKB_30_04_2026.pdf'),
  },

  itrakonazol: {
    name: 'İtrakonazol',
    brand: ['Itraspor', 'Sporanox', 'Candistat', 'Funit'],
    dose: 'Vulvovajinal kandidoz: 1 gün 2×200 mg veya 3 gün 200 mg/gün. Dermatomikoz: 200 mg/gün 7 gün veya 100 mg/gün 15 gün. Onikomikoz: puls tedavi.',
    form: 'Sert kapsül (mikropellet), oral çözelti',
    sgkCovered: true,
    category: 'Azol antifungal',
    siniflar: ['Azol antifungal', 'Antifungal', 'Triazol', 'CYP3A4 inhibitörü', 'P-glikoprotein inhibitörü', 'QT uzatan ilaç'],
    contraindications: [
      'İtrakonazol aşırı duyarlılığı',
      'Konjestif kalp yetmezliği / kalp yetmezliği öyküsü',
      'QT uzatan CYP3A4 substratları ile birlikte kullanım (kinidin, pimozid, sisaprid, dofetilid)',
      'CYP3A4 ile metabolize olan statinlerle (simvastatin, lovastatin) birlikte kullanım',
      'Ergot alkaloidleriyle birlikte kullanım',
      'Gebelik (hayati tehdit eden vakalar dışında)',
    ],
    interactions: ['Simvastatin', 'Lovastatin', 'Pimozid', 'Kinidin', 'Sisaprid', 'Ergot alkaloidleri', 'Midazolam', 'Rifampisin', 'Fenitoin', 'Antiasitler', 'PPI', 'Varfarin', 'Digoksin'],
    etkilesimler: [
      { ile: 'Simvastatin', siddet: 'ciddi', not: 'KONTRENDİKE — rabdomiyoliz riski (KÜB §4.3).' },
      { ile: 'Pimozid', siddet: 'ciddi', not: 'KONTRENDİKE — QT uzaması ve Torsade de Pointes (KÜB §4.3).' },
      { ile: 'Ergotamin', siddet: 'ciddi', not: 'KONTRENDİKE — ergot toksisitesi (KÜB §4.3).' },
      { ile: 'Midazolam', siddet: 'ciddi', not: 'Oral midazolam maruziyeti çok artar, uzamış sedasyon (KÜB §4.5).' },
      { ile: 'Rifampisin', siddet: 'ciddi', not: 'Güçlü CYP3A4 indüksiyonu itrakonazol etkinliğini büyük ölçüde ortadan kaldırır; birlikte kullanımdan kaçınılmalı (KÜB §4.5).' },
      { ile: 'Proton pompa inhibitörü', siddet: 'orta', not: 'Gastrik asiditeyi azaltan ilaçlar kapsül emilimini düşürür; asitli içecekle alınmalı veya en az 1 saat ara verilmeli (KÜB §4.5).' },
      { ile: 'Antiasit', siddet: 'orta', not: 'Alüminyum hidroksit gibi antiasitler en az 1 saat sonra alınmalıdır (KÜB §4.5).' },
      { ile: 'Varfarin', siddet: 'ciddi', not: 'INR yükselir; kanama riski, sık takip.' },
      { ile: 'Digoksin', siddet: 'ciddi', not: 'P-glikoprotein inhibisyonu ile digoksin düzeyi yükselir.' },
    ],
    gebelik: { metin: 'Hayati tehdit eden vakalar dışında gebelikte kullanılmamalıdır; pazarlama sonrası konjenital anomali bildirimleri vardır (KÜB §4.3/4.6).' },
    emzirme: 'Anne sütüne geçer; emzirme döneminde önerilmez.',
    bobrekDozUyarisi: true,
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Kapsül formu emilim için tok karnına alınmalıdır. Negatif inotrop etkisi nedeniyle kalp yetmezliğinde kontrendikedir.',
    kaynak: kub('CANDİSTAT 100 MG SERT KAPSÜL (onay 12/02/2021)', 'https://titck.gov.tr/storage/Archive/2021/kubKtAttachments/CandistatKB_93784544-4f1e-48aa-a264-5961cfd140b7.pdf'),
  },

  nistatin: {
    name: 'Nistatin',
    brand: ['Mikostatin', 'Fungostatin', 'Nistatin'],
    dose: 'Yetişkin oral kandidiyaz: günde 4 kez 1 mL süspansiyon ağız içine damlatılır; semptomlar geçtikten sonra en az 48 saat devam edilir.',
    pediatricDose: 'Bebek ve çocuklarda oral/intestinal kandidoz: günde 4 kez 1 mL. Yenidoğanda profilaksi: günde 1 kez 1 mL',
    pediatrik: {
      min: 1, max: 1, birim: 'mg/kg/doz', gunlukBolum: 4,
      metin: 'KÜB §4.2 (hacim olarak, mg/kg değil): bebek ve çocuklarda intestinal ve oral kandidozda (pamukçuk) günde 4 kez 1 mL süspansiyon ağız içine damlatılır. Yenidoğanlarda profilaksi dozu günde 1 kez 1 mL\'dir.',
    },
    form: 'Oral süspansiyon, pastil, vajinal tablet, pomat',
    sgkCovered: true,
    category: 'Polien antifungal',
    siniflar: ['Polien', 'Antifungal'],
    contraindications: ['Nistatine aşırı duyarlılık'],
    interactions: [],
    etkilesimler: [],
    gebelik: { metin: 'Gebede yeterli veri yoktur; gerekli olmadıkça gebelik döneminde kullanılmaz (KÜB §4.6). Sistemik emilimi ihmal edilebilir düzeydedir.' },
    emzirme: 'Sistemik emilimi yok denecek kadar azdır; emzirme döneminde kullanılabilir.',
    renkliRecete: 'normal',
    notes: 'GİS\'ten emilmez — etkisi temas süresine bağlıdır, yutmadan önce ağızda tutulmalıdır.',
    kaynak: kub('MİKOSTATİN 100.000 IU/ML ORAL SÜSPANSİYON (onay 07/05/2021)', 'https://titck.gov.tr/storage/Archive/2021/kubKtAttachments/MKOSTATN100.000KB_d9eae0d1-5f8b-4f22-b075-5fc4f4545864.pdf'),
  },

  asiklovir: {
    name: 'Asiklovir',
    brand: ['Zovirax', 'Hernovir', 'Asiklovir', 'Virless'],
    dose: 'Herpes simplex tedavisi: 5 gün boyunca günde 5 kez 200 mg (gece dozu atlanarak). Suçiçeği/zoster: günde 5 kez 800 mg, 7 gün.',
    pediatricDose: 'Suçiçeği (6 yaş ve üzeri): günde 4 kez 800 mg. 2 yaş altı HSV: erişkin dozunun yarısı',
    pediatrik: {
      min: 20, max: 20, birim: 'mg/kg/doz', gunlukBolum: 4,
      mutlakMaxMgDoz: 800,
      metin: 'KÜB §4.2: herpes simplex tedavi/profilaksisinde 2 yaşın üzerinde erişkin dozu, 2 yaşın altında erişkin dozunun yarısı. Suçiçeğinde 6 yaş ve üzeri günde 4 kez 800 mg; küçük yaşta doz 20 mg/kg olarak verilir (tek doz 800 mg\'ı geçmemek üzere). Neonatal herpeste IV asiklovir önerilir.',
    },
    form: 'Tablet, süspansiyon, krem, göz pomadı, IV',
    sgkCovered: true,
    category: 'Antiviral (nükleozid analoğu)',
    siniflar: ['Antiviral', 'Nükleozid analoğu', 'Herpes antiviral'],
    contraindications: ['Asiklovir veya valasiklovire aşırı duyarlılık'],
    interactions: ['Probenesid', 'Simetidin', 'Mikofenolat mofetil', 'Teofilin', 'Nefrotoksik ilaçlar'],
    etkilesimler: [
      { ile: 'Probenesid', siddet: 'orta', not: 'Asiklovirin EAA değerini artırır ve renal klirensini azaltır (KÜB §4.5).' },
      { ile: 'Teofilin', siddet: 'orta', not: 'Teofilin EAA\'sını ~%50 artırır; plazma düzeyi ölçülmesi önerilir (KÜB §4.5).' },
      { ile: 'Mikofenolat mofetil', siddet: 'orta', not: 'İnaktif metabolit EAA değerleri artar (KÜB §4.5).' },
    ],
    gebelik: { kategori: 'B', metin: 'Gebelik kayıtlarında doğum kusurlarında genel popülasyona göre artış saptanmamıştır (KÜB §4.6).' },
    emzirme: 'Anne sütüne geçer; terapötik dozlarda uyumlu kabul edilir.',
    bobrekDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Böbrek yetmezliğinde doz aralığı uzatılmalı; yeterli hidrasyon sağlanmalıdır.',
    kaynak: kub('HERNOVİR 400 MG TABLET (onay 04/06/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/HERNOVR400mgtabletkub_05_06_2026.pdf'),
  },

  valasiklovir: {
    name: 'Valasiklovir',
    brand: ['Valtrex', 'Valavir', 'Valcistin'],
    dose: 'Herpes zoster (bağışıklığı yeterli erişkin): günde 3 kez 1000 mg, 7 gün. Genital herpes ilk atak: günde 2 kez 500 mg, 5–10 gün.',
    form: 'Film kaplı tablet',
    sgkCovered: true,
    category: 'Antiviral (nükleozid analoğu ön ilacı)',
    siniflar: ['Antiviral', 'Nükleozid analoğu', 'Herpes antiviral'],
    yasKontrendikasyonAy: 144,
    contraindications: ['Valasiklovir veya asiklovire aşırı duyarlılık', '12 yaş altı çocuklarda etkinlik/güvenlilik değerlendirilmemiştir'],
    interactions: ['Probenesid', 'Simetidin', 'Mikofenolat mofetil', 'Nefrotoksik ilaçlar'],
    etkilesimler: [
      { ile: 'Probenesid', siddet: 'orta', not: 'Asiklovirin renal klirensini azaltır, EAA\'sını ~%65 artırır (KÜB §4.5).' },
      { ile: 'Simetidin', siddet: 'orta', not: 'Asiklovir maruziyetini artırır (KÜB §4.5).' },
    ],
    gebelik: { metin: 'Sınırlı veri; malformasyon sinyali saptanmamıştır. Yarar/risk değerlendirmesiyle kullanılır (KÜB §4.6).' },
    emzirme: 'Aktif metaboliti asiklovir anne sütüne geçer; terapötik dozlarda uyumlu kabul edilir.',
    bobrekDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Herpes zosterde tedaviye döküntü başladıktan sonra ilk 72 saat içinde başlanmalıdır.',
    kaynak: kub('VALTREX 1000 MG FİLM KAPLI TABLET (onay 29/03/2024)', 'https://titck.gov.tr/storage/Archive/2024/kubKtAttachments/uygunkbvaltrex1000mg_829ae4b9-1121-463b-8206-b0257224b90b.pdf'),
  },

  oseltamivir: {
    name: 'Oseltamivir',
    brand: ['Tamiflu', 'Oseflu', 'Osetamin'],
    dose: 'Yetişkin ve ≥13 yaş (>40 kg): 5 gün boyunca günde iki kez 75 mg. Tedaviye ilk 48 saat içinde başlanmalıdır.',
    pediatricDose: 'Kiloya göre: 10–15 kg 2×30 mg; >15–23 kg 2×45 mg; >23–40 kg 2×60 mg; >40 kg 2×75 mg',
    pediatrik: {
      min: 30, max: 75, birim: 'mg/kg/doz', gunlukBolum: 2, enAzAy: 12,
      metin: 'KÜB §4.2 (kiloya göre sabit doz, mg/kg değil): 1 yaş ve üzeri çocukta 5 gün boyunca günde iki kez — 10–15 kg: 30 mg; >15–23 kg: 45 mg; >23–40 kg: 60 mg; >40 kg: 75 mg. 1 yaşın altında güvenlilik ve etkililik saptanmamıştır.',
    },
    form: 'Kapsül, granül içeren saşe, oral süspansiyon',
    sgkCovered: true,
    sgkRestriction: 'SUT: influenza sezonu ve endikasyon koşullarına bağlıdır.',
    category: 'Nöraminidaz inhibitörü antiviral',
    siniflar: ['Antiviral', 'Nöraminidaz inhibitörü', 'İnfluenza antivirali'],
    yasKontrendikasyonAy: 12,
    contraindications: ['Oseltamivir fosfata aşırı duyarlılık', '1 yaş altında güvenlilik/etkililik saptanmamıştır'],
    interactions: ['Probenesid', 'Metotreksat', 'Klorpropamid', 'Fenilbutazon'],
    etkilesimler: [
      { ile: 'Probenesid', siddet: 'orta', not: 'Aktif metabolit konsantrasyonu ~2 kat artar; normal böbrek fonksiyonunda doz ayarı gerekmez (KÜB §4.5).' },
      { ile: 'Metotreksat', siddet: 'orta', not: 'Aynı renal tübüler yolu kullanan dar terapötik indeksli ilaçlarla birlikte dikkat (KÜB §4.5).' },
    ],
    gebelik: { kategori: 'C', metin: 'Geniş pazarlama sonrası veri malformasyon veya fetal/neonatal toksisite göstermemiştir; influenza kendisi olumsuz gebelik sonuçlarıyla ilişkilidir (KÜB §4.6).' },
    emzirme: 'Anne sütüne düşük düzeyde geçer; emzirme döneminde kullanılabilir.',
    bobrekDozUyarisi: true,
    renkliRecete: 'normal',
    kaynak: kub('OSEFLU 30 MG GRANÜL İÇEREN SAŞE (onay 22/08/2024)', 'https://titck.gov.tr/storage/Archive/2024/kubKtAttachments/OSEFLUSAEKB_48b2475b-21e2-491c-8b16-89bce8032009.pdf'),
  },
}
