/**
 * Antibiyotikler — beta-laktamlar, makrolidler, linkozamid, tetrasiklin, sülfonamid.
 *
 * Allergy cross-reactivity is the reason this group needs `alerjiSinifi`: a file that says
 * "penisilin alerjisi" has to reach amoksisilin AND ampisilin AND fenoksimetilpenisilin without
 * anyone remembering to write the pair down, and a beta-laktam allergy has to raise its head on the
 * sefalosporin card too (every sefalosporin KÜB §4.3 here says so in as many words).
 *
 * Pediatric mg/kg lines come from the pediatric suspension's own KÜB wherever one exists — that is
 * the document a Turkish pediatrician actually dispenses from.
 */
import { kub } from '../kaynak'
import type { TürkishDrug } from '../tipler'

const PENISILIN_ETKILESIM = [
  { ile: 'Metotreksat', siddet: 'ciddi' as const, not: 'Penisilinler metotreksatın renal atılımını azaltır; MTX toksisitesi riski artar (KÜB §4.5).' },
  { ile: 'Probenesid', siddet: 'orta' as const, not: 'Renal tübüler sekresyonu azaltır, penisilin kan düzeyi ve yarı ömrü artar; birlikte kullanım önerilmez.' },
  { ile: 'Varfarin', siddet: 'orta' as const, not: 'INR yükselmesi bildirilmiştir; antibiyotik başlanırken/kesilirken INR yakından izlenmeli (KÜB §4.5).' },
  { ile: 'Oral kontraseptif', siddet: 'orta' as const, not: 'Bağırsak florasını etkileyerek östrojen emilimini azaltabilir; ek korunma önerilir (KÜB §4.5).' },
  { ile: 'Allopurinol', siddet: 'orta' as const, not: 'Birlikte kullanımda alerjik deri döküntüsü riski artar (KÜB §4.5).' },
] as const

const SEFALOSPORIN_ETKILESIM = [
  { ile: 'Aminoglikozid', siddet: 'orta' as const, not: 'Sefalosporin + aminoglikozid birlikte kullanımında nefrotoksisite artışı bildirilmiştir (KÜB §4.5).' },
  { ile: 'Probenesid', siddet: 'orta' as const, not: 'Renal atılım azalır, sefalosporin maruziyeti artar.' },
  { ile: 'Varfarin', siddet: 'orta' as const, not: 'INR yükselebilir; oral antikoagülan alan hastada takip (KÜB §4.5).' },
  { ile: 'Oral kontraseptif', siddet: 'orta' as const, not: 'Doğum kontrol haplarının etkinliğini azaltabilir; ek korunma önerilir.' },
] as const

/** Every macrolide KÜB §4.3/4.5 lists the same CYP3A4 + QT block. */
const MAKROLID_ETKILESIM = [
  { ile: 'Ergotamin', siddet: 'ciddi' as const, not: 'KONTRENDİKE — ergot toksisitesi (vazospazm, iskemi) riski (KÜB §4.3).' },
  { ile: 'Pimozid', siddet: 'ciddi' as const, not: 'KONTRENDİKE — QT uzaması, ventriküler aritmi ve Torsade de Pointes riski (KÜB §4.3).' },
  { ile: 'Simvastatin', siddet: 'ciddi' as const, not: 'CYP3A4 inhibisyonu ile statin düzeyi artar; miyopati/rabdomiyoliz riski. Statin geçici kesilmeli.' },
  { ile: 'Atorvastatin', siddet: 'ciddi' as const, not: 'Statin maruziyeti artar; rabdomiyoliz bildirilmiştir (KÜB §4.5).' },
  { ile: 'Varfarin', siddet: 'ciddi' as const, not: 'INR artışı ve kanama bildirilmiştir; birlikte kullanımda INR takibi (KÜB §4.5).' },
  { ile: 'Digoksin', siddet: 'orta' as const, not: 'P-glikoprotein inhibisyonu ile serum digoksin düzeyi yükselebilir (KÜB §4.5).' },
  { ile: 'Kolşisin', siddet: 'ciddi' as const, not: 'Kolşisin toksisitesi bildirilmiştir; böbrek/karaciğer yetmezliğinde birlikte kullanılmamalı.' },
  { ile: 'QT uzatan ilaç', siddet: 'ciddi' as const, not: 'Makrolid QT\'yi uzatır; başka bir QT uzatan ilaçla birlikte Torsade de Pointes riski artar.' },
  { ile: 'Siklosporin', siddet: 'ciddi' as const, not: 'CYP3A4 inhibisyonu ile siklosporin düzeyi yükselir; düzey takibi zorunlu.' },
] as const

export const ANTIBIYOTIK: Record<string, TürkishDrug> = {
  amoksisilin: {
    name: 'Amoksisilin',
    brand: ['Largopen', 'Amoksina', 'Alfoxil', 'Amoksilin', 'Remoxil', 'Atoksilin'],
    dose: 'Yetişkin ve >40 kg çocuk: 8 saatte bir 250–500 mg veya 12 saatte bir 500 mg–1 g. Ciddi enfeksiyonda 8 saatte bir 750 mg–1 g. Günlük maksimum 6 g.',
    pediatricDose: '20–90 mg/kg/gün, bölünmüş dozlar halinde (40 kg altı çocuk)',
    pediatrik: {
      min: 20, max: 90, birim: 'mg/kg/gün', gunlukBolum: 3,
      maxMgKgGun: 90, mutlakMaxMgGun: 6000, enAzAy: 3,
      metin: 'KÜB §4.2: 40 kg altı çocukta bölünmüş dozlar halinde 20–90 mg/kg/gün (akut otitis media / sinüzit gibi endikasyonlarda 40–90 mg/kg/gün). 40 kg ve üzerinde erişkin dozu. 3 aylıktan küçük bebekte doz dikkatle ayarlanmalı (renal fonksiyonlar tam gelişmemiştir).',
    },
    form: 'Kapsül, tablet, oral süspansiyon',
    sgkCovered: true,
    category: 'Penisilin antibiyotik',
    siniflar: ['Penisilin', 'Beta-laktam', 'Aminopenisilin', 'Antibiyotik'],
    alerjiSinifi: ['penisilin'],
    contraindications: ['Penisilin alerjisi', 'Beta-laktam antibiyotiklere aşırı duyarlılık', 'Enfeksiyöz mononükleoz (döküntü riski)'],
    interactions: ['Metotreksat', 'Probenesid', 'Varfarin', 'Allopurinol', 'Oral kontraseptifler'],
    etkilesimler: PENISILIN_ETKILESIM,
    gebelik: { kategori: 'B', metin: 'Hayvan çalışmalarında teratojenik etki saptanmamıştır; gebe kadınlara verilirken tedbirli olunmalıdır (KÜB §4.6).' },
    emzirme: 'Anne sütüne az miktarda geçer; emzirme döneminde kullanılabilir (bebekte ishal/kandidiyaz izlenmeli).',
    bobrekDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Sefalosporin, karbapenem ve monobaktamlarla çapraz duyarlılık olasılığına dikkat (KÜB §4.3).',
    kaynak: kub('AMOKSİNA 125 MG/5 ML SÜSPANSİYONLUK TOZ (onay 14/06/2024)', 'https://titck.gov.tr/storage/Archive/2024/kubKtAttachments/temizkub125_f78ff716-9fe4-45e7-911d-a4c1e513f4ab.pdf'),
  },

  amoksisilinKlavulanat: {
    name: 'Amoksisilin + Klavulanik asit',
    brand: ['Augmentin', 'Amoklavin', 'Klavunat', 'Croxilex', 'Bioment', 'Klamoks'],
    dose: 'Yetişkin: 12 saatte bir 875/125 mg veya 8 saatte bir 500/125 mg. Günlük maksimum 6000 mg amoksisilin / 600 mg klavulanik asit.',
    pediatricDose: '20/5 – 60/15 mg/kg/gün, 3 doza bölünmüş (2 yaş altında 40/10 mg/kg/gün üstü veri yok)',
    pediatrik: {
      min: 20, max: 60, birim: 'mg/kg/gün', gunlukBolum: 3,
      maxMgKgGun: 60, mutlakMaxMgGun: 6000, enAzAy: 2,
      metin: 'KÜB §4.2 (4:1 pediatrik süspansiyon): üçe bölünmüş dozlar halinde 20/5 – 60/15 mg/kg/gün. 2 yaş altında 40/10 mg/kg/gün üzerindeki dozlar için klinik veri yoktur; 2 aylıktan küçük hastada doz önerisi yoktur. Doz amoksisilin içeriğine göre hesaplanır.',
    },
    form: 'Film tablet, oral süspansiyon, IV flakon',
    sgkCovered: true,
    category: 'Beta-laktamaz inhibitörlü penisilin',
    siniflar: ['Penisilin', 'Beta-laktam', 'Aminopenisilin', 'Beta-laktamaz inhibitörlü penisilin', 'Antibiyotik'],
    alerjiSinifi: ['penisilin'],
    contraindications: [
      'Penisilin alerjisi',
      'Diğer beta-laktamlara (sefalosporin, karbapenem, monobaktam) anafilaksi öyküsü',
      'Amoksisilin/klavulanata bağlı sarılık veya karaciğer fonksiyon bozukluğu öyküsü',
    ],
    interactions: ['Metotreksat', 'Probenesid', 'Varfarin', 'Allopurinol', 'Oral kontraseptifler'],
    etkilesimler: PENISILIN_ETKILESIM,
    gebelik: { kategori: 'B', metin: 'Hayvan çalışmalarında zararlı etki gösterilmemiştir; gebe kadınlara verilirken tedbirli olunmalıdır (KÜB §4.6).' },
    emzirme: 'Anne sütüne geçer; emzirme döneminde kullanılabilir.',
    bobrekDozUyarisi: true,
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Kolestatik sarılık/hepatit riski amoksisiline göre yüksektir. Tedavi inceleme yapılmadan 14 günü aşmamalıdır.',
    kaynak: kub('KLAVUNAT PEDİATRİK 125 MG + 31,25 MG/5 ML ORAL SÜSPANSİYON (onay 30/07/2025)', 'https://titck.gov.tr/storage/Archive/2025/kubKtAttachments/125kub_08_08_2025.pdf'),
  },

  ampisilinSulbaktam: {
    name: 'Ampisilin + Sulbaktam',
    brand: ['Duocid', 'Duobak', 'Sulcid', 'Ampisid', 'Alfasid'],
    dose: 'Yetişkin (normal böbrek fonksiyonu): 1,5–12 g/gün, 6–8 saatte bir bölünmüş IM/IV doz. Sulbaktamın günlük maksimum dozu 4 g.',
    pediatricDose: '150 mg/kg/gün (100 mg/kg ampisilin + 50 mg/kg sulbaktam), 6–8 saatte bir',
    pediatrik: {
      min: 150, max: 150, birim: 'mg/kg/gün', gunlukBolum: 4,
      maxMgKgGun: 150,
      metin: 'KÜB §4.2: çocuk, bebek ve yenidoğanda çoğu enfeksiyon için 150 mg/kg/gün (100 mg/kg ampisilin + 50 mg/kg sulbaktam), 6–8 saatte bir. Yaşamın ilk haftasındaki yenidoğanda (özellikle prematürede) 12 saatte bir bölünmüş 75 mg/kg/gün.',
    },
    form: 'IM/IV flakon, oral tablet (sultamisilin)',
    sgkCovered: true,
    category: 'Beta-laktamaz inhibitörlü penisilin',
    siniflar: ['Penisilin', 'Beta-laktam', 'Aminopenisilin', 'Beta-laktamaz inhibitörlü penisilin', 'Antibiyotik'],
    alerjiSinifi: ['penisilin'],
    contraindications: ['Herhangi bir penisiline alerjik reaksiyon öyküsü', 'Amid tipi lokal anestezik alerjisi (lidokainli IM form)', 'Kalp bloğu (lidokainli IM form)'],
    interactions: ['Metotreksat', 'Probenesid', 'Allopurinol', 'Aminoglikozidler'],
    etkilesimler: [
      ...PENISILIN_ETKILESIM,
      { ile: 'Aminoglikozid', siddet: 'orta', not: 'Aynı sıvıda karıştırılmamalı; birlikte verilecekse en az 1 saat arayla ve farklı bölgelerden (KÜB §4.5).' },
    ],
    gebelik: { kategori: 'B', metin: 'Gebelikte güvenli kullanım tespit edilmemiştir; sulbaktam plasentayı geçer (KÜB §4.6).' },
    emzirme: 'Anne sütüne düşük konsantrasyonda geçer.',
    bobrekDozUyarisi: true,
    renkliRecete: 'normal',
    kaynak: kub('DUOBAK 250 MG/125 MG IM ENJEKSİYONLUK ÇÖZELTİ (onay 13/08/2025)', 'https://titck.gov.tr/storage/Archive/2025/kubKtAttachments/uygunkub_07_10_2025.pdf'),
  },

  fenoksimetilpenisilin: {
    name: 'Fenoksimetilpenisilin',
    brand: ['Pen-Os', 'Fenopen', 'Cliacil'],
    dose: 'Yetişkin: 500.000–1.000.000 IU (≈300–600 mg), günde 3–4 doza bölünmüş.',
    pediatricDose: '40.000–64.000 IU/kg/gün, 3–4 doza bölünmüş',
    pediatrik: {
      min: 40000, max: 64000, birim: 'IU/gün', gunlukBolum: 4, enAzAy: 3,
      metin: 'KÜB §4.2: 4–12 haftalık infantta (4–5 kg) günlük doz 40.000–64.000 IU/kg. Günlük doz gün içinde eşit aralıklarla 3–4 doza bölünür. 3 aydan küçük bebekte emilim yetersizliği nedeniyle oral penisilin önerilmez. (1 mg fenoksimetilpenisilin ≈ 1.695 IU.)',
    },
    form: 'Tablet, şurup hazırlamak için kuru toz',
    sgkCovered: true,
    category: 'Penisilin antibiyotik',
    siniflar: ['Penisilin', 'Beta-laktam', 'Dar spektrumlu penisilin', 'Antibiyotik'],
    alerjiSinifi: ['penisilin'],
    yasKontrendikasyonAy: 3,
    contraindications: ['Penisilin alerjisi', 'Diğer beta-laktamlarla çapraz alerji olasılığı', '3 ay altı bebekte oral kullanım önerilmez'],
    interactions: ['Probenesid', 'Metotreksat', 'Oral antikoagülanlar', 'Oral kontraseptifler', 'Bakteriyostatik antibiyotikler', 'İndometazin', 'Salisilatlar'],
    etkilesimler: [
      ...PENISILIN_ETKILESIM,
      { ile: 'Tetrasiklin', siddet: 'orta', not: 'Bakteriyostatik antibiyotikler penisilinin bakterisidal etkisini antagonize edebilir (KÜB §4.5).' },
    ],
    gebelik: { kategori: 'B', metin: 'Doğru endikasyonda gebeliğin herhangi bir aşamasında kullanılabilir; fetüs üzerinde zararlı etki gösterilmemiştir (KÜB §4.6).' },
    emzirme: 'Anne sütüne az miktarda geçer; kullanılabilir.',
    renkliRecete: 'normal',
    notes: 'A grubu streptokok farenjitinde ilk seçenek; akut romatizmal ateş profilaksisinde kullanılır.',
    kaynak: kub('FENOPEN 300.000 IU/5 ML ŞURUP (onay 18/10/2022)', 'https://titck.gov.tr/storage/Archive/2022/kubKtAttachments/OnaylKB_007b4de7-0e95-46d4-b053-0a43aee71351.pdf'),
  },

  benzatinPenisilinG: {
    name: 'Benzatin penisilin G',
    brand: ['Penadur', 'Pentin-LA', 'Deposilin'],
    dose: 'Yetişkin A grubu streptokok enfeksiyonu: tek doz 1.200.000 IU IM. ARA profilaksisi: 3–4 haftada bir 1.200.000 IU IM.',
    pediatricDose: 'A grubu streptokok enfeksiyonunda genellikle tek doz (1.200.000 IU IM)',
    form: 'IM enjektabl toz içeren flakon',
    sgkCovered: true,
    category: 'Penisilin antibiyotik (depo)',
    siniflar: ['Penisilin', 'Beta-laktam', 'Depo penisilin', 'Antibiyotik'],
    alerjiSinifi: ['penisilin'],
    contraindications: ['Penisilin alerjisi', 'Prokain aşırı duyarlılığı', 'İntravenöz uygulama (KESİNLİKLE sadece IM)'],
    interactions: ['Probenesid', 'Metotreksat', 'Bakteriyostatik antibiyotikler'],
    etkilesimler: [
      { ile: 'Metotreksat', siddet: 'ciddi', not: 'Penisilinler metotreksatın atılımını azaltır, toksisite riski artar (KÜB §4.5).' },
      { ile: 'Probenesid', siddet: 'orta', not: 'Penisilinin böbrek tübüllerinden atılımı azalır, kan düzeyi artar (KÜB §4.5).' },
    ],
    gebelik: { kategori: 'B', metin: 'İnsanda fetüs üzerine advers etki kanıtı yoktur; tedbir olarak gerekli olmadıkça kullanılmaz (KÜB §4.6).' },
    emzirme: 'Anne sütüne az miktarda geçer.',
    renkliRecete: 'normal',
    notes: 'Akut romatizmal ateş sekonder profilaksisinin omurgası. Anafilaksiye hazırlıklı ortamda uygulanmalıdır.',
    kaynak: kub('PENTİN-LA 6.3.3 ENJEKTABL TOZ İÇEREN FLAKON (onay 04/11/2019)', 'https://titck.gov.tr/storage/Archive/2019/kubKtAttachments/T%C4%B0TCK%20Onayl%C4%B1%20K%C3%9CB%20PENTIN.pdf_ddb6ae02-eb96-42ad-a89c-10c0f0c58673.pdf'),
  },

  sefuroksim: {
    name: 'Sefuroksim aksetil',
    brand: ['Zinnat', 'Cefaks', 'Aksef', 'Sefurocide', 'Multisef'],
    dose: 'Yetişkin: çoğu enfeksiyonda 12 saatte bir 250 mg; ciddi alt solunum yolu enfeksiyonunda 12 saatte bir 500 mg. Komplike olmayan gonore: tek doz 1 g.',
    pediatricDose: '10–15 mg/kg, 12 saatte bir (otitis media / ciddi enfeksiyonda 15 mg/kg)',
    pediatrik: {
      min: 10, max: 15, birim: 'mg/kg/doz', gunlukBolum: 2,
      mutlakMaxMgGun: 500, enAzAy: 3,
      metin: 'KÜB §4.2: 3 ay–12 yaş bebek ve çocukta çoğu enfeksiyon için 12 saatte bir 10 mg/kg (günde en fazla 250 mg); otitis media ve daha şiddetli enfeksiyonlarda 12 saatte bir 15 mg/kg (günde en fazla 500 mg). 3 aydan küçük çocukta klinik veri yoktur, kullanımı önerilmez.',
    },
    form: 'Film tablet, oral süspansiyon',
    sgkCovered: true,
    category: 'Sefalosporin (2. kuşak)',
    siniflar: ['Sefalosporin', 'Beta-laktam', '2. kuşak sefalosporin', 'Antibiyotik'],
    alerjiSinifi: ['sefalosporin', 'penisilin'],
    yasKontrendikasyonAy: 3,
    contraindications: ['Sefalosporin alerjisi', 'Beta-laktam antibiyotiklere (penisilin, monobaktam, karbapenem) aşırı duyarlılık öyküsü', '3 ay altı bebekte önerilmez'],
    interactions: ['Probenesid', 'Antiasitler', 'Oral antikoagülanlar', 'H2 reseptör antagonistleri', 'Proton pompa inhibitörleri'],
    etkilesimler: [
      ...SEFALOSPORIN_ETKILESIM,
      { ile: 'Proton pompa inhibitörü', siddet: 'orta', not: 'Mide asiditesini azaltan ilaçlar sefuroksim aksetilin biyoyararlanımını düşürür (KÜB §4.5).' },
    ],
    gebelik: { kategori: 'B', metin: 'Hayvan çalışmalarında zararlı etki gösterilmemiştir; gebe kadınlara verilirken tedbirli olunmalıdır (KÜB §4.6).' },
    emzirme: 'Anne sütüne geçer; emzirme döneminde kullanılabilir.',
    bobrekDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Yemekle birlikte alındığında emilimi artar.',
    kaynak: kub('CEFAKS 250 MG/5 ML ORAL SÜSPANSİYON (onay 02/05/2024)', 'https://titck.gov.tr/storage/Archive/2024/kubKtAttachments/TTCKOnaylKBCEFAKS250_07177e07-4a1c-493d-bb1f-09c86b02a934.pdf'),
  },

  sefdinir: {
    name: 'Sefdinir',
    brand: ['Cefdiel', 'Tamcef', 'Sefdin', 'Cednir'],
    dose: 'Yetişkin: günde 600 mg (tek doz veya 12 saatte bir 300 mg).',
    pediatricDose: '14 mg/kg/gün (tek doz veya 2 doza bölünmüş, 7 mg/kg)',
    pediatrik: {
      min: 14, max: 14, birim: 'mg/kg/gün', gunlukBolum: 2,
      maxMgKgGun: 14, mutlakMaxMgGun: 600, enAzAy: 6,
      metin: 'KÜB §4.2: 6 aydan büyük–12 yaş çocukta akut otitis media, tonsillit/farenjit ve komplike olmayan cilt enfeksiyonunda günlük toplam doz 14 mg/kg/gün — iki doza bölünerek (7 mg/kg) veya tek doz. Sefdinir 6 aylıktan küçük bebeklere verilmemelidir.',
    },
    form: 'Kapsül, oral süspansiyon',
    sgkCovered: true,
    category: 'Sefalosporin (3. kuşak)',
    siniflar: ['Sefalosporin', 'Beta-laktam', '3. kuşak sefalosporin', 'Antibiyotik'],
    alerjiSinifi: ['sefalosporin', 'penisilin'],
    yasKontrendikasyonAy: 6,
    contraindications: ['Sefalosporin alerjisi', '6 ay altı bebek'],
    interactions: ['Antiasitler', 'Demir preparatları', 'Probenesid'],
    etkilesimler: [
      ...SEFALOSPORIN_ETKILESIM,
      { ile: 'Demir', siddet: 'orta', not: 'Demir içeren preparatlar sefdinir emilimini %80\'e varan oranda azaltır; en az 2 saat arayla alınmalı (KÜB §4.5).' },
      { ile: 'Antiasit', siddet: 'orta', not: 'Alüminyum/magnezyum içeren antiasit emilimi ~%40 azaltır; 2 saat ara verilmeli.' },
    ],
    gebelik: { kategori: 'B', metin: 'Gebelikte klinik veri yoktur; hayvan çalışmalarında zararlı etki gösterilmemiştir (KÜB §4.6).' },
    emzirme: 'Anne sütünde saptanmamıştır.',
    bobrekDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Demirle birlikte alındığında kırmızı-renkli dışkı görülebilir (zararsız, kanama değildir).',
    kaynak: kub('TAMCEF 250 MG/5 ML ORAL SÜSPANSİYON (onay 05/04/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/TAMCEF250KBTEMZ_06_04_2026.pdf'),
  },

  sefiksim: {
    name: 'Sefiksim',
    brand: ['Suprax', 'Innocef', 'Sefiksim', 'Zifi'],
    dose: 'Yetişkin ve >12 yaş: 200–400 mg/gün (tek doz veya 12 saat arayla iki eşit doz).',
    pediatricDose: '8 mg/kg/gün (6 aylıktan itibaren)',
    pediatrik: {
      min: 8, max: 8, birim: 'mg/kg/gün', gunlukBolum: 2,
      maxMgKgGun: 8, mutlakMaxMgGun: 400, enAzAy: 6,
      metin: 'KÜB §4.2: 6 aylıktan küçük çocuklarda etkililik ve güvenlilik kanıtlanmamıştır. 12 yaş üstünde erişkin dozu (200–400 mg/gün). Pediatrik mg/kg dozu için ürünün kendi dozaj tablosuna bakılmalıdır.',
    },
    form: 'Film tablet, saşe, oral süspansiyon',
    sgkCovered: true,
    category: 'Sefalosporin (3. kuşak)',
    siniflar: ['Sefalosporin', 'Beta-laktam', '3. kuşak sefalosporin', 'Antibiyotik'],
    alerjiSinifi: ['sefalosporin', 'penisilin'],
    yasKontrendikasyonAy: 6,
    contraindications: ['Sefiksim veya diğer sefalosporinlere aşırı duyarlılık', '6 ay altı bebekte etkililik/güvenlilik kanıtlanmamıştır'],
    interactions: ['Oral antikoagülanlar', 'Probenesid', 'Karbamazepin'],
    etkilesimler: SEFALOSPORIN_ETKILESIM,
    gebelik: { kategori: 'B', metin: 'Gebelikte klinik veri yoktur; hayvan çalışmalarında zararlı etki gösterilmemiştir. Plasentaya geçer (KÜB §4.6).' },
    emzirme: 'Anne sütüne geçişi saptanmamıştır.',
    bobrekDozUyarisi: true,
    renkliRecete: 'normal',
    kaynak: kub('İNNOCEF 100 MG SAŞE (onay 20/09/2021)', 'https://titck.gov.tr/storage/Archive/2021/kubKtAttachments/innocef100saekb_35d86f8a-8ca5-420f-8fa7-3af05bc1f0ad.pdf'),
  },

  sefaleksin: {
    name: 'Sefaleksin',
    brand: ['Sef', 'Maksipor', 'Cephalex', 'Sefalin'],
    dose: 'Yetişkin: 6 saatte bir 250 mg (1–4 g/gün). Streptokokal farenjit, deri/yumuşak doku ve komplike olmayan sistitte 12 saatte bir 500 mg.',
    pediatricDose: '25–50 mg/kg/gün, eşit dozlara bölünmüş (otitis mediada 75–100 mg/kg/gün, 4 doza bölünmüş)',
    pediatrik: {
      min: 25, max: 50, birim: 'mg/kg/gün', gunlukBolum: 3,
      maxMgKgGun: 100, mutlakMaxMgGun: 4000,
      metin: 'KÜB §4.2: çocuklarda günlük toplam doz 25–50 mg/kg, eşit dozlara bölünerek. 5 yaş altında 8 saatte bir 125 mg, 5 yaş ve üstünde 8 saatte bir 250 mg. Otitis media tedavisinde günlük toplam 75–100 mg/kg, dört eşit doza bölünerek.',
    },
    form: 'Kapsül, tablet, oral süspansiyon',
    sgkCovered: true,
    category: 'Sefalosporin (1. kuşak)',
    siniflar: ['Sefalosporin', 'Beta-laktam', '1. kuşak sefalosporin', 'Antibiyotik'],
    alerjiSinifi: ['sefalosporin', 'penisilin'],
    contraindications: ['Sefaleksin veya sefalosporin grubu antibiyotiklere aşırı duyarlılık'],
    interactions: ['Metformin', 'Aminoglikozidler', 'Oral kontraseptifler', 'Probenesid'],
    etkilesimler: [
      ...SEFALOSPORIN_ETKILESIM,
      { ile: 'Metformin', siddet: 'orta', not: 'Sefaleksin metforminin renal tübüler sekresyonunu azaltıp plazma düzeyini artırabilir (KÜB §4.5).' },
    ],
    gebelik: { kategori: 'B', metin: 'İnsanda yeterli çalışma yoktur; gerekli olmadıkça gebelikte kullanılmaz (KÜB §4.6).' },
    emzirme: 'Anne sütüne geçer; düşük düzeylerde, genellikle uyumlu kabul edilir.',
    bobrekDozUyarisi: true,
    renkliRecete: 'normal',
    kaynak: kub('SEF 250 MG/5 ML ORAL SÜSPANSİYON TOZU (onay 11/08/2025)', 'https://titck.gov.tr/storage/Archive/2025/kubKtAttachments/yaynlanacakkub_09_09_2025.pdf'),
  },

  sefprozil: {
    name: 'Sefprozil',
    brand: ['Serozil', 'Erasef', 'Cefzil'],
    dose: 'Yetişkin ve >12 yaş: üst solunum yolu 500 mg 1x1; sinüzit 12 saatte bir 250–500 mg; alt solunum yolu 12 saatte bir 500 mg.',
    pediatricDose: '7,5–20 mg/kg (otitis mediada 12 saatte bir 15 mg/kg)',
    pediatrik: {
      min: 7.5, max: 20, birim: 'mg/kg/doz', gunlukBolum: 2,
      mutlakMaxMgGun: 1000,
      metin: 'KÜB §4.2: otitis media 12 saatte bir 15 mg/kg; üst solunum yolu/farenjit/tonsillit günde bir 20 mg/kg veya 12 saatte bir 7,5 mg/kg; sinüzit 12 saatte bir 7,5–15 mg/kg; komplike olmayan deri enfeksiyonu günde bir 20 mg/kg. En yüksek günlük pediatrik doz erişkin dozunu geçmemelidir.',
    },
    form: 'Film tablet, oral süspansiyon',
    sgkCovered: true,
    category: 'Sefalosporin (2. kuşak)',
    siniflar: ['Sefalosporin', 'Beta-laktam', '2. kuşak sefalosporin', 'Antibiyotik'],
    alerjiSinifi: ['sefalosporin', 'penisilin'],
    contraindications: ['Sefprozil veya sefalosporin grubu antibiyotiklere alerji'],
    interactions: ['Aminoglikozidler', 'Probenesid', 'Oral kontraseptifler'],
    etkilesimler: SEFALOSPORIN_ETKILESIM,
    gebelik: { metin: 'Gebelikte klinik veri yoktur; hayvan çalışmalarında zararlı etki gösterilmemiştir (KÜB §4.6).' },
    emzirme: 'Anne sütüne az miktarda geçer.',
    bobrekDozUyarisi: true,
    renkliRecete: 'normal',
    kaynak: kub('ERASEF 250 MG/5 ML ORAL SÜSPANSİYON (onay 30/05/2025)', 'https://titck.gov.tr/storage/Archive/2025/kubKtAttachments/yaynlanacakerasefek2kub_02_09_2025.pdf'),
  },

  seftriakson: {
    name: 'Seftriakson',
    brand: ['Rocephin', 'Desefin', 'Sefetki', 'Iesef', 'Unacefin'],
    dose: 'Yetişkin ve >12 yaş: günde tek doz 1–2 g IM/IV; ağır vakada 4 g/gün.',
    pediatricDose: '20–80 mg/kg/gün tek doz (yenidoğanda 20–50 mg/kg/gün, 50 mg/kg aşılmaz)',
    pediatrik: {
      min: 20, max: 80, birim: 'mg/kg/gün', gunlukBolum: 1,
      maxMgKgGun: 80, mutlakMaxMgGun: 4000,
      metin: 'KÜB §4.2: 12 yaşından küçük çocukta günde tek doz 20–80 mg/kg. Yenidoğanda (14 günlüğe kadar) günde tek doz 20–50 mg/kg, günlük doz 50 mg/kg\'ı aşmamalıdır. Menenjitte günde tek doz 100 mg/kg (4 g aşılmaz). Akut otitis mediada 50 mg/kg (1 g\'ı aşmamak üzere).',
    },
    form: 'IM/IV enjeksiyonluk toz',
    sgkCovered: true,
    category: 'Sefalosporin (3. kuşak)',
    siniflar: ['Sefalosporin', 'Beta-laktam', '3. kuşak sefalosporin', 'Antibiyotik'],
    alerjiSinifi: ['sefalosporin', 'penisilin'],
    contraindications: [
      'Sefalosporin alerjisi',
      'Hiperbilirubinemili yenidoğan',
      'Prematüre yenidoğan',
      'Yenidoğanda (≤28 gün) IV kalsiyum içeren ürünlerle eş zamanlı kullanım',
    ],
    interactions: ['IV kalsiyum içeren çözeltiler', 'Kloramfenikol', 'Oral antikoagülanlar'],
    etkilesimler: [
      { ile: 'Kalsiyum', siddet: 'ciddi', not: 'Yenidoğanda (≤28 gün) IV kalsiyumla eş zamanlı kullanım KONTRENDİKE — seftriakson-kalsiyum presipitatı (KÜB §4.3). Diğer hastalarda aynı hatta verilmez.' },
      { ile: 'Kloramfenikol', siddet: 'orta', not: 'In vitro antagonist etki gösterilmiştir (KÜB §4.5).' },
      { ile: 'Varfarin', siddet: 'orta', not: 'INR yükselebilir; antikoagülan alan hastada takip.' },
    ],
    gebelik: { kategori: 'B', metin: 'Plasentayı geçer; hayvan üreme çalışmalarında olumsuz etki gösterilmemiştir, gebede güvenlilik kesinleşmemiştir (KÜB §4.6).' },
    emzirme: 'Anne sütüne düşük konsantrasyonda geçer.',
    bobrekDozUyarisi: true,
    renkliRecete: 'normal',
    kaynak: kub('SEFETKİ 0,5 G IV ENJEKSİYONLUK ÇÖZELTİ (onay 07/03/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/sefetki0.5vkb_10_03_2026.pdf'),
  },

  azitromisin: {
    name: 'Azitromisin',
    brand: ['Zitromax', 'Azeltin', 'Azitro', 'Zitrotek', 'Ribotrex'],
    dose: 'Yetişkin: 3 gün 500 mg 1x1 (toplam 1500 mg) veya 1. gün 500 mg + 2–5. gün 250 mg. Klamidyal üretrit/servisit: tek doz 1 g.',
    pediatricDose: '10 mg/kg/gün tek doz, 3 gün (toplam 30 mg/kg)',
    pediatrik: {
      min: 10, max: 10, birim: 'mg/kg/gün', gunlukBolum: 1,
      maxMgKgGun: 10, mutlakMaxMgGun: 500,
      metin: 'KÜB §4.2: çocuklarda 3 gün süreyle günde tek doz 10 mg/kg/gün; alternatif olarak 1. gün 10 mg/kg, 2.–5. gün 5 mg/kg (5 günde toplam 30 mg/kg). Akut otitis mediada tek doz 30 mg/kg seçeneği vardır. Pediatrik tedavide önerilen toplam maksimum doz 1500 mg. 45 kg üstü çocukta erişkin dozu.',
    },
    form: 'Film tablet, oral süspansiyon',
    sgkCovered: true,
    sgkRestriction: 'SUT: penisilin alerjisi veya atipik pnömoni belgelendiğinde ödenir.',
    category: 'Makrolid antibiyotik',
    siniflar: ['Makrolid', 'Azalid', 'Antibiyotik', 'QT uzatan ilaç'],
    alerjiSinifi: ['makrolid'],
    contraindications: ['Azitromisin, makrolid veya ketolid antibiyotiklere aşırı duyarlılık', 'Eritromisin alerjisi', 'Konjenital/dokümante QT uzaması'],
    interactions: ['Ergot türevleri', 'Digoksin', 'Siklosporin', 'Varfarin', 'Antiasitler', 'Statinler', 'QT uzatan ilaçlar'],
    etkilesimler: MAKROLID_ETKILESIM,
    gebelik: { kategori: 'B', metin: 'Hayvan üreme çalışmalarında fetal risk kanıtı yoktur; teratojenik etki gözlenmemiştir (KÜB §4.6).' },
    emzirme: 'Anne sütüne geçer; kısa kürlerde genellikle uyumlu kabul edilir.',
    bobrekDozUyarisi: true,
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Antiasitlerle birlikte alınmamalı. Şiddetli karaciğer yetmezliğinde kullanılmaz.',
    kaynak: kub('AZELTİN 200 MG/5 ML ORAL SÜSPANSİYON (onay 01/11/2024)', 'https://titck.gov.tr/storage/Archive/2024/kubKtAttachments/kubAZELTN200mg5mloralsspansiyoniinkurutoz_460216e1-dc03-4f0a-a048-fe8d7f90818b.pdf'),
  },

  klaritromisin: {
    name: 'Klaritromisin',
    brand: ['Klacid', 'Macrol', 'Clabel', 'Klarin', 'Lekoklar'],
    dose: 'Yetişkin: 12 saatte bir 250–500 mg. H. pylori eradikasyonunda 12 saatte bir 500 mg (kombinasyon içinde).',
    pediatricDose: '7,5 mg/kg, günde 2 kez (15 mg/kg/gün); maksimum günde 2×500 mg',
    pediatrik: {
      min: 15, max: 15, birim: 'mg/kg/gün', gunlukBolum: 2,
      maxMgKgGun: 15, mutlakMaxMgGun: 1000, mutlakMaxMgDoz: 500,
      metin: 'KÜB §4.2: çocuklarda günde iki defa 7,5 mg/kg (= 15 mg/kg/gün); mikobakteriyel olmayan enfeksiyonlar için maksimum doz günde iki defa 500 mg. 8 kg altındaki çocuğa 0,15 mL/kg (7,5 mg/kg) günde 2 kez.',
    },
    form: 'Film tablet, MR tablet, oral süspansiyon',
    sgkCovered: true,
    category: 'Makrolid antibiyotik',
    siniflar: ['Makrolid', 'Antibiyotik', 'CYP3A4 inhibitörü', 'QT uzatan ilaç'],
    alerjiSinifi: ['makrolid'],
    contraindications: [
      'Makrolid antibiyotiklere aşırı duyarlılık',
      'Astemizol, sisaprid, pimozid veya terfenadin ile birlikte kullanım',
      'Ergotamin / dihidroergotamin ile birlikte kullanım',
      'CYP3A4 ile metabolize olan statinlerle (simvastatin, lovastatin) birlikte kullanım',
      'QT uzaması / ventriküler aritmi öyküsü',
    ],
    interactions: ['Sisaprid', 'Pimozid', 'Terfenadin', 'Astemizol', 'Ergotamin', 'Simvastatin', 'Varfarin', 'Digoksin', 'Kolşisin', 'Siklosporin', 'Rifampisin', 'Karbamazepin'],
    etkilesimler: [
      ...MAKROLID_ETKILESIM,
      { ile: 'Sisaprid', siddet: 'ciddi', not: 'KONTRENDİKE — sisaprid düzeyi yükselir, QT uzaması ve Torsade de Pointes (KÜB §4.3).' },
      { ile: 'Rifampisin', siddet: 'orta', not: 'CYP3A indüksiyonu ile klaritromisin serum düzeyi düşer, etkinlik azalır (KÜB §4.5).' },
      { ile: 'Karbamazepin', siddet: 'ciddi', not: 'Klaritromisin karbamazepin düzeyini yükseltir; toksisite riski, düzey takibi gerekir.' },
    ],
    gebelik: { kategori: 'C', metin: 'Gebede yeterli veri yoktur; dikkatli yarar/risk değerlendirmesi yapılmadan kullanılması önerilmez (KÜB §4.6).' },
    emzirme: 'Anne sütüne geçer; emzirilen bebekte güvenlilik saptanmamıştır.',
    bobrekDozUyarisi: true,
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    kaynak: kub('CLABEL 250 MG/5 ML SÜSPANSİYON (onay 12/01/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/CLABEL250mg5mlssp.haz.iinkurutozkub_13_01_2026.pdf'),
  },

  eritromisin: {
    name: 'Eritromisin',
    brand: ['Eritro', 'Erythrocin', 'Eritromisin'],
    dose: 'Yetişkin ve >8 yaş çocuk: 8 saatte bir 500 mg. Hafif/orta enfeksiyonda 2 g/gün, şiddetli enfeksiyonda 4 g/gün\'e çıkılabilir.',
    pediatricDose: '30–50 mg/kg/gün, 3 doza bölünmüş (8 saatte bir)',
    pediatrik: {
      min: 30, max: 50, birim: 'mg/kg/gün', gunlukBolum: 3,
      maxMgKgGun: 50, mutlakMaxMgGun: 4000,
      metin: 'KÜB §4.2: çocuklarda genel doz günlük 30–50 mg/kg; günlük doz 3\'e bölünerek 8 saatte bir uygulanır.',
    },
    form: 'Film tablet, oral süspansiyon, göz pomadı',
    sgkCovered: true,
    category: 'Makrolid antibiyotik',
    siniflar: ['Makrolid', 'Antibiyotik', 'CYP3A4 inhibitörü', 'QT uzatan ilaç'],
    alerjiSinifi: ['makrolid'],
    contraindications: [
      'Eritromisin aşırı duyarlılığı',
      'Konjenital uzamış QT sendromu / Torsade de Pointes',
      'Astemizol, terfenadin, sisaprid veya pimozid kullanımı',
      'Ergotamin / dihidroergotamin ile birlikte kullanım',
    ],
    interactions: ['Sisaprid', 'Pimozid', 'Terfenadin', 'Ergotamin', 'Statinler', 'Varfarin', 'Teofilin', 'Midazolam', 'Kolşisin', 'Verapamil', 'Siklosporin'],
    etkilesimler: [
      ...MAKROLID_ETKILESIM,
      { ile: 'Teofilin', siddet: 'ciddi', not: 'Eritromisin teofilin klerensini azaltır; teofilin dozu azaltılmalı, düzey izlenmeli (KÜB §4.5).' },
      { ile: 'Midazolam', siddet: 'ciddi', not: 'Benzodiazepin klerensi azalır; uzamış sedasyon riski (KÜB §4.5).' },
      { ile: 'Verapamil', siddet: 'ciddi', not: 'Hipotansiyon, bradiaritmi ve laktik asidoz bildirilmiştir (KÜB §4.5).' },
    ],
    gebelik: { kategori: 'B', metin: 'Gözlemsel çalışmalarda erken gebelikte maruziyette kardiyovasküler malformasyon bildirilmiştir (KÜB §4.6).' },
    emzirme: 'Anne sütüne geçer; yenidoğanda pilor stenozu bildirimleri nedeniyle dikkatli kullanılır.',
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    kaynak: kub('ERİTRO 500 MG FİLM TABLET (onay 26/12/2014)', 'https://titck.gov.tr/storage/kubKtAttachments/37b2278288418.pdf'),
  },

  klindamisin: {
    name: 'Klindamisin',
    brand: ['Cleocin', 'Klindan', 'Klindaver', 'Dalacin'],
    dose: 'Yetişkin: 6 saatte bir 150–300 mg (ağır enfeksiyonda 450 mg).',
    pediatricDose: '8–25 mg/kg/gün, 3–4 eşit doza bölünmüş (1 aylıktan büyük çocuk)',
    pediatrik: {
      min: 8, max: 25, birim: 'mg/kg/gün', gunlukBolum: 4,
      maxMgKgGun: 25, enAzAy: 1,
      metin: 'KÜB §4.2: bir aylıktan büyük çocuklarda üç ya da dört eşit doz halinde günde 8–25 mg/kg. 10 kg ve altındaki çocukta önerilen en düşük doz 8 saatte bir 37,5 mg. Obeziteden bağımsız olarak toplam vücut ağırlığına göre dozlanır.',
    },
    form: 'Kapsül, oral süspansiyon, ampul, vajinal krem, topikal solüsyon',
    sgkCovered: true,
    category: 'Linkozamid antibiyotik',
    siniflar: ['Linkozamid', 'Antibiyotik'],
    contraindications: ['Klindamisin veya linkomisine aşırı duyarlılık'],
    interactions: ['Eritromisin', 'Rifampisin', 'Varfarin', 'Nöromusküler blokerler', 'Güçlü CYP3A4 inhibitörleri'],
    etkilesimler: [
      { ile: 'Eritromisin', siddet: 'orta', not: 'Antagonist etki — bu iki ilaç birlikte kullanılmamalıdır (KÜB §4.5).' },
      { ile: 'Rifampisin', siddet: 'orta', not: 'Güçlü CYP3A4 indükleyicisi klindamisin plazma konsantrasyonunu azaltır (KÜB §4.5).' },
      { ile: 'Varfarin', siddet: 'ciddi', not: 'K vitamini antagonistiyle birlikte INR ve kanama artışı bildirilmiştir; INR takibi (KÜB §4.5).' },
    ],
    gebelik: { metin: 'İlk trimesterde yeterli/kontrollü çalışma yoktur; gebe kadınlara verilirken tedbirli olunmalıdır (KÜB §4.6).' },
    emzirme: 'Anne sütüne geçer; bebekte ishal/kanlı dışkı açısından izlenmeli.',
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'C. difficile ilişkili diyare/psödomembranöz kolit riski sınıfın en yüksekleri arasındadır — tedavi sırasında ve sonrasında ishal sorgulanmalıdır.',
    kaynak: kub('CLEOCİN PEDİYATRİK 75 MG/5 ML ORAL SÜSPANSİYON (onay 06/05/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/UygunbulunanKBmetni7_07_05_2026.pdf'),
  },

  doksisiklin: {
    name: 'Doksisiklin',
    brand: ['Tetradox', 'Monodoks', 'Rosergol', 'Doksin', 'Vibramycin'],
    dose: 'Yetişkin ve >12 yaş: ilk gün 200 mg, sonra 100 mg/gün. Ağır enfeksiyonda tedavi boyunca 200 mg/gün.',
    form: 'Kapsül, dağılabilir tablet',
    sgkCovered: true,
    category: 'Tetrasiklin antibiyotik',
    siniflar: ['Tetrasiklin', 'Antibiyotik'],
    alerjiSinifi: ['tetrasiklin'],
    yasKontrendikasyonAy: 96,
    contraindications: [
      'Doksisiklin veya diğer tetrasiklinlere aşırı duyarlılık',
      'Gebelik',
      '8 yaş altı çocuk (dişlerde kalıcı renk değişimi)',
    ],
    interactions: ['Antiasitler', 'Demir preparatları', 'Kalsiyum', 'Penisilinler', 'Siklosporin', 'İzotretinoin', 'Metoksifluran', 'Varfarin', 'Karbamazepin'],
    etkilesimler: [
      { ile: 'Demir', siddet: 'orta', not: 'İki/üç değerlikli katyonlar doksisiklin emilimini belirgin azaltır; en az 2–3 saat arayla alınmalı (KÜB §4.5).' },
      { ile: 'Antiasit', siddet: 'orta', not: 'Alüminyum/magnezyum/kalsiyum içeren antiasitler emilimi bozar; ara verilmeli.' },
      { ile: 'Kalsiyum', siddet: 'orta', not: 'Kalsiyum şelasyonu emilimi azaltır; ayrı saatlerde alınmalı.' },
      { ile: 'İzotretinoin', siddet: 'ciddi', not: 'Birlikte kullanımdan KAÇINILMALIDIR — benign intrakraniyal hipertansiyon riski (KÜB §4.5).' },
      { ile: 'Siklosporin', siddet: 'orta', not: 'Doksisiklin siklosporin plazma konsantrasyonunu artırabilir (KÜB §4.5).' },
      { ile: 'Varfarin', siddet: 'orta', not: 'Antikoagülan etki artabilir; INR takibi önerilir.' },
      { ile: 'Penisilin', siddet: 'orta', not: 'Bakteriyostatik tetrasiklin penisilinin bakterisidal etkisini antagonize edebilir; birlikte verilmemesi önerilir.' },
    ],
    gebelik: { kategori: 'D', metin: 'Gebelikte KONTRENDİKE — 2. ve 3. trimesterde fetal diş ve iskelet gelişimi üzerine etki; 1. trimesterde de kaçınılmalıdır (KÜB §4.3/4.6).' },
    emzirme: 'Anne sütüne geçer; uzun süreli kullanım emzirme döneminde önerilmez.',
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Fotosensitivite yapar — güneş koruması önerilmeli. Özofagus ülserini önlemek için bol suyla ve ayakta alınmalıdır.',
    kaynak: kub('ROSERGOL 100 MG DAĞILABİLİR TABLET (onay 26/05/2023)', 'https://titck.gov.tr/storage/Archive/2023/kubKtAttachments/KB_4b778d4b-de22-4336-a37b-90e96d7bd9e7.pdf'),
  },

  trimetoprimSulfametoksazol: {
    name: 'Trimetoprim + Sülfametoksazol',
    brand: ['Bactrim', 'Septrin', 'Kemoprim', 'Metoprim'],
    dose: 'Yetişkin: 12 saatte bir 160/800 mg (forte tablet). Komplike olmayan alt ÜSE\'de 3 günlük kısa tedavi seçeneği vardır.',
    pediatricDose: '6 mg/kg trimetoprim + 30 mg/kg sülfametoksazol/gün, 2 doza bölünmüş',
    pediatrik: {
      min: 6, max: 6, birim: 'mg/kg/gün', gunlukBolum: 2,
      maxMgKgGun: 6, enAzAy: 1.5,
      metin: 'KÜB §4.2 (trimetoprim üzerinden): 12 yaş ve altı çocuklarda günde ~6 mg/kg trimetoprim + 30 mg/kg sülfametoksazol, eşit iki doza bölünerek. 6 hafta–5 ay: 12 saatte bir 2,5 mL; 6 ay–5 yaş: 12 saatte bir 5 mL; 6–12 yaş: 12 saatte bir 10 mL (pediatrik süspansiyon). Yaşamın ilk 6 haftasında uygulanmaz.',
    },
    form: 'Film tablet, forte tablet, oral süspansiyon, IV',
    sgkCovered: true,
    category: 'Sülfonamid + dihidrofolat redüktaz inhibitörü',
    siniflar: ['Sülfonamid', 'Antibiyotik', 'Ko-trimoksazol', 'Folat antagonisti'],
    alerjiSinifi: ['sulfonamid'],
    yasKontrendikasyonAy: 1.5,
    contraindications: [
      'Sülfonamid, trimetoprim veya ko-trimoksazol aşırı duyarlılığı',
      'Ciddi karaciğer fonksiyon bozukluğu',
      'Ciddi böbrek yetmezliği (plazma düzeyi izlenemiyorsa)',
      'Yaşamın ilk 6 haftasındaki yenidoğan',
      'İlaca bağlı immün trombositopeni öyküsü',
      'Akut porfiri',
    ],
    interactions: ['Varfarin', 'Metotreksat', 'Digoksin', 'Fenitoin', 'Sülfonilüre', 'ACE inhibitörleri', 'ARB', 'Spironolakton', 'Rifampisin', 'Siklosporin'],
    etkilesimler: [
      { ile: 'Varfarin', siddet: 'ciddi', not: 'Antikoagülan etkiyi belirgin artırır; INR sıkı takip edilmeli (KÜB §4.5).' },
      { ile: 'Metotreksat', siddet: 'ciddi', not: 'Serbest MTX düzeyini yükseltir ve folat antagonizmasını toplar; pansitopeni riski. Birlikte kullanımdan kaçınılmalı.' },
      { ile: 'ACE inhibitörü', siddet: 'ciddi', not: 'Trimetoprim potasyum atılımını azaltır; birlikte ciddi hiperkalemi riski (KÜB §4.5).' },
      { ile: 'Anjiyotensin II reseptör blokeri', siddet: 'ciddi', not: 'Hiperkalemi riski artar; özellikle yaşlıda potasyum izlenmeli.' },
      { ile: 'Spironolakton', siddet: 'ciddi', not: 'Potasyum tutucu diüretikle birlikte hayatı tehdit eden hiperkalemi bildirilmiştir (KÜB §4.5).' },
      { ile: 'Sülfonilüre', siddet: 'orta', not: 'Hipoglisemik etki güçlenebilir (KÜB §4.5).' },
      { ile: 'Fenitoin', siddet: 'orta', not: 'Fenitoin metabolizması yavaşlar, düzeyi yükselir.' },
      { ile: 'Digoksin', siddet: 'orta', not: 'Özellikle yaşlıda plazma digoksin düzeyini yükseltir (KÜB §4.5).' },
      { ile: 'Rifampisin', siddet: 'orta', not: 'Bir haftadan sonra trimetoprim plazma düzeyini belirgin düşürür (KÜB §4.5).' },
    ],
    gebelik: { kategori: 'C', metin: 'Plasentadan geçer, folat antagonistidir; gebede yeterli veri yoktur. Son trimesterde kernikterus riski nedeniyle kaçınılır (KÜB §4.6).' },
    emzirme: 'Anne sütüne geçer; prematüre, hiperbilirubinemili ve G6PD eksikliği olan bebeklerde kullanılmaz.',
    bobrekDozUyarisi: true,
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Stevens-Johnson sendromu / toksik epidermal nekroliz riski — döküntü gelişirse ilaç derhal kesilmelidir.',
    kaynak: kub('BACTRİM 200 MG + 40 MG/5 ML SÜSPANSİYON (onay 19/09/2025)', 'https://titck.gov.tr/storage/Archive/2025/kubKtAttachments/BACTRM200SSPKBTEMZ_17_10_2025.pdf'),
  },
}
