/**
 * Dermatoloji sistemik + romatoloji + sistemik/oftalmik kortikosteroidler.
 *
 * Two entries here are the ones a Turkish outpatient card most needs to shout about:
 *   • izotretinoin — gebelikte MUTLAK kontrendike, Gebelik Önleme Programı ve tetrasiklinle
 *     birlikte kullanım yasağı;
 *   • metotreksat — HAFTADA BİR dozlanır; günlük verilmesi ölümcüldür ve NSAİİ, penisilin,
 *     ko-trimoksazol, PPİ ve salisilatlarla etkileşimi ayrı ayrı yazılıdır.
 */
import { kub } from '../kaynak'
import type { TürkishDrug } from '../tipler'

const KORTIKOSTEROID_SINIF = ['Kortikosteroid', 'Glukokortikoid', 'Sistemik kortikosteroid', 'İmmünosupresan'] as const

const KORTIKOSTEROID_ETKILESIM = [
  { ile: 'NSAİİ', siddet: 'ciddi' as const, not: 'GİS ülserasyon ve kanama riski belirgin artar; birlikte kullanımda gastroproteksiyon düşünülmelidir.' },
  { ile: 'Antidiyabetik', siddet: 'orta' as const, not: 'Kan şekerini yükseltir; antidiyabetik doz gereksinimi artar.' },
  { ile: 'Diüretik', siddet: 'orta' as const, not: 'Potasyum kaybı toplanır; hipokalemi riski.' },
  { ile: 'Varfarin', siddet: 'orta' as const, not: 'Antikoagülan yanıt değişebilir; INR izlenmelidir.' },
  { ile: 'Rifampisin', siddet: 'orta' as const, not: 'Enzim indüksiyonu steroid etkinliğini azaltır; doz artırımı gerekebilir.' },
  { ile: 'Canlı aşı', siddet: 'ciddi' as const, not: 'İmmünosupresif dozda kortikosteroid alan hastada canlı aşı KONTRENDİKEDİR (KÜB §4.3).' },
] as const

export const DERM_ROMATOLOJI: Record<string, TürkishDrug> = {
  izotretinoin: {
    name: 'İzotretinoin',
    brand: ['Roaccutane', 'Aknetrent', 'Zoretanin', 'Isotrex'],
    dose: 'Tedaviye 0,5 mg/kg/gün ile başlanır; idame 0,5–1,0 mg/kg/gün (gerekirse 2,0 mg/kg\'a kadar). Remisyon için hedeflenen kümülatif doz 120–150 mg/kg.',
    pediatricDose: '12 yaşından büyük çocuklarda doz ayarlaması gerekmez; 12 yaşından küçük çocuklarda KONTRENDİKE',
    pediatrik: {
      min: 0.5, max: 1.0, birim: 'mg/kg/gün', gunlukBolum: 2,
      maxMgKgGun: 2.0, enAzAy: 144,
      metin: 'KÜB §4.2: tedaviye günde 0,5 mg/kg\'lık dozla başlanır; idame dozu 0,5–1,0 mg/kg arasında değişir, bazı hastalarda 2,0 mg/kg\'a varan dozlar gerekebilir. Kümülatif 120–150 mg/kg tedavi dozunun remisyon oranlarını artırdığı bildirilmiştir. 12 yaşından küçük çocuklarda kontrendikedir; 12 yaşından büyük çocuklarda doz ayarlaması gerekli değildir.',
    },
    form: 'Yumuşak kapsül',
    sgkCovered: true,
    sgkRestriction: 'SUT: dermatoloji uzman hekim raporu ve endikasyon koşullarına bakınız.',
    category: 'Sistemik retinoid',
    siniflar: ['Retinoid', 'Sistemik retinoid', 'A vitamini türevi'],
    yasKontrendikasyonAy: 144,
    contraindications: [
      'GEBELİK',
      'Emzirme',
      'Gebelik Önleme Programı koşulları yerine getirilmeyen doğurganlık çağındaki kadınlar',
      'Tetrasiklinlerle birlikte tedavi',
      'Karaciğer yetmezliği',
      'Aşırı yüksek kan lipid değerleri',
      'Hipervitaminoz A',
      '12 yaş altı çocuklar',
    ],
    interactions: ['Tetrasiklinler', 'Doksisiklin', 'A vitamini', 'Diğer retinoidler', 'Progesteron içeren düşük doz kontraseptifler'],
    etkilesimler: [
      { ile: 'Doksisiklin', siddet: 'ciddi', not: 'KONTRENDİKE — birlikte kullanım benign intrakraniyal hipertansiyon (psödotümör serebri) riskini artırır (KÜB §4.3).' },
      { ile: 'Tetrasiklin', siddet: 'ciddi', not: 'KONTRENDİKE — intrakraniyal hipertansiyon riski (KÜB §4.3).' },
      { ile: 'A vitamini', siddet: 'ciddi', not: 'Hipervitaminoz A belirtileri toplanır.' },
    ],
    gebelik: { kategori: 'X', metin: 'MUTLAK KONTRENDİKE — çok ağır fetal malformasyon riski. Tedaviden önceki iki hafta içinde negatif gebelik testi, tedavi boyunca aylık test, tedavi süresince ve kesildikten sonra 1 ay etkili kontrasepsiyon zorunludur. Tedaviye bir sonraki adetin 2.–3. gününden önce başlanmaz (KÜB §4.2/4.3).' },
    emzirme: 'KONTRENDİKE — emziren kadınlarda kullanılmaz (KÜB §4.3).',
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Karaciğer enzimleri ve lipid profili tedavi öncesi, 1. ayda ve periyodik izlenmelidir. Depresyon/intihar düşüncesi bildirilmiştir; hasta ve aile bilgilendirilmelidir. Tedavi sırasında ve sonrasında 1 ay kan bağışı yapılmaz.',
    kaynak: kub('AKNETRENT 10 MG YUMUŞAK KAPSÜL (onay 13/11/2023)', 'https://titck.gov.tr/storage/Archive/2023/kubKtAttachments/AKNETRENT10TEMZKB_83d6837d-6ece-46bb-974a-da641859909a.pdf'),
  },

  metotreksat: {
    name: 'Metotreksat',
    brand: ['Methotrexate', 'Emthexate', 'Trexan', 'Zexate'],
    dose: 'Romatoid artrit (erişkin): HAFTADA BİR 7,5 mg oral (veya 12 saat arayla bölünmüş 3×2,5 mg). Haftalık toplam doz 20 mg\'ı geçmeyecek şekilde titre edilir. Tedaviye başlamadan 1 hafta önce 5–10 mg test dozu önerilir.',
    pediatricDose: 'Pediyatrik hastalarda güvenlilik ve etkililik belirlenmemiştir (bu üründe)',
    form: 'Tablet, enjeksiyonluk çözelti, kullanıma hazır kalem',
    sgkCovered: true,
    sgkRestriction: 'SUT: romatoloji/onkoloji endikasyon ve rapor koşullarına bakınız.',
    category: 'Folat antagonisti / DMARD',
    siniflar: ['DMARD', 'Folat antagonisti', 'İmmünosupresan', 'Antimetabolit', 'Sitotoksik'],
    contraindications: [
      'Metotreksata aşırı duyarlılık',
      'Karaciğer yetmezliği; fibrozis, siroz, aktif veya yakın hepatit',
      'Aşırı alkol kullanımı',
      'Renal yetmezlik (kreatinin klerensi <20 mL/dk)',
      'Kemik iliği hipoplazisi, lökopeni, trombositopeni, belirgin anemi',
      'İmmün yetmezlik, tüberküloz, HIV gibi ağır akut/kronik enfeksiyon',
      'Ağız boşluğu ülserleri ve aktif peptik ülser',
      'Gebelik ve emzirme',
    ],
    interactions: ['NSAİİ', 'Asetilsalisilik asit', 'Penisilinler', 'Trimetoprim + sülfametoksazol', 'Proton pompa inhibitörleri', 'Probenesid', 'Siprofloksasin', 'Levetirasetam'],
    etkilesimler: [
      { ile: 'NSAİİ', siddet: 'ciddi', not: 'Renal klerensi azaltır; MTX düzeyi yükselir, hematolojik toksisite riski. Yüksek doz MTX ile birlikte verilmez (KÜB §4.5).' },
      { ile: 'Asetilsalisilik asit', siddet: 'ciddi', not: '≥15 mg/hafta MTX ile birlikte kullanım KONTRENDİKEDİR (aspirin KÜB §4.3).' },
      { ile: 'Trimetoprim', siddet: 'ciddi', not: 'Folat antagonizması toplanır; pansitopeni bildirilmiştir — birlikte kullanımdan kaçınılmalıdır.' },
      { ile: 'Penisilin', siddet: 'ciddi', not: 'Penisilinler MTX atılımını azaltır, toksisite riski artar.' },
      { ile: 'Proton pompa inhibitörü', siddet: 'ciddi', not: 'Yüksek doz MTX ile birlikte MTX düzeyini yükseltir; PPİ geçici kesilmelidir.' },
      { ile: 'Siprofloksasin', siddet: 'ciddi', not: 'Renal tübüler taşınma yarışması MTX düzeyini yükseltir.' },
      { ile: 'Probenesid', siddet: 'ciddi', not: 'MTX renal atılımını azaltır; toksisite riski.' },
    ],
    gebelik: { kategori: 'X', metin: 'Gebelikte KONTRENDİKE — teratojen ve abortifasiyan. Kadınlarda tedavi sonrası en az 6 ay, erkeklerde 3 ay etkili kontrasepsiyon önerilir.' },
    emzirme: 'KONTRENDİKE — emzirme döneminde kullanılmaz.',
    bobrekDozUyarisi: true,
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'HAFTADA BİR dozlanır — günlük alım ölümcül pansitopeni yapar; reçete ve hasta eğitimi bu noktayı açıkça belirtmelidir. Folik asit desteği yan etkileri azaltır. Tam kan sayımı, karaciğer ve böbrek fonksiyonları düzenli izlenmelidir.',
    kaynak: kub('EMTHEXATE 2,5 MG TABLET (onay 13/04/2020)', 'https://titck.gov.tr/storage/Archive/2020/kubKtAttachments/UYGUNKUB_1987c77e-9b23-4480-ae63-79d1b764260c.pdf'),
  },

  hidroksiklorokin: {
    name: 'Hidroksiklorokin',
    brand: ['Plaquenil', 'Kinovir', 'Quensyl'],
    dose: 'En düşük etkili doz uygulanır; doz ideal vücut ağırlığına göre 6,5 mg/kg/günü AŞMAMALIDIR. Her doz yiyecek veya bir bardak sütle alınır.',
    pediatricDose: '6,5 mg/kg/gün (ideal vücut ağırlığına göre) aşılmamalıdır; 200 mg tablet 35 kg altı çocuklar için uygun değildir',
    pediatrik: {
      min: 6.5, max: 6.5, birim: 'mg/kg/gün', gunlukBolum: 1,
      maxMgKgGun: 6.5, enAzAy: 72,
      metin: 'KÜB §4.2: en düşük etkili doz uygulanmalı ve doz ideal vücut ağırlığına göre 6,5 mg/kg/günü aşmamalıdır. 200 mg tablet, 6 yaşından küçük ve ideal vücut ağırlığı 31–35 kg\'dan düşük çocuklar için uygun değildir. Çok zayıf hastalarda ideal vücut ağırlığı kullanıldığında retinal toksisite riski artar.',
    },
    form: 'Film kaplı tablet',
    sgkCovered: true,
    sgkRestriction: 'SUT: romatoloji endikasyon ve rapor koşullarına bakınız.',
    category: 'Antimalaryal / DMARD',
    siniflar: ['DMARD', '4-aminokinolin', 'Antimalaryal', 'İmmünomodülatör', 'QT uzatan ilaç'],
    yasKontrendikasyonAy: 72,
    contraindications: [
      '4-aminokinolin bileşiklerine aşırı duyarlılık',
      'Gözde önceden var olan makulopati',
      '6 yaşından küçük çocuklar (200 mg tablet formu)',
      'İdeal vücut ağırlığı 31 kg\'dan düşük çocuklar',
    ],
    interactions: ['Digoksin', 'İnsülin', 'Antidiyabetikler', 'QT uzatan ilaçlar', 'Metotreksat', 'Siklosporin', 'Antiasitler'],
    etkilesimler: [
      { ile: 'QT uzatan ilaç', siddet: 'ciddi', not: 'Hidroksiklorokin QT\'yi uzatır; birlikte kullanımda ventriküler aritmi riski artar.' },
      { ile: 'Digoksin', siddet: 'orta', not: 'Serum digoksin düzeyini yükseltebilir; düzey izlenmelidir.' },
      { ile: 'Antidiyabetik', siddet: 'orta', not: 'Hipoglisemik etkiyi güçlendirebilir; kan şekeri izlenmelidir.' },
      { ile: 'Siklosporin', siddet: 'orta', not: 'Siklosporin plazma düzeyini yükseltebilir.' },
      { ile: 'Antiasit', siddet: 'orta', not: 'Emilimi azaltır; en az 4 saat ara verilmelidir.' },
    ],
    gebelik: { metin: 'Romatolojik endikasyonlarda gebelikte sürdürülebilen az sayıdaki DMARD\'dan biridir; karar hekimindir.' },
    emzirme: 'Anne sütüne az miktarda geçer; emzirme döneminde genellikle uyumlu kabul edilir.',
    renkliRecete: 'normal',
    notes: 'Retinal toksisite kümülatif doz ve süreyle ilişkilidir — tedavi başında ve yıllık göz muayenesi (OCT dahil) önerilir.',
    kaynak: kub('KİNOVİR 200 MG FİLM KAPLI TABLET (onay 15/09/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/EkOnaylananKBmetni_858bee83-94c3-4fa9-851d-199c6b0ce2b9.pdf'),
  },

  siklosporin: {
    name: 'Siklosporin',
    brand: ['Sandimmun Neoral', 'Cylorin', 'Sigmasporin'],
    dose: 'Günlük doz mutlaka iki eşit doza bölünür ve her gün aynı saatte, öğünle aynı ilişkide alınır. Transplantasyonda başlangıç 10–15 mg/kg/gün, idame 3–6 mg/kg/gün. Non-transplant endikasyonlarda erişkinde 5 mg/kg/gün, çocukta 6 mg/kg/gün aşılmamalıdır.',
    pediatricDose: 'Non-transplant endikasyonlarda çocuklarda 6 mg/kg/gün aşılmamalıdır',
    pediatrik: {
      min: 3, max: 6, birim: 'mg/kg/gün', gunlukBolum: 2,
      maxMgKgGun: 6,
      metin: 'KÜB §4.2: günlük doz mutlaka iki eşit doza bölünerek verilir. Transplantasyon dışı endikasyonlarda yetişkinlerde 5 mg/kg/gün, çocuklarda 6 mg/kg/gün\'lük dozlar aşılmamalıdır. Yalnızca immünosupresif tedavi/organ transplantasyonu deneyimi olan hekim tarafından reçete edilmelidir.',
    },
    form: 'Yumuşak kapsül, oral çözelti, IV konsantre',
    sgkCovered: true,
    sgkRestriction: 'SUT: transplantasyon / romatoloji / dermatoloji endikasyon ve rapor koşullarına bakınız.',
    category: 'Kalsinörin inhibitörü (immünosupresan)',
    siniflar: ['İmmünosupresan', 'Kalsinörin inhibitörü', 'CYP3A4 substratı'],
    contraindications: [
      'Siklosporine aşırı duyarlılık',
      'Sarı kantaron (Hypericum perforatum) içeren ürünlerle kombinasyon',
      'P-gp veya OATP substratı olup yüksek plazma konsantrasyonu yaşamı tehdit eden ilaçlarla (bosentan, dabigatran) kombinasyon',
    ],
    interactions: ['Statinler', 'NSAİİ', 'Makrolidler', 'Azol antifungaller', 'Rifampisin', 'Sarı kantaron', 'Greyfurt suyu', 'ACE inhibitörleri', 'Metotreksat', 'Kolşisin', 'Fenofibrat'],
    etkilesimler: [
      { ile: 'Statin', siddet: 'ciddi', not: 'Statin plazma düzeyini belirgin yükseltir; rabdomiyoliz riski. Rosuvastatin ile birlikte kullanım kontrendikedir.' },
      { ile: 'NSAİİ', siddet: 'ciddi', not: 'Renal prostaglandin inhibisyonu ile nefrotoksisite riski artar (KÜB §4.5).' },
      { ile: 'Klaritromisin', siddet: 'ciddi', not: 'CYP3A4 inhibisyonu siklosporin düzeyini belirgin yükseltir; düzey takibi zorunlu.' },
      { ile: 'İtrakonazol', siddet: 'ciddi', not: 'Siklosporin maruziyetini artırır; doz azaltımı ve düzey takibi gerekir.' },
      { ile: 'Rifampisin', siddet: 'ciddi', not: 'Siklosporin düzeyini belirgin düşürür; rejeksiyon riski.' },
      { ile: 'ACE inhibitörü', siddet: 'ciddi', not: 'Hiperkalemi riski artar; potasyum izlenmelidir.' },
      { ile: 'Kolşisin', siddet: 'ciddi', not: 'Kolşisin toksisitesi (miyopati, nöropati, pansitopeni) riski belirgin artar.' },
      { ile: 'Amlodipin', siddet: 'ciddi', not: 'Siklosporin kan düzeyini yükseltir; düzey izlenmeli ve gerekirse doz düşürülmelidir.' },
    ],
    gebelik: { metin: 'Gebelikte yalnızca açık gereklilikte; plasentayı geçer, prematürite ve düşük doğum ağırlığı bildirilmiştir.' },
    emzirme: 'Anne sütüne geçer; emzirme döneminde önerilmez.',
    bobrekDozUyarisi: true,
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Kan düzeyi, kan basıncı, kreatinin ve potasyum düzenli izlenmelidir. Greyfurt suyu maruziyeti belirgin artırır. Marka değişiminde düzey yeniden ölçülmelidir.',
    kaynak: kub('CYLORİN 25 MG YUMUŞAK KAPSÜL (onay 17/01/2025)', 'https://titck.gov.tr/storage/Archive/2025/kubKtAttachments/1311kuUbtemiz_22_01_2025.pdf'),
  },

  metilprednizolon: {
    name: 'Metilprednizolon',
    brand: ['Prednol', 'Precort', 'Medrol', 'Metpred'],
    dose: 'Başlangıç günlük doz endikasyona göre: alerjik hastalıklar 12–40 mg, bronşiyal astım 64 mg\'a kadar (alternatif gün maksimum 100 mg), SLE 20–100 mg, hematolojik hastalıklar 16–100 mg. Tek doz veya bölünmüş dozlar halinde.',
    pediatricDose: 'Organ naklinde 3,6 mg/kg/güne kadar. Büyüme geriliği riski nedeniyle zorunlu neden olmadıkça çocuklarda kullanılmamalıdır',
    pediatrik: {
      min: 0.5, max: 3.6, birim: 'mg/kg/gün', gunlukBolum: 2,
      maxMgKgGun: 3.6,
      metin: 'KÜB §4.2: organ naklinde 3,6 mg/kg/güne kadar. Diğer endikasyonlarda pediyatrik doz erişkin dozları üzerinden ve mümkün olan en kısa süre/en düşük dozla belirlenir; mümkünse gün aşırı tek doz verilir. Büyümede gerileme riski nedeniyle çocuklarda zorunlu nedenler olmadıkça kullanılmamalıdır.',
    },
    form: 'Tablet, IV/IM flakon, depo enjeksiyon',
    sgkCovered: true,
    category: 'Sistemik kortikosteroid',
    siniflar: [...KORTIKOSTEROID_SINIF],
    contraindications: [
      'Metilprednizolon veya diğer glukokortikoidlere aşırı duyarlılık',
      'Sistemik fungal enfeksiyon',
      'Spesifik antiinfektif tedavi uygulanmayan sistemik enfeksiyon',
      'İmmünosupresif dozlarda canlı aşı uygulaması',
    ],
    interactions: ['NSAİİ', 'Antidiyabetikler', 'Varfarin', 'Diüretikler', 'Rifampisin', 'Klaritromisin', 'Canlı aşılar', 'Siklosporin'],
    etkilesimler: [
      ...KORTIKOSTEROID_ETKILESIM,
      { ile: 'Klaritromisin', siddet: 'orta', not: 'CYP3A4 inhibisyonu steroid maruziyetini artırır; sistemik yan etki riski.' },
      { ile: 'Siklosporin', siddet: 'orta', not: 'Karşılıklı metabolizma inhibisyonu; konvülsiyon bildirilmiştir.' },
    ],
    gebelik: { metin: 'Gebelikte gerektiğinde kullanılabilir; uzun süreli yüksek dozda fetal büyüme geriliği ve adrenal supresyon riski.' },
    emzirme: 'Anne sütüne az miktarda geçer; düşük dozlarda emzirme sürdürülebilir.',
    renkliRecete: 'normal',
    notes: 'Ani kesilmesi adrenal yetmezlik yapar — 2 haftadan uzun kullanımda kademeli azaltılmalıdır. Canlı aşı immünosupresif dozda kontrendikedir.',
    kaynak: kub('PRECORT 4 MG TABLET (onay 29/05/2021)', 'https://titck.gov.tr/storage/Archive/2021/kubKtAttachments/TTCKONAYLIKBPRECORT4MG_fbefbd6b-4216-4581-bf64-c91b91daeb5b.pdf'),
  },

  prednizolon: {
    name: 'Prednizolon',
    brand: ['Deltacortril', 'Prednol-L', 'Codelton'],
    dose: 'Genellikle 10–30 mg/gün; çok ciddi akut vakalarda birkaç gün 50–60 mg veya daha fazla. Yanıt alındıktan sonra her 2–5 günde bir 2,5–5 mg azaltılarak en düşük idame dozuna inilir. İdame doz sabah 08:00\'de verilmelidir.',
    pediatricDose: 'Uzun süreli farmakolojik dozlardan kaçınılmalı; gerekirse büyüme ve gelişim yakından takip edilmelidir',
    form: 'Tablet',
    sgkCovered: true,
    category: 'Sistemik kortikosteroid',
    siniflar: [...KORTIKOSTEROID_SINIF],
    contraindications: [
      'Prednizolona aşırı duyarlılık',
      'Sistemik mantar enfeksiyonu',
      'İmmünosupresif dozda kortikosteroid alan hastada canlı aşı uygulaması',
    ],
    interactions: ['NSAİİ', 'Antidiyabetikler', 'Varfarin', 'Diüretikler', 'Rifampisin', 'Canlı aşılar'],
    etkilesimler: KORTIKOSTEROID_ETKILESIM,
    gebelik: { metin: 'Gebelikte gerektiğinde kullanılabilir; plasentayı prednizolon büyük ölçüde geçmez (11-beta-HSD2 ile inaktive edilir).' },
    emzirme: 'Anne sütüne az miktarda geçer; emzirme döneminde kullanılabilir (yüksek dozda alımdan 4 saat sonra emzirme önerilir).',
    renkliRecete: 'normal',
    notes: 'Hayat kurtarıcı olduğu durumlarda kontrendikasyonlar geçerli değildir (KÜB §4.3). Uzun kullanımda kemik yoğunluğu, kan şekeri ve kan basıncı izlenmelidir.',
    kaynak: kub('DELTACORTRİL 5 MG TABLET (onay 12/06/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/DELTACORTRL5mgtabletkub_17_06_2026.pdf'),
  },

  deksametazonOftalmik: {
    name: 'Deksametazon (oftalmik)',
    brand: ['Maxidex', 'Dexa-Sine', 'Tobradex (kombinasyon)'],
    dose: 'Konjonktival keseye 1–2 damla. Ciddi/akut inflamasyonda başlangıçta 30–60 dakikada bir, yanıt alındıktan sonra 2–4 saatte bir; kontrol sağlandıkça günde 3–4 kez 1 damlaya inilir.',
    pediatricDose: 'Çocuk hastalarda güvenlilik ve etkililik saptanmamıştır',
    form: 'Steril oftalmik süspansiyon (göz damlası)',
    sgkCovered: true,
    category: 'Oftalmik kortikosteroid',
    siniflar: ['Kortikosteroid', 'Glukokortikoid', 'Oftalmik kortikosteroid'],
    contraindications: [
      'Deksametazona aşırı duyarlılık',
      'Akut, tedavi edilmemiş bakteriyel enfeksiyon',
      'Herpes simpleks keratiti',
      'Mikobakteriyel göz hastalıkları',
      'Kornea/konjonktivanın viral enfeksiyonları (vaccinia, varicella)',
      'Gözün fungal hastalıkları veya tedavi edilmemiş paraziter enfeksiyonları',
    ],
    interactions: [],
    etkilesimler: [],
    gebelik: { metin: 'Topikal oftalmik kullanımda sistemik maruziyet düşüktür; gebelikte yarar/risk değerlendirilir.' },
    emzirme: 'Topikal kullanımda sistemik maruziyet düşüktür.',
    renkliRecete: 'normal',
    notes: 'Uzun süreli kullanımda göz içi basıncı artışı, glokom ve katarakt riski — göz hekimi takibi gerekir. Kırmızı gözde tanı konmadan verilmemelidir.',
    kaynak: kub('MAXİDEX %0,1 STERİL OFTALMİK SÜSPANSİYON (onay 29/12/2021)', 'https://titck.gov.tr/storage/Archive/2021/kubKtAttachments/MAXDEX0.1OFTALMKSSPANSYONKBTEMZ_8cea638a-54f6-4edd-ba4a-3d60276a9400.pdf'),
  },

  kolsisin: {
    name: 'Kolşisin',
    brand: ['Colchicum-Dispert', 'Colxeris', 'Kolsin'],
    dose: 'Gut profilaksisi: başlangıçta günde 1×0,5 mg; gerekirse 2×0,5 mg. Akut atakta ilk belirtiyle 0,5–1 mg, sonra ağrı geçene veya GİS yan etki çıkana kadar; toplam maksimum 6 mg.',
    pediatricDose: 'Ailevi Akdeniz Ateşi: <5 yaş günde 1×0,5 mg; ≥5 yaş günde 1–2×0,5 mg',
    pediatrik: {
      min: 0.5, max: 1.0, birim: 'mg/kg/gün', gunlukBolum: 2,
      metin: 'KÜB §4.2 (sabit doz, mg/kg değil): Ailevi Akdeniz Hastalığı olan çocuklarda 5 yaşından küçüklerde günde bir defa 1 film kaplı tablet (0,5 mg); 5 yaş ve daha büyüklerde günde bir-iki tablet. Tedaviye 5 yaşından önce başlanan çocuklarda genellikle 7 yaş civarında doz artışı gerekir.',
    },
    form: 'Film kaplı tablet, dispert tablet',
    sgkCovered: true,
    category: 'Antigut / antiinflamatuvar',
    siniflar: ['Antigut ilaç', 'Mikrotübül inhibitörü', 'Antiinflamatuvar'],
    contraindications: [
      'Kolşisine aşırı duyarlılık',
      'Ciddi böbrek yetmezliği (KrKl <10 mL/dk)',
      'Ciddi karaciğer yetmezliği',
      'Kan diskrazileri',
      'Hemodiyaliz hastaları',
      'Gebelik',
    ],
    interactions: ['Klaritromisin', 'Eritromisin', 'İtrakonazol', 'Siklosporin', 'Statinler', 'Verapamil', 'Diltiazem', 'Greyfurt suyu'],
    etkilesimler: [
      { ile: 'Klaritromisin', siddet: 'ciddi', not: 'Güçlü CYP3A4/P-gp inhibisyonu ile kolşisin toksisitesi (pansitopeni, rabdomiyoliz, ölüm) bildirilmiştir; böbrek/karaciğer yetmezliğinde birlikte kullanılmamalıdır.' },
      { ile: 'Eritromisin', siddet: 'ciddi', not: 'Kolşisin toksisitesi bildirilmiştir (eritromisin KÜB §4.5).' },
      { ile: 'Siklosporin', siddet: 'ciddi', not: 'P-gp inhibisyonu ile kolşisin toksisitesi (miyopati, nöropati) riski belirgin artar.' },
      { ile: 'Statin', siddet: 'ciddi', not: 'Miyopati ve rabdomiyoliz riski toplanır; kas semptomları sorgulanmalıdır.' },
      { ile: 'İtrakonazol', siddet: 'ciddi', not: 'Kolşisin maruziyeti artar; doz azaltılmalıdır (KÜB §4.2/4.5).' },
      { ile: 'Verapamil', siddet: 'ciddi', not: 'P-gp inhibisyonu kolşisin düzeyini yükseltir.' },
    ],
    gebelik: { metin: 'Bu ürünün KÜB §4.3\'ünde gebelikte kullanımı KONTRENDİKE olarak listelenmiştir. (FMF\'de gebelikte sürdürülmesi ayrı bir uzman kararıdır — ürün bilgisi ile klinik uygulama arasındaki bu fark hekime bırakılır.)' },
    emzirme: 'Anne sütüne geçer; emzirme döneminde dikkatle kullanılır.',
    bobrekDozUyarisi: true,
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Dar terapötik aralık — doz aşımı ölümcüldür. İshal ilk toksisite belirtisidir ve dozun durdurulması gerekir. Böbrek yetmezliğinde doz yarıya indirilir (günde en fazla 3 mg).',
    kaynak: kub('COLXERIS 0,5 MG FİLM KAPLI TABLET (onay 27/04/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/ColxerisOnaylKB_09_06_2026.pdf'),
  },

  allopurinol: {
    name: 'Allopurinol',
    brand: ['Ürikoliz', 'Zyloric', 'Allopurinol'],
    dose: 'Advers reaksiyon riskini azaltmak için 100 mg/gün ile başlanır ve serum ürat yanıtına göre artırılır. Hafif: 100–200 mg/gün; orta: 300–600 mg/gün; şiddetli: 700–900 mg/gün.',
    pediatricDose: '15 yaş altı: 10–20 mg/kg/gün (günlük maksimum 400 mg)',
    pediatrik: {
      min: 10, max: 20, birim: 'mg/kg/gün', gunlukBolum: 3,
      maxMgKgGun: 20, mutlakMaxMgGun: 400,
      metin: 'KÜB §4.2: 15 yaşın altındaki çocuklarda günlük maksimum 400 mg\'a kadar, gün başına 10–20 mg/kg vücut ağırlığı. Çocuklarda kullanım bazı enzim rahatsızlıkları ve malignite dışında nadiren endikedir. Vücut ağırlığı 45 kg\'ın altındaki çocuklarda bu form kullanılmamalıdır.',
    },
    form: 'Tablet',
    sgkCovered: true,
    category: 'Ksantin oksidaz inhibitörü',
    siniflar: ['Antigut ilaç', 'Ksantin oksidaz inhibitörü', 'Ürikostatik'],
    contraindications: [
      'Allopurinole veya bileşenlerine daha önce ciddi reaksiyon',
      'Ciddi böbrek yetmezliği (kreatinin klerensi <20 mL/dk)',
      'Vücut ağırlığı 45 kg altındaki çocuklar (300 mg tablet formu)',
    ],
    interactions: ['Azatiyoprin', '6-merkaptopürin', 'Amoksisilin', 'Ampisilin', 'Varfarin', 'Siklosporin', 'Tiyazid diüretikler', 'ACE inhibitörleri'],
    etkilesimler: [
      { ile: 'Azatiyoprin', siddet: 'ciddi', not: 'Azatiyoprin metabolizması bloke olur; ölümcül miyelosupresyon riski — azatiyoprin dozu 1/4\'e indirilmelidir.' },
      { ile: 'Amoksisilin', siddet: 'orta', not: 'Birlikte kullanımda alerjik deri döküntüsü riski artar (amoksisilin KÜB §4.5).' },
      { ile: 'Varfarin', siddet: 'orta', not: 'Antikoagülan etkiyi artırabilir; INR izlenmelidir.' },
      { ile: 'Siklosporin', siddet: 'orta', not: 'Siklosporin plazma düzeyini yükseltebilir.' },
      { ile: 'ACE inhibitörü', siddet: 'orta', not: 'Birlikte kullanımda aşırı duyarlılık reaksiyonu riski artabilir (özellikle böbrek yetmezliğinde).' },
    ],
    gebelik: { metin: 'Gebelikte yalnızca açık gereklilikte; veri sınırlıdır.' },
    emzirme: 'Anne sütüne geçer; emzirme döneminde dikkatle kullanılır.',
    bobrekDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Akut gut atağı sırasında BAŞLANMAZ (atağı uzatır/alevlendirir). Başlangıçta 6 ay kolşisin/NSAİİ profilaksisi önerilir. HLA-B*5801 taşıyıcılarında ciddi deri reaksiyonu riski yüksektir.',
    kaynak: kub('ÜRİKOLİZ 300 MG TABLET (onay 04/11/2025)', 'https://titck.gov.tr/storage/Archive/2025/kubKtAttachments/RKOLZKBTEMZ_10_11_2025.pdf'),
  },

  sulfasalazin: {
    name: 'Sülfasalazin',
    brand: ['Salazopyrin', 'Sulfasalazin'],
    dose: 'Ülseratif kolit ağır/orta atak: günde 4 defa 2–4 tablet (500 mg). Gece dozları arasındaki aralık 8 saati geçmemelidir. Romatoid artritte enterik kaplı formda kademeli titrasyon.',
    pediatricDose: 'Akut atak/nüks: 40–60 mg/kg/gün. İdame: 20–30 mg/kg/gün',
    pediatrik: {
      min: 20, max: 60, birim: 'mg/kg/gün', gunlukBolum: 4,
      maxMgKgGun: 60, enAzAy: 72,
      metin: 'KÜB §4.2: doz vücut ağırlığı oranında hesaplanır — akut atak veya nüksde günde 40–60 mg/kg, idame dozajı günde 20–30 mg/kg. 6 yaşın altında bu form kullanılmamalıdır; iki yaşından küçük çocuklarda kontrendikedir.',
    },
    form: 'Enterik kaplı tablet, tablet',
    sgkCovered: true,
    sgkRestriction: 'SUT: romatoloji / gastroenteroloji endikasyon ve rapor koşullarına bakınız.',
    category: 'Aminosalisilat / DMARD',
    siniflar: ['DMARD', 'Aminosalisilat', 'Sülfonamid', 'Salisilat', 'Antiinflamatuvar (bağırsak)'],
    alerjiSinifi: ['sulfonamid', 'aspirin'],
    yasKontrendikasyonAy: 24,
    contraindications: [
      'Sülfasalazin, metabolitleri, sülfonamidler veya salisilatlara aşırı duyarlılık',
      'Porfiri',
      'İki yaşından küçük çocuklar',
    ],
    interactions: ['Azatiyoprin', 'Metotreksat', 'Digoksin', 'Folik asit', 'Varfarin'],
    etkilesimler: [
      { ile: 'Azatiyoprin', siddet: 'ciddi', not: 'Miyelosupresyon riski toplanır; tam kan sayımı izlenmelidir.' },
      { ile: 'Metotreksat', siddet: 'ciddi', not: 'Folat antagonizması ve miyelosupresyon riski toplanır; folik asit desteği ve kan sayımı izlemi gerekir.' },
      { ile: 'Digoksin', siddet: 'orta', not: 'Digoksin emilimini azaltabilir; düzey izlenmelidir.' },
      { ile: 'Folik asit', siddet: 'orta', not: 'Folat emilimini azaltır; folik asit desteği önerilir.' },
    ],
    gebelik: { metin: 'Gebelikte kullanılabilir; folat emilimini azalttığı için yüksek doz folik asit desteği verilmelidir.' },
    emzirme: 'Anne sütüne az geçer; sağlıklı term bebekte emzirme sürdürülebilir (prematüre ve hiperbilirubinemide dikkat).' ,
    bobrekDozUyarisi: true,
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'İdrarı ve kontakt lensleri turuncu-sarı boyar (zararsız). Erkekte geri dönüşümlü oligospermi yapar. Tam kan sayımı ve karaciğer testleri izlenmelidir.',
    kaynak: kub('SALAZOPYRİN 500 MG ENTERİK TABLET (onay 26/06/2025)', 'https://titck.gov.tr/storage/Archive/2025/kubKtAttachments/uygunkbsalazopyrin_26_06_2025.pdf'),
  },

  febuksostat: {
    name: 'Febuksostat',
    brand: ['Adenuric', 'Febugut', 'Feburic'],
    dose: 'Yemekle birlikte veya ayrı, günde bir kez 80 mg. 2–4 hafta sonra serum ürik asit >6 mg/dL ise günde bir kez 120 mg düşünülebilir. Hedef: ürik asidi 6 mg/dL altında tutmak.',
    pediatricDose: '18 yaş altı çocuklarda etkililik ve güvenlilik belirlenmemiştir',
    form: 'Film kaplı tablet',
    sgkCovered: true,
    sgkRestriction: 'SUT: gut endikasyon ve rapor koşullarına bakınız.',
    category: 'Ksantin oksidaz inhibitörü (non-purin)',
    siniflar: ['Antigut ilaç', 'Ksantin oksidaz inhibitörü', 'Ürikostatik'],
    yasKontrendikasyonAy: 216,
    contraindications: ['Febuksostata aşırı duyarlılık'],
    interactions: ['Azatiyoprin', '6-merkaptopürin', 'Teofilin'],
    etkilesimler: [
      { ile: 'Azatiyoprin', siddet: 'ciddi', not: 'Azatiyoprin metabolizması bloke olur; ciddi miyelosupresyon riski — birlikte kullanım önerilmez.' },
      { ile: 'Teofilin', siddet: 'orta', not: 'Teofilin metabolizmasını etkileyebilir; düzey izlenmelidir.' },
    ],
    gebelik: { metin: 'Gebelikte veri yoktur; kullanımı önerilmez.' },
    emzirme: 'Emzirme döneminde önerilmez.',
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Kardiyovasküler hastalığı olanlarda mortalite artışı bildirilmiştir — bu hastalarda allopurinol tercih edilmelidir. Tedavi başında gut alevlenmesi için en az 6 ay profilaksi önerilir.',
    kaynak: kub('FEBUGUT 80 MG FİLM KAPLI TABLET (onay 28/07/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/FEBUGUT80mgfilmkapltabletkb_28_07_2026.pdf'),
  },
}
