/**
 * Endokrin — antidiyabetikler (biguanid, sülfonilüre, SGLT2, DPP-4, GLP-1, insülin), tiroid
 * ilaçları ve lipid düşürücüler.
 *
 * Two classes carry the risk here and are written as class labels so they fire without pairwise
 * entries: 'Statin' (CYP3A4 inhibitörleriyle rabdomiyoliz) and 'Antidiyabetik' / 'Sülfonilüre'
 * (hipoglisemi potansiyalizasyonu — beta blokörün belirti maskelemesi buradan da yakalanır).
 */
import { kub } from '../kaynak'
import type { TürkishDrug } from '../tipler'

const STATIN_SINIF = ['Statin', 'HMG-CoA redüktaz inhibitörü', 'Lipid düşürücü'] as const

const STATIN_ETKILESIM = [
  { ile: 'Klaritromisin', siddet: 'ciddi' as const, not: 'Güçlü CYP3A4 inhibisyonu statin maruziyetini artırır; miyopati ve rabdomiyoliz riski — statin geçici kesilmelidir (KÜB §4.5).' },
  { ile: 'İtrakonazol', siddet: 'ciddi' as const, not: 'Güçlü CYP3A4 inhibitörü — statinle birlikte kullanımdan kaçınılmalıdır (KÜB §4.5).' },
  { ile: 'Siklosporin', siddet: 'ciddi' as const, not: 'Statin plazma düzeyini belirgin yükseltir; miyopati/rabdomiyoliz riski (KÜB §4.5).' },
  { ile: 'Gemfibrozil', siddet: 'ciddi' as const, not: 'Fibrat + statin birlikteliğinde ciddi kas toksisitesi riski artar (KÜB §4.5).' },
  { ile: 'Fenofibrat', siddet: 'ciddi' as const, not: 'Fibrat ile birlikte miyopati riski artar; CK ve kas semptomları izlenmelidir (KÜB §4.5).' },
  { ile: 'Rifampisin', siddet: 'orta' as const, not: 'CYP3A indüksiyonu ve taşıyıcı inhibisyonu ile statin maruziyeti değişir; etkinlik düşebilir (KÜB §4.5).' },
  { ile: 'Eritromisin', siddet: 'ciddi' as const, not: 'Orta-güçlü CYP3A4 inhibitörüyle birlikte miyopati riskinde artış gözlenmiştir (KÜB §4.5).' },
  { ile: 'Verapamil', siddet: 'orta' as const, not: 'Orta güçte CYP3A4 inhibitörü — statin maruziyeti ve miyopati riski artar (KÜB §4.5).' },
  { ile: 'Diltiazem', siddet: 'orta' as const, not: 'Orta güçte CYP3A4 inhibitörü — statin maruziyeti artar (KÜB §4.5).' },
  { ile: 'Amlodipin', siddet: 'orta' as const, not: 'Simvastatin maruziyetini artırır; simvastatin dozu 20 mg/gün ile sınırlanmalıdır.' },
] as const

const HIPOGLISEMI_ETKILESIM = [
  { ile: 'Beta blokör', siddet: 'ciddi' as const, not: 'Hipoglisemi uyarı belirtilerini (taşikardi, tremor) maskeler ve düzelmeyi geciktirir.' },
  { ile: 'ACE inhibitörü', siddet: 'orta' as const, not: 'İnsülin duyarlılığını artırarak hipoglisemi riskini yükseltebilir.' },
  { ile: 'Antidiyabetik', siddet: 'orta' as const, not: 'Kombinasyonda hipoglisemi riski artar; insülin/sülfonilüre dozunun düşürülmesi düşünülmelidir (KÜB §4.2).' },
] as const

export const ENDOKRIN: Record<string, TürkishDrug> = {
  metformin: {
    name: 'Metformin',
    brand: ['Glucophage', 'Glifor', 'Diaformin', 'Matofin', 'Metforal'],
    dose: 'Standart başlangıç: yemekle birlikte günde 2–3 kez 500 mg veya 850 mg. 10–15 gün sonra kan glukozuna göre titre edilir. Önerilen maksimum 3 g/gün (üçe bölünmüş).',
    pediatricDose: '10 yaş ve üzeri: başlangıç günde 1 kez 500–850 mg; maksimum 2 g/gün (iki-üçe bölünmüş)',
    pediatrik: {
      min: 500, max: 850, birim: 'mg/kg/gün', gunlukBolum: 1,
      mutlakMaxMgGun: 2000, enAzAy: 120,
      metin: 'KÜB §4.2 (sabit doz, mg/kg değil): 10 yaş veya üzeri çocuk ve ergenlerde monoterapi veya insülinle birlikte standart başlangıç dozu yemekle birlikte günde 1 kez 500 mg veya 850 mg; 10–15 gün sonra kan glukozuna göre ayarlanır. Bu yaş grubunda önerilen maksimum doz iki veya üçe bölünmüş şekilde günlük 2 g\'dır.',
    },
    form: 'Film kaplı tablet, XR tablet',
    sgkCovered: true,
    category: 'Biguanid antidiyabetik',
    siniflar: ['Antidiyabetik', 'Biguanid', 'Oral antidiyabetik'],
    contraindications: [
      'Metformine aşırı duyarlılık',
      'Akut metabolik asidoz (laktik asidoz, diyabetik ketoasidoz)',
      'Diyabetik prekoma',
      'Şiddetli böbrek yetmezliği (GFR <30 mL/dk)',
      'Böbrek fonksiyonunu bozabilecek akut durumlar (dehidratasyon, şiddetli enfeksiyon, şok)',
      'Doku hipoksisi yapan akut/kötüleşen kronik hastalık (dekompanse kalp yetmezliği, solunum yetmezliği, yakın MI, şok)',
      'Hepatik yetmezlik, akut alkol intoksikasyonu, alkolizm',
    ],
    interactions: ['İyotlu kontrast maddeler', 'Alkol', 'Diüretikler', 'Kortikosteroidler', 'Sefaleksin', 'ACE inhibitörleri', 'NSAİİ'],
    etkilesimler: [
      { ile: 'Diüretik', siddet: 'ciddi', not: 'Fonksiyonel böbrek yetmezliği laktik asidoz riskini artırır; böbrek fonksiyonu izlenmelidir (KÜB §4.5).' },
      { ile: 'Alkol', siddet: 'ciddi', not: 'Akut alkol intoksikasyonu laktik asidoz riskini artırır — kontrendikedir (KÜB §4.3).' },
      { ile: 'Kortikosteroid', siddet: 'orta', not: 'Kan şekerini yükseltir; metformin dozu gözden geçirilmelidir.' },
      { ile: 'Sefaleksin', siddet: 'orta', not: 'Renal tübüler sekresyonu azaltarak metformin plazma düzeyini artırabilir.' },
      ...HIPOGLISEMI_ETKILESIM,
    ],
    gebelik: { metin: 'Gebelikte kullanımı hekim kararıdır; kontrolsüz diyabet malformasyon riskini artırır. KÜB gebeliği kontrendikasyon olarak listelememektedir.' },
    emzirme: 'Anne sütüne az miktarda geçer; emzirme döneminde kullanılabilir.',
    bobrekDozUyarisi: true,
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'İyotlu kontrast madde uygulanacaksa metformin işlem öncesi kesilir ve böbrek fonksiyonu normal bulunduktan 48 saat sonra yeniden başlanır. Tip 2 DM birinci basamak tedavisidir.',
    kaynak: kub('DIAFORMIN 850 MG FİLM KAPLI TABLET (onay 25/08/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/uygunkbdiaformin_25_08_2026.pdf'),
  },

  gliklazid: {
    name: 'Gliklazid',
    brand: ['Diamicron', 'Medlazid', 'Betanorm', 'Glucomet'],
    dose: 'MR form: kahvaltıda tek doz 30–120 mg. Başlangıç 30 mg/gün; gerekirse en az birer ay arayla 60, 90, 120 mg\'a çıkarılır.',
    pediatricDose: 'Pediyatrik kullanım için doz önerisi yoktur',
    form: 'Uzatılmış salımlı tablet, tablet',
    sgkCovered: true,
    category: 'Sülfonilüre antidiyabetik',
    siniflar: ['Antidiyabetik', 'Sülfonilüre', 'Oral antidiyabetik', 'Sülfonamid türevi'],
    alerjiSinifi: ['sulfonamid'],
    contraindications: [
      'Gliklazid, diğer sülfonilüreler veya sülfonamidlere aşırı duyarlılık',
      'Tip 1 diyabet',
      'Diyabetik prekoma/koma, diyabetik ketoasidoz',
      'Şiddetli böbrek veya karaciğer yetmezliği',
      'Mikonazol ile tedavi',
      'Emzirme',
    ],
    interactions: ['Mikonazol', 'Flukonazol', 'NSAİİ', 'Varfarin', 'Beta blokörler', 'ACE inhibitörleri', 'Kortikosteroidler', 'Alkol'],
    etkilesimler: [
      { ile: 'Mikonazol', siddet: 'ciddi', not: 'KONTRENDİKE — hipoglisemik etkiyi şiddetle artırır, koma tablosuna yol açabilir (KÜB §4.3/4.5).' },
      { ile: 'Flukonazol', siddet: 'ciddi', not: 'Sülfonilüre yarı ömrü uzar; hipoglisemi riski artar.' },
      { ile: 'NSAİİ', siddet: 'ciddi', not: 'Hipoglisemik etki güçlenebilir; kan şekeri izlenmeli.' },
      { ile: 'Trimetoprim', siddet: 'orta', not: 'Hipoglisemik etki güçlenebilir.' },
      { ile: 'Kortikosteroid', siddet: 'orta', not: 'Kan şekerini yükseltir, glisemik kontrol bozulabilir.' },
      ...HIPOGLISEMI_ETKILESIM,
    ],
    gebelik: { metin: 'Gebelikte insüline geçilmesi önerilir; sülfonilüre ile gebelik deneyimi sınırlıdır.' },
    emzirme: 'KONTRENDİKE — emzirme döneminde kullanılmaz (KÜB §4.3).',
    bobrekDozUyarisi: true,
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Uzun süreli hipoglisemi riski vardır; öğün atlanmamalı, yaşlı ve böbrek yetmezliği olan hastada dikkatli titre edilmelidir.',
    kaynak: kub('MEDLAZİD MR 60 MG UZATILMIŞ SALIMLI TABLET (onay 21/11/2023)', 'https://titck.gov.tr/storage/Archive/2024/kubKtAttachments/kb_0e8d6a50-9645-40b8-a067-be3e1eee58da.pdf'),
  },

  glimepirid: {
    name: 'Glimepirid',
    brand: ['Amaryl', 'Glimax', 'Diaglin', 'Glimepirid'],
    dose: 'Doz istenen kan/idrar glukoz düzeyine göre bireysel ayarlanır; etkin en düşük doz hedeflenir. Tipik aralık 1–6 mg/gün (kahvaltıyla).',
    pediatricDose: '8 yaşın altında veri yoktur; 8–17 yaş için ayrıntılı veri KÜB\'de sınırlıdır',
    form: 'Tablet',
    sgkCovered: true,
    category: 'Sülfonilüre antidiyabetik',
    siniflar: ['Antidiyabetik', 'Sülfonilüre', 'Oral antidiyabetik', 'Sülfonamid türevi'],
    alerjiSinifi: ['sulfonamid'],
    contraindications: [
      'Glimepirid, diğer sülfonilüreler veya sülfonamidlere aşırı duyarlılık',
      'Tip 1 diyabet',
      'Diyabetik ketoasidoz',
      'Diyabetik koma',
      'Ciddi böbrek veya karaciğer fonksiyon bozukluğu',
    ],
    interactions: ['Mikonazol', 'Flukonazol', 'NSAİİ', 'Varfarin', 'Beta blokörler', 'Kortikosteroidler', 'Alkol', 'Trimetoprim + sülfametoksazol'],
    etkilesimler: [
      { ile: 'Mikonazol', siddet: 'ciddi', not: 'Hipoglisemik etkiyi şiddetle artırır; birlikte kullanılmamalıdır.' },
      { ile: 'NSAİİ', siddet: 'ciddi', not: 'Hipoglisemik etki güçlenebilir.' },
      { ile: 'Trimetoprim', siddet: 'orta', not: 'Hipoglisemi riski artar.' },
      { ile: 'Kortikosteroid', siddet: 'orta', not: 'Glisemik kontrolü bozar.' },
      ...HIPOGLISEMI_ETKILESIM,
    ],
    gebelik: { metin: 'Gebelikte insüline geçilmelidir.' },
    emzirme: 'Emzirme döneminde önerilmez; insülin tercih edilir.',
    bobrekDozUyarisi: true,
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Atlanan doz, bir sonraki dozun artırılmasıyla ASLA telafi edilmez (KÜB §4.2).',
    kaynak: kub('GLİMAX 1 MG TABLET (onay 24/11/2025)', 'https://titck.gov.tr/storage/Archive/2025/kubKtAttachments/Glimax1KB_25_11_2025.pdf'),
  },

  empagliflozin: {
    name: 'Empagliflozin',
    brand: ['Jardiance', 'Jardifloz', 'Empaglif'],
    dose: 'Başlangıç günde bir kez 10 mg. eGFR ≥60 olan ve daha sıkı kontrol gereken hastada 25 mg\'a yükseltilebilir. Maksimum günlük doz 25 mg.',
    pediatricDose: 'Pediyatrik kullanım için doz önerisi bu KÜB\'de verilmemektedir',
    form: 'Film kaplı tablet',
    sgkCovered: true,
    sgkRestriction: 'SUT: tip 2 DM / kalp yetmezliği endikasyon ve rapor koşullarına bakınız.',
    category: 'SGLT2 inhibitörü',
    siniflar: ['Antidiyabetik', 'SGLT2 inhibitörü', 'Oral antidiyabetik'],
    contraindications: ['Empagliflozine aşırı duyarlılık'],
    interactions: ['Diüretikler', 'İnsülin', 'Sülfonilüreler'],
    etkilesimler: [
      { ile: 'Diüretik', siddet: 'ciddi', not: 'Ozmotik diürez toplanır: volüm azalması, hipotansiyon ve akut böbrek hasarı riski artar.' },
      { ile: 'İnsülin', siddet: 'ciddi', not: 'Hipoglisemi riski artar; insülin dozunun düşürülmesi düşünülmelidir (KÜB §4.2).' },
      { ile: 'Sülfonilüre', siddet: 'ciddi', not: 'Hipoglisemi riski artar; sülfonilüre dozu azaltılmalıdır (KÜB §4.2).' },
    ],
    gebelik: { metin: 'Gebelikte kullanımı önerilmez; gebelik saptandığında kesilmelidir.' },
    emzirme: 'Emzirme döneminde önerilmez.',
    bobrekDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Öglisemik diyabetik ketoasidoz riski — cerrahi, açlık ve akut hastalıkta geçici kesilmelidir. Genital mikotik enfeksiyon sıktır.',
    kaynak: kub('JARDİFLOZ 10 MG FİLM KAPLI TABLET (onay 05/09/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/UygunbulunanKBmetni33_843edb5d-e49c-4389-ac32-ae3f2db65bc4.pdf'),
  },

  dapagliflozin: {
    name: 'Dapagliflozin',
    brand: ['Forxiga', 'Daglifa', 'Dapagli'],
    dose: 'Tip 2 DM: günde bir defa 10 mg, yemeklerle birlikte veya aç karnına.',
    pediatricDose: '18 yaş altında güvenlilik ve etkililik belirlenmemiştir',
    form: 'Film kaplı tablet',
    sgkCovered: true,
    sgkRestriction: 'SUT: tip 2 DM / kalp yetmezliği / KBH endikasyon ve rapor koşullarına bakınız.',
    category: 'SGLT2 inhibitörü',
    siniflar: ['Antidiyabetik', 'SGLT2 inhibitörü', 'Oral antidiyabetik'],
    yasKontrendikasyonAy: 216,
    contraindications: ['Dapagliflozine aşırı duyarlılık'],
    interactions: ['Diüretikler', 'İnsülin', 'Sülfonilüreler'],
    etkilesimler: [
      { ile: 'Diüretik', siddet: 'ciddi', not: 'Volüm azalması ve hipotansiyon riski artar (KÜB §4.5).' },
      { ile: 'İnsülin', siddet: 'ciddi', not: 'Hipoglisemi riskini azaltmak için insülin dozunun düşürülmesi düşünülmelidir (KÜB §4.2).' },
      { ile: 'Sülfonilüre', siddet: 'ciddi', not: 'Hipoglisemi riski artar; sülfonilüre dozu düşürülmelidir (KÜB §4.2).' },
    ],
    gebelik: { metin: 'Gebelikte kullanımı önerilmez; gebelik saptandığında kesilmelidir.' },
    emzirme: 'Emzirme döneminde önerilmez.',
    bobrekDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Öglisemik ketoasidoz ve genital mikotik enfeksiyon açısından hasta bilgilendirilmelidir.',
    kaynak: kub('DAGLİFA 5 MG FİLM KAPLI TABLET (onay 13/08/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/EkOnaylKB_88208249-b50c-46bd-a267-2dfd11b0e8a6.pdf'),
  },

  sitagliptin: {
    name: 'Sitagliptin',
    brand: ['Januvia', 'Asugar', 'Sitaglip', 'Janumet (kombinasyon)'],
    dose: 'Günde bir kez 100 mg. Sülfonilüre veya insülinle kombine edilirken hipoglisemi riski için o ilacın dozu düşürülebilir.',
    pediatricDose: '10–17 yaşta yetersiz etkililik nedeniyle kullanılmamalıdır; 10 yaş altında çalışılmamıştır',
    form: 'Film kaplı tablet',
    sgkCovered: true,
    sgkRestriction: 'SUT: tip 2 DM endikasyon ve rapor koşullarına bakınız.',
    category: 'DPP-4 inhibitörü',
    siniflar: ['Antidiyabetik', 'DPP-4 inhibitörü', 'Oral antidiyabetik'],
    yasKontrendikasyonAy: 216,
    contraindications: ['Sitagliptine aşırı duyarlılık'],
    interactions: ['Sülfonilüreler', 'İnsülin', 'ACE inhibitörleri'],
    etkilesimler: [
      { ile: 'Sülfonilüre', siddet: 'ciddi', not: 'Hipoglisemi riski artar; sülfonilüre dozunun düşürülmesi düşünülmelidir (KÜB §4.2).' },
      { ile: 'İnsülin', siddet: 'ciddi', not: 'Hipoglisemi riski artar; insülin dozu azaltılabilir (KÜB §4.2).' },
      { ile: 'ACE inhibitörü', siddet: 'orta', not: 'DPP-4 inhibitörü ile birlikte anjiyoödem riski artabilir.' },
    ],
    gebelik: { metin: 'Gebelikte veri sınırlıdır; kullanımı önerilmez, insüline geçilir.' },
    emzirme: 'Emzirme döneminde önerilmez.',
    bobrekDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Akut pankreatit bildirimleri vardır — şiddetli, inatçı karın ağrısında ilaç kesilmelidir.',
    kaynak: kub('ASUGAR 25 MG FİLM KAPLI TABLET (onay 29/12/2025)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/kubYAYIN25_20_01_2026.pdf'),
  },

  linagliptin: {
    name: 'Linagliptin',
    brand: ['Trajenta', 'Atalyna', 'Linaglip'],
    dose: 'Günde bir kez 5 mg; aç veya tok karnına, günün herhangi bir saatinde.',
    pediatricDose: 'Çocuk ve adolesanlarda tedavi önerilmemektedir',
    form: 'Film kaplı tablet',
    sgkCovered: true,
    sgkRestriction: 'SUT: tip 2 DM endikasyon ve rapor koşullarına bakınız.',
    category: 'DPP-4 inhibitörü',
    siniflar: ['Antidiyabetik', 'DPP-4 inhibitörü', 'Oral antidiyabetik'],
    yasKontrendikasyonAy: 216,
    contraindications: ['Linagliptine aşırı duyarlılık'],
    interactions: ['Sülfonilüreler', 'İnsülin', 'Rifampisin', 'ACE inhibitörleri'],
    etkilesimler: [
      { ile: 'Sülfonilüre', siddet: 'ciddi', not: 'Hipoglisemi riski artar; sülfonilüre dozu düşürülebilir (KÜB §4.2).' },
      { ile: 'İnsülin', siddet: 'ciddi', not: 'Hipoglisemi riski artar (KÜB §4.2).' },
      { ile: 'Rifampisin', siddet: 'orta', not: 'Güçlü P-gp/CYP3A4 indükleyicisi linagliptin etkinliğini azaltabilir.' },
      { ile: 'ACE inhibitörü', siddet: 'orta', not: 'Birlikte anjiyoödem riski artabilir.' },
    ],
    gebelik: { metin: 'Gebelikte kullanımı önerilmez; insüline geçilir.' },
    emzirme: 'Emzirme döneminde önerilmez.',
    renkliRecete: 'normal',
    notes: 'Böbrek yetmezliğinde doz ayarı gerektirmeyen tek DPP-4 inhibitörüdür (safra ile atılır).',
    kaynak: kub('ATALYNA 5 MG FİLM KAPLI TABLET (onay 14/03/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/atalynayaymlanacakkb_25_03_2026.pdf'),
  },

  semaglutidOral: {
    name: 'Semaglutid (oral)',
    brand: ['Rybelsus', 'Ozempic (subkutan)', 'Wegovy (subkutan)'],
    dose: 'Başlangıç 1 ay boyunca günde bir kez 3 mg; sonra 7 mg idame. En az bir ay sonra gerekirse 14 mg. Önerilen maksimum günlük tek doz 14 mg.',
    pediatricDose: '18 yaş altında güvenlilik ve etkililik belirlenmemiştir',
    form: 'Tablet (oral), kalem enjektör (subkutan)',
    sgkCovered: true,
    sgkRestriction: 'SUT: tip 2 DM endikasyon ve rapor koşullarına bakınız; obezite endikasyonu ayrıdır.',
    category: 'GLP-1 reseptör agonisti',
    siniflar: ['Antidiyabetik', 'GLP-1 agonisti', 'İnkretin mimetik'],
    yasKontrendikasyonAy: 216,
    contraindications: [
      'Semaglutide aşırı duyarlılık',
      'Kendisinde veya aile öyküsünde medüller tiroid karsinomu',
      'Çoklu endokrin neoplazi sendromu tip 2 (MEN2)',
    ],
    interactions: ['Levotiroksin', 'İnsülin', 'Sülfonilüreler', 'Varfarin'],
    etkilesimler: [
      { ile: 'İnsülin', siddet: 'ciddi', not: 'Hipoglisemi riski artar; insülin dozu düşürülmelidir.' },
      { ile: 'Sülfonilüre', siddet: 'ciddi', not: 'Hipoglisemi riski artar; sülfonilüre dozu düşürülmelidir.' },
      { ile: 'Levotiroksin', siddet: 'orta', not: 'Mide boşalmasını geciktirerek eş zamanlı alınan oral ilaçların emilimini etkileyebilir; tiroid fonksiyonu izlenmeli.' },
    ],
    gebelik: { metin: 'Gebelikte kullanılmamalıdır; planlanan gebelikten en az 2 ay önce kesilmesi önerilir.' },
    emzirme: 'Emzirme döneminde kullanılmamalıdır.',
    renkliRecete: 'normal',
    notes: 'Oral form aç karnına, en fazla yarım bardak su ile ve sonraki 30 dakika yemek/içecek/ilaç alınmadan kullanılır. Akut pankreatit ve safra kesesi hastalığı bildirilmiştir.',
    kaynak: kub('RYBELSUS 3 MG TABLET (onay 28/08/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/UygunbulunanKBmetni24_bb04defd-0dc4-434b-8956-560e4c0690e5.pdf'),
  },

  insulinGlarjin: {
    name: 'İnsülin glarjin',
    brand: ['Lantus', 'Toujeo', 'Abasaglar', 'Basalog'],
    dose: 'Günde bir kez subkutan, her gün aynı saatte. Doz kan glukozuna göre bireysel titre edilir. Potens ÜNİTE bazındadır ve diğer insülinlerin IU\'su ile aynı değildir.',
    pediatricDose: 'Pediatrik doz kan glukozuna göre bireyselleştirilir — mg/kg olarak ifade edilmez',
    form: 'Subkutan enjeksiyonluk çözelti (kalem/flakon)',
    sgkCovered: true,
    category: 'Uzun etkili insülin analoğu',
    siniflar: ['İnsülin', 'Antidiyabetik', 'Uzun etkili insülin'],
    contraindications: ['İnsülin glarjine veya yardımcı maddelere aşırı duyarlılık'],
    interactions: ['Beta blokörler', 'ACE inhibitörleri', 'Kortikosteroidler', 'Alkol', 'Sülfonilüreler', 'SGLT2 inhibitörleri'],
    etkilesimler: [
      ...HIPOGLISEMI_ETKILESIM,
      { ile: 'Kortikosteroid', siddet: 'orta', not: 'İnsülin ihtiyacını artırır; doz gözden geçirilmelidir.' },
      { ile: 'Alkol', siddet: 'ciddi', not: 'Hipoglisemi riskini artırır ve uzatır.' },
    ],
    gebelik: { metin: 'Gebelikte insülin tercih edilen tedavidir; doz gereksinimi trimesterlere göre değişir ve yakın izlem gerekir.' },
    emzirme: 'Emzirme döneminde kullanılabilir; insülin dozu ve diyet ayarı gerekebilir.',
    renkliRecete: 'normal',
    notes: 'Diğer insülinlerle KARIŞTIRILMAZ ve sulandırılmaz. Ünite sayısı ürüne özgüdür — marka değişiminde doz yeniden titre edilmelidir.',
    kaynak: kub('LANTUS SOLOSTAR 100 U/ML S.C. ENJEKSİYONLUK ÇÖZELTİ (onay 12/08/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/Ekek4kubtemiz_21_08_2026.pdf'),
  },

  levotiroksin: {
    name: 'Levotiroksin sodyum',
    brand: ['Euthyrox', 'Levotiron', 'Tefor', 'Votryxe'],
    dose: 'Doz laboratuvar testleri ve klinik muayeneye göre bireyselleştirilir (25–200 mcg tablet formları mevcuttur). Sabah aç karnına, kahvaltıdan en az 30 dakika önce.',
    pediatricDose: 'İdame 100–150 mikrogram/m² vücut yüzey alanı; bebeklerde ilk öğünden en az yarım saat önce tek doz',
    pediatrik: {
      min: 100, max: 150, birim: 'mikrogram/kg/gün', gunlukBolum: 1,
      metin: 'KÜB §4.2 (vücut YÜZEY ALANI başına, kilogram başına değil): konjenital hipotiroidi idame tedavisinde 100–150 mikrogram/m² vücut yüzey alanı. Bebeklerde doz günün ilk öğününden en az yarım saat önce tek seferde verilir; tablet ezilip su içinde süspansiyon haline getirilir.',
    },
    form: 'Tablet',
    sgkCovered: true,
    category: 'Tiroid hormonu',
    siniflar: ['Tiroid hormonu', 'Hormon'],
    contraindications: [
      'Levotiroksine aşırı duyarlılık',
      'Tedavi edilmemiş adrenal yetmezlik',
      'Tedavi edilmemiş hipofiz yetmezliği',
      'Tedavi edilmemiş tirotoksikoz',
      'Akut miyokard infarktüsü, akut miyokardit, akut pankardit',
      'Gebelikte hipertiroidi için antitiroid ilaçla kombinasyon',
    ],
    interactions: ['Demir', 'Kalsiyum', 'Proton pompa inhibitörleri', 'Kolestiramin', 'Varfarin', 'İnsülin', 'Antidiyabetikler', 'Amiodaron', 'Sertralin'],
    etkilesimler: [
      { ile: 'Demir', siddet: 'ciddi', not: 'Levotiroksin emilimini belirgin azaltır; en az 4 saat arayla alınmalıdır.' },
      { ile: 'Kalsiyum', siddet: 'ciddi', not: 'Kalsiyum tuzları emilimi azaltır; en az 4 saat ara verilmelidir.' },
      { ile: 'Proton pompa inhibitörü', siddet: 'orta', not: 'Mide asiditesinin azalması levotiroksin emilimini düşürebilir; TSH izlenmeli.' },
      { ile: 'Varfarin', siddet: 'ciddi', not: 'Antikoagülan etki artar; tiroid durumu değiştikçe INR izlenmelidir.' },
      { ile: 'Amiodaron', siddet: 'ciddi', not: 'Tiroid fonksiyonunu hem hipo hem hipertiroidi yönünde bozar; TSH izlenmelidir.' },
      { ile: 'Antidiyabetik', siddet: 'orta', not: 'Levotiroksin antidiyabetik ihtiyacını artırabilir; kan şekeri izlenmelidir.' },
    ],
    gebelik: { metin: 'Gebelikte tedaviye DEVAM edilir ve doz genellikle artırılır; hipotiroidi tedavisiz bırakılmamalıdır. Antitiroid ilaçla kombinasyon gebelikte uygun değildir (KÜB §4.3/4.6).' },
    emzirme: 'Anne sütüne az miktarda geçer; emzirme döneminde kullanılabilir.',
    renkliRecete: 'normal',
    notes: 'Aç karnına ve diğer ilaçlardan ayrı alınması emilim için kritiktir. Doz değişiminden 6–8 hafta sonra TSH ile kontrol edilir.',
    kaynak: kub('VOTRYXE 150 MCG TABLET (onay 22/07/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/Votryxe150ONAYLIKB_31_07_2026.pdf'),
  },

  propiltiourasil: {
    name: 'Propiltiourasil',
    brand: ['Propycil', 'PTU'],
    dose: 'Yetişkin ve >10 yaş: orta şiddetli hipertiroidide başlangıç 100–300 mg/gün, 2–3 doza bölünmüş (her doz 50–100 mg). Ağır hipertiroidide 300–600 mg/gün. 6–8 saatte bir alınır.',
    pediatricDose: '6–10 yaş: başlangıç 50–150 mg/gün (tek doz veya bölünmüş). 6 yaş altında güvenlilik bilinmemektedir',
    pediatrik: {
      min: 50, max: 150, birim: 'mg/kg/gün', gunlukBolum: 3, enAzAy: 72,
      metin: 'KÜB §4.2 (sabit doz, mg/kg değil): 6–10 yaş arası çocuklarda başlangıç dozu günde bir kere veya bölünmüş dozlar halinde 50–150 mg. 6 yaşından küçük çocuklarda ilacın güvenlilik ve etkililiği bilinmemektedir.',
    },
    form: 'Tablet',
    sgkCovered: true,
    category: 'Antitiroid (tiyonamid)',
    siniflar: ['Antitiroid', 'Tiyonamid'],
    yasKontrendikasyonAy: 72,
    contraindications: [
      'Propiltiourasil veya diğer antitiroid ilaçlara aşırı duyarlılık',
      'Substernal guatr',
      'Önceki propiltiourasil tedavisinde agranülositoz veya ağır hepatik lezyon',
    ],
    interactions: ['Varfarin', 'Beta blokörler', 'Digoksin', 'Teofilin'],
    etkilesimler: [
      { ile: 'Varfarin', siddet: 'ciddi', not: 'K vitamini bağımlı faktörleri etkileyerek antikoagülan yanıtı değiştirir; INR izlenmelidir.' },
      { ile: 'Digoksin', siddet: 'orta', not: 'Ötiroidiye geçişle digoksin gereksinimi değişir; düzey izlenmelidir.' },
    ],
    gebelik: { metin: 'Gebeliğin ilk trimesterinde metimazole tercih edilir (metimazol embriyopatisi nedeniyle); en düşük etkili dozda kullanılır.' },
    emzirme: 'Anne sütüne az geçer; emzirme döneminde düşük dozda kullanılabilir, bebeğin tiroid fonksiyonu izlenir.',
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Ağır hepatotoksisite ve agranülositoz riski — ateş, boğaz ağrısı veya sarılıkta ilaç kesilip tam kan sayımı ve karaciğer testleri istenmelidir.',
    kaynak: kub('PROPYCİL 50 MG TABLET (onay 14/02/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/temizkb_24_04_2026.pdf'),
  },

  tiamazol: {
    name: 'Tiamazol (Metimazol)',
    brand: ['Thyromazol', 'Mucavo', 'Metimazol'],
    dose: 'Yetişkin: başlangıç 10–40 mg/gün (çoğu vakada 20–30 mg). İdamede doz düşürülür. Toplam günlük 40 mg aşılmamalıdır.',
    pediatricDose: 'Başlangıç 0,5 mg/kg/gün, iki-üç eşit doza bölünmüş (günlük toplam 40 mg aşılmaz)',
    pediatrik: {
      min: 0.5, max: 0.5, birim: 'mg/kg/gün', gunlukBolum: 3,
      maxMgKgGun: 0.5, mutlakMaxMgGun: 40, enAzAy: 24,
      metin: 'KÜB §4.2: pediyatride genellikle iki veya üç eşit doza bölünen 0,5 mg/kg günlük dozla başlanır. İdamede günlük doz düşürülüp günde bir kez verilebilir. Toplam günlük 40 mg metimazol dozu aşılmamalıdır. 2 yaş ve altında güvenlilik/etkililik sistematik olarak değerlendirilmemiştir, önerilmez.',
    },
    form: 'Film kaplı tablet',
    sgkCovered: true,
    category: 'Antitiroid (tiyonamid)',
    siniflar: ['Antitiroid', 'Tiyonamid'],
    yasKontrendikasyonAy: 24,
    contraindications: [
      'Metimazol, diğer tiyonamid türevlerine aşırı duyarlılık',
      'Orta veya şiddetli granülositopeni',
      'Hipertiroidiye bağlı olmayan, önceden var olan kolestaz',
      'Metimazol/karbimazol ile önceki tedavide kemik iliği hasarı',
      'Ciddi karaciğer yetmezliği',
      'Tiyamazol/karbimazol sonrası akut pankreatit öyküsü',
      '2 yaş ve altı çocuklarda önerilmez',
    ],
    interactions: ['Varfarin', 'Beta blokörler', 'Digoksin', 'Teofilin', 'İyot'],
    etkilesimler: [
      { ile: 'Varfarin', siddet: 'ciddi', not: 'Tiroid durumu değiştikçe antikoagülan yanıt değişir; INR izlenmelidir.' },
      { ile: 'Digoksin', siddet: 'orta', not: 'Ötiroidiye geçişle digoksin gereksinimi azalabilir; düzey izlenmelidir.' },
    ],
    gebelik: { metin: 'İlk trimesterde metimazol embriyopatisi (aplazia cutis, koanal/özofageal atrezi) riski nedeniyle propiltiourasil tercih edilir. Levotiroksin ile kombine tedavi gebelikte uygun değildir (KÜB §4.6).' },
    emzirme: 'Anne sütüne geçer; düşük dozda emzirme sürdürülebilir, bebeğin tiroid fonksiyonu izlenir.',
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Agranülositoz riski — ateş ve boğaz ağrısında derhal tam kan sayımı istenmelidir. 1 mg metimazol 1 mg karbimazole EŞDEĞER DEĞİLDİR (KÜB §4.2).',
    kaynak: kub('MUCAVO 5 MG FİLM KAPLI TABLET (onay 26/12/2024)', 'https://titck.gov.tr/storage/Archive/2025/kubKtAttachments/kubYAYIN5_24_03_2025.pdf'),
  },

  atorvastatin: {
    name: 'Atorvastatin',
    brand: ['Lipitor', 'Ator', 'Colastin', 'Atorvax', 'Cholvast'],
    dose: 'Günde bir defa 10–80 mg. Başlangıç ve idame dozu LDL-K değerine, hedefe ve yanıta göre bireyselleştirilir; 2–4 haftada lipid kontrolü yapılır.',
    pediatricDose: '10 yaş altı hastaların tedavisinde endike değildir',
    form: 'Film kaplı tablet',
    sgkCovered: true,
    sgkRestriction: 'SUT: lipid düşürücü ilaçların ödeme koşullarına (LDL eşikleri, risk grubu) bakınız.',
    category: 'Statin (HMG-CoA redüktaz inhibitörü)',
    siniflar: [...STATIN_SINIF],
    yasKontrendikasyonAy: 120,
    contraindications: [
      'Atorvastatine aşırı duyarlılık',
      'Aktif karaciğer hastalığı veya ULN\'nin 3 katını aşan açıklanamayan transaminaz yüksekliği',
      'Gebelik, emzirme ve uygun kontrasepsiyon kullanmayan doğurganlık çağındaki kadınlar',
      'Glekaprevir/pibrentasvir ile tedavi',
      '10 yaş altı',
    ],
    interactions: ['Klaritromisin', 'İtrakonazol', 'Siklosporin', 'Gemfibrozil', 'Fenofibrat', 'Rifampisin', 'Eritromisin', 'Diltiazem', 'Verapamil', 'Greyfurt suyu', 'Kolşisin'],
    etkilesimler: [...STATIN_ETKILESIM, { ile: 'Kolşisin', siddet: 'ciddi', not: 'Birlikte kullanımda miyopati ve rabdomiyoliz bildirilmiştir; kas semptomları sorgulanmalıdır.' }],
    gebelik: { metin: 'Gebelikte KONTRENDİKE — kolesterol fetal gelişim için gereklidir (KÜB §4.3/4.6). Doğurganlık çağındaki kadın etkili kontrasepsiyon kullanmalıdır.' },
    emzirme: 'KONTRENDİKE — emzirme döneminde kullanılmaz (KÜB §4.3).',
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Açıklanamayan kas ağrısı, hassasiyet veya güçsüzlükte CK ölçülmelidir.',
    kaynak: kub('COLASTİN-L 10 MG FİLM KAPLI TABLET (onay 29/06/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/uygunkbcolastin10mg_29_06_2026.pdf'),
  },

  rosuvastatin: {
    name: 'Rosuvastatin',
    brand: ['Crestor', 'Ronap', 'Rosuva', 'Rosucor'],
    dose: 'Statine yeni başlayanda günde tek doz 5 veya 10 mg. Maksimum 40 mg (yalnız yüksek riskli ve hedefe ulaşamayan hastada).',
    pediatricDose: 'Heterozigot ailesel hiperkolesterolemide 6–9 yaş: 5–10 mg/gün; 10–17 yaş: 5–20 mg/gün',
    pediatrik: {
      min: 5, max: 20, birim: 'mg/kg/gün', gunlukBolum: 1,
      mutlakMaxMgGun: 20, enAzAy: 72,
      metin: 'KÜB §4.2 (sabit doz, mg/kg değil): heterozigot ailesel hiperkolesterolemili çocuk ve ergenlerde normal başlangıç dozu günde 5 mg. 6–9 yaş arasında normal doz aralığı günde bir kez 5–10 mg (10 mg üzeri çalışılmamıştır); 10–17 yaş arasında pediyatrik maksimum doz günde bir defa 20 mg\'dır. 6 yaşın altında kullanımı önerilmemektedir.',
    },
    form: 'Film kaplı tablet',
    sgkCovered: true,
    sgkRestriction: 'SUT: lipid düşürücü ilaçların ödeme koşullarına bakınız.',
    category: 'Statin (HMG-CoA redüktaz inhibitörü)',
    siniflar: [...STATIN_SINIF],
    yasKontrendikasyonAy: 72,
    contraindications: [
      'Rosuvastatine aşırı duyarlılık',
      'Aktif karaciğer hastalığı veya transaminazlarda 3xULN yükselme',
      'Ağır böbrek yetmezliği (KrKl <30 mL/dk)',
      'Miyopati',
      'Sofosbuvir/velpatasvir/voksilaprevir ile eş zamanlı kullanım',
      'Siklosporin ile eş zamanlı kullanım',
      'Gebelik, laktasyon ve kontrasepsiyon kullanmayan doğurganlık çağındaki kadınlar',
    ],
    interactions: ['Siklosporin', 'Gemfibrozil', 'Proteaz inhibitörleri', 'Varfarin', 'Antiasitler', 'Fenofibrat'],
    etkilesimler: [
      ...STATIN_ETKILESIM,
      { ile: 'Siklosporin', siddet: 'ciddi', not: 'KONTRENDİKE — rosuvastatin EAA değerleri belirgin artar (KÜB §4.3/4.5).' },
      { ile: 'Varfarin', siddet: 'ciddi', not: 'INR yükselebilir; statin başlanırken/kesilirken INR izlenmelidir.' },
    ],
    gebelik: { metin: 'Gebelikte KONTRENDİKE (KÜB §4.3/4.6).' },
    emzirme: 'KONTRENDİKE — emzirme döneminde kullanılmaz (KÜB §4.3).',
    bobrekDozUyarisi: true,
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    kaynak: kub('RONAP 10 MG FİLM KAPLI TABLET (onay 04/06/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/onaylkb_17_06_2026.pdf'),
  },

  simvastatin: {
    name: 'Simvastatin',
    brand: ['Zocor', 'Lipvakol', 'Simvakol', 'Simvor'],
    dose: 'Akşamları tek doz 5–80 mg/gün. Doz ayarlamaları en az 4 haftalık aralıklarla. 80 mg yalnız yüksek riskli ve hedefe ulaşamayan hastada.',
    pediatricDose: 'Heterozigot ailesel hiperkolesterolemide 10–17 yaş: akşamları 10 mg/gün',
    pediatrik: {
      min: 10, max: 10, birim: 'mg/kg/gün', gunlukBolum: 1,
      mutlakMaxMgGun: 40, enAzAy: 120,
      metin: 'KÜB §4.2 (sabit doz, mg/kg değil): heterozigot ailesel hiperkolesterolemili 10–17 yaş arası çocuk ve adolesanlarda (erkeklerde Tanner evresi II ve üzeri, kızlarda menarştan en az bir yıl sonra) tavsiye edilen klasik başlangıç dozu akşamları günde bir kez 10 mg.',
    },
    form: 'Film kaplı tablet',
    sgkCovered: true,
    sgkRestriction: 'SUT: lipid düşürücü ilaçların ödeme koşullarına bakınız.',
    category: 'Statin (HMG-CoA redüktaz inhibitörü)',
    siniflar: [...STATIN_SINIF],
    contraindications: [
      'Simvastatine aşırı duyarlılık',
      'Aktif karaciğer hastalığı veya açıklanamayan kalıcı transaminaz yüksekliği',
      'Gebelik ve emzirme',
      'Güçlü CYP3A4 inhibitörleriyle (klaritromisin, itrakonazol, HIV proteaz inhibitörleri) birlikte kullanım',
    ],
    interactions: ['Klaritromisin', 'İtrakonazol', 'Siklosporin', 'Gemfibrozil', 'Amlodipin', 'Verapamil', 'Diltiazem', 'Amiodaron', 'Greyfurt suyu'],
    etkilesimler: [
      ...STATIN_ETKILESIM,
      { ile: 'Amiodaron', siddet: 'ciddi', not: 'Simvastatin dozu 20 mg/gün ile sınırlanmalıdır; miyopati riski.' },
    ],
    gebelik: { metin: 'Gebelikte KONTRENDİKE (KÜB §4.3).' },
    emzirme: 'KONTRENDİKE — emzirme döneminde kullanılmaz (KÜB §4.3).',
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Statinler içinde CYP3A4 etkileşimi en belirgin olanıdır; greyfurt suyu ile alınmamalıdır.',
    kaynak: kub('LİPVAKOL 10 MG FİLM KAPLI TABLET (onay 02/07/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/LPVAKOL10mgKB_03_07_2026.pdf'),
  },

  fenofibrat: {
    name: 'Fenofibrat',
    brand: ['Lipanthyl', 'Liphonis', 'Fenoklip', 'Trilipix'],
    dose: 'Erişkin: günde bir defa 200 mg; gerekirse 267 mg\'a titre edilir. Kapsül yiyeceklerle birlikte bütün olarak yutulur.',
    pediatricDose: '18 yaş altında kullanılması önerilmemektedir (veri yok)',
    form: 'Sert kapsül, tablet',
    sgkCovered: true,
    sgkRestriction: 'SUT: hipertrigliseridemi endikasyon koşullarına bakınız.',
    category: 'Fibrat',
    siniflar: ['Fibrat', 'Lipid düşürücü', 'PPAR-alfa agonisti'],
    yasKontrendikasyonAy: 216,
    contraindications: [
      'Fenofibrata aşırı duyarlılık',
      'Karaciğer yetmezliği (biliyer siroz, kalıcı karaciğer fonksiyon anormalliği dahil)',
      'Bilinen safra kesesi hastalığı',
      'Şiddetli böbrek yetmezliği (eGFR <30)',
      'Kronik veya akut pankreatit (şiddetli hipertrigliseridemiye bağlı akut pankreatit hariç)',
      'Fibrat veya ketoprofen ile fototoksik reaksiyon öyküsü',
    ],
    interactions: ['Varfarin', 'Siklosporin', 'Statinler', 'Diğer fibratlar', 'Glitazonlar', 'Ezetimib'],
    etkilesimler: [
      { ile: 'Varfarin', siddet: 'ciddi', not: 'Oral antikoagülan etkiyi güçlendirir; başlangıçta antikoagülan dozu 1/3 azaltılmalı ve INR ile titre edilmelidir (KÜB §4.5).' },
      { ile: 'Siklosporin', siddet: 'ciddi', not: 'Şiddetli geri dönüşümlü böbrek fonksiyon bozukluğu bildirilmiştir (KÜB §4.5).' },
      { ile: 'Statin', siddet: 'ciddi', not: 'Birlikte ciddi kas toksisitesi riski artar; CK ve kas semptomları izlenmelidir (KÜB §4.5).' },
      { ile: 'Ezetimib', siddet: 'orta', not: 'Kolelitiyazis ve safra kesesi hastalığı riskine karşı dikkatli olunmalıdır (ezetimib KÜB §4.5).' },
    ],
    gebelik: { metin: 'Gebelikte yeterli veri yoktur; yalnızca açık gereklilikte kullanılır.' },
    emzirme: 'Emzirme döneminde önerilmez.',
    bobrekDozUyarisi: true,
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    kaynak: kub('LİPHONİS 267 MG SERT KAPSÜL (onay 04/08/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/kb_f96d6f19-fcda-40b0-b217-7618e026af75.pdf'),
  },

  ezetimib: {
    name: 'Ezetimib',
    brand: ['Ezetrol', 'Ezelipin', 'Zetia', 'Inegy (kombinasyon)'],
    dose: 'Günde 1 defa 10 mg, yiyeceklerle birlikte veya aç karnına. Statinle birlikte kullanıldığında aynı saatte alınmalıdır.',
    pediatricDose: '6 yaşından küçük çocuklarda kullanılmamalıdır; 6 yaş üzerinde tedavi uzman gözetiminde başlatılır',
    form: 'Tablet',
    sgkCovered: true,
    sgkRestriction: 'SUT: lipid düşürücü ilaçların ödeme koşullarına bakınız.',
    category: 'Kolesterol emilim inhibitörü',
    siniflar: ['Lipid düşürücü', 'Kolesterol emilim inhibitörü'],
    yasKontrendikasyonAy: 72,
    contraindications: [
      'Ezetimibe aşırı duyarlılık',
      'Statinle birlikte kullanımda: gebelik ve emzirme',
      'Statinle birlikte kullanımda: aktif karaciğer hastalığı veya açıklanamayan kalıcı transaminaz yüksekliği',
      '6 yaş altı çocuklar',
    ],
    interactions: ['Kolestiramin', 'Siklosporin', 'Fenofibrat', 'Statinler', 'Antiasitler'],
    etkilesimler: [
      { ile: 'Siklosporin', siddet: 'ciddi', not: 'Ezetimib EAA\'sını ortalama 3,4 kat artırır; birlikte kullanımda siklosporin düzeyi izlenmelidir (KÜB §4.5).' },
      { ile: 'Fenofibrat', siddet: 'orta', not: 'Kolelitiyazis ve safra kesesi hastalığı riskine karşı dikkatli olunmalıdır (KÜB §4.5).' },
      { ile: 'Antiasit', siddet: 'orta', not: 'Emilim hızını azaltır (biyoyararlanımı etkilemez, KÜB §4.5).' },
    ],
    gebelik: { metin: 'Tek başına kullanımda veri sınırlıdır; statinle birlikte kullanımı gebelikte KONTRENDİKEDİR (KÜB §4.3).' },
    emzirme: 'Statinle birlikte kullanımı emzirme döneminde kontrendikedir.',
    renkliRecete: 'normal',
    kaynak: kub('EZELİPİN 10 MG TABLET (onay 23/09/2025)', 'https://titck.gov.tr/storage/Archive/2025/kubKtAttachments/TTCKOnaylKBEZELPN_24_09_2025.pdf'),
  },
}
