/**
 * Gastrointestinal sistem — PPİ'ler, H2 blokeri, prokinetikler, antiemetikler, laksatif,
 * antispazmodik, antidiyareik, aminosalisilat.
 *
 * The PPI class carries one interaction Turkish outpatient practice actually trips over — PPİ +
 * klopidogrel (CYP2C19 inhibisyonu ile antiagregan aktivasyonun azalması) — and one the KÜBs make a
 * contraindication (atazanavir / nelfinavir / rilpivirin). Both are written on every PPI here, as
 * class entries, so a new PPI cannot be added without them.
 */
import { kub } from '../kaynak'
import type { TürkishDrug } from '../tipler'

const PPI_SINIF = ['Proton pompa inhibitörü', 'PPİ', 'Antisekretuvar', 'Benzimidazol'] as const

const PPI_ETKILESIM = [
  { ile: 'Metotreksat', siddet: 'ciddi' as const, not: 'PPİ ile birlikte metotreksat serum düzeyi yükselebilir; yüksek doz MTX tedavisinde PPİ geçici kesilmelidir (KÜB §4.5).' },
  { ile: 'Atazanavir', siddet: 'ciddi' as const, not: 'Mide asiditesinin baskılanması atazanavir maruziyetini belirgin azaltır; birlikte kullanım önerilmez/kontrendikedir (KÜB §4.3/4.5).' },
  { ile: 'İtrakonazol', siddet: 'orta' as const, not: 'Asit bağımlı emilim azalır; antifungal etkinlik düşebilir (KÜB §4.5).' },
  { ile: 'Takrolimus', siddet: 'orta' as const, not: 'PPİ takrolimus serum düzeyini artırır; düzey ve böbrek fonksiyonu izlenmeli (KÜB §4.5).' },
  { ile: 'Digoksin', siddet: 'orta' as const, not: 'Digoksin biyoyararlanımı artar; uzun kullanımda ayrıca hipomagnezemi dijital toksisitesini kolaylaştırır (KÜB §4.5).' },
] as const

export const GASTROINTESTINAL: Record<string, TürkishDrug> = {
  omeprazol: {
    name: 'Omeprazol',
    brand: ['Losec', 'Prosek', 'Omeprol', 'Omeprazid', 'Erbolin'],
    dose: 'Duodenal ülser: 20 mg 1x1, 2–4 hafta. Zayıf yanıtta 40 mg 1x1. GÖRH idame: 20 mg 1x1. Sabah aç karnına.',
    pediatricDose: '≥1 yaş ve 10–20 kg: 10 mg/gün; ≥2 yaş ve >20 kg: 20 mg/gün',
    pediatrik: {
      min: 10, max: 20, birim: 'mg/kg/gün', gunlukBolum: 1,
      mutlakMaxMgGun: 40, enAzAy: 12,
      metin: 'KÜB §4.2 (kiloya göre sabit doz, mg/kg değil): 1 yaşından büyük ve ≥10 kg çocukta reflü özofajit/GÖRH tedavisinde 10–20 kg için günde bir defa 10 mg (gerekirse 20 mg); ≥2 yaş ve >20 kg için günde bir defa 20 mg (gerekirse 40 mg). Tedavi süresi 4–8 hafta.',
    },
    form: 'Enterik kaplı kapsül, IV flakon',
    sgkCovered: true,
    category: 'Proton pompa inhibitörü',
    siniflar: [...PPI_SINIF, 'CYP2C19 inhibitörü'],
    contraindications: ['Omeprazol veya benzimidazol türevlerine aşırı duyarlılık', 'Nelfinavir ile eş zamanlı kullanım'],
    interactions: ['Klopidogrel', 'Nelfinavir', 'Atazanavir', 'Metotreksat', 'Takrolimus', 'Digoksin', 'Sitalopram', 'Silostazol', 'İtrakonazol'],
    etkilesimler: [
      ...PPI_ETKILESIM,
      { ile: 'Klopidogrel', siddet: 'ciddi', not: 'CYP2C19 inhibisyonu klopidogrelin aktif metabolitini azaltır; trombosit inhibisyonu düşer — birlikte kullanımdan kaçınılmalı, gerekiyorsa pantoprazol tercih edilmeli (KÜB §4.5).' },
      { ile: 'Nelfinavir', siddet: 'ciddi', not: 'KONTRENDİKE — nelfinavir maruziyeti ~%40 azalır (KÜB §4.3/4.5).' },
      { ile: 'Sitalopram', siddet: 'orta', not: 'CYP2C19 ile metabolize olan ilaçların düzeyi yükselir; QT uzaması açısından dikkat (KÜB §4.5).' },
    ],
    gebelik: { kategori: 'C', metin: '1000\'den fazla maruziyeti kapsayan üç prospektif çalışma gebelik veya fetüs/yenidoğan sağlığı üzerinde zararlı etki göstermemiştir (KÜB §4.6).' },
    emzirme: 'Anne sütüne geçer; terapötik dozlarda bebekte etki beklenmez.',
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Uzun süreli kullanımda B12 eksikliği, hipomagnezemi, kemik kırığı riski ve C. difficile enfeksiyonu açısından endikasyon periyodik gözden geçirilmelidir.',
    kaynak: kub('PROSEK 20 MG ENTERİK KAPLI KAPSÜL (onay 13/02/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/ek4kubtemiz_13_02_2026.pdf'),
  },

  pantoprazol: {
    name: 'Pantoprazol',
    brand: ['Pantpas', 'Protinum', 'Panto', 'Pandev', 'Controloc'],
    dose: 'Semptomatik GÖRH: 20 mg 1x1. Reflü özofajit tedavisi: 40 mg 1x1, 4–8 hafta. İdame: 20 mg 1x1.',
    pediatricDose: '40 kg altındaki çocuklarda günde 20 mg aşılmamalıdır; 5 yaş altında kullanılmaz',
    pediatrik: {
      min: 20, max: 20, birim: 'mg/kg/gün', gunlukBolum: 1,
      mutlakMaxMgGun: 20, enAzAy: 60,
      metin: 'KÜB §4.2 (sabit doz, mg/kg değil): 40 kilonun altındaki çocuklarda günde 20 mg pantoprazol dozu aşılmamalıdır. 5 yaşından küçük çocuklarda kullanılmamalıdır.',
    },
    form: 'Enterik kaplı tablet, IV flakon',
    sgkCovered: true,
    category: 'Proton pompa inhibitörü',
    siniflar: [...PPI_SINIF],
    yasKontrendikasyonAy: 60,
    contraindications: ['Pantoprazol veya benzimidazollere aşırı duyarlılık', '5 yaş altı çocuklarda kullanılmaz'],
    interactions: ['HIV proteaz inhibitörleri', 'Varfarin', 'Metotreksat', 'Fluvoksamin', 'Rifampisin', 'Sarı kantaron', 'İtrakonazol'],
    etkilesimler: [
      ...PPI_ETKILESIM,
      { ile: 'Varfarin', siddet: 'orta', not: 'INR ve protrombin zamanında artış rapor edilmiştir; birlikte kullanımda INR izlenmeli (KÜB §4.5).' },
      { ile: 'Rifampisin', siddet: 'orta', not: 'CYP2C19 indüksiyonu pantoprazol maruziyetini azaltır (KÜB §4.5).' },
    ],
    gebelik: { kategori: 'B', metin: '300–1000 gebelik sonucu malformasyon veya föto/neonatal toksisite göstermemiştir (KÜB §4.6).' },
    emzirme: 'Anne sütüne geçer; yarar/risk değerlendirilir.',
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'PPİ\'ler içinde klopidogrel etkileşimi en zayıf olanıdır — antiagregan alan hastada tercih edilir. Ağır karaciğer yetmezliğinde günlük 20 mg aşılmamalıdır.',
    kaynak: kub('PROTİNUM 20 MG ENTERİK KAPLI TABLET (onay 12/09/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/Ekek41311kubtemiz_09ad74cc-8b78-4227-ae0e-442560c1adbc.pdf'),
  },

  esomeprazol: {
    name: 'Esomeprazol',
    brand: ['Nexium', 'Esopral', 'Esogast', 'Esomep'],
    dose: 'Eroziv reflü özofajit: 40 mg 1x1, 4 hafta. İdame: 20 mg 1x1. Özofajiti olmayan GÖRH: 20 mg 1x1.',
    pediatricDose: '12 yaş altında kullanılmaz',
    form: 'Kapsül, enterik tablet, IV flakon',
    sgkCovered: true,
    category: 'Proton pompa inhibitörü',
    siniflar: [...PPI_SINIF, 'CYP2C19 inhibitörü'],
    yasKontrendikasyonAy: 144,
    contraindications: [
      'Esomeprazol veya benzimidazol türevlerine aşırı duyarlılık',
      'Atazanavir veya nelfinavir ile birlikte kullanım',
      '12 yaş altı çocuklar',
    ],
    interactions: ['Klopidogrel', 'Atazanavir', 'Nelfinavir', 'Metotreksat', 'Takrolimus', 'Digoksin', 'İtrakonazol'],
    etkilesimler: [
      ...PPI_ETKILESIM,
      { ile: 'Klopidogrel', siddet: 'ciddi', not: 'CYP2C19 inhibisyonu ile klopidogrelin antiagregan etkisi azalır; birlikte kullanımdan kaçınılmalı (KÜB §4.5).' },
      { ile: 'Nelfinavir', siddet: 'ciddi', not: 'KONTRENDİKE — nelfinavir maruziyeti belirgin azalır (KÜB §4.3/4.5).' },
    ],
    gebelik: { kategori: 'B', metin: 'Gebelikte klinik veri sınırlıdır; gebe kadınlara verilirken tedbirli olunmalıdır (KÜB §4.6).' },
    emzirme: 'Anne sütüne geçişi bilinmiyor; emzirme döneminde kullanılmamalıdır.',
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Ağır karaciğer yetmezliğinde 20 mg\'lık doz aşılmamalıdır.',
    kaynak: kub('ESOPRAL 40 MG KAPSÜL (onay 18/04/2023)', 'https://titck.gov.tr/storage/Archive/2023/kubKtAttachments/ek7temizkubESOPRAL_93128310-b019-4c8b-8f08-bcff399155c0.pdf'),
  },

  lansoprazol: {
    name: 'Lansoprazol',
    brand: ['Lansor', 'Degastrol', 'Lansoprol', 'Helicol'],
    dose: 'Duodenal ülser: 30 mg 1x1, 2 hafta. Gastrik ülser / reflü özofajit: 30 mg 1x1, 4 hafta. İdame: 15 mg 1x1.',
    pediatricDose: '1–11 yaş ≤30 kg: 15 mg/gün; >30 kg: 30 mg/gün',
    pediatrik: {
      min: 15, max: 30, birim: 'mg/kg/gün', gunlukBolum: 1,
      mutlakMaxMgGun: 30, enAzAy: 12,
      metin: 'KÜB §4.2 (kiloya göre sabit doz, mg/kg değil): 1–11 yaş arası ≤30 kg çocukta GÖRH/eroziv özofajitin kısa süreli tedavisinde 12 haftaya kadar günde bir defa 15 mg; 30 kg üstünde günde bir defa 30 mg. Klinik zorunluluk yoksa günlük 30 mg aşılmamalıdır.',
    },
    form: 'Mikropellet kapsül, ağızda dağılan tablet',
    sgkCovered: true,
    category: 'Proton pompa inhibitörü',
    siniflar: [...PPI_SINIF],
    contraindications: [
      'Lansoprazole aşırı duyarlılık',
      'Atazanavir ile birlikte kullanım',
      'Rilpivirin içeren ilaçlarla birlikte kullanım',
    ],
    interactions: ['Atazanavir', 'Rilpivirin', 'Nelfinavir', 'Mikofenolat mofetil', 'Digoksin', 'Metotreksat', 'Takrolimus', 'Klopidogrel'],
    etkilesimler: [
      ...PPI_ETKILESIM,
      { ile: 'Rilpivirin', siddet: 'ciddi', not: 'KONTRENDİKE — rilpivirin alt-terapötik konsantrasyona düşer, direnç gelişebilir (KÜB §4.3/4.5).' },
      { ile: 'Mikofenolat mofetil', siddet: 'orta', not: 'Gastrik pH artışı MMF çözünürlüğünü azaltır, aktif metabolit maruziyeti düşer; nakil hastasında dikkat (KÜB §4.5).' },
      { ile: 'Klopidogrel', siddet: 'orta', not: 'CYP2C19 üzerinden antiagregan aktivasyon azalabilir.' },
    ],
    gebelik: { kategori: 'B', metin: 'Gebelikte klinik veri yoktur; gebelik döneminde kullanımı önerilmemektedir (KÜB §4.6).' },
    emzirme: 'Lansoprazol ve metabolitleri anne sütüne geçer; emzirme döneminde önerilmez.',
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Orta/ciddi karaciğer yetmezliğinde günlük doz yarıya indirilmelidir (KÜB §4.2).',
    kaynak: kub('DEGASTROL 15 MG MİKROPELLET KAPSÜL (onay 22/04/2025)', 'https://titck.gov.tr/storage/Archive/2025/kubKtAttachments/DEGASTROL15mgmikropelletkapslkub_24_04_2025.pdf'),
  },

  famotidin: {
    name: 'Famotidin',
    brand: ['Famodin', 'Gastrofam', 'Duofam', 'Pepcidin'],
    dose: 'Aktif duodenal ülser: yatmadan önce 40 mg, 4–8 hafta. İdame: yatmadan önce 20 mg.',
    pediatricDose: 'Çocuklarda güvenlilik ve etkinlik belirlenmemiştir, kullanımı önerilmez',
    form: 'Film kaplı tablet, IV flakon',
    sgkCovered: true,
    category: 'H2 reseptör antagonisti',
    siniflar: ['H2 reseptör antagonisti', 'Antisekretuvar'],
    contraindications: ['Famotidine aşırı duyarlılık', 'Diğer H2 reseptör antagonistlerine aşırı duyarlılık (çapraz duyarlılık)'],
    interactions: ['İtrakonazol', 'Ketokonazol', 'Ulipristal', 'Antiasitler', 'Kalsiyum karbonat'],
    etkilesimler: [
      { ile: 'İtrakonazol', siddet: 'orta', not: 'Asit bağımlı emilim azalır; antifungal etkinlik düşebilir — hekime danışılmalıdır (KÜB §4.5).' },
      { ile: 'Antiasit', siddet: 'orta', not: 'Antiasitler famotidin emilimini ve plazma düzeyini azaltır (KÜB §4.5).' },
      { ile: 'Kalsiyum', siddet: 'orta', not: 'Hemodiyaliz hastasında fosfat bağlayıcı kalsiyum karbonatla birlikte kullanımdan kaçınılmalıdır (KÜB §4.5).' },
    ],
    gebelik: { kategori: 'B', metin: 'Gebelikte kullanımı önerilmez; yalnızca açık gereklilikte ve yarar/risk değerlendirmesiyle reçete edilmelidir (KÜB §4.6).' },
    emzirme: 'Anne sütüne geçer; emzirme veya ilaç kesilmelidir (KÜB §4.6).',
    bobrekDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Ranitidin NDMA safsızlığı nedeniyle TİTCK tarafından piyasadan çekilmiştir; H2 blokeri gerekiyorsa famotidin kullanılır.',
    kaynak: kub('GASTROFAM 20 MG FİLM KAPLI TABLET (onay 18/03/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/Ek41311kubtemizkopyaX_25_03_2026.pdf'),
  },

  domperidon: {
    name: 'Domperidon',
    brand: ['Motilium', 'Domperon', 'Dompy'],
    dose: 'Erişkin ve ≥12 yaş (≥35 kg): günde 3 defaya kadar 10 mg. Günlük maksimum 30 mg. Tedavi süresi 1 haftayı aşmamalıdır.',
    pediatricDose: '12 yaş altı veya 35 kg altındaki bireylerde KULLANILMAZ',
    form: 'Film tablet, oral süspansiyon',
    sgkCovered: true,
    category: 'Dopamin D2 antagonisti (prokinetik)',
    siniflar: ['Prokinetik', 'Antiemetik', 'Dopamin antagonisti', 'QT uzatan ilaç'],
    yasKontrendikasyonAy: 144,
    contraindications: [
      'Domperidona aşırı duyarlılık',
      'Prolaktin salgılayan hipofiz tümörü (prolaktinoma)',
      'Gastrointestinal kanama, mekanik obstrüksiyon veya perforasyon',
      'Orta veya şiddetli karaciğer yetmezliği',
      'QTc uzaması, konjestif kalp yetmezliği, önemli elektrolit bozukluğu',
      '12 yaş altı veya 35 kg altı',
    ],
    interactions: ['Güçlü CYP3A4 inhibitörleri', 'Klaritromisin', 'Sınıf III antiaritmikler', 'Apomorfin', 'Levodopa', 'Antiasitler', 'Diltiazem', 'Verapamil', 'QT uzatan ilaçlar'],
    etkilesimler: [
      { ile: 'Klaritromisin', siddet: 'ciddi', not: 'KONTRENDİKE — güçlü CYP3A4 inhibitörü domperidon düzeyini yükseltir, QT uzaması ve Torsade de Pointes riski (KÜB §4.3/4.5).' },
      { ile: 'Amiodaron', siddet: 'ciddi', not: 'KONTRENDİKE — Sınıf III antiaritmikle birlikte Torsade de Pointes riski (KÜB §4.3/4.5).' },
      { ile: 'QT uzatan ilaç', siddet: 'ciddi', not: 'QTc uzatan ilaçlarla birlikte kullanımı kontrendikedir (KÜB §4.3).' },
      { ile: 'İtrakonazol', siddet: 'ciddi', not: 'Güçlü CYP3A4 inhibitörü — birlikte kullanım kontrendikedir (KÜB §4.3).' },
      { ile: 'Levodopa', siddet: 'orta', not: 'Levodopa plazma konsantrasyonunda %30\'a varan artış (KÜB §4.5).' },
      { ile: 'Verapamil', siddet: 'orta', not: 'Orta etkili CYP3A4 inhibitörü — birlikte kullanım tavsiye edilmez (KÜB §4.5).' },
      { ile: 'Proton pompa inhibitörü', siddet: 'orta', not: 'Antisekretuvar ilaçlar domperidonla aynı anda alınmamalıdır; domperidon yemekten önce alınır (KÜB §4.5).' },
    ],
    gebelik: { kategori: 'C', metin: 'Gebe verisi sınırlıdır; ancak beklenen terapötik yarar doğrulanabiliyorsa kullanılmalıdır (KÜB §4.6).' },
    emzirme: 'Anne sütüne az miktarda geçer; yarar/risk değerlendirilir.',
    karacigerDozUyarisi: true,
    bobrekDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Ani kardiyak ölüm riski nedeniyle en düşük etkili dozda ve en kısa sürede kullanılır (maksimum 1 hafta).',
    kaynak: kub('MOTİLİUM 1 MG/ML ORAL SÜSPANSİYON (onay 23/09/2022)', 'https://titck.gov.tr/storage/Archive/2022/kubKtAttachments/MOTILIUM1KB_4db09de4-56b8-42c9-a324-86c46f00fdb7.pdf'),
  },

  metoklopramid: {
    name: 'Metoklopramid',
    brand: ['Metpamid', 'Metoklamide', 'Primperan'],
    dose: 'Yetişkin: tek seferde 10 mg, günde 3 defaya kadar. Maksimum günlük doz 30 mg veya 0,5 mg/kg. Maksimum tedavi süresi 5 gün.',
    pediatricDose: '1–18 yaş (yalnız KİBK önlenmesinde): 0,1–0,15 mg/kg/doz, günde 3 defaya kadar; 24 saatte maksimum 0,5 mg/kg',
    pediatrik: {
      min: 0.1, max: 0.15, birim: 'mg/kg/doz', gunlukBolum: 3,
      maxMgKgGun: 0.5, mutlakMaxMgGun: 30, enAzAy: 12,
      metin: 'KÜB §4.2: kemoterapinin indüklediği bulantı-kusmanın önlenmesinde 1–18 yaş arası pediyatrik hastada önerilen doz 0,1–0,15 mg/kg, günde 3 defaya kadar; 24 saatte uygulanabilir maksimum günlük doz 0,5 mg/kg. 18 yaş altında ancak yarar/risk dengesi dikkatlice değerlendirildikten sonra kullanılır. 1 yaşın altında KONTRENDİKEDİR.',
    },
    form: 'Tablet, ampul, oral çözelti',
    sgkCovered: true,
    category: 'Dopamin D2 antagonisti (prokinetik/antiemetik)',
    siniflar: ['Prokinetik', 'Antiemetik', 'Dopamin antagonisti'],
    yasKontrendikasyonAy: 12,
    contraindications: [
      'Metoklopramide aşırı duyarlılık',
      'Gastrointestinal kanama, mekanik tıkanma veya perforasyon',
      'Onaylanmış veya şüpheli feokromositoma',
      'Nöroleptik veya metoklopramide bağlı tardif diskinezi öyküsü',
      'Epilepsi',
      'Parkinson hastalığı',
      'Levodopa veya dopaminerjik agonistlerle kombinasyon',
      '1 yaş altı çocuklar',
    ],
    interactions: ['Levodopa', 'Dopaminerjik agonistler', 'Antikolinerjikler', 'Nöroleptikler', 'Serotonerjik ilaçlar', 'Digoksin', 'Siklosporin', 'Alkol'],
    etkilesimler: [
      { ile: 'Levodopa', siddet: 'ciddi', not: 'KONTRENDİKE — karşılıklı antagonizma; Parkinson tedavisi bozulur (KÜB §4.3).' },
      { ile: 'Antipsikotik', siddet: 'ciddi', not: 'Ekstrapiramidal yan etkiler ve tardif diskinezi riski toplanır.' },
      { ile: 'SSRI', siddet: 'ciddi', not: 'Serotonin sendromu riski artar.' },
      { ile: 'Antikolinerjik', siddet: 'orta', not: 'Metoklopramidin prokinetik etkisini antagonize eder.' },
      { ile: 'Alkol', siddet: 'orta', not: 'Metoklopramidin sedatif etkisi alkolle belirgin artar; araç kullanımı ve düşme riski uyarısı yapılmalıdır.' },
    ],
    gebelik: { kategori: 'B', metin: '1000\'den fazla maruziyet verisi gebelik veya fetüs/yenidoğan üzerinde advers etki göstermemiştir; tedbirli kullanılır (KÜB §4.6).' },
    emzirme: 'Anne sütüne geçer; emzirme döneminde önerilmez.',
    bobrekDozUyarisi: true,
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Tardif diskinezi riski nedeniyle 5 günden uzun kullanılmamalıdır. Akut distonik reaksiyon özellikle genç kadınlarda görülür.',
    kaynak: kub('METOKLAMİDE 10 MG TABLET (onay 28/03/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/MetoklamideEk1311kub_13_05_2026.pdf'),
  },

  ondansetron: {
    name: 'Ondansetron',
    brand: ['Zofran', 'Zofer', 'Onseren', 'Setron'],
    dose: 'Emetojenik kemoterapi: tedaviden 1–2 saat önce 8 mg, sonra 12 saatte bir 8 mg (maksimum 5 gün). Yüksek emetojenik rejimde tek seferde 24 mg\'a kadar.',
    pediatricDose: '6 ay–17 yaş: 0,15 mg/kg IV, 4 saatte bir 3 doza kadar (tek doz 8 mg\'ı aşmaz)',
    pediatrik: {
      min: 0.15, max: 0.15, birim: 'mg/kg/doz', gunlukBolum: 3,
      mutlakMaxMgDoz: 8, enAzAy: 6,
      metin: 'KÜB §4.2: 6 aydan 17 yaşa kadar sitotoksik kemoterapinin neden olduğu bulantı-kusmada 0,15 mg/kg IV, her dört saatte bir 3 doza kadar (vücut yüzey alanı ile dozlamada 5 mg/m²). Yetişkin dozları aşılmamalıdır.',
    },
    form: 'Film kaplı tablet, ağızda dağılan tablet, ampul, şurup',
    sgkCovered: true,
    category: '5-HT3 reseptör antagonisti',
    siniflar: ['Antiemetik', '5-HT3 antagonisti', 'Serotonerjik ilaç', 'QT uzatan ilaç'],
    contraindications: ['Ondansetrona aşırı duyarlılık', 'Apomorfin ile eşzamanlı kullanım'],
    interactions: ['Apomorfin', 'QT uzatan ilaçlar', 'Kardiyotoksik ilaçlar', 'SSRI', 'SNRI', 'Tramadol', 'Fenitoin', 'Karbamazepin', 'Rifampisin'],
    etkilesimler: [
      { ile: 'Apomorfin', siddet: 'ciddi', not: 'KONTRENDİKE — şiddetli hipotansiyon ve bilinç kaybı bildirilmiştir (KÜB §4.3/4.5).' },
      { ile: 'QT uzatan ilaç', siddet: 'ciddi', not: 'QT uzamasına katkı — aritmi riski artar (KÜB §4.5).' },
      { ile: 'SSRI', siddet: 'ciddi', not: 'Serotonin sendromu bildirilmiştir (KÜB §4.5).' },
      { ile: 'SNRI', siddet: 'ciddi', not: 'Serotonin sendromu riski artar (KÜB §4.5).' },
      { ile: 'Tramadol', siddet: 'orta', not: 'Ondansetron tramadolün analjezik etkisini azaltabilir; ayrıca serotonerjik yük artar (KÜB §4.5).' },
      { ile: 'Rifampisin', siddet: 'orta', not: 'Güçlü CYP3A4 indükleyicisi ondansetron maruziyetini azaltır (KÜB §4.5).' },
      { ile: 'Karbamazepin', siddet: 'orta', not: 'Enzim indüksiyonu ondansetron düzeyini düşürür (KÜB §4.5).' },
    ],
    gebelik: { metin: 'Birinci trimesterde kullanımın orofasiyal malformasyon (oral yarık) riskini artırdığından şüphelenilmektedir — 1,8 milyon gebelik kohortunda 10.000 kadında 3 ek vaka (KÜB §4.6). İlk trimesterde kaçınılmalıdır.' },
    emzirme: 'Anne sütüne geçer; yarar/risk değerlendirilir.',
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Orta/şiddetli karaciğer yetmezliğinde günlük toplam doz 8 mg\'ı aşmamalıdır (KÜB §4.2).',
    kaynak: kub('ZOFER 4 MG FİLM KAPLI TABLET (onay 07/12/2025)', 'https://titck.gov.tr/storage/Archive/2025/kubKtAttachments/ONAYLIKB_25_12_2025.pdf'),
  },

  trimebutin: {
    name: 'Trimebutin',
    brand: ['Debridat', 'Tribudat', 'Trimedat'],
    dose: 'Yetişkin: günde 3 kez 100–200 mg (1–2 tablet).',
    pediatricDose: '2 yaş üzeri çocuklar için oral süspansiyon formu kullanılır',
    form: 'Tablet, oral süspansiyon',
    sgkCovered: true,
    category: 'Gastrointestinal motilite düzenleyici',
    siniflar: ['Antispazmodik', 'Prokinetik', 'Opioid reseptör agonisti (periferik)'],
    yasKontrendikasyonAy: 24,
    contraindications: ['Trimebutine aşırı duyarlılık', '2 yaşın altındaki çocuklar (tablet formu)'],
    interactions: [],
    etkilesimler: [],
    gebelik: { kategori: 'B', metin: 'Hayvan çalışmalarında teratojenik etki saptanmamıştır (KÜB §4.6).' },
    emzirme: 'Anne sütüne geçişi hakkında yeterli veri yoktur.',
    renkliRecete: 'normal',
    kaynak: kub('TRİBUDAT 100 MG TABLET (onay 29/04/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/UygunbulunanKBmetni6_30_04_2026.pdf'),
  },

  laktuloz: {
    name: 'Laktüloz',
    brand: ['Duphalac', 'Medulac', 'Laevolac', 'Osmolak'],
    dose: 'Konstipasyon yetişkin: başlangıç 15–45 mL/gün, idame 15–30 mL/gün. Hepatik ensefalopati: başlangıç günde 3 defa 30–50 mL.',
    pediatricDose: '<1 yaş: 5 mL/güne kadar; 1–6 yaş: 5–10 mL/gün; 7–14 yaş: başlangıç 15 mL/gün',
    pediatrik: {
      min: 5, max: 15, birim: 'mg/kg/gün', gunlukBolum: 1,
      metin: 'KÜB §4.2 (mL olarak sabit doz, mg/kg değil): 1 yaşın altındaki bebeklerde 5 mL\'ye kadar (3 g laktüloza kadar); 1–6 yaş arası 5–10 mL (3–7 g); 7–14 yaş arası başlangıç 15 mL (10 g), idame 10–15 mL. Hepatik ensefalopati dozu yalnızca erişkinler içindir.',
    },
    form: 'Şurup, saşe',
    sgkCovered: true,
    category: 'Ozmotik laksatif',
    siniflar: ['Laksatif', 'Ozmotik laksatif', 'Disakkarit'],
    contraindications: [
      'Laktüloza aşırı duyarlılık',
      'Galaktozemi',
      'Gastrointestinal obstrüksiyon veya perforasyon riski (ülseratif kolit, Crohn gibi akut enflamatuvar bağırsak hastalıkları)',
    ],
    interactions: ['Tiyazid diüretikler', 'Kortikosteroidler', 'Digoksin'],
    etkilesimler: [
      { ile: 'Digoksin', siddet: 'orta', not: 'Laktüloza bağlı potasyum kaybı kardiyak glikozitlerin etkisini ve toksisitesini artırabilir (KÜB §4.5).' },
      { ile: 'Diüretik', siddet: 'orta', not: 'Potasyum kaybı toplanır; uzun kullanımda elektrolit izlenmeli (KÜB §4.5).' },
      { ile: 'Kortikosteroid', siddet: 'orta', not: 'Potasyum kaybını artırabilir (KÜB §4.5).' },
    ],
    gebelik: { kategori: 'B', metin: 'Sistemik maruziyet ihmal edilebilir düzeydedir; gebelikte etki beklenmez (KÜB §4.6).' },
    emzirme: 'Sistemik emilimi yok denecek kadar azdır; emzirme döneminde kullanılabilir.',
    renkliRecete: 'normal',
    notes: 'Laksatif tedavisi sırasında günlük 1,5–2 litre sıvı alımı önerilir (KÜB §4.2).',
    kaynak: kub('MEDULAC-WM 667 MG/ML ŞURUP (onay 10/02/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/UYGUNKBMEDULAC_10_02_2026.pdf'),
  },

  simetikon: {
    name: 'Simetikon',
    brand: ['Disflatyl', 'Metlinox', 'Gazex', 'Espumisan'],
    dose: 'Yetişkin: 4–6 saatte bir 30–45 damla (1,2–1,8 mL).',
    pediatricDose: 'Yenidoğan: 10 damla, günde 4 defaya kadar; >4 hafta–12 ay: 15 damla, günde 6 defaya kadar',
    pediatrik: {
      min: 10, max: 30, birim: 'mg/kg/doz', gunlukBolum: 4,
      metin: 'KÜB §4.2 (damla sayısıyla sabit doz, mg/kg değil): yenidoğanlarda tek doz 10 damla (0,4 mL), maksimum günde 4 defa; >4 hafta–12 ay arası 15 damla (0,6 mL), günde 6 defaya kadar; >12 ay–6 yaş 15 damla; >6 yaş–18 yaş 20–30 damla. Doz 4–6 saatte bir alınır.',
    },
    form: 'Oral damla süspansiyon, çiğneme tableti, emülsiyon',
    sgkCovered: true,
    category: 'Antiflatülan',
    siniflar: ['Antiflatülan', 'Yüzey aktif madde'],
    contraindications: ['Simetikona aşırı duyarlılık'],
    interactions: [],
    etkilesimler: [],
    gebelik: { kategori: 'B', metin: 'Gebe verisi yeterli değildir; hayvan çalışmalarında teratojenik etki görülmemiştir. Sadece kesin gerekliyse kullanılır (KÜB §4.6).' },
    emzirme: 'Sistemik emilimi yoktur; emzirme döneminde kullanılabilir.',
    renkliRecete: 'normal',
    notes: 'Emilmez, sistemik etkisi yoktur — bebek koliğinde en sık kullanılan seçeneklerden biridir.',
    kaynak: kub('METLİNOX 69,19 MG/ML ORAL DAMLA (onay 26/12/2024)', 'https://titck.gov.tr/storage/Archive/2025/kubKtAttachments/METLNOXKB_21_02_2025.pdf'),
  },

  mesalazin: {
    name: 'Mesalazin',
    brand: ['Salofalk', 'Asacol', 'Rektacol', 'Pentasa'],
    dose: 'Aktif ülseratif kolit (rektal): günde bir kez yatmadan önce 4 g lavman. Oral formlarda 1,5–4 g/gün.',
    pediatricDose: 'Çocuklarda etkililiğe dair deneyim ve doküman sınırlıdır',
    form: 'Rektal süspansiyon (lavman), supozituvar, gastrorezistan tablet, granül',
    sgkCovered: true,
    sgkRestriction: 'SUT: ülseratif kolit / Crohn tanısı ve uzman hekim raporu koşullarına bakınız.',
    category: 'Aminosalisilat',
    siniflar: ['Aminosalisilat', '5-ASA', 'Antiinflamatuvar (bağırsak)', 'Salisilat'],
    alerjiSinifi: ['aspirin'],
    contraindications: [
      'Mesalazin veya salisilatlara aşırı duyarlılık',
      'Şiddetli karaciğer yetmezliği',
      'Şiddetli böbrek yetmezliği',
    ],
    interactions: ['Azatiyoprin', '6-merkaptopürin', 'Tioguanin', 'Varfarin'],
    etkilesimler: [
      { ile: 'Azatiyoprin', siddet: 'ciddi', not: 'Birlikte kullanımda miyelosupresyon riski artar; tam kan sayımı izlenmelidir (KÜB §4.5).' },
      { ile: 'Varfarin', siddet: 'orta', not: 'Mesalazinin varfarinin antikoagülan etkisini azalttığına dair zayıf kanıtlar vardır; INR izlenmeli (KÜB §4.5).' },
    ],
    gebelik: { kategori: 'B', metin: 'Sınırlı gebelik verisi advers etki göstermemiştir (KÜB §4.6).' },
    emzirme: 'Anne sütüne az miktarda geçer; bebekte ishal bildirilmiştir.',
    bobrekDozUyarisi: true,
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    kaynak: kub('REKTACOL 4 G/60 ML REKTAL SÜSPANSİYON (onay 20/03/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/TTCKOnaylKBREKTACOL_23_03_2026.pdf'),
  },

  rasekadotril: {
    name: 'Rasekadotril',
    brand: ['Hidrasec', 'Raventris', 'Sekadril'],
    dose: 'Yetişkin: başlangıçta bir kapsül (100 mg), sonra günde 3 kez bir kapsül, tercihen ana yemeklerden önce. İki normal dışkılama görülene kadar.',
    pediatricDose: 'Bebek, çocuk ve adolesanlar için ayrı (kiloya göre) saşe formülasyonları vardır',
    form: 'Sert kapsül, pediatrik saşe granül',
    sgkCovered: true,
    category: 'Enkefalinaz inhibitörü (antisekretuvar antidiyareik)',
    siniflar: ['Antidiyareik', 'Enkefalinaz inhibitörü'],
    contraindications: ['Rasekadotrile aşırı duyarlılık'],
    interactions: ['ACE inhibitörleri', 'Loperamid', 'Nifuroksazid'],
    etkilesimler: [
      { ile: 'ACE inhibitörü', siddet: 'ciddi', not: 'Birlikte kullanım anjiyoödem riskini artırabilir (KÜB §4.5).' },
    ],
    gebelik: { kategori: 'B', metin: 'Gebede klinik veri yoktur; spesifik klinik çalışma olmadığından gebe kadınlara reçete edilmemelidir (KÜB §4.6).' },
    emzirme: 'Veri yetersizdir; emzirme döneminde önerilmez.',
    renkliRecete: 'normal',
    notes: 'Motiliteyi yavaşlatmaz — loperamidin aksine akut çocukluk çağı ishalinde kullanılabilir. Uzun dönem tedavi önerilmez.',
    kaynak: kub('RAVENTRİS 100 MG SERT KAPSÜL (onay 12/01/2024)', 'https://titck.gov.tr/storage/Archive/2024/kubKtAttachments/Raventris100UygunKB_39123599-7f55-48d6-ac90-e87d3a094b69.pdf'),
  },
}
