/**
 * Antikoagülan ve antiagreganlar.
 *
 * Everything here bleeds when stacked, so the whole group carries the same two class labels —
 * 'Antikoagülan' and 'Antiagregan' — and an entry written against either fires from both sides.
 * That is what lets the card warn on varfarin + NSAİİ, apiksaban + klopidogrel and enoksaparin +
 * aspirin without anyone writing those pairs down one by one.
 */
import { kub } from '../kaynak'
import type { TürkishDrug } from '../tipler'

const KANAMA_ETKILESIM = [
  { ile: 'NSAİİ', siddet: 'ciddi' as const, not: 'GİS kanama riski sinerjik olarak artar; mümkünse kaçınılmalı, gerekiyorsa gastroproteksiyon eklenmelidir.' },
  { ile: 'Asetilsalisilik asit', siddet: 'ciddi' as const, not: 'Antiagregan + antikoagülan: majör kanama riski belirgin artar. Ancak bazı endikasyonlarda birlikte verilmesi hekim kararıdır.' },
  { ile: 'Antiagregan', siddet: 'ciddi' as const, not: 'Trombosit inhibisyonu + antikoagülasyon: kanama riski artar; endikasyon ve süre gözden geçirilmelidir.' },
  { ile: 'Antikoagülan', siddet: 'ciddi' as const, not: 'İki antikoagülanın birlikte kullanımı (geçiş dönemi dışında) majör kanama riski taşır.' },
  { ile: 'SSRI', siddet: 'ciddi' as const, not: 'Trombosit serotonin alımının inhibisyonu kanama riskini artırır.' },
  { ile: 'Kortikosteroid', siddet: 'ciddi' as const, not: 'GİS ülserasyon ve kanama riski artar.' },
] as const

export const HEMATOLOJI: Record<string, TürkishDrug> = {
  varfarin: {
    name: 'Varfarin sodyum',
    brand: ['Coumadin', 'Warfmadin', 'Orfarin'],
    dose: 'Başlangıç tipik olarak 2,5–5 mg/gün. INR terapötik aralıkta stabil hale gelene kadar (genellikle 3.–4. gün) günlük INR ölçülür; doz INR yanıtına göre bireyselleştirilir.',
    pediatricDose: 'Pediatrik doz INR hedefine göre bireyselleştirilir — mg/kg olarak ifade edilmez',
    form: 'Tablet',
    sgkCovered: true,
    category: 'K vitamini antagonisti (oral antikoagülan)',
    siniflar: ['Antikoagülan', 'K vitamini antagonisti', 'Kumarin'],
    contraindications: [
      'Gebelik (mekanik kalp kapağı olan yüksek riskli gebeler dışında)',
      'Hemorajik eğilim veya kan diskrazileri',
      'Yakın zamanda SSS, göz veya geniş travma cerrahisi',
      'Aktif ülserasyonla ilişkili GİS/ürogenital/solunum sistemi kanaması',
      'Merkezi sinir sistemi kanaması, serebral anevrizma, aort diseksiyonu',
      'Perikardit, perikardiyal efüzyon, bakteriyel endokardit',
      'Düşük tehdidi, eklampsi ve preeklampsi',
    ],
    interactions: ['NSAİİ', 'Asetilsalisilik asit', 'Metronidazol', 'Flukonazol', 'Trimetoprim + sülfametoksazol', 'Amiodaron', 'Makrolidler', 'Rifampisin', 'Levotiroksin', 'SSRI', 'Fenofibrat', 'K vitamini'],
    etkilesimler: [
      ...KANAMA_ETKILESIM,
      { ile: 'Metronidazol', siddet: 'ciddi', not: 'Varfarin metabolizmasını inhibe eder; INR belirgin yükselir, doz azaltılmalı ve INR sık izlenmelidir.' },
      { ile: 'Flukonazol', siddet: 'ciddi', not: 'CYP2C9 inhibisyonu ile INR yükselir; kanama riski.' },
      { ile: 'Trimetoprim', siddet: 'ciddi', not: 'Antikoagülan etkiyi belirgin artırır; INR sıkı takip edilmelidir.' },
      { ile: 'Amiodaron', siddet: 'ciddi', not: 'Varfarin klerensini azaltır; INR haftalar boyunca yükselmeye devam edebilir, doz ~%30–50 azaltılır.' },
      { ile: 'Rifampisin', siddet: 'ciddi', not: 'Enzim indüksiyonu INR\'yi düşürür; tromboz riski, doz artırımı ve sık INR gerekir.' },
      { ile: 'Makrolid', siddet: 'ciddi', not: 'INR yükselebilir; antibiyotik başlanınca ve kesilince INR ölçülmelidir.' },
      { ile: 'Levotiroksin', siddet: 'ciddi', not: 'Tiroid durumu değiştikçe antikoagülan yanıt değişir; INR izlenmelidir.' },
      { ile: 'Fenofibrat', siddet: 'ciddi', not: 'Antikoagülan etkiyi güçlendirir; fibrat başlanırken varfarin dozu 1/3 azaltılmalıdır.' },
    ],
    gebelik: { metin: 'Gebelikte KONTRENDİKE (mekanik kapak olan yüksek riskli gebeler dışında) — varfarin embriyopatisi ve fetal kanama riski (KÜB §4.3).' },
    emzirme: 'Anne sütüne anlamlı düzeyde geçmez; emzirme döneminde kullanılabilir.',
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Dar terapötik aralık. K vitamini içeriği yüksek gıdalarda ANİ değişiklik INR\'yi kaydırır — tutarlı diyet önerilir. Her yeni ilaçta INR kontrolü gerekir.',
    kaynak: kub('WARFMADİN 10 MG TABLET (onay 07/11/2025)', 'https://titck.gov.tr/storage/Archive/2025/kubKtAttachments/warfmadin10ek2kub_11_12_2025.pdf'),
  },

  rivaroksaban: {
    name: 'Rivaroksaban',
    brand: ['Xarelto', 'Onaxan', 'Rivaxa'],
    dose: 'NVAF\'ta inme/sistemik emboli önlenmesi: günde 1 kez 20 mg (önerilen maksimum doz). Böbrek yetmezliğinde kanama riski tromboz riskinden fazlaysa 15 mg/gün.',
    pediatricDose: '30–50 kg: günde bir kez 15 mg; ≥50 kg: günde bir kez 20 mg (bu dozlar maksimum günlük dozdur)',
    pediatrik: {
      min: 15, max: 20, birim: 'mg/kg/gün', gunlukBolum: 1,
      mutlakMaxMgGun: 20,
      metin: 'KÜB §4.2 (kiloya göre sabit doz, mg/kg değil): 30–50 kg vücut ağırlığında günde bir kez 15 mg, 50 kg ve üzerinde günde bir kez 20 mg — her ikisi de maksimum günlük dozdur. Tedavi en az 5 günlük başlangıç antikoagülan tedavisinin ardından başlatılır. Çocuğun kilosu takip edilip doz düzenli gözden geçirilmelidir.',
    },
    form: 'Film kaplı tablet, oral süspansiyon',
    sgkCovered: true,
    sgkRestriction: 'SUT: NVAF / VTE endikasyon ve rapor koşullarına bakınız.',
    category: 'Direkt faktör Xa inhibitörü',
    siniflar: ['Antikoagülan', 'DOAK', 'Faktör Xa inhibitörü'],
    contraindications: [
      'Rivaroksabana aşırı duyarlılık',
      'Klinik olarak anlamlı aktif kanama',
      'Majör kanama riski taşıyan lezyon/durum (GİS ülserasyonu, yakın beyin/omurilik yaralanması veya cerrahisi, intrakraniyal kanama, özofagus varisi, vasküler anevrizma/malformasyon)',
      'Diğer antikoagülanlarla eş zamanlı tedavi (geçiş dönemi hariç)',
      'Koagülopati ile seyreden karaciğer hastalığı',
      'Gebelik ve emzirme',
    ],
    interactions: ['Güçlü CYP3A4/P-gp inhibitörleri', 'Ketokonazol', 'Ritonavir', 'Rifampisin', 'NSAİİ', 'Antiagreganlar', 'SSRI'],
    etkilesimler: [
      ...KANAMA_ETKILESIM,
      { ile: 'İtrakonazol', siddet: 'ciddi', not: 'Güçlü CYP3A4 + P-gp inhibisyonu rivaroksaban maruziyetini belirgin artırır; kanama riski — birlikte kullanım önerilmez.' },
      { ile: 'Rifampisin', siddet: 'ciddi', not: 'Güçlü indüksiyon rivaroksaban düzeyini düşürür; tromboz riski.' },
    ],
    gebelik: { metin: 'Gebelikte KONTRENDİKE (KÜB §4.3).' },
    emzirme: 'Emzirme döneminde kontrendikedir.',
    bobrekDozUyarisi: true,
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: '15 mg ve 20 mg tabletler YEMEKLE alınmalıdır (biyoyararlanım için). Spesifik antidotu andeksanet alfadır.',
    kaynak: kub('ONAXAN 15 MG FİLM KAPLI TABLET (onay 01/09/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/1311kub2_1f25d374-204c-4acd-88ff-45d1d8bf7ae9.pdf'),
  },

  apiksaban: {
    name: 'Apiksaban',
    brand: ['Eliquis', 'Olpixa', 'Apixa'],
    dose: 'VTE profilaksisi (elektif kalça/diz replasmanı): günde iki kez 2,5 mg, ilk doz operasyondan 12–24 saat sonra. NVAF\'ta genellikle günde iki kez 5 mg.',
    pediatricDose: '18 yaş altında güvenlilik ve etkililik belirlenmemiştir',
    form: 'Film kaplı tablet',
    sgkCovered: true,
    sgkRestriction: 'SUT: NVAF / VTE endikasyon ve rapor koşullarına bakınız.',
    category: 'Direkt faktör Xa inhibitörü',
    siniflar: ['Antikoagülan', 'DOAK', 'Faktör Xa inhibitörü'],
    yasKontrendikasyonAy: 216,
    contraindications: [
      'Apiksabana aşırı duyarlılık',
      'Klinik olarak anlamlı aktif kanama',
      'Koagülopati ve anlamlı kanama riski ile ilişkili karaciğer hastalığı',
      'Majör kanama riski taşıyan lezyon/durum',
      'Diğer antikoagülanlarla eş zamanlı tedavi (geçiş dönemi hariç)',
    ],
    interactions: ['Güçlü CYP3A4/P-gp inhibitörleri', 'Ketokonazol', 'Ritonavir', 'Rifampisin', 'NSAİİ', 'Antiagreganlar', 'SSRI'],
    etkilesimler: [
      ...KANAMA_ETKILESIM,
      { ile: 'İtrakonazol', siddet: 'ciddi', not: 'Güçlü CYP3A4 + P-gp inhibisyonu apiksaban maruziyetini artırır; birlikte kullanım önerilmez.' },
      { ile: 'Rifampisin', siddet: 'ciddi', not: 'Apiksaban düzeyini belirgin düşürür; tromboz riski.' },
    ],
    gebelik: { metin: 'Gebelikte kullanımı önerilmez; veri yoktur.' },
    emzirme: 'Emzirme döneminde önerilmez.',
    bobrekDozUyarisi: true,
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Spesifik antidotu andeksanet alfadır. Yaş ≥80, kilo ≤60 kg, kreatinin ≥1,5 mg/dL kriterlerinden ikisi varsa NVAF dozu 2,5 mg 2x1\'e düşürülür.',
    kaynak: kub('OLPİXA 2,5 MG FİLM KAPLI TABLET (onay 30/07/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/Ek1311kub_14_08_2026.pdf'),
  },

  dabigatran: {
    name: 'Dabigatran eteksilat',
    brand: ['Pradaxa'],
    dose: 'Ortopedik cerrahide VTE profilaksisi: cerrahiden 1–4 saat sonra başlanır, ertesi günden itibaren idame dozu. NVAF\'ta genellikle günde iki kez 150 mg (veya 110 mg).',
    pediatricDose: 'Ortopedik cerrahi profilaksisi endikasyonunda pediyatrik kullanım yeri yoktur',
    form: 'Sert kapsül',
    sgkCovered: true,
    sgkRestriction: 'SUT: NVAF / VTE endikasyon ve rapor koşullarına bakınız.',
    category: 'Direkt trombin inhibitörü',
    siniflar: ['Antikoagülan', 'DOAK', 'Direkt trombin inhibitörü'],
    contraindications: [
      'Dabigatrana aşırı duyarlılık',
      'Şiddetli böbrek yetmezliği (KrKl <30 mL/dk)',
      'Klinik olarak önemli aktif kanama',
      'Majör kanama riski taşıyan lezyon/durum',
      'Diğer antikoagülanlarla eş zamanlı tedavi (geçiş dönemi hariç)',
      'Mekanik protez kalp kapağı',
    ],
    interactions: ['P-gp inhibitörleri', 'Amiodaron', 'Verapamil', 'Ketokonazol', 'Rifampisin', 'NSAİİ', 'Antiagreganlar'],
    etkilesimler: [
      ...KANAMA_ETKILESIM,
      { ile: 'Amiodaron', siddet: 'ciddi', not: 'P-gp inhibisyonu dabigatran maruziyetini artırır; doz azaltımı gerekebilir.' },
      { ile: 'Verapamil', siddet: 'ciddi', not: 'P-gp inhibisyonu ile dabigatran düzeyi yükselir; doz ayarı gerekir.' },
      { ile: 'Rifampisin', siddet: 'ciddi', not: 'P-gp indüksiyonu dabigatran düzeyini düşürür; birlikte kullanımdan kaçınılmalıdır.' },
    ],
    gebelik: { metin: 'Gebelikte kullanımı önerilmez.' },
    emzirme: 'Emzirme döneminde önerilmez.',
    bobrekDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Böbrekle atılır — KrKl <30 mL/dk kontrendikedir. Spesifik antidotu idarusizumabdır. Kapsüller blisterden çıkarılıp haznede saklanmaz (nem duyarlı).',
    kaynak: kub('PRADAXA 110 MG SERT KAPSÜL (onay 23/06/2022)', 'https://titck.gov.tr/storage/Archive/2022/kubKtAttachments/Pradaxa110KB_2fae9670-de83-48e6-bb7c-4a8862662d31.pdf'),
  },

  enoksaparin: {
    name: 'Enoksaparin sodyum',
    brand: ['Clexane', 'Venaperta', 'Enoxa', 'Oksapar'],
    dose: 'Orta riskli cerrahide VTE profilaksisi: günde bir kez subkutan 2.000 IU (20 mg), ilk doz cerrahiden 2 saat önce; en az 7–10 gün. Yüksek riskte ve tedavi dozlarında doz kiloya göre hesaplanır.',
    pediatricDose: 'Pediatrik doz kiloya göre hesaplanır; bu ürünün KÜB\'ünde pediatrik mg/kg şeması yer almamaktadır',
    form: 'Kullanıma hazır enjektör (subkutan)',
    sgkCovered: true,
    category: 'Düşük molekül ağırlıklı heparin (DMAH)',
    siniflar: ['Antikoagülan', 'Heparin', 'DMAH', 'Düşük molekül ağırlıklı heparin'],
    contraindications: [
      'Enoksaparin, heparin veya diğer DMAH\'lara aşırı duyarlılık',
      'Son 100 gün içinde immün aracılı heparin ilişkili trombositopeni (HIT) öyküsü veya dolaşımda antikor',
      'Klinik açıdan anlamlı aktif kanama',
      'Yakın zamanda hemorajik inme',
      'Gastrointestinal ülser, yüksek kanama riskli malign neoplazm',
      'Yakın zamanda beyin, spinal veya oftalmik cerrahi',
    ],
    interactions: ['NSAİİ', 'Asetilsalisilik asit', 'Klopidogrel', 'Kortikosteroidler', 'ACE inhibitörleri', 'Spironolakton', 'Trombolitikler'],
    etkilesimler: [
      ...KANAMA_ETKILESIM,
      { ile: 'ACE inhibitörü', siddet: 'orta', not: 'Heparin potasyum atılımını azaltır; RAAS blokeriyle birlikte hiperkalemi riski artar.' },
      { ile: 'Spironolakton', siddet: 'ciddi', not: 'Hiperkalemi riski artar; potasyum izlenmelidir.' },
    ],
    gebelik: { metin: 'Plasentayı geçmez; gebelikte tercih edilen antikoagülandır. Doğum/epidural anestezi zamanlaması planlanmalıdır.' },
    emzirme: 'Anne sütüne anlamlı geçmez; emzirme döneminde kullanılabilir.',
    bobrekDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Spinal/epidural anestezi ile birlikte spinal hematom riski — zamanlama kuralları KÜB §4.4\'tedir. Trombosit sayımı HIT açısından izlenmelidir.',
    kaynak: kub('VENAPERTA 10000 ANTİ-XA IU/1 ML ENJEKSİYONLUK ÇÖZELTİ (onay 15/05/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/onaylKB10000_22_05_2026.pdf'),
  },

  klopidogrel: {
    name: 'Klopidogrel',
    brand: ['Plavix', 'Planor', 'Pingel', 'Karum'],
    dose: 'Geçirilmiş MI/inme/PAH: 75 mg 1x1. NSTE-AKS: 300 mg (PKG planlanan <75 yaş hastada 600 mg) yükleme, sonra 75 mg 1x1.',
    pediatricDose: 'Pediyatrik kullanım için doz önerisi yoktur',
    form: 'Film kaplı tablet',
    sgkCovered: true,
    sgkRestriction: 'SUT: akut koroner sendrom / stent / PAH endikasyon ve rapor koşullarına bakınız.',
    category: 'P2Y12 (ADP) reseptör antagonisti',
    siniflar: ['Antiagregan', 'P2Y12 inhibitörü', 'Trombosit agregasyon inhibitörü', 'Tienopiridin'],
    contraindications: [
      'Klopidogrele aşırı duyarlılık',
      'Ciddi karaciğer hastalığı',
      'Aktif patolojik kanama (peptik ülser, intrakraniyal hemoraji)',
    ],
    interactions: ['Omeprazol', 'Esomeprazol', 'NSAİİ', 'Varfarin', 'SSRI', 'Antikoagülanlar', 'Rifampisin'],
    etkilesimler: [
      ...KANAMA_ETKILESIM,
      { ile: 'Omeprazol', siddet: 'ciddi', not: 'CYP2C19 inhibisyonu klopidogrelin aktif metabolitini azaltır; antiagregan etki düşer — pantoprazol tercih edilmelidir (KÜB §4.5).' },
      { ile: 'Esomeprazol', siddet: 'ciddi', not: 'CYP2C19 inhibisyonu ile antiagregan etki azalır; kaçınılmalıdır (KÜB §4.5).' },
    ],
    gebelik: { metin: 'Gebelikte tercihen kullanılmaz; veri sınırlıdır.' },
    emzirme: 'Emzirme döneminde önerilmez.',
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Elektif cerrahiden 5–7 gün önce kesilmesi düşünülmelidir (stent öyküsü varsa kardiyolog kararı).',
    kaynak: kub('PLANOR 75 MG FİLM KAPLI TABLET (onay 26/09/2025)', 'https://titck.gov.tr/storage/Archive/2025/kubKtAttachments/Pkub_07_10_2025.pdf'),
  },

  tikagrelor: {
    name: 'Tikagrelor',
    brand: ['Brilinta', 'Talderol', 'Tikagrel'],
    dose: 'AKS: 180 mg yükleme, sonra günde iki kez 90 mg. 1–3 yıl önce MI geçirmiş yüksek riskli hastada uzatılmış tedavide günde iki kez 60 mg. Kontrendike değilse birlikte günde bir kez 75–150 mg ASA kullanılır.',
    pediatricDose: '18 yaş altında güvenlilik ve etkililik belirlenmemiştir',
    form: 'Film kaplı tablet',
    sgkCovered: true,
    sgkRestriction: 'SUT: akut koroner sendrom endikasyon ve rapor koşullarına bakınız.',
    category: 'P2Y12 (ADP) reseptör antagonisti',
    siniflar: ['Antiagregan', 'P2Y12 inhibitörü', 'Trombosit agregasyon inhibitörü'],
    yasKontrendikasyonAy: 216,
    contraindications: [
      'Tikagrelore aşırı duyarlılık',
      'Aktif patolojik kanama',
      'İntrakraniyal hemoraji öyküsü',
      'Ağır karaciğer yetmezliği',
      'Güçlü CYP3A4 inhibitörleriyle (ketokonazol, klaritromisin, nefazodon, ritonavir, atazanavir) birlikte kullanım',
    ],
    interactions: ['Klaritromisin', 'Ketokonazol', 'Ritonavir', 'Rifampisin', 'Simvastatin', 'Digoksin', 'NSAİİ', 'Antikoagülanlar'],
    etkilesimler: [
      ...KANAMA_ETKILESIM,
      { ile: 'Klaritromisin', siddet: 'ciddi', not: 'KONTRENDİKE — güçlü CYP3A4 inhibisyonu tikagrelor maruziyetini belirgin artırır (KÜB §4.3/4.5).' },
      { ile: 'İtrakonazol', siddet: 'ciddi', not: 'KONTRENDİKE — güçlü CYP3A4 inhibitörü (KÜB §4.3).' },
      { ile: 'Simvastatin', siddet: 'ciddi', not: 'Simvastatin maruziyetini artırır; simvastatin dozu 40 mg/gün ile sınırlanmalıdır.' },
      { ile: 'Digoksin', siddet: 'orta', not: 'P-gp inhibisyonu ile digoksin düzeyi yükselebilir.' },
      { ile: 'Asetilsalisilik asit', siddet: 'orta', not: 'Birlikte kullanım endikedir; ancak ASA idame dozu günde 150 mg\'ı aşmamalıdır (yüksek doz etkinliği azaltır).' },
    ],
    gebelik: { metin: 'Gebelikte kullanımı önerilmez.' },
    emzirme: 'Emzirme döneminde önerilmez.',
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Dispne sık görülen ve genellikle geçici bir yan etkidir; hastaya önceden anlatılmalıdır. Elektif cerrahiden 5 gün önce kesilir.',
    kaynak: kub('TALDEROL 60 MG FİLM KAPLI TABLET (onay 12/07/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/Ek2kbtemiz_13_07_2026.pdf'),
  },
}
