/**
 * Kadın hastalıkları ve doğum + vitamin/mineral.
 *
 * The two entries that most need a loud card in Turkish outpatient practice are here:
 *   • kombine oral kontraseptif — VTE riski, 35 yaş üstü sigara, ve enzim indükleyicilerin
 *     (rifampisin, karbamazepin) kontraseptif etkinliği ORTADAN KALDIRMASI;
 *   • misoprostol — gebelikte KONTRENDİKE, uterus kontraksiyonu.
 * Both are modelled with the 'Kombine hormonal kontraseptif' / 'Prostaglandin' class labels so a
 * class-level interaction written on rifampisin or an NSAİİ resolves onto them.
 */
import { kub } from '../kaynak'
import type { TürkishDrug } from '../tipler'

const KOK_SINIF = ['Kombine oral kontraseptif', 'Kombine hormonal kontraseptif', 'KOK', 'Östrojen', 'Progestojen', 'Hormon'] as const

const KOK_ETKILESIM = [
  { ile: 'Rifampisin', siddet: 'ciddi' as const, not: 'Güçlü enzim indüksiyonu kontraseptif etkinliği ORTADAN KALDIRIR; tedavi süresince ve sonrasında 28 gün bariyer yöntem şarttır.' },
  { ile: 'Karbamazepin', siddet: 'ciddi' as const, not: 'Enzim indüksiyonu kontraseptif etkinliği azaltır; alternatif yöntem gerekir.' },
  { ile: 'Topiramat', siddet: 'ciddi' as const, not: 'Yüksek dozda kontraseptif etkinliği azaltabilir; ek korunma önerilir.' },
  { ile: 'Lamotrijin', siddet: 'ciddi' as const, not: 'KOK lamotrijin düzeyini belirgin düşürür; başlarken/bırakırken lamotrijin dozu ayarlanmalıdır.' },
  { ile: 'Antibiyotik', siddet: 'orta' as const, not: 'Geniş spektrumlu antibiyotikler bağırsak florasını etkileyerek emilimi azaltabilir; kür boyunca ek korunma önerilir.' },
] as const

export const KADIN_DOGUM: Record<string, TürkishDrug> = {
  folikAsit: {
    name: 'Folik asit',
    brand: ['Folbiol', 'Folbetake', 'Folacin', 'Folik Asit'],
    dose: 'Folat eksikliği megaloblastik anemi: 4 ay süreyle 5 mg/gün; malabsorbsiyonda 15 mg/gün\'e kadar. Kronik hemolitik durumlarda günde veya haftada 5 mg profilaksi.',
    pediatricDose: '1–18 yaş megaloblastik anemi: 4 ay süreyle 5 mg/gün; idamede her 1–7 günde bir 5 mg',
    pediatrik: {
      min: 5, max: 5, birim: 'mg/kg/gün', gunlukBolum: 1,
      mutlakMaxMgGun: 15, enAzAy: 12,
      metin: 'KÜB §4.2 (sabit doz, mg/kg değil): folat eksikliğine bağlı megaloblastik anemide 1–18 yaş arası çocuklarda 4 ay süreyle günde 5 mg (1 tablet); idame tedavisi için her 1–7 günde bir 5 mg. Küçük çocuklar için daha uygun bir dozaj formu kullanılmalıdır.',
    },
    form: 'Tablet, damla',
    sgkCovered: true,
    category: 'Vitamin (B9)',
    siniflar: ['Vitamin', 'Folat', 'B grubu vitamin', 'Hematinik'],
    contraindications: [
      'Folik aside aşırı duyarlılık',
      'Tedavi edilmemiş kobalamin (B12) eksikliğinde uzun dönem folat tedavisi',
    ],
    interactions: ['Metotreksat', 'Fenitoin', 'Sülfasalazin', 'Trimetoprim'],
    etkilesimler: [
      { ile: 'Fenitoin', siddet: 'orta', not: 'Folik asit fenitoin düzeyini düşürebilir; nöbet kontrolü izlenmelidir.' },
      { ile: 'Sülfasalazin', siddet: 'orta', not: 'Sülfasalazin folat emilimini azaltır; destek tedavisi endikedir.' },
      { ile: 'Metotreksat', siddet: 'orta', not: 'MTX tedavisinde folik asit desteği yan etkileri azaltır; ancak yüksek doz onkolojik MTX\'te zamanlama uzman kararıdır.' },
    ],
    gebelik: { metin: 'Gebelikte ve gebelik planlarken nöral tüp defekti profilaksisi için önerilir; yüksek riskli gebelerde doz farklıdır (hekim kararı).' },
    emzirme: 'Emzirme döneminde güvenle kullanılır.',
    renkliRecete: 'normal',
    notes: 'B12 eksikliği dışlanmadan uzun süreli yüksek doz folat verilmesi kobalamin nöropatisini HIZLANDIRIR (KÜB §4.3). Yaşlıda uzun dönem folat öncesi kobalamin değerlendirilmelidir.',
    kaynak: kub('FOLBETAKE 5 MG TABLET (onay 15/09/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/onaylkbf_9a92db95-91e8-4f10-8a3e-94d5fc225f5d.pdf'),
  },

  demirPolimaltoz: {
    name: 'Demir (III) hidroksit polimaltoz kompleksi',
    brand: ['Ferrum Hausmann', 'Hidrofer', 'Maltofer', 'Ferro Sanol'],
    dose: '>12 yaş ve erişkin — anemisiz demir eksikliği: 50–100 mg/gün. Demir eksikliği anemisi: günde 1–3 defa 100 mg (100–300 mg/gün). Yemek sırasında veya hemen sonra alınır.',
    pediatricDose: '12 yaş ve altındaki çocuklarda damla/şurup formu kullanılmalıdır (bu form önerilmez)',
    form: 'Oral çözelti (flakon), damla, şurup, çiğneme tableti',
    sgkCovered: true,
    category: 'Oral demir preparatı',
    siniflar: ['Demir', 'Hematinik', 'Mineral'],
    contraindications: [
      'Demir polimaltoz kompleksine aşırı duyarlılık',
      'Demir yüklenmesi (hemokromatoz, hemosideroz)',
      'Demir metabolizma bozuklukları (kurşun anemisi, sideroblastik anemi, talasemi)',
      'Demir eksikliğine bağlı olmayan anemiler (hemolitik anemi, B12 eksikliği megaloblastik anemi)',
    ],
    interactions: ['Levotiroksin', 'Tetrasiklinler', 'Kinolonlar', 'Sefdinir', 'Antiasitler', 'Kalsiyum', 'Metildopa'],
    etkilesimler: [
      { ile: 'Levotiroksin', siddet: 'ciddi', not: 'Demir levotiroksin emilimini belirgin azaltır; en az 4 saat arayla alınmalıdır.' },
      { ile: 'Doksisiklin', siddet: 'orta', not: 'Karşılıklı şelasyon; her iki ilacın emilimi azalır — en az 2–3 saat ara.' },
      { ile: 'Kinolon', siddet: 'orta', not: 'Kinolon emilimini belirgin azaltır; kinolon demirden 1–2 saat önce veya 4 saat sonra alınmalı.' },
      { ile: 'Sefdinir', siddet: 'orta', not: 'Sefdinir emilimini %80\'e varan oranda azaltır; 2 saat ara verilmelidir.' },
      { ile: 'Antiasit', siddet: 'orta', not: 'Demir emilimini azaltır; ayrı saatlerde alınmalıdır.' },
      { ile: 'Metildopa', siddet: 'orta', not: 'Metildopa biyoyararlanımını belirgin azaltır.' },
    ],
    gebelik: { metin: 'Gebelikte demir eksikliği anemisinde yaygın olarak kullanılır; gebeliğin ilk trimesterinde hekim kararıyla.' },
    emzirme: 'Emzirme döneminde kullanılabilir.',
    renkliRecete: 'normal',
    notes: 'Dışkıyı siyaha boyar (zararsız, melena ile karıştırılmamalıdır). Polimaltoz kompleksi tuz formlarına göre daha az GİS yan etkisi yapar ancak emilimi de yavaştır.',
    kaynak: kub('HİDROFER 100 MG/5 ML ORAL ÇÖZELTİ (onay 04/06/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/HidroferOralzeltiKB_05_06_2026.pdf'),
  },

  progesteron: {
    name: 'Progesteron',
    brand: ['Progestan', 'Progynex', 'Prolutex', 'Crinone'],
    dose: 'Amenorede çekilme kanaması: tek doz IM 100–150 mg. Diğer endikasyonlarda haftada iki defa veya daha sık 25–100 mg IM. Oral mikronize ve vajinal formlar ayrı dozlanır.',
    pediatricDose: 'Pediyatrik kullanımda etkililik incelenmemiştir',
    form: 'IM enjeksiyonluk çözelti, mikronize yumuşak kapsül (oral/vajinal), vajinal jel',
    sgkCovered: true,
    sgkRestriction: 'SUT: luteal faz desteği / YÜT endikasyon koşullarına bakınız.',
    category: 'Progestojen (doğal progesteron)',
    siniflar: ['Progestojen', 'Hormon', 'Steroid hormon'],
    contraindications: [
      'Progestinlere aşırı duyarlılık',
      'Teşhis edilmemiş vajinal kanama',
      'Gecikmiş veya tamamlanmamış abortus',
      'Meme veya genital sistem karsinomu',
      'Tromboflebit',
      'Serebral hemoraji',
      'Ağır hepatik disfonksiyon',
      'Gebelik için tanısal test olarak kullanım',
    ],
    interactions: ['Rifampisin', 'Karbamazepin', 'Fenitoin', 'Ketokonazol', 'Siklosporin'],
    etkilesimler: [
      { ile: 'Rifampisin', siddet: 'ciddi', not: 'Enzim indüksiyonu progesteron düzeyini belirgin düşürür; etkinlik kaybı.' },
      { ile: 'Karbamazepin', siddet: 'orta', not: 'Progesteron metabolizmasını hızlandırır.' },
      { ile: 'İtrakonazol', siddet: 'orta', not: 'CYP3A4 inhibisyonu progesteron düzeyini yükseltebilir.' },
    ],
    gebelik: { metin: 'Luteal destek ve tehdit altındaki düşük endikasyonlarında gebelikte kullanılır; ancak bu ürünün KÜB\'ü gecikmiş/tamamlanmamış abortusu kontrendikasyon olarak listeler.' },
    emzirme: 'Anne sütüne geçer; emzirme döneminde hekim kararıyla.',
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Oral mikronize form sedasyon yapar — gece alınması önerilir.',
    kaynak: kub('PROGESTAN 25 MG/ML IM ENJEKSİYONLUK ÇÖZELTİ (onay 08/01/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/PROGESTANKBONAY_12_01_2026.pdf'),
  },

  didrogesteron: {
    name: 'Didrogesteron',
    brand: ['Duphaston', 'Didrogest'],
    dose: 'Siklus düzenlenmesi: siklusun 11.–25. günleri arasında günde 1 tablet (10 mg). Endometriozis: siklusun 5.–25. günleri veya tüm siklus boyunca günde 1–3 tablet.',
    pediatricDose: 'İlk adet öncesinde kullanımı yoktur; 12–18 yaş adolesanlarda güvenlilik/etkililik belirlenmemiştir',
    form: 'Film kaplı tablet',
    sgkCovered: true,
    category: 'Progestojen (retroprogesteron)',
    siniflar: ['Progestojen', 'Hormon', 'Steroid hormon'],
    contraindications: [
      'Didrogesterona aşırı duyarlılık',
      'Tanı konmamış vajinal kanama',
      'Ciddi karaciğer bozukluğu veya öyküsü (karaciğer değerleri normale dönene kadar)',
      'Progestojen veya östrojene bağlı tümörler',
    ],
    interactions: ['Rifampisin', 'Karbamazepin', 'Fenitoin', 'Sarı kantaron'],
    etkilesimler: [
      { ile: 'Rifampisin', siddet: 'ciddi', not: 'Güçlü CYP3A4 indüksiyonu didrogesteron etkinliğini azaltır.' },
      { ile: 'Karbamazepin', siddet: 'orta', not: 'Enzim indüksiyonu progestojen düzeyini düşürür.' },
    ],
    gebelik: { metin: 'Luteal destek ve tekrarlayan düşük endikasyonlarında gebelikte kullanılır; ART tedavisinde abortus gelişirse kesilmelidir (KÜB §4.3).' },
    emzirme: 'Anne sütüne geçer; emzirme döneminde önerilmez.',
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    kaynak: kub('DUPHASTON 10 MG FİLM KAPLI TABLET (onay 18/12/2025)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/Dkub_13_01_2026.pdf'),
  },

  drospirenonEtinilestradiol: {
    name: 'Drospirenon + Etinilestradiol',
    brand: ['Yasmin', 'Yaz', 'Drosmax', 'Diane (farklı progestin)'],
    dose: '21 gün boyunca her gün yaklaşık aynı saatte 1 tablet; ardından 7 günlük tablet alınmayan dönem. Tablet alımına hiçbir zaman 7 günden fazla ara verilmez.',
    pediatricDose: 'Yalnızca menarştan sonra endikedir; doz ayarlaması gerektiğini gösteren veri yoktur',
    form: 'Film kaplı tablet',
    sgkCovered: true,
    category: 'Kombine oral kontraseptif',
    siniflar: [...KOK_SINIF, 'Antimineralokortikoid progestin'],
    contraindications: [
      'Venöz tromboembolizm (VTE) varlığı veya öyküsü',
      'VTE için kalıtımsal/kazanılmış yatkınlık (Faktör V Leiden, antitrombin III, protein C veya S eksikliği)',
      'Arteriyel tromboembolizm varlığı veya öyküsü (MI, inme, TİA)',
      'Majör cerrahi ile uzun süreli immobilizasyon',
      'Vasküler tutulumlu diabetes mellitus',
      'Fokal nörolojik semptomlu migren öyküsü',
      'Ciddi hipertansiyon, dislipoproteinemi',
      'Şiddetli karaciğer hastalığı veya karaciğer tümörü',
      'Bilinen/şüpheli seks steroidine bağımlı malignite (meme, endometrium)',
      'Teşhis edilmemiş vajinal kanama',
      'Böbrek yetmezliği (drospirenonun potasyum tutucu etkisi)',
      'Gebelik',
    ],
    interactions: ['Rifampisin', 'Karbamazepin', 'Fenitoin', 'Topiramat', 'Lamotrijin', 'Sarı kantaron', 'ACE inhibitörleri', 'Potasyum tutucu diüretikler', 'NSAİİ'],
    etkilesimler: [
      ...KOK_ETKILESIM,
      { ile: 'ACE inhibitörü', siddet: 'orta', not: 'Drospirenon antimineralokortikoid etkilidir; potasyum tutucu ilaçlarla birlikte hiperkalemi riski — potasyum izlenmelidir.' },
      { ile: 'Spironolakton', siddet: 'ciddi', not: 'İki antimineralokortikoid: hiperkalemi riski artar.' },
      { ile: 'NSAİİ', siddet: 'orta', not: 'Potasyum yükselmesi riski artabilir (özellikle böbrek yetmezliğinde).' },
    ],
    gebelik: { metin: 'Gebelikte KONTRENDİKE; gebelik saptandığında derhal kesilir.' },
    emzirme: 'Süt miktarını ve bileşimini etkileyebilir; emzirme döneminde progestin-only yöntemler tercih edilir.',
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'VTE riski ilk kullanım yılında ve ara verip yeniden başlandığında en yüksektir. 35 yaş üstü sigara içenlerde arteriyel tromboembolizm riski nedeniyle önerilmez (KÜB §4.4).',
    kaynak: kub('DROSMAX 3 MG/30 MCG FİLM KAPLI TABLET (onay 15/05/2025)', 'https://titck.gov.tr/storage/Archive/2025/kubKtAttachments/UYGUNKBDROSMAX_20_05_2025.pdf'),
  },

  levonorgestrelEtinilestradiol: {
    name: 'Levonorgestrel + Etinilestradiol',
    brand: ['Microgynon', 'Miranova', 'Lo-Femenal'],
    dose: 'İlk siklus: menstrüel siklusun ilk günü başlayarak 21 gün boyunca günde 1 tablet; kontraseptif koruma derhal başlar. Sonraki sikluslar 7 günlük aradan sonra aynı günde başlar.',
    pediatricDose: 'Yalnızca menarştan sonra endikedir',
    form: 'Kaplı tablet',
    sgkCovered: true,
    category: 'Kombine oral kontraseptif',
    siniflar: [...KOK_SINIF],
    contraindications: [
      'Venöz tromboembolizm varlığı veya öyküsü (DVT, PE)',
      'APC direnci (Faktör V Leiden), antitrombin III / protein C / protein S eksikliği',
      'Arteriyel tromboembolizm varlığı veya öyküsü',
      'Majör cerrahi ile uzun süreli immobilizasyon',
      'Vasküler tutulumlu diabetes mellitus',
      'Fokal nörolojik semptomlu migren öyküsü',
      'Şiddetli karaciğer hastalığı veya karaciğer tümörü',
      'Seks steroidine bağımlı malignite',
      'Teşhis edilmemiş vajinal kanama',
      'Gebelik',
    ],
    interactions: ['Rifampisin', 'Karbamazepin', 'Fenitoin', 'Topiramat', 'Lamotrijin', 'Sarı kantaron', 'Antibiyotikler'],
    etkilesimler: KOK_ETKILESIM,
    gebelik: { metin: 'Gebelikte KONTRENDİKE; gebelik saptandığında derhal kesilir.' },
    emzirme: 'Süt miktarını azaltabilir; emzirme döneminde progestin-only yöntemler tercih edilir.',
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Levonorgestrel içeren KOK\'lar VTE riski en düşük kombinasyonlardandır. 35 yaş üstü sigara içenlerde önerilmez.',
    kaynak: kub('MİCROGYNON 150 MCG/30 MCG KAPLI TABLET (onay 25/03/2025)', 'https://titck.gov.tr/storage/Archive/2025/kubKtAttachments/MCROGYNONKBSON_02_12_2025.pdf'),
  },

  levonorgestrelAcil: {
    name: 'Levonorgestrel (acil kontrasepsiyon)',
    brand: ['Norlevo', 'Ertes72', 'Escapelle'],
    dose: 'Tek tablet (1,5 mg), korunmasız cinsel temastan sonra 72 saati aşmaksızın, mümkün olduğunca erken (tercihen ilk 12 saat). Alımdan sonraki 3 saat içinde kusma olursa bir tablet daha alınır.',
    pediatricDose: 'Ergenlik öncesi yaştaki çocuklar için uygun kullanım yoktur',
    form: 'Tablet',
    sgkCovered: false,
    category: 'Acil kontraseptif (progestojen)',
    siniflar: ['Progestojen', 'Acil kontraseptif', 'Hormon'],
    contraindications: ['Levonorgestrele aşırı duyarlılık'],
    interactions: ['Rifampisin', 'Karbamazepin', 'Fenitoin', 'Sarı kantaron', 'Ulipristal'],
    etkilesimler: [
      { ile: 'Rifampisin', siddet: 'ciddi', not: 'Enzim indüksiyonu levonorgestrel etkinliğini azaltır; son 4 haftada enzim indükleyici kullanan kadına hormonal olmayan acil kontrasepsiyon (Cu-RİA) önerilmelidir (KÜB §4.2/4.5).' },
      { ile: 'Karbamazepin', siddet: 'ciddi', not: 'Enzim indüksiyonu etkinliği azaltır; hormonal olmayan yöntem önerilir.' },
    ],
    gebelik: { metin: 'Mevcut gebelikte etkisizdir ve endike değildir; ancak yanlışlıkla alındığında fetal zarar bildirilmemiştir.' },
    emzirme: 'Anne sütüne geçer; alımdan sonra 8 saat emzirmeye ara verilmesi önerilebilir.',
    renkliRecete: 'normal',
    notes: 'Düzenli kontrasepsiyon yöntemi DEĞİLDİR. 72 saati aşan durumlarda Cu-RİA veya ulipristal değerlendirilmelidir.',
    kaynak: kub('ERTES72 1,5 MG TABLET (onay 06/06/2024)', 'https://titck.gov.tr/storage/Archive/2024/kubKtAttachments/ERTESKB_723bfea8-4cfe-48d9-86e7-bb9f65e85e79.pdf'),
  },

  klomifen: {
    name: 'Klomifen sitrat',
    brand: ['Klomen', 'Serophene', 'Gonaphene'],
    dose: 'İlk kür: 5 gün süreyle 50 mg/gün (siklusun 5. gününden itibaren). Ovülasyon sağlanamazsa 30 gün sonraki ikinci siklusta 100 mg. Maksimum günlük doz 250 mg.',
    pediatricDose: 'Pediyatrik endikasyonu yoktur',
    form: 'Tablet',
    sgkCovered: true,
    sgkRestriction: 'SUT: infertilite tedavisi endikasyon ve rapor koşullarına bakınız.',
    category: 'Selektif östrojen reseptör modülatörü (ovülasyon indüksiyonu)',
    siniflar: ['SERM', 'Ovülasyon indükleyici', 'Hormon'],
    contraindications: [
      'Gebelik',
      'Karaciğer hastalığı veya karaciğer fonksiyon bozukluğu öyküsü',
      'Hormona bağımlı tümörler',
      'Belirlenmemiş orijinli anormal uterin kanama',
      'Yumurtalık kisti (polikistik over hariç)',
    ],
    interactions: [],
    etkilesimler: [],
    gebelik: { metin: 'Gebelikte KONTRENDİKE (KÜB §4.3).' },
    emzirme: 'Süt üretimini baskılayabilir; emzirme döneminde önerilmez.',
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Her kür öncesi yumurtalık kisti açısından değerlendirme yapılmalıdır. Ovaryan hiperstimülasyon sendromu ve çoğul gebelik riski hastaya anlatılmalıdır.',
    kaynak: kub('KLOMEN 50 MG TABLET (onay 24/01/2018)', 'https://titck.gov.tr/storage/kubKtAttachments/sIy7ZmR0aK1tl.pdf'),
  },

  traneksamikAsit: {
    name: 'Traneksamik asit',
    brand: ['Transamine', 'Traneksan', 'Cyklokapron'],
    dose: 'Lokal fibrinoliz: 15–25 mg/kg (genellikle 2–3 tablet), günde 2–3 kez. Hipermenore: günde 3 kez 1000 mg. GİS kanamada bir hafta süreyle günde 3 kez 1000 mg.',
    pediatricDose: 'Genellikle önerilen doz günde 3–4 kez 25 mg/kg',
    pediatrik: {
      min: 25, max: 25, birim: 'mg/kg/doz', gunlukBolum: 4,
      metin: 'KÜB §4.2: pediyatrik hastalarda sınırlı sayıda çalışma mevcuttur; genellikle önerilen doz günde 3–4 kez 25 mg/kg\'dır.',
    },
    form: 'Film tablet, ampul',
    sgkCovered: true,
    category: 'Antifibrinolitik',
    siniflar: ['Antifibrinolitik', 'Hemostatik'],
    contraindications: [
      'Traneksamik aside aşırı duyarlılık',
      'Edinilmiş renk görme bozukluğu',
      'Subaraknoid hemoraji',
      'Aktif intravasküler pıhtılaşma',
      'Tromboembolik hastalık öyküsü',
      'Şiddetli böbrek yetmezliği',
    ],
    interactions: ['Kombine oral kontraseptifler', 'Antikoagülanlar', 'Faktör IX konsantreleri'],
    etkilesimler: [
      { ile: 'Kombine oral kontraseptif', siddet: 'ciddi', not: 'Tromboembolik risk toplanır; birlikte kullanımda dikkat gerekir.' },
      { ile: 'Antikoagülan', siddet: 'orta', not: 'Antikoagülan alan hastada tromboz/kanama dengesi hekim tarafından değerlendirilmelidir.' },
    ],
    gebelik: { metin: 'Gebelikte gerektiğinde kullanılabilir (postpartum kanamada yaygın); plasentayı geçer.' },
    emzirme: 'Anne sütüne az miktarda geçer.',
    bobrekDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Uzun süreli kullanımda renk görme testi önerilir. Böbrekle atılır — doz kreatinin düzeyine göre azaltılmalıdır.',
    kaynak: kub('TRANSAMİNE 500 MG FİLM TABLET (onay 05/12/2014)', 'https://titck.gov.tr/storage/kubKtAttachments/59993bfa85112.pdf'),
  },

  misoprostol: {
    name: 'Misoprostol',
    brand: ['Cytotec', 'Misodel'],
    dose: 'Peptik ülser / NSAİİ ülseri: 800 mcg/gün, 2–4 doza bölünmüş, öğünlerle ve yatmadan önce; minimum 4 hafta. Obstetrik kullanım (düşük, indüksiyon) ayrı protokollerle ve hastane koşullarında uygulanır.',
    pediatricDose: 'Peptik ülser endikasyonunda pediyatrik kullanım değerlendirilmemiştir',
    form: 'Tablet',
    sgkCovered: true,
    category: 'Prostaglandin E1 analoğu',
    siniflar: ['Prostaglandin', 'Prostaglandin E1 analoğu', 'Gastroprotektif', 'Uterotonik'],
    contraindications: [
      'GEBELİK veya gebe kalmayı planlayan kadınlar (peptik ülser endikasyonunda)',
      'Misoprostol veya prostaglandinlere alerji',
    ],
    interactions: ['NSAİİ', 'Antiasitler', 'Oksitosin'],
    etkilesimler: [
      { ile: 'Antiasit', siddet: 'orta', not: 'Magnezyum içeren antiasitler misoprostolün yaptığı ishali şiddetlendirebilir.' },
      { ile: 'NSAİİ', siddet: 'orta', not: 'NSAİİ ülser profilaksisi için birlikte kullanılır; bu endikasyonda etkileşim değil, kombinasyon amaçlıdır.' },
    ],
    gebelik: { kategori: 'X', metin: 'Peptik ülser endikasyonunda gebelikte KONTRENDİKE — uterus tonusunu ve kontraksiyonlarını artırır, düşüğe ve doğum kusurlarına yol açar (KÜB §4.3). Obstetrik kullanımı ayrı, denetimli bir endikasyondur.' },
    emzirme: 'Anne sütüne geçer; bebekte ishal yapabilir.',
    renkliRecete: 'normal',
    notes: 'Doğurganlık çağındaki kadına peptik ülser endikasyonuyla verilecekse negatif gebelik testi ve etkili kontrasepsiyon şarttır.',
    kaynak: kub('CYTOTEC 200 MCG TABLET (onay 23/08/2011)', 'https://titck.gov.tr/storage/kubKtAttachments/5cce89fd14629.pdf'),
  },

  metilergonovin: {
    name: 'Metilergonovin maleat',
    brand: ['Methergin', 'Metiler'],
    dose: 'Normal yetişkin dozu 1 mL (0,2 mg) IM; gerekirse 2–4 saat arayla en fazla 5 doza kadar tekrarlanabilir. Uterus atonisinde omuz/plasenta gelişinden hemen sonra uygulanır.',
    pediatricDose: 'Pediyatrik hastalarda etkililik ve güvenlilik incelenmemiştir',
    form: 'IM/IV enjeksiyonluk çözelti, tablet',
    sgkCovered: true,
    category: 'Ergot alkaloidi (uterotonik)',
    siniflar: ['Ergot alkaloidi', 'Uterotonik', 'Vazokonstriktör'],
    contraindications: [
      'Hipertansiyon',
      'Toksemi (preeklampsi/eklampsi)',
      'Gebelik',
      'Metilergonovine aşırı duyarlılık',
      'Potent CYP3A4 inhibitörleri ile birlikte kullanım',
    ],
    interactions: ['Klaritromisin', 'Eritromisin', 'İtrakonazol', 'Ritonavir', 'Triptanlar', 'Beta blokörler'],
    etkilesimler: [
      { ile: 'Klaritromisin', siddet: 'ciddi', not: 'KONTRENDİKE — güçlü CYP3A4 inhibisyonu ergot toksisitesi (vazospazm, iskemi) yapar (KÜB §4.3).' },
      { ile: 'Eritromisin', siddet: 'ciddi', not: 'KONTRENDİKE — ergot toksisitesi bildirilmiştir (KÜB §4.3).' },
      { ile: 'İtrakonazol', siddet: 'ciddi', not: 'KONTRENDİKE — güçlü CYP3A4 inhibitörü (KÜB §4.3).' },
      { ile: 'Triptan', siddet: 'ciddi', not: 'Vazospazm riski toplanır; ergot ve triptan arasında en az 24 saat bırakılmalıdır.' },
    ],
    gebelik: { metin: 'Gebelikte KONTRENDİKE — doğum öncesi kullanılmaz; doğum sonrası uterotonik olarak kullanılır (KÜB §4.3).' },
    emzirme: 'Süt üretimini azaltabilir; emzirme döneminde kısa süreli kullanımda hekim kararıyla.',
    renkliRecete: 'normal',
    notes: 'Kan basıncı izlenmelidir — hipertansiyon ve preeklampside kontrendikedir.',
    kaynak: kub('METİLER 0,2 MG/ML IM ENJEKSİYONLUK ÇÖZELTİ (onay 17/06/2025)', 'https://titck.gov.tr/storage/Archive/2025/kubKtAttachments/02kub_30_06_2025.pdf'),
  },

  kolekalsiferol: {
    name: 'Kolekalsiferol (D3 vitamini)',
    brand: ['Devit-3', 'Coledan-D3', 'D-Vi-Tal', 'Dekristol'],
    dose: 'Yenidoğan profilaksisi 400 IU/gün (1 damla). Eksiklik tedavi dozu ve idame dozu yaş grubuna göre KÜB tablosundan belirlenir. Tek seferde 50.000 IU\'den fazla kullanılması önerilmez.',
    pediatricDose: 'Yenidoğan profilaksisi 400 IU/gün (10 mcg/gün); tedavi dozu yaş grubuna göre KÜB tablosundadır',
    pediatrik: {
      min: 400, max: 400, birim: 'IU/gün', gunlukBolum: 1,
      metin: 'KÜB §4.2: 1 damla = 400 IU. Yenidoğanda profilaksi/idame dozu 400 IU/gün (10 mcg/gün). D vitamini eksikliği tedavi dozu, idame dozu ve tolere edilebilen en yüksek doz yaş grubuna göre KÜB tablosunda verilmiştir. Tek seferde 50.000 IU\'den fazla D vitamini kullanılması önerilmez.',
    },
    form: 'Oral damla çözelti, yumuşak kapsül, ampul',
    sgkCovered: true,
    category: 'D vitamini',
    siniflar: ['Vitamin', 'D vitamini', 'Yağda çözünen vitamin'],
    contraindications: [
      'D vitaminine aşırı duyarlılık',
      'Hiperkalsemi ve/veya hiperkalsiüri ile sonuçlanan hastalıklar',
      'Nefrolitiyazis, nefrokalsinozis',
      'D vitamini hipervitaminozu',
      'Şiddetli böbrek yetmezliği',
    ],
    interactions: ['Tiyazid diüretikler', 'Digoksin', 'Kortikosteroidler', 'Fenitoin', 'Karbamazepin', 'Kolestiramin'],
    etkilesimler: [
      { ile: 'Diüretik', siddet: 'orta', not: 'Tiyazid diüretikler idrarla kalsiyum atılımını azaltır; birlikte kullanımda hiperkalsemi riski — kalsiyum izlenmelidir.' },
      { ile: 'Digoksin', siddet: 'ciddi', not: 'D vitaminine bağlı hiperkalsemi dijital toksisitesini ve aritmi riskini artırır.' },
      { ile: 'Kortikosteroid', siddet: 'orta', not: 'D vitamini etkisini azaltır; doz gereksinimi artabilir.' },
      { ile: 'Karbamazepin', siddet: 'orta', not: 'Enzim indüksiyonu D vitamini metabolizmasını hızlandırır; eksiklik gelişebilir.' },
    ],
    gebelik: { metin: 'Gebelikte önerilen dozlarda kullanılır; yüksek dozdan (hiperkalsemi riski) kaçınılmalıdır.' },
    emzirme: 'Emzirme döneminde önerilen dozlarda kullanılır.',
    bobrekDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Türkiye\'de tüm bebeklere ilk günlerden itibaren 400 IU/gün D vitamini profilaksisi verilir (Sağlık Bakanlığı programı). Aşırı doz hiperkalsemi yapar.',
    kaynak: kub('COLEDAN-D3 10.000 IU/ML ORAL DAMLA (onay 30/03/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/TTCKOnaylKBCOLEDAN10000_01_04_2026.pdf'),
  },

  siyanokobalamin: {
    name: 'Siyanokobalamin (B12 vitamini)',
    brand: ['Dodex', 'Vi-Plex B12', 'Bemiks (kombinasyon)'],
    dose: 'Akut nevralji/nevrit: 500–1000 mcg/gün IM, 10 gün. Pernisiyöz anemi ve hiperkrom makrositer anemi: gün aşırı 250–1000 mcg IM, 1–2 hafta; sonra haftada 1 kez 250 mcg.',
    pediatricDose: 'Bu üründe pediyatrik doz verisi bulunmamaktadır',
    form: 'IM enjeksiyonluk çözelti, tablet, damla',
    sgkCovered: true,
    category: 'B12 vitamini',
    siniflar: ['Vitamin', 'B grubu vitamin', 'Kobalamin', 'Hematinik'],
    contraindications: ['B12 vitaminine aşırı duyarlılık', 'Leber hastalığı (herediter optik atrofi)'],
    interactions: ['Metformin', 'Proton pompa inhibitörleri', 'Kolşisin', 'Folik asit'],
    etkilesimler: [
      { ile: 'Metformin', siddet: 'orta', not: 'Uzun süreli metformin B12 emilimini azaltır; düzey periyodik izlenmelidir.' },
      { ile: 'Proton pompa inhibitörü', siddet: 'orta', not: 'Uzun süreli PPİ kullanımı B12 emilimini azaltır.' },
      { ile: 'Folik asit', siddet: 'ciddi', not: 'Tedavi edilmemiş B12 eksikliğinde yüksek doz folat, anemiyi düzeltip nörolojik hasarı MASKELEYEREK ilerletir.' },
    ],
    gebelik: { metin: 'Gebelikte önerilen dozlarda güvenle kullanılır.' },
    emzirme: 'Emzirme döneminde güvenle kullanılır.',
    renkliRecete: 'normal',
    notes: 'Leber hastalığında optik atrofiyi hızlandırabileceği için kontrendikedir (KÜB §4.3).',
    kaynak: kub('Vİ-PLEX B12 1000 MCG I.M. ENJEKSİYONLUK ÇÖZELTİ (onay 20/09/2025)', 'https://titck.gov.tr/storage/Archive/2025/kubKtAttachments/VPLEXKB_23_09_2025.pdf'),
  },

  cinko: {
    name: 'Çinko sülfat',
    brand: ['Zinco', 'Zinplex', 'Zinc'],
    dose: 'Yaşa göre önerilen miktar: 19 yaş üstü 11 mg/gün (tolere edilebilen maksimum 40 mg/gün). Diyare tedavisinde 6 aydan büyük çocuklarda 7 günden uzun ve 20 mg/günden fazla kullanılmaz.',
    pediatricDose: '7–12 ay: 3 mg/gün; 1–3 yaş: 3 mg/gün; 4–8 yaş: 5 mg/gün; 9–13 yaş: 8 mg/gün; 14–18 yaş: 11 mg/gün',
    pediatrik: {
      min: 3, max: 11, birim: 'mg/kg/gün', gunlukBolum: 1,
      mutlakMaxMgGun: 34, enAzAy: 6,
      metin: 'KÜB §4.2 (yaşa göre sabit doz, mg/kg değil): 7–12 ay 3 mg/gün (tolere edilebilen maksimum 5), 1–3 yaş 3 mg/gün (max 7), 4–8 yaş 5 mg/gün (max 12), 9–13 yaş 8 mg/gün (max 23), 14–18 yaş 11 mg/gün (max 34), 19 yaş üstü 11 mg/gün (max 40). Çinko, 6 aydan büyük çocuklarda diyare tedavisinde 7 günden uzun ve 20 mg/günden fazla kullanılmamalıdır. 0–6 ay arası bebeklerde kullanılmaz.',
    },
    form: 'Şurup, tablet, damla',
    sgkCovered: true,
    category: 'Mineral (çinko)',
    siniflar: ['Mineral', 'Eser element', 'Çinko'],
    yasKontrendikasyonAy: 6,
    contraindications: ['Çinko tuzlarına veya ürün bileşenlerine alerji', '0–6 ay arası bebekler'],
    interactions: ['Kinolonlar', 'Tetrasiklinler', 'Demir', 'Kalsiyum', 'Bakır'],
    etkilesimler: [
      { ile: 'Kinolon', siddet: 'orta', not: 'Çinko içeren preparatlar florokinolon emilimini azaltır; en az 2 saat ara verilmelidir.' },
      { ile: 'Doksisiklin', siddet: 'orta', not: 'Şelasyon ile tetrasiklin emilimi azalır; ayrı saatlerde alınmalıdır.' },
      { ile: 'Demir', siddet: 'orta', not: 'Yüksek doz demir çinko emilimini azaltır (ve tersi).' },
    ],
    gebelik: { metin: 'Gebelikte önerilen günlük miktarlarda kullanılır.' },
    emzirme: 'Emzirme döneminde önerilen miktarlarda kullanılır.',
    renkliRecete: 'normal',
    notes: 'Akut çocukluk çağı ishalinde DSÖ/Sağlık Bakanlığı önerisi 10–14 gün çinko desteğidir; bu ürünün KÜB\'ü ise diyare endikasyonunda 7 gün / 20 mg sınırını koyar — endikasyon ve süre hekim kararıdır.',
    kaynak: kub('ZİNCO 15 MG/5 ML ŞURUP (onay 12/02/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/onaylkb_16_02_2026.pdf'),
  },
}
