/**
 * Kardiyovasküler — ADE inhibitörleri, ARB'ler, kalsiyum kanal blokörleri, beta blokörler,
 * diüretikler, digoksin, nitrat, santral etkili antihipertansif.
 *
 * Three class facts do the work here, written once as class labels so they fire without pairwise
 * entries:
 *   • 'Antihipertansif' — NSAİİ'nin antihipertansif etkiyi azaltması her iki taraftan da yakalanır;
 *   • 'RAAS blokeri'    — ADE + ARB + aliskiren ikili blokajı ve hiperkalemi zinciri;
 *   • 'QT uzatan ilaç'  — indapamid/diüretik hipokalemisi ile aritmi riski.
 *
 * `renkliRecete` is 'normal' throughout: none of these molecules is on the TİTCK kontrole tabi
 * (kırmızı/yeşil) list, and a test re-derives that from lib/doktor/receteRengi rather than trusting
 * the field.
 */
import { kub } from '../kaynak'
import type { TürkishDrug } from '../tipler'

const RAAS_SINIF = ['Antihipertansif', 'RAAS blokeri'] as const

const RAAS_ETKILESIM = [
  { ile: 'Potasyum tutucu diüretik', siddet: 'ciddi' as const, not: 'Hiperkalemi riski belirgin artar; serum potasyumu izlenmeli (KÜB §4.5).' },
  { ile: 'Spironolakton', siddet: 'ciddi' as const, not: 'Aldosteron antagonistiyle birlikte hayatı tehdit eden hiperkalemi olabilir; potasyum ve kreatinin takibi zorunlu.' },
  { ile: 'Potasyum', siddet: 'ciddi' as const, not: 'Potasyum tuzu/destekleri serum potasyumunu yükseltir; birlikte kullanım önerilmez (KÜB §4.5).' },
  { ile: 'Trimetoprim', siddet: 'ciddi' as const, not: 'Trimetoprim potasyum atılımını azaltır; RAAS blokeriyle birlikte ciddi hiperkalemi bildirilmiştir (KÜB §4.5).' },
  { ile: 'Lityum', siddet: 'ciddi' as const, not: 'Lityum atılımı azalır, toksisite riski artar; kombinasyon önerilmez, gerekliyse lityum düzeyi izlenmeli (KÜB §4.5).' },
  { ile: 'NSAİİ', siddet: 'ciddi' as const, not: 'Antihipertansif etki azalır; diüretikle üçlü kullanımda akut böbrek yetmezliği ve hiperkalemi riski (KÜB §4.5).' },
  { ile: 'Siklosporin', siddet: 'orta' as const, not: 'Birlikte kullanımda hiperkalemi bildirilmiştir (KÜB §4.5).' },
  { ile: 'Heparin', siddet: 'orta' as const, not: 'Birlikte kullanımda hiperkalemi bildirilmiştir (KÜB §4.5).' },
  { ile: 'RAAS blokeri', siddet: 'ciddi' as const, not: 'İkili RAAS blokajı (ADE + ARB veya aliskiren): hipotansiyon, hiperkalemi ve böbrek fonksiyon bozukluğu sıklığı artar — önerilmez (KÜB §4.5).' },
] as const

const BETABLOKOR_SINIF = ['Beta blokör', 'Antihipertansif', 'Beta-adrenerjik blokör'] as const

const BETABLOKOR_ETKILESIM = [
  { ile: 'Verapamil', siddet: 'ciddi' as const, not: 'Negatif inotrop/kronotrop etkiler toplanır: ağır bradikardi, AV blok ve kalp yetmezliği riski. Birlikte kullanımdan kaçınılmalıdır.' },
  { ile: 'Diltiazem', siddet: 'ciddi' as const, not: 'Bradikardi ve AV iletim bozukluğu riski artar; birlikte kullanımda yakın izlem.' },
  { ile: 'Beta-2 agonist', siddet: 'ciddi' as const, not: 'Beta blokör bronkodilatör etkiyi antagonize eder; astımda non-selektif beta blokör kontrendikedir.' },
  { ile: 'İnsülin', siddet: 'ciddi' as const, not: 'Hipoglisemi belirtilerini (taşikardi, tremor) maskeler ve iyileşmeyi geciktirir; diyabetikte dikkat.' },
  { ile: 'Antidiyabetik', siddet: 'orta' as const, not: 'Hipoglisemi uyarı belirtileri maskelenebilir; kan şekeri izlenmeli.' },
  { ile: 'Klonidin', siddet: 'ciddi' as const, not: 'Klonidin kesilirken rebound hipertansiyon şiddetlenir; önce beta blokör kesilmelidir.' },
  { ile: 'Digoksin', siddet: 'orta' as const, not: 'AV iletim yavaşlaması toplanır; bradikardi ve blok riski.' },
] as const

export const KARDIYOVASKULER: Record<string, TürkishDrug> = {
  ramipril: {
    name: 'Ramipril',
    brand: ['Delix', 'Tritace', 'Ramipril', 'Genprixa', 'Ramace'],
    dose: 'Hipertansiyon: başlangıç 2,5 mg 1x1; idame 2,5–5 mg/gün. İzin verilen maksimum günlük doz 10 mg.',
    pediatricDose: 'Çocuklarda yeterli deneyim yoktur',
    form: 'Tablet, kapsül',
    sgkCovered: true,
    category: 'ACE inhibitörü',
    siniflar: [...RAAS_SINIF, 'ACE inhibitörü', 'ADE inhibitörü'],
    contraindications: [
      'Ramipril veya diğer ACE inhibitörlerine aşırı duyarlılık',
      'Anjiyoödem öyküsü',
      'Gebelik',
      'Bilateral renal arter stenozu',
      'Sakubitril/valsartan ile eş zamanlı kullanım',
      'Diyabet veya böbrek yetmezliğinde aliskiren ile birlikte kullanım',
    ],
    interactions: ['Sakubitril/valsartan', 'Potasyum tutucu diüretikler', 'Potasyum tuzları', 'Lityum', 'NSAİİ', 'mTOR inhibitörleri', 'Vildagliptin', 'Rasekadotril', 'Siklosporin', 'Heparin'],
    etkilesimler: [
      ...RAAS_ETKILESIM,
      { ile: 'Rasekadotril', siddet: 'ciddi', not: 'Nötral endopeptidaz inhibitörüyle birlikte anjiyoödem riski artar (KÜB §4.5).' },
      { ile: 'Vildagliptin', siddet: 'orta', not: 'DPP-4 inhibitörüyle birlikte anjiyoödem riski artabilir; tedaviye başlanırken dikkatli olunmalı (KÜB §4.5).' },
    ],
    gebelik: { metin: 'Gebelikte KONTRENDİKE — 2. ve 3. trimesterde fetal renal yetmezlik, oligohidramnios, kafatası kemikleşme kusuru (KÜB §4.3/4.6). Gebelik planlayan kadında alternatife geçilmeli.' },
    emzirme: 'Emzirme döneminde önerilmez.',
    bobrekDozUyarisi: true,
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'KrKl 20–50 mL/dk ise 1,25 mg/gün ile başlanır. Karaciğer yetmezliğinde en yüksek günlük doz 2,5 mg\'dır (KÜB §4.2). Kuru öksürük sınıf etkisidir.',
    kaynak: kub('GENPRİXA 2,5 MG TABLET (onay 19/06/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/25uygunkb_30_07_2026.pdf'),
  },

  perindopril: {
    name: 'Perindopril',
    brand: ['Coversyl', 'Serperil', 'Preterax (kombinasyon)', 'Perindo'],
    dose: 'Hipertansiyon: sabah tek doz 4 mg; idamede 8 mg/gün\'e çıkılabilir. Yemeklerden önce alınır.',
    pediatricDose: '18 yaş altında etkililik ve güvenlilik belirlenmemiştir, kullanımı önerilmez',
    form: 'Tablet',
    sgkCovered: true,
    category: 'ACE inhibitörü',
    siniflar: [...RAAS_SINIF, 'ACE inhibitörü', 'ADE inhibitörü'],
    yasKontrendikasyonAy: 216,
    contraindications: [
      'Perindopril veya diğer ACE inhibitörlerine aşırı duyarlılık',
      'Anjiyoödem öyküsü',
      'Gebelik',
      'Sakubitril/valsartan ile eş zamanlı kullanım',
      'Diyabet veya böbrek yetmezliğinde aliskiren ile birlikte kullanım',
    ],
    interactions: ['Sakubitril/valsartan', 'Potasyum tutucu diüretikler', 'Lityum', 'NSAİİ', 'Diüretikler', 'Siklosporin', 'Heparin'],
    etkilesimler: [
      ...RAAS_ETKILESIM,
      { ile: 'Diüretik', siddet: 'orta', not: 'Tedavinin başında semptomatik hipotansiyon riski artar; düşük dozla başlanmalı ve böbrek fonksiyonu ilk haftalarda izlenmelidir (KÜB §4.4/4.5).' },
    ],
    gebelik: { metin: 'Gebelikte KONTRENDİKE (KÜB §4.3/4.6).' },
    emzirme: 'Emzirme döneminde önerilmez.',
    bobrekDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Böbrek yetmezliğinde doz kreatinin klerensine göre ayarlanır: KrKl 30–60 → 2 mg/gün; 15–30 → iki günde bir 2 mg (KÜB §4.2).',
    kaynak: kub('SERPERİL 2 MG TABLET (onay 01/09/2025)', 'https://titck.gov.tr/storage/Archive/2025/kubKtAttachments/SERPERL2mgtabletkub_02_09_2025.pdf'),
  },

  enalapril: {
    name: 'Enalapril',
    brand: ['Enapril', 'Konveril', 'Zalepril', 'Renitec'],
    dose: 'Hipertansiyon: günde 1 defa, kahvaltıdan en az 15 dakika önce. Doz hastaya göre titre edilir.',
    pediatricDose: 'Pediyatrik hipertansiyon endikasyonu yoktur (bu üründe)',
    form: 'Film kaplı tablet',
    sgkCovered: true,
    category: 'ACE inhibitörü',
    siniflar: [...RAAS_SINIF, 'ACE inhibitörü', 'ADE inhibitörü'],
    contraindications: [
      'Enalapril veya ACE inhibitörlerine aşırı duyarlılık',
      'Anjiyoödem öyküsü',
      'Gebelik',
      'Şiddetli böbrek yetmezliği (KrKl <30 mL/dk) veya hemodiyaliz',
      'Şiddetli karaciğer yetmezliği',
      'Sakubitril/valsartan ile eş zamanlı kullanım',
      'Greyfurt / greyfurt suyu',
    ],
    interactions: ['Sakubitril/valsartan', 'Potasyum tutucu diüretikler', 'Lityum', 'NSAİİ', 'Siklosporin', 'Heparin', 'mTOR inhibitörleri', 'Vildagliptin', 'Rasekadotril'],
    etkilesimler: RAAS_ETKILESIM,
    gebelik: { metin: 'Gebelikte KONTRENDİKE (KÜB §4.3/4.6).' },
    emzirme: 'Emzirme döneminde önerilmez.',
    bobrekDozUyarisi: true,
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    kaynak: kub('ZALEPRİL 20 MG/20 MG FİLM KAPLI TABLET (onay 29/01/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/ZALEPRLKB_19_02_2026.pdf'),
  },

  lizinopril: {
    name: 'Lizinopril',
    brand: ['Zestril', 'Sinopryl', 'Rilace', 'Lizinopril'],
    dose: 'Hipertansiyon: başlangıç 10 mg 1x1; kan basıncı kontrol edilene kadar günde maksimum 40 mg\'a kadar titre edilir.',
    pediatricDose: '6 yaş üzeri hipertansif çocukta sınırlı deneyim: 20–<50 kg günlük maksimum 20 mg, ≥50 kg günlük maksimum 40 mg',
    pediatrik: {
      min: 20, max: 40, birim: 'mg/kg/gün', gunlukBolum: 1,
      mutlakMaxMgGun: 40, enAzAy: 72,
      metin: 'KÜB §4.2 (kiloya göre sabit tavan, mg/kg değil): 6 yaş üzeri hipertansif çocukta dozaj bireysel olarak, 20–<50 kg hastalarda günlük maksimum 20 mg\'a ve ≥50 kg hastalarda günlük maksimum 40 mg\'a ayarlanır. Diğer endikasyonlarda deneyim yoktur.',
    },
    form: 'Tablet',
    sgkCovered: true,
    category: 'ACE inhibitörü',
    siniflar: [...RAAS_SINIF, 'ACE inhibitörü', 'ADE inhibitörü'],
    contraindications: [
      'Lizinopril veya ACE inhibitörlerine aşırı duyarlılık',
      'Anjiyoödem öyküsü',
      'Gebelik',
      'Sakubitril/valsartan ile eş zamanlı kullanım',
      'Diyabet veya böbrek yetmezliğinde aliskiren ile birlikte kullanım',
    ],
    interactions: ['Sakubitril/valsartan', 'Potasyum tutucu diüretikler', 'Lityum', 'NSAİİ', 'Trimetoprim + sülfametoksazol', 'Siklosporin', 'Heparin', 'mTOR inhibitörleri'],
    etkilesimler: RAAS_ETKILESIM,
    gebelik: { metin: 'Gebelikte KONTRENDİKE (KÜB §4.3/4.6).' },
    emzirme: 'Emzirme döneminde önerilmez.',
    bobrekDozUyarisi: true,
    renkliRecete: 'normal',
    kaynak: kub('SİNOPRYL 5 MG TABLET (onay 05/04/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/SNOPRYLEkek3kubtemiz_13_05_2026.pdf'),
  },

  valsartan: {
    name: 'Valsartan',
    brand: ['Diovan', 'Valcor', 'Valsart', 'Co-Diovan (kombinasyon)'],
    dose: 'Hipertansiyon: günde 1 defa 80 mg veya 160 mg; yeterli kontrol yoksa 320 mg\'a yükseltilir veya diüretik eklenir.',
    pediatricDose: '6–18 yaş: <35 kg 40 mg/gün; ≥35 kg 80 mg/gün',
    pediatrik: {
      min: 40, max: 80, birim: 'mg/kg/gün', gunlukBolum: 1,
      mutlakMaxMgGun: 80, enAzAy: 72,
      metin: 'KÜB §4.2 (kiloya göre sabit doz, mg/kg değil): 6–18 yaş pediyatrik hipertansiyonda 35 kg\'dan hafif çocuklarda başlangıç günde bir kez 40 mg, 35 kg ve üzerinde günde bir kez 80 mg. Doz kan basıncı yanıtına göre ayarlanır.',
    },
    form: 'Film kaplı tablet',
    sgkCovered: true,
    category: 'Anjiyotensin II reseptör blokeri (ARB)',
    siniflar: [...RAAS_SINIF, 'Anjiyotensin II reseptör blokeri', 'ARB', 'Sartan'],
    contraindications: [
      'Valsartana aşırı duyarlılık',
      'Şiddetli karaciğer yetmezliği, biliyer siroz, kolestaz',
      'Gebelik',
      'Diyabet veya böbrek yetmezliğinde aliskiren ile birlikte kullanım',
    ],
    interactions: ['Potasyum tutucu diüretikler', 'Potasyum tuzları', 'Lityum', 'NSAİİ', 'Aliskiren', 'ACE inhibitörleri'],
    etkilesimler: RAAS_ETKILESIM,
    gebelik: { metin: 'Gebelikte KONTRENDİKE — fetotoksisite (renal yetmezlik, oligohidramnios, kafatası kemikleşme kusuru) (KÜB §4.3/4.6).' },
    emzirme: 'Emzirme döneminde önerilmez.',
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Kolestazın eşlik etmediği hafif-orta karaciğer yetersizliğinde doz 80 mg\'ı aşmamalıdır (KÜB §4.2).',
    kaynak: kub('VALCOR 320 MG FİLM KAPLI TABLET (onay 02/05/2025)', 'https://titck.gov.tr/storage/Archive/2025/kubKtAttachments/UYGUNKBVALCOR320mg_05_05_2025.pdf'),
  },

  losartan: {
    name: 'Losartan',
    brand: ['Cozaar', 'Loxibin', 'Sarilen', 'Hyzaar (kombinasyon)'],
    dose: 'Hipertansiyon: başlangıç ve idame günde bir defa 50 mg; bazı hastalarda 100 mg (sabah). Maksimum etki 3–6 haftada.',
    pediatricDose: 'Çocuk ve ergenlerde veri sınırlıdır',
    form: 'Film kaplı tablet',
    sgkCovered: true,
    category: 'Anjiyotensin II reseptör blokeri (ARB)',
    siniflar: [...RAAS_SINIF, 'Anjiyotensin II reseptör blokeri', 'ARB', 'Sartan'],
    contraindications: [
      'Losartana aşırı duyarlılık',
      'Gebelik',
      'Ciddi karaciğer fonksiyon bozukluğu',
      'Diyabet veya böbrek yetmezliğinde aliskiren ile birlikte kullanım',
    ],
    interactions: ['Potasyum tutucu diüretikler', 'Lityum', 'NSAİİ', 'Flukonazol', 'Rifampisin', 'Greyfurt suyu', 'Aliskiren'],
    etkilesimler: [
      ...RAAS_ETKILESIM,
      { ile: 'Flukonazol', siddet: 'orta', not: 'CYP2C9 inhibisyonu losartanın aktif metabolitine maruziyeti ~%50 azaltır, antihipertansif etki düşer (KÜB §4.5).' },
      { ile: 'Rifampisin', siddet: 'orta', not: 'Enzim indüksiyonu aktif metabolit düzeyini düşürür.' },
    ],
    gebelik: { metin: 'Gebelikte KONTRENDİKE (KÜB §4.3/4.6).' },
    emzirme: 'Emzirme döneminde önerilmez.',
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Greyfurt suyu aktif metabolit oluşumunu azaltarak etkiyi düşürebilir (KÜB §4.5). Ürikozürik etkisi vardır — hiperürisemide tercih edilebilir.',
    kaynak: kub('LOXİBİN 50 MG FİLM KAPLI TABLET (onay 23/01/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/kubtemiz_02_02_2026.pdf'),
  },

  telmisartan: {
    name: 'Telmisartan',
    brand: ['Micardis', 'Tenvia', 'Telmis', 'Pritor'],
    dose: 'Hipertansiyon: 40–80 mg 1x1. Hafif-orta karaciğer yetmezliğinde günde 40 mg aşılmamalıdır.',
    pediatricDose: '18 yaş altında etkililik ve güvenlilik belirlenmemiştir, önerilmez',
    form: 'Tablet (tek başına ve hidroklorotiyazid kombinasyonu)',
    sgkCovered: true,
    category: 'Anjiyotensin II reseptör blokeri (ARB)',
    siniflar: [...RAAS_SINIF, 'Anjiyotensin II reseptör blokeri', 'ARB', 'Sartan'],
    yasKontrendikasyonAy: 216,
    contraindications: [
      'Telmisartana aşırı duyarlılık',
      'Gebelik',
      'Kolestaz ve biliyer obstrüktif hastalıklar',
      'Şiddetli karaciğer yetmezliği',
      'Diyabet veya böbrek yetmezliğinde aliskiren ile birlikte kullanım',
      '18 yaş altı',
    ],
    interactions: ['Lityum', 'Potasyum tutucu diüretikler', 'NSAİİ', 'Ramipril', 'Digoksin', 'Aliskiren'],
    etkilesimler: [
      ...RAAS_ETKILESIM,
      { ile: 'Digoksin', siddet: 'orta', not: 'Telmisartan digoksin plazma düzeyini yükseltebilir; düzey izlenmelidir.' },
    ],
    gebelik: { metin: 'Gebelikte KONTRENDİKE (KÜB §4.3/4.6).' },
    emzirme: 'Emzirme döneminde önerilmez.',
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Kaynak, telmisartan + hidroklorotiyazid sabit kombinasyonunun KÜB\'üdür; telmisartan bileşenine ilişkin ifadeler oradan alınmıştır.',
    kaynak: kub('TENVİA PLUS 80 MG/12,5 MG TABLET — telmisartan bileşeni (onay 10/08/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/Ekek31311kubtemizkopya_21_08_2026.pdf'),
  },

  irbesartan: {
    name: 'İrbesartan',
    brand: ['Aprovel', 'Rebevea', 'Irbes', 'Karvea'],
    dose: 'Hipertansiyon: başlangıç ve idame 150 mg 1x1; yeterli kontrol yoksa 300 mg. Hemodiyaliz ve >75 yaşta 75 mg ile başlanması düşünülür.',
    pediatricDose: 'Çocuk ve adolesanlarda kullanılması tavsiye edilmemektedir',
    form: 'Film tablet',
    sgkCovered: true,
    category: 'Anjiyotensin II reseptör blokeri (ARB)',
    siniflar: [...RAAS_SINIF, 'Anjiyotensin II reseptör blokeri', 'ARB', 'Sartan'],
    contraindications: [
      'İrbesartana aşırı duyarlılık',
      'Gebelik',
      'Diyabet veya böbrek yetmezliğinde (GFR <60) aliskiren ile birlikte kullanım',
    ],
    interactions: ['Aliskiren', 'ACE inhibitörleri', 'Potasyum tuzları', 'Potasyum tutucu diüretikler', 'Lityum', 'NSAİİ', 'Heparin'],
    etkilesimler: RAAS_ETKILESIM,
    gebelik: { metin: 'Gebelikte KONTRENDİKE (KÜB §4.3/4.6).' },
    emzirme: 'Emzirme döneminde önerilmez.',
    renkliRecete: 'normal',
    notes: 'Böbrek yetmezliğinde doz ayarı gerekmez; hemodiyaliz hastasında 75 mg ile başlanır (KÜB §4.2).',
    kaynak: kub('REBEVEA 300 MG FİLM TABLET (onay 17/01/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/rebevea300yaynlanacakkb_30_01_2026.pdf'),
  },

  amlodipin: {
    name: 'Amlodipin',
    brand: ['Norvasc', 'Amlodis', 'Amlovas', 'Tenox', 'Vasocard'],
    dose: 'Hipertansiyon ve anjina: başlangıç 5 mg 1x1; yanıta göre maksimum 10 mg 1x1.',
    pediatricDose: '6–17 yaş: başlangıç 2,5–5 mg 1x1; 4 hafta sonra gerekirse 5 mg. 5 mg üzeri dozlar çocuklarda incelenmemiştir',
    pediatrik: {
      min: 2.5, max: 5, birim: 'mg/kg/gün', gunlukBolum: 1,
      mutlakMaxMgGun: 5, enAzAy: 72,
      metin: 'KÜB §4.2 (sabit doz, mg/kg değil): 6–17 yaş pediyatrik hipertansif hastalarda önerilen başlangıç dozu günde bir kez 2,5–5 mg. Dört hafta sonra hedefe ulaşılamazsa günde 5 mg\'a çıkarılabilir; günde 5 mg\'ın üzerindeki dozlar pediyatrik hastalarda incelenmemiştir. 6 yaşın altında kan basıncı üzerine etkisi bilinmemektedir.',
    },
    form: 'Tablet',
    sgkCovered: true,
    category: 'Kalsiyum kanal blokörü (dihidropiridin)',
    siniflar: ['Kalsiyum kanal blokörü', 'Dihidropiridin', 'Antihipertansif', 'Antianjinal'],
    contraindications: [
      'Dihidropiridin türevlerine veya amlodipine hassasiyet',
      'Şiddetli hipotansiyon',
      'Şok (kardiyojenik şok dahil)',
      'Sol ventrikül çıkış obstrüksiyonu (yüksek dereceli aort stenozu)',
      'Miyokard infarktüsü sonrası hemodinamik olarak stabil olmayan kalp yetmezliği',
      'Kararsız anjina (Prinzmetal hariç)',
    ],
    interactions: ['Güçlü CYP3A4 inhibitörleri', 'Rifampisin', 'Simvastatin', 'Siklosporin', 'Takrolimus', 'Dantrolen', 'Greyfurt suyu'],
    etkilesimler: [
      { ile: 'İtrakonazol', siddet: 'ciddi', not: 'Güçlü CYP3A4 inhibitörü amlodipin plazma düzeyini belirgin yükseltir; hipotansiyon riski (KÜB §4.5).' },
      { ile: 'Klaritromisin', siddet: 'ciddi', not: 'CYP3A4 inhibisyonu ile amlodipin maruziyeti artar, hipotansiyon riski (KÜB §4.5).' },
      { ile: 'Rifampisin', siddet: 'orta', not: 'CYP3A4 indüksiyonu amlodipinin kan basıncı düşürücü etkisini azaltabilir (KÜB §4.5).' },
      { ile: 'Simvastatin', siddet: 'ciddi', not: 'Simvastatin maruziyeti artar; miyopati riski nedeniyle simvastatin dozu 20 mg/gün ile sınırlanmalıdır (KÜB §4.5).' },
      { ile: 'Siklosporin', siddet: 'ciddi', not: 'Siklosporin kan düzeyi yükselir; düzey izlenmeli ve gerekirse doz düşürülmeli (KÜB §4.5).' },
      { ile: 'Takrolimus', siddet: 'ciddi', not: 'Takrolimus kan seviyesinde artma riski vardır (KÜB §4.5).' },
      { ile: 'Antihipertansif', siddet: 'orta', not: 'Kan basıncı düşürücü etkiler toplanır (KÜB §4.5).' },
    ],
    gebelik: { kategori: 'C', metin: 'İnsanda güvenlilik saptanmamıştır; ancak daha güvenli alternatif yoksa ve hastalığın kendisi daha büyük risk taşıyorsa önerilebilir (KÜB §4.6).' },
    emzirme: 'Anne sütüne geçer (maternal dozun ~%3–7\'si); karar yarar/risk değerlendirmesiyle verilir.',
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Ayak bileği ödemi en sık yan etkidir, doza bağımlıdır. Böbrek yetmezliğinde normal dozda kullanılabilir, diyalize edilemez.',
    kaynak: kub('AMLODİS 10 MG TABLET (onay 28/11/2025)', 'https://titck.gov.tr/storage/Archive/2025/kubKtAttachments/amlodis10mgek3kub_12_12_2025.pdf'),
  },

  lerkanidipin: {
    name: 'Lerkanidipin',
    brand: ['Lercadip', 'Lernipin', 'Zanidip', 'Lerdip'],
    dose: 'Yemeklerden en az 15 dakika önce 10 mg 1x1; yanıta göre 20 mg\'a çıkarılabilir (dikkatle). Maksimal etki ~2 hafta.',
    pediatricDose: '18 yaş altında güvenlilik ve etkililik belirlenmemiştir',
    form: 'Film kaplı tablet',
    sgkCovered: true,
    category: 'Kalsiyum kanal blokörü (dihidropiridin)',
    siniflar: ['Kalsiyum kanal blokörü', 'Dihidropiridin', 'Antihipertansif'],
    yasKontrendikasyonAy: 216,
    contraindications: [
      'Lerkanidipine aşırı duyarlılık',
      'Sol ventrikül çıkış yolu tıkanması',
      'Tedavi edilmemiş konjestif kalp yetmezliği',
      'Stabil olmayan anjina pektoris veya son bir ay içinde miyokard enfarktüsü',
      'Şiddetli karaciğer yetmezliği',
      'Şiddetli böbrek yetmezliği (GFR <30 mL/dk) ve diyaliz',
      'Güçlü CYP3A4 inhibitörleri ile birlikte kullanım',
      'Siklosporin ile birlikte kullanım',
      'Greyfurt veya greyfurt suyu',
    ],
    interactions: ['Güçlü CYP3A4 inhibitörleri', 'Siklosporin', 'Greyfurt suyu', 'Beta blokörler', 'Diüretikler', 'ACE inhibitörleri'],
    etkilesimler: [
      { ile: 'İtrakonazol', siddet: 'ciddi', not: 'KONTRENDİKE — güçlü CYP3A4 inhibitörü lerkanidipin maruziyetini belirgin artırır (KÜB §4.3/4.5).' },
      { ile: 'Klaritromisin', siddet: 'ciddi', not: 'KONTRENDİKE — güçlü CYP3A4 inhibitörü (KÜB §4.3/4.5).' },
      { ile: 'Siklosporin', siddet: 'ciddi', not: 'KONTRENDİKE — karşılıklı plazma düzeyi artışı (KÜB §4.3/4.5).' },
      { ile: 'Antihipertansif', siddet: 'orta', not: 'Kan basıncı düşürücü etkiler toplanır.' },
    ],
    gebelik: { metin: 'Gebelikte kullanımı önerilmez; yeterli veri yoktur (KÜB §4.6).' },
    emzirme: 'Emzirme döneminde önerilmez.',
    bobrekDozUyarisi: true,
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Amlodipine göre daha az ayak bileği ödemi yapar; yemekten önce alınması emilim için önemlidir.',
    kaynak: kub('LERNİPİN 20 MG FİLM KAPLI TABLET (onay 24/02/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/1311kub_27_03_2026.pdf'),
  },

  nifedipin: {
    name: 'Nifedipin',
    brand: ['Adalat', 'Nidilat', 'Nidicard', 'Nifelat'],
    dose: 'Başlangıç 8 saat ara ile 5 mg; yanıta göre 8 saat ara ile 20 mg\'a titre edilir. Maksimum günlük doz 60 mg.',
    pediatricDose: '18 yaş altında güvenlilik ve etkililik saptanmamıştır',
    form: 'Yumuşak kapsül, kontrollü salım tablet',
    sgkCovered: true,
    category: 'Kalsiyum kanal blokörü (dihidropiridin)',
    siniflar: ['Kalsiyum kanal blokörü', 'Dihidropiridin', 'Antihipertansif', 'Tokolitik'],
    yasKontrendikasyonAy: 216,
    contraindications: [
      'Nifedipin veya diğer dihidropiridinlere aşırı duyarlılık',
      'Kardiyojenik şok',
      'Klinik açıdan anlamlı aort stenozu',
      'Stabil olmayan anjina pektoris',
      'Miyokard enfarktüsü sırasında veya sonraki bir ay içinde',
      'Akut anjina atağı tedavisi',
      'Miyokard enfarktüsünde sekonder koruma',
    ],
    interactions: ['Güçlü CYP3A4 inhibitörleri', 'CYP3A4 indükleyicileri', 'Rifampisin', 'Greyfurt suyu', 'Beta blokörler', 'Digoksin'],
    etkilesimler: [
      { ile: 'Rifampisin', siddet: 'ciddi', not: 'Güçlü CYP3A4 indüksiyonu nifedipin etkinliğini ortadan kaldırabilir; birlikte kullanımda doz ayarı ya da ilaç değişikliği gerekir (KÜB §4.2/4.5).' },
      { ile: 'İtrakonazol', siddet: 'ciddi', not: 'CYP3A4 inhibisyonu ile nifedipin düzeyi yükselir, hipotansiyon riski.' },
      { ile: 'Digoksin', siddet: 'orta', not: 'Digoksin plazma düzeyi yükselebilir.' },
      { ile: 'Antihipertansif', siddet: 'orta', not: 'Kan basıncı düşürücü etkiler toplanır.' },
    ],
    gebelik: { metin: 'Gebede kullanımı ancak kesin endikasyonla (örn. preeklampside kan basıncı kontrolü, tokoliz) ve uzman kararıyla düşünülür; ürün KÜB\'ünde gebelik için genel kullanım önerisi yoktur.' },
    emzirme: 'Anne sütüne geçer; kısa süreli kullanımda genellikle uyumlu kabul edilir.',
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Kısa etkili formun hipertansif acilde dil altı kullanımı TERK EDİLMİŞTİR — refleks taşikardi ve iskemi yapar.',
    kaynak: kub('NİDİCARD 10 MG YUMUŞAK KAPSÜL (onay 30/10/2017)', 'https://titck.gov.tr/storage/kubKtAttachments/mZiB2ATVm9DPa.pdf'),
  },

  metoprolol: {
    name: 'Metoprolol',
    brand: ['Beloc', 'Beloc-Zok', 'Problok', 'Lopresor', 'Metoprolol'],
    dose: 'Hipertansiyon: 100–200 mg/gün (sabah tek doz veya ikiye bölünmüş). Anjina: 100–200 mg/gün, gerekirse 400 mg\'a kadar. Taşiaritmi: 100–150 mg/gün, 2–3 doza bölünmüş.',
    pediatricDose: 'Metoprolol tartaratın pediyatrik güvenliliği ve etkililiği kanıtlanmamıştır',
    form: 'Film kaplı tablet, kontrollü salım tablet, IV ampul',
    sgkCovered: true,
    category: 'Beta-1 selektif blokör',
    siniflar: [...BETABLOKOR_SINIF, 'Kardiyoselektif beta blokör'],
    contraindications: [
      'Kardiyojenik şok',
      'Hasta sinüs sendromu (kalıcı kalp pili yoksa)',
      'İkinci veya üçüncü derece AV blok',
      'Dekompanse kalp yetmezliği',
      'Semptomatik bradikardi veya hipotansiyon',
      'Şiddetli bronşiyal astım veya şiddetli bronkospazm öyküsü',
      'Metabolik asidoz',
      'Tedavi edilmemiş feokromositoma',
      'Gangren tehlikesi olan şiddetli periferik vasküler hastalık',
    ],
    interactions: ['Verapamil', 'Diltiazem', 'Klonidin', 'İnsülin', 'Salbutamol', 'Digoksin', 'NSAİİ', 'Terbinafin', 'Fluoksetin', 'Paroksetin'],
    etkilesimler: [
      ...BETABLOKOR_ETKILESIM,
      { ile: 'Terbinafin', siddet: 'ciddi', not: 'CYP2D6 inhibisyonu metoprolol düzeyini yükseltir; bradikardi ve hipotansiyon riski.' },
      { ile: 'Paroksetin', siddet: 'ciddi', not: 'Güçlü CYP2D6 inhibitörü metoprolol maruziyetini belirgin artırır.' },
      { ile: 'NSAİİ', siddet: 'orta', not: 'Beta blokörün antihipertansif etkisi azalır.' },
    ],
    gebelik: { metin: 'Gebelikte yalnızca kesin gereklilikte; fetal bradikardi ve intrauterin gelişme geriliği bildirilmiştir. Doğuma yakın kesilmesi düşünülmelidir.' },
    emzirme: 'Anne sütüne geçer; terapötik dozlarda genellikle uyumlu kabul edilir.',
    renkliRecete: 'normal',
    notes: 'Ani kesilmesi anjinayı ve miyokard infarktüsü riskini artırır — 1–2 haftada kademeli azaltılmalıdır.',
    kaynak: kub('PROBLOK 100 MG FİLM KAPLI TABLET (onay 27/10/2025)', 'https://titck.gov.tr/storage/Archive/2025/kubKtAttachments/problokkb_19_11_2025.pdf'),
  },

  bisoprolol: {
    name: 'Bisoprolol',
    brand: ['Concor', 'Kardoritm', 'Bisobeta', 'Bisoblok'],
    dose: 'Hipertansiyon/anjina: günde bir kez 5 mg; gerekirse 10 mg. Önerilen maksimum 20 mg/gün. Kalp yetersizliğinde 1,25 mg ile başlanıp titre edilir (maksimum 10 mg/gün).',
    pediatricDose: 'Çocuklarda kullanım deneyimi yoktur',
    form: 'Film kaplı tablet',
    sgkCovered: true,
    category: 'Beta-1 selektif blokör',
    siniflar: [...BETABLOKOR_SINIF, 'Kardiyoselektif beta blokör'],
    contraindications: [
      'Bisoprolole aşırı duyarlılık',
      'Akut veya dekompanse kalp yetersizliği',
      'Kardiyojenik şok',
      'İkinci veya üçüncü derece AV blok (kalp pili yoksa)',
      'Hasta sinüs sendromu, sinoatriyal blok',
      'Semptomatik bradikardi veya hipotansiyon',
      'Şiddetli bronşiyal astım veya şiddetli KOAH',
      'Raynaud sendromunun ağır formları, şiddetli oklüzif periferik arter hastalığı',
      'Tedavi edilmemiş feokromositoma',
      'Metabolik asidoz',
    ],
    interactions: ['Verapamil', 'Diltiazem', 'Klonidin', 'İnsülin', 'Antidiyabetikler', 'Sınıf I antiaritmikler', 'Digoksin', 'NSAİİ'],
    etkilesimler: BETABLOKOR_ETKILESIM,
    gebelik: { metin: 'Gebelikte yalnızca kesin gereklilikte; fetal bradikardi ve hipoglisemi riski nedeniyle doğumdan 2–3 gün önce kesilmesi düşünülmelidir.' },
    emzirme: 'Anne sütüne geçişi hakkında veri sınırlıdır; emzirme döneminde önerilmez.',
    renkliRecete: 'normal',
    notes: 'Kalp yetersizliğinde başlangıç ve titrasyon yakın klinik gözetim altında yapılmalıdır (KÜB §4.2).',
    kaynak: kub('KARDORİTM 10 MG FİLM KAPLI TABLET (onay 15/05/2025)', 'https://titck.gov.tr/storage/Archive/2025/kubKtAttachments/Kardoritm10KB_16_05_2025.pdf'),
  },

  karvedilol: {
    name: 'Karvedilol',
    brand: ['Dilatrend', 'Carvexal', 'Calbicor', 'Karvidil'],
    dose: 'Esansiyel hipertansiyon: ilk 2 gün 12,5 mg 1x1, sonra 25 mg 1x1; gerekirse en az 2 hafta arayla maksimum 50 mg/gün. Kalp yetmezliğinde 3,125 mg 2x1 ile başlanıp titre edilir.',
    pediatricDose: 'Pediyatrik kullanım için yeterli veri yoktur',
    form: 'Tablet',
    sgkCovered: true,
    category: 'Non-selektif beta blokör + alfa-1 blokör',
    siniflar: [...BETABLOKOR_SINIF, 'Non-selektif beta blokör', 'Alfa blokör'],
    contraindications: [
      'Karvedilole aşırı duyarlılık',
      'Stabil olmayan/dekompanse kalp yetmezliği',
      'Klinik olarak belirgin karaciğer disfonksiyonu',
      'İkinci ve üçüncü derece AV blok (kalıcı pacemaker yoksa)',
      'Ağır bradikardi (<50/dk)',
      'Hasta sinüs sendromu (sinoatriyal blok dahil)',
      'Ağır hipotansiyon (sistolik <85 mmHg)',
      'Kardiyojenik şok',
      'Bronkospazm veya astım öyküsü',
      'Metabolik asidoz',
    ],
    interactions: ['Verapamil', 'Diltiazem', 'Digoksin', 'Siklosporin', 'İnsülin', 'Antidiyabetikler', 'Rifampisin', 'Klonidin', 'Amiodaron'],
    etkilesimler: [
      ...BETABLOKOR_ETKILESIM,
      { ile: 'Siklosporin', siddet: 'ciddi', not: 'Karvedilol siklosporin kan düzeyini yükseltir; düzey izlenmeli ve doz azaltılmalı.' },
      { ile: 'Rifampisin', siddet: 'orta', not: 'Karvedilol plazma konsantrasyonunu belirgin düşürür.' },
    ],
    gebelik: { metin: 'Gebelikte yalnızca kesin gereklilikte; fetal bradikardi ve büyüme geriliği riski.' },
    emzirme: 'Anne sütüne geçer; emzirme döneminde önerilmez.',
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Tedavi birdenbire kesilmemeli, haftalar içinde kademeli azaltılmalıdır — özellikle koroner arter hastalığında (KÜB §4.2).',
    kaynak: kub('CALBİCOR 12,5 MG TABLET (onay 31/07/2025)', 'https://titck.gov.tr/storage/Archive/2025/kubKtAttachments/CALBCOR12.5KB_05_08_2025.pdf'),
  },

  nebivolol: {
    name: 'Nebivolol',
    brand: ['Vasoxen', 'Nebilet', 'Valende', 'Nebispes'],
    dose: 'Hipertansiyon: günde bir tablet (5 mg), her gün aynı saatte. Gerekirse 2 haftalık aralıklarla 40 mg\'a kadar çıkarılabilir. >65 yaşta 2,5 mg ile başlanır.',
    pediatricDose: '18 yaş altında güvenlilik ve etkililik kanıtlanmamıştır',
    form: 'Tablet',
    sgkCovered: true,
    category: 'Beta-1 selektif blokör (vazodilatör)',
    siniflar: [...BETABLOKOR_SINIF, 'Kardiyoselektif beta blokör'],
    yasKontrendikasyonAy: 216,
    contraindications: [
      'Nebivolole aşırı duyarlılık',
      'Karaciğer yetmezliği veya karaciğer fonksiyon bozukluğu',
      'Akut kalp yetersizliği, kardiyojenik şok, dekompanse kalp yetersizliği',
      'Hasta sinüs sendromu (sinoatriyal blok dahil)',
      'İkinci ve üçüncü derece kalp bloğu (pacemaker yoksa)',
      'Bronkospazm ve bronşiyal astım öyküsü',
      'Tedavi edilmemiş feokromositoma',
      'Metabolik asidoz',
      'Bradikardi',
    ],
    interactions: ['Verapamil', 'Diltiazem', 'Klonidin', 'Sınıf I antiaritmikler', 'İnsülin', 'Antidiyabetikler', 'Digoksin'],
    etkilesimler: BETABLOKOR_ETKILESIM,
    gebelik: { metin: 'Gebelikte yalnızca kesin gereklilikte; fetal bradikardi/hipoglisemi riski.' },
    emzirme: 'Emzirme döneminde önerilmez.',
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    kaynak: kub('VALENDE 5 MG TABLET (onay 04/06/2025)', 'https://titck.gov.tr/storage/Archive/2025/kubKtAttachments/1311kubtemiz5_04_06_2025.pdf'),
  },

  propranolol: {
    name: 'Propranolol',
    brand: ['Dideral', 'Inderal', 'Propranolol'],
    dose: 'Hipertansiyon: başlangıç 80 mg 2x1, idame 160–320 mg/gün. Anjina/anksiyete/migren/esansiyel tremor: 40 mg 2–3x1, idame 80–160 mg/gün (anjinada 120–240 mg/gün).',
    pediatricDose: 'Disritmi/feokromositoma/tirotoksikoz: 0,25–0,5 mg/kg, günde 3–4 defa. Migren <12 yaş: 20 mg 2–3x1',
    pediatrik: {
      min: 0.25, max: 0.5, birim: 'mg/kg/doz', gunlukBolum: 4,
      metin: 'KÜB §4.2: disritmi, feokromositoma ve tirotoksikozda oral olarak ihtiyaca göre günde üç veya dört defa 0,25–0,5 mg/kg. Migren profilaksisinde 12 yaşın altında günde iki veya üç defa 20 mg; 12 yaş üzerinde yetişkin dozu. Dozaj hastaya göre düzenlenmelidir.',
    },
    form: 'Tablet',
    sgkCovered: true,
    category: 'Non-selektif beta blokör',
    siniflar: [...BETABLOKOR_SINIF, 'Non-selektif beta blokör'],
    contraindications: [
      'Propranolole aşırı duyarlılık',
      'Bradikardi, ikinci veya üçüncü derece kalp bloğu',
      'Hasta sinüs sendromu',
      'Kardiyojenik şok',
      'Kontrolsüz kalp yetmezliği',
      'Bronşiyal astım öyküsü, bronkospazm',
      'KOAH',
      'Uzun süreli açlık',
      'Metabolik asidoz',
      'Hipotansiyon',
      'Ciddi periferik arter hastalığı',
      'Prinzmetal anjina',
      'Tedavi edilmemiş feokromositoma',
    ],
    interactions: ['Verapamil', 'Diltiazem', 'Salbutamol', 'İnsülin', 'Klonidin', 'NSAİİ', 'Rizatriptan', 'Flurbiprofen', 'Sınıf I antiaritmikler'],
    etkilesimler: [
      ...BETABLOKOR_ETKILESIM,
      { ile: 'Salbutamol', siddet: 'ciddi', not: 'Non-selektif beta blokör bronkodilatör etkiyi bloke eder; astımlıda birlikte reçete edilmemelidir.' },
    ],
    gebelik: { metin: 'Gebelikte yalnızca kesin gereklilikte; fetal bradikardi, hipoglisemi ve büyüme geriliği riski.' },
    emzirme: 'Anne sütüne geçer; düşük düzeyde, izlemle kullanılabilir.',
    renkliRecete: 'normal',
    notes: 'Hipoglisemiye yatkın hastalarda (diyabet, uzun açlık, çocuk) hipoglisemiyi maskeler ve derinleştirir.',
    kaynak: kub('DİDERAL 40 MG TABLET (onay 02/07/2024)', 'https://titck.gov.tr/storage/Archive/2024/kubKtAttachments/uygunkbdideral_ab2d37dc-ca5c-49cd-8969-28b9caf08366.pdf'),
  },

  hidroklorotiyazid: {
    name: 'Hidroklorotiyazid',
    brand: ['Hipotiyazid', 'Co-Diovan (kombinasyon)', 'Tenvia Plus (kombinasyon)', 'Hyzaar (kombinasyon)'],
    dose: 'Antihipertansif kombinasyonlarda tipik bileşen dozu 12,5–25 mg/gün. Tek başına kullanımda doz hekim tarafından titre edilir.',
    pediatricDose: '18 yaşından küçük hastalarda etkililik ve güvenlilik belirlenmemiştir',
    form: 'Tablet (çoğunlukla ARB/ACE inhibitörü ile sabit kombinasyon)',
    sgkCovered: true,
    category: 'Tiyazid diüretik',
    siniflar: ['Diüretik', 'Tiyazid diüretik', 'Antihipertansif', 'Sülfonamid türevi'],
    alerjiSinifi: ['sulfonamid'],
    yasKontrendikasyonAy: 216,
    contraindications: [
      'Hidroklorotiyazide aşırı duyarlılık',
      'Diğer sülfonamid türevi maddelere aşırı duyarlılık',
      'Gebelik',
      'Kolestaz ve biliyer obstrüktif hastalıklar',
      'Şiddetli karaciğer yetmezliği',
      'Şiddetli böbrek yetmezliği (KrKl <30 mL/dk), anüri',
      'Refrakter hipokalemi, hiperkalsemi',
    ],
    interactions: ['Lityum', 'Digoksin', 'NSAİİ', 'Sınıf III antiaritmikler', 'Metformin', 'Kortikosteroidler', 'ACE inhibitörleri'],
    etkilesimler: [
      { ile: 'Lityum', siddet: 'ciddi', not: 'Tiyazid lityum atılımını azaltır, toksisite riski; birlikte kullanım önerilmez (KÜB §4.5).' },
      { ile: 'Digoksin', siddet: 'ciddi', not: 'Hipokalemi dijital toksisitesini ve ventriküler aritmi riskini artırır; potasyum izlenmeli (KÜB §4.5).' },
      { ile: 'QT uzatan ilaç', siddet: 'ciddi', not: 'Tiyazide bağlı hipokalemi QT uzamasını ve Torsade de Pointes riskini artırır; EKG ve elektrolit takibi (KÜB §4.5).' },
      { ile: 'Metformin', siddet: 'orta', not: 'Hidroklorotiyazide bağlı fonksiyonel böbrek yetmezliği laktik asidoz riskiyle ilişkilendirilmiştir; dikkatli kullanılmalı (KÜB §4.5).' },
      { ile: 'NSAİİ', siddet: 'orta', not: 'Diüretik ve antihipertansif etki azalır; böbrek fonksiyonu bozulabilir (KÜB §4.5).' },
      { ile: 'Kortikosteroid', siddet: 'orta', not: 'Potasyum kaybı toplanır.' },
    ],
    gebelik: { metin: 'Gebelikte KONTRENDİKE — fetoplasental perfüzyonu azaltır; fetal/neonatal sarılık, trombositopeni ve elektrolit bozukluğu bildirilmiştir (KÜB §4.3/4.6).' },
    emzirme: 'Süt üretimini baskılayabilir; emzirme döneminde önerilmez.',
    bobrekDozUyarisi: true,
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Kaynak, telmisartan + hidroklorotiyazid sabit kombinasyonunun KÜB\'üdür; hidroklorotiyazid bileşenine ilişkin ifadeler oradan alınmıştır. Ürik asidi ve kan şekerini yükseltebilir.',
    kaynak: kub('TENVİA PLUS 80 MG/12,5 MG TABLET — hidroklorotiyazid bileşeni (onay 10/08/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/Ekek31311kubtemizkopya_21_08_2026.pdf'),
  },

  indapamid: {
    name: 'İndapamid',
    brand: ['Fludex', 'Flubest', 'Indapen', 'Preterax (kombinasyon)'],
    dose: 'Tercihen sabah günde bir tablet (SR 1,5 mg). Yüksek dozlar antihipertansif etkiyi artırmaz, yalnızca salüretik etkiyi artırır.',
    pediatricDose: 'Çocuk ve ergenlerde araştırılmamıştır, veri yoktur',
    form: 'Uzatılmış salımlı tablet',
    sgkCovered: true,
    category: 'Tiyazid benzeri diüretik',
    siniflar: ['Diüretik', 'Tiyazid benzeri diüretik', 'Antihipertansif', 'Sülfonamid türevi'],
    alerjiSinifi: ['sulfonamid'],
    contraindications: [
      'İndapamide veya sülfonamidlere aşırı duyarlılık',
      'Ciddi böbrek yetmezliği (kreatinin klerensi <30 mL/dk)',
      'Hepatik ensefalopati veya ciddi karaciğer yetmezliği',
      'Hipokalemi',
    ],
    interactions: ['Lityum', 'QT uzatan ilaçlar', 'Digoksin', 'NSAİİ', 'ACE inhibitörleri', 'Kortikosteroidler'],
    etkilesimler: [
      { ile: 'Lityum', siddet: 'ciddi', not: 'Lityum atılımı azalır, toksisite riski artar (KÜB §4.5).' },
      { ile: 'QT uzatan ilaç', siddet: 'ciddi', not: 'Hipokalemi QT uzamasını ve Torsade de Pointes riskini artırır (KÜB §4.4/4.5).' },
      { ile: 'Digoksin', siddet: 'ciddi', not: 'Hipokalemi dijital toksisitesini kolaylaştırır; potasyum izlenmeli.' },
      { ile: 'NSAİİ', siddet: 'orta', not: 'Antihipertansif etki azalır, akut böbrek yetmezliği riski artar.' },
    ],
    gebelik: { metin: 'Gebelikte önerilmez — fetoplasental iskemi ve fetal büyüme geriliği riski.' },
    emzirme: 'Emzirme döneminde önerilmez (süt üretimini baskılayabilir).',
    bobrekDozUyarisi: true,
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Hiponatremi ve hipokalemi riski nedeniyle tedavi başında ve periyodik olarak elektrolit kontrolü gerekir.',
    kaynak: kub('FLUBEST SR 1,5 MG UZATILMIŞ SALIMLI TABLET (onay 21/03/2023)', 'https://titck.gov.tr/storage/Archive/2023/kubKtAttachments/ek7flubestsr15kubtemiz_9bad4ac3-7cdb-4faa-a6de-ba3caae16421.pdf'),
  },

  furosemid: {
    name: 'Furosemid',
    brand: ['Lasix', 'Desal', 'Furomid', 'Furosemid'],
    dose: 'Böbrek/karaciğer hastalığına bağlı ödemde yetişkin başlangıç dozu genellikle 40 mg (1 tablet), aç karnına.',
    pediatricDose: 'Pediatrik günlük maksimum doz 40 mg furosemiddir',
    pediatrik: {
      min: 40, max: 40, birim: 'mg/kg/gün', gunlukBolum: 1,
      mutlakMaxMgGun: 40,
      metin: 'KÜB §4.2: pediyatrik popülasyonda günlük maksimum doz 40 mg furosemiddir. Ağırlığa göre mg/kg dozu bu üründe belirtilmemiştir — pediatrik dozlama için oral çözelti formunun KÜB\'üne bakılmalıdır.',
    },
    form: 'Tablet, ampul, oral çözelti',
    sgkCovered: true,
    category: 'Loop diüretik',
    siniflar: ['Diüretik', 'Loop diüretik', 'Antihipertansif', 'Sülfonamid türevi'],
    alerjiSinifi: ['sulfonamid'],
    contraindications: [
      'Furosemide aşırı duyarlılık',
      'Sülfonamid alerjisi (çapraz duyarlılık olabilir)',
      'Hipovolemi veya dehidratasyon',
      'Furosemide yanıt vermeyen anürik böbrek yetmezliği',
      'Şiddetli hipokalemi',
      'Şiddetli hiponatremi',
      'Hepatik ensefalopatiye bağlı prekomatöz/komatöz durum',
      'Emziren kadınlar',
    ],
    interactions: ['Digoksin', 'Aminoglikozidler', 'NSAİİ', 'Lityum', 'ACE inhibitörleri', 'Sisplatin', 'Kortikosteroidler', 'QT uzatan ilaçlar'],
    etkilesimler: [
      { ile: 'Digoksin', siddet: 'ciddi', not: 'Hipokalemi/hipomagnezemi dijital toksisitesini artırır; potasyum ve magnezyum izlenmeli.' },
      { ile: 'Aminoglikozid', siddet: 'ciddi', not: 'Ototoksisite ve nefrotoksisite riski belirgin artar.' },
      { ile: 'Lityum', siddet: 'ciddi', not: 'Lityum atılımı azalır, toksisite riski artar.' },
      { ile: 'NSAİİ', siddet: 'orta', not: 'Diüretik etki azalır ve nefrotoksisite riski artar (KÜB §4.5).' },
      { ile: 'QT uzatan ilaç', siddet: 'ciddi', not: 'Hipokalemi QT uzamasını ve aritmi riskini artırır.' },
      { ile: 'ACE inhibitörü', siddet: 'orta', not: 'Tedavi başında belirgin hipotansiyon; düşük dozla başlanmalı.' },
    ],
    gebelik: { metin: 'Gebelikte kesin gereklilik dışında kullanılmaz — plasental perfüzyonu azaltır.' },
    emzirme: 'KONTRENDİKE — emziren kadınlarda kullanılmaz; süt üretimini de baskılar (KÜB §4.3).' ,
    bobrekDozUyarisi: true,
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Potasyum takibi zorunludur. Sülfonamid alerjisi olan hastada çapraz duyarlılık bildirilmiştir (KÜB §4.3).',
    kaynak: kub('DESAL 40 MG TABLET (onay 14/04/2025)', 'https://titck.gov.tr/storage/Archive/2025/kubKtAttachments/xxkub_16_04_2025.pdf'),
  },

  spironolakton: {
    name: 'Spironolakton',
    brand: ['Aldactone', 'Spylacton', 'Spiroctan', 'Aldospiron'],
    dose: 'Konjestif kalp yetersizliği: başlangıç 100 mg/gün (100–200 mg aralığında). Standart tedaviye ek olarak (K ≤5 mEq/L, kreatinin ≤2,5 mg/dL): günde bir kez 25 mg.',
    pediatricDose: 'Başlangıç 1–3 mg/kg/gün, bölünmüş dozlarda (yalnız pediatri uzmanı yönlendirmesiyle)',
    pediatrik: {
      min: 1, max: 3, birim: 'mg/kg/gün', gunlukBolum: 2,
      maxMgKgGun: 3,
      metin: 'KÜB §4.2: pediyatrik günlük başlangıç dozu vücut ağırlığının her bir kilogramı için 1–3 mg spironolakton, bölünmüş dozlarda. Doz yanıta ve toleransa göre ayarlanır. Ürün çocuklara sadece pediyatri uzmanının yönlendirmesiyle verilir; mevcut pediyatrik veri sınırlıdır.',
    },
    form: 'Film kaplı tablet',
    sgkCovered: true,
    category: 'Potasyum tutucu diüretik (aldosteron antagonisti)',
    siniflar: ['Diüretik', 'Potasyum tutucu diüretik', 'Aldosteron antagonisti', 'Antihipertansif', 'Antiandrojen'],
    contraindications: [
      'Akut böbrek yetmezliği, anüri, ciddi böbrek fonksiyon bozukluğu',
      'Addison hastalığı',
      'Hiperkalemi',
      'Spironolaktona aşırı duyarlılık',
      'Eplerenon ile birlikte kullanım (orta-şiddetli böbrek yetersizliği olan pediyatrik hastada)',
    ],
    interactions: ['ACE inhibitörleri', 'ARB', 'Potasyum tuzları', 'Heparin', 'NSAİİ', 'Trimetoprim', 'Digoksin', 'Lityum'],
    etkilesimler: [
      { ile: 'ACE inhibitörü', siddet: 'ciddi', not: 'Hayatı tehdit eden hiperkalemi riski; potasyum ve kreatinin düzenli izlenmelidir (KÜB §4.3/4.5).' },
      { ile: 'Anjiyotensin II reseptör blokeri', siddet: 'ciddi', not: 'Hiperkalemi riski belirgin artar (KÜB §4.3/4.5).' },
      { ile: 'Potasyum', siddet: 'ciddi', not: 'Potasyum destekleriyle birlikte hiperkalemi riski (KÜB §4.3).' },
      { ile: 'Trimetoprim', siddet: 'ciddi', not: 'Trimetoprim potasyum atılımını azaltır; birlikte ciddi hiperkalemi bildirilmiştir.' },
      { ile: 'NSAİİ', siddet: 'ciddi', not: 'Hiperkalemi ve böbrek fonksiyon bozukluğu riski artar (KÜB §4.3).' },
      { ile: 'Digoksin', siddet: 'orta', not: 'Spironolakton digoksin klerensini azaltır, düzeyi yükseltebilir.' },
      { ile: 'Lityum', siddet: 'ciddi', not: 'Lityum atılımı azalır, toksisite riski artar.' },
    ],
    gebelik: { metin: 'Antiandrojenik etkisi nedeniyle gebelikte kullanılmaz (erkek fetüste feminizasyon riski).' },
    emzirme: 'Metaboliti anne sütüne geçer; emzirme döneminde önerilmez.',
    bobrekDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Jinekomasti doza ve süreye bağımlı, sık görülen yan etkidir. Potasyum ve kreatinin tedavi başında, 1. haftada ve düzenli aralıklarla ölçülmelidir.',
    kaynak: kub('SPYLACTON 25 MG FİLM KAPLI TABLET (onay 27/08/2025)', 'https://titck.gov.tr/storage/Archive/2025/kubKtAttachments/SPYLACTON25mgfilmkapltabletkub_28_08_2025.pdf'),
  },

  digoksin: {
    name: 'Digoksin',
    brand: ['Digoxin', 'Lanoxin'],
    dose: 'Yavaş dijitalizasyon (>40 kg yetişkin ve >10 yaş çocuk): günlük idame ortalama 0,25 mg (0,125–0,5 mg/gün). Kararlı duruma 7–10 günde ulaşılır. >65 yaşta idame 0,25 mg/günü aşmamalıdır.',
    pediatricDose: '40 kg altı çocuk ve ergenlerde (<10 yaş) yaşa/ağırlığa göre; şiddetli böbrek bozukluğunda 10 µg/kg aşılmamalıdır',
    pediatrik: {
      min: 10, max: 10, birim: 'mikrogram/kg/gün', gunlukBolum: 1,
      metin: 'KÜB §4.2: 40 kg ağırlığına kadarki çocuk ve ergenlerde (<10 yaş) doz yaşa ve vücut ağırlığına göre belirlenir; şiddetli renal fonksiyon bozukluğu olan hastalarda 10 µg/kg vücut ağırlığını aşmamalıdır. Prematüre ve term neonatta gerekli doz belirgin değişkendir — digoksin düzey tayini özellikle önerilir.',
    },
    form: 'Tablet, ampul, pediatrik eliksir',
    sgkCovered: true,
    category: 'Kardiyak glikozit',
    siniflar: ['Kardiyak glikozit', 'Dijital', 'Antiaritmik', 'İnotrop'],
    contraindications: [
      'Digoksin veya diğer kardiyak glikozitlere aşırı duyarlılık',
      'Şüpheli digital zehirlenmesi',
      'İkinci veya üçüncü derece AV blok, sinüs düğümü disfonksiyonu (pacemaker yoksa)',
      'Ventriküler taşikardi veya ventriküler fibrilasyon',
      'Aksesuar AV yollar (Wolff-Parkinson-White sendromu)',
      'Hipokalemi, hiperkalsemi, hipomagnezemi',
      'Hipoksi',
      'Hipertrofik obstrüktif kardiyomiyopati',
      'Eşzamanlı IV kalsiyum tuzu uygulaması',
      'Torasik aort anevrizması',
    ],
    interactions: ['Amiodaron', 'Verapamil', 'Diüretikler', 'Makrolidler', 'İtrakonazol', 'Spironolakton', 'Siklosporin', 'IV kalsiyum', 'NSAİİ', 'PPİ'],
    etkilesimler: [
      { ile: 'Kalsiyum', siddet: 'ciddi', not: 'KONTRENDİKE — eşzamanlı IV kalsiyum tuzu uygulaması ölümcül aritmi yapabilir (KÜB §4.3/4.5).' },
      { ile: 'Amiodaron', siddet: 'ciddi', not: 'Digoksin plazma düzeyini yaklaşık iki katına çıkarır; digoksin dozu yarıya indirilmeli.' },
      { ile: 'Verapamil', siddet: 'ciddi', not: 'Digoksin düzeyini yükseltir ve AV iletimi yavaşlatır; bradikardi/blok riski.' },
      { ile: 'Diüretik', siddet: 'ciddi', not: 'Hipokalemi/hipomagnezemi dijital toksisitesini tetikler; elektrolit izlenmeli.' },
      { ile: 'Makrolid', siddet: 'ciddi', not: 'Klaritromisin/eritromisin digoksin düzeyini yükseltir.' },
      { ile: 'Spironolakton', siddet: 'orta', not: 'Digoksin klerensini azaltır, düzeyi yükseltir.' },
      { ile: 'Beta blokör', siddet: 'orta', not: 'AV iletim yavaşlaması toplanır.' },
    ],
    gebelik: { metin: 'Gebelikte kullanılabilir (fetal taşiaritmi tedavisi dahil); doz gereksinimi gebelikte artabilir, düzey izlenmelidir.' },
    emzirme: 'Anne sütüne az miktarda geçer; emzirme döneminde kullanılabilir.',
    bobrekDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Dar terapötik aralık — bulantı, görme bozukluğu (sarı-yeşil halo), bradikardi ve aritmi toksisiteyi düşündürür. Böbrek fonksiyonu ve potasyum izlenmelidir.',
    kaynak: kub('DİGOXİN-ASSOS 0,25 MG TABLET (onay 01/06/2018)', 'https://titck.gov.tr/storage/kubKtAttachments/FigMf3eckYGC9.pdf'),
  },

  izosorbidDinitrat: {
    name: 'İzosorbid dinitrat',
    brand: ['İsordil', 'Isoket', 'Monoket (mononitrat)'],
    dose: 'Kronik stabil anjina: başlangıç 5–20 mg oral; idamede 6 saatte bir (günde 4 kez) 10–40 mg. Kalp yetmezliğinde günde 3–4 kez 20 mg, hedef 120–160 mg/gün.',
    pediatricDose: 'Pediatrik kullanım için doz önerisi yoktur',
    form: 'Tablet, dil altı tablet, sprey, IV infüzyon',
    sgkCovered: true,
    category: 'Nitrat (vazodilatör)',
    siniflar: ['Nitrat', 'Vazodilatör', 'Antianjinal', 'Nitrik oksit donörü'],
    contraindications: [
      'İzosorbid dinitrata veya organik nitratlara aşırı duyarlılık',
      'Fosfodiesteraz-5 inhibitörleri (sildenafil, tadalafil, vardenafil) ile birlikte kullanım',
      'Dar açılı glokom',
      'Kafa travması veya serebral hemoraji',
      'Şiddetli anemi',
      'Sistolik kan basıncı <90 mmHg',
    ],
    interactions: ['Sildenafil', 'Tadalafil', 'Vardenafil', 'Antihipertansifler', 'Alkol', 'Riosiguat'],
    etkilesimler: [
      { ile: 'Sildenafil', siddet: 'ciddi', not: 'KONTRENDİKE — PDE-5 inhibitörü nitratın hipotansif etkisini şiddetle artırır; hayatı tehdit eden hipotansiyon (KÜB §4.3).' },
      { ile: 'Antihipertansif', siddet: 'orta', not: 'Kan basıncı düşürücü etkiler toplanır; senkop riski.' },
      { ile: 'Alkol', siddet: 'orta', not: 'Hipotansif etki artar.' },
    ],
    gebelik: { metin: 'Gebede yeterli veri yoktur; yalnızca açık gereklilikte kullanılır.' },
    emzirme: 'Veri yetersizdir; yarar/risk değerlendirilir.',
    bobrekDozUyarisi: true,
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Tolerans gelişimini önlemek için günde 8–12 saatlik nitratsız aralık bırakılmalıdır. Baş ağrısı en sık yan etkidir.',
    kaynak: kub('İSORDİL 10 MG TABLET (onay 26/04/2025)', 'https://titck.gov.tr/storage/Archive/2025/kubKtAttachments/Ek3OnerilenIsordil10mgKUBtemiz_28_04_2025.pdf'),
  },

  metildopa: {
    name: 'Metildopa',
    brand: ['Alfamet', 'Aldomet', 'Dopegyt'],
    dose: 'Yetişkin: başlangıç ilk 48 saat günde 2–3 defa 250 mg; doz en az iki günlük aralıklarla ayarlanır. Önerilen maksimum günlük doz 3 g.',
    pediatricDose: 'Başlangıç günde 2–4 defa 10 mg/kg; maksimum günlük 65 mg/kg veya 3 g (hangisi azsa)',
    pediatrik: {
      min: 10, max: 10, birim: 'mg/kg/doz', gunlukBolum: 4,
      maxMgKgGun: 65, mutlakMaxMgGun: 3000,
      metin: 'KÜB §4.2: pediyatrik başlangıç dozu günde 2–4 defa 10 mg/kg. Yeterli yanıt alınana kadar günlük doz artırılır veya azaltılır. Maksimum doz günlük 65 mg/kg veya 3 g\'dır (hangisi daha az ise).',
    },
    form: 'Film kaplı tablet',
    sgkCovered: true,
    category: 'Santral etkili antihipertansif (alfa-2 agonist)',
    siniflar: ['Antihipertansif', 'Santral etkili antihipertansif', 'Alfa-2 agonist'],
    contraindications: [
      'Akut hepatit, aktif siroz gibi aktif karaciğer hastalıkları',
      'Önceki metildopa tedavisine bağlı karaciğer rahatsızlığı',
      'Metildopaya aşırı duyarlılık',
      'Depresyon',
      'MAO inhibitörü tedavisi',
      'Feokromositoma veya paraganglioma',
      'Porfiri',
    ],
    interactions: ['MAO inhibitörleri', 'Lityum', 'Demir', 'Sempatomimetikler', 'Diğer antihipertansifler', 'Haloperidol'],
    etkilesimler: [
      { ile: 'MAO inhibitörü', siddet: 'ciddi', not: 'KONTRENDİKE — hipertansif kriz ve santral etkiler (KÜB §4.3).' },
      { ile: 'Demir', siddet: 'orta', not: 'Demir tuzları metildopanın biyoyararlanımını belirgin azaltır; saat ayrımı gerekir.' },
      { ile: 'Lityum', siddet: 'ciddi', not: 'Lityum toksisitesi bildirilmiştir; düzey izlenmeli.' },
      { ile: 'Antihipertansif', siddet: 'orta', not: 'Kan basıncı düşürücü etkiler toplanır.' },
    ],
    gebelik: { metin: 'Gebelik hipertansiyonunda en uzun deneyime sahip antihipertansiflerden biridir; KÜB bu üründe gebeliği kontrendikasyon olarak listelememektedir. Endikasyon ve doz kararı hekimindir.' },
    emzirme: 'Anne sütüne az miktarda geçer; emzirme döneminde genellikle uyumlu kabul edilir.',
    karacigerDozUyarisi: true,
    bobrekDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Tedavi başında ve doz artışında 2–3 gün sedasyon olur — doz artışına akşam başlanmalıdır. Coombs pozitifliği ve hemolitik anemi ile karaciğer toksisitesi izlenmelidir.',
    kaynak: kub('ALFAMET 250 MG FİLM KAPLI TABLET (onay 21/09/2023)', 'https://titck.gov.tr/storage/Archive/2023/kubKtAttachments/kubtemiz_b97593f7-2335-4b94-a83c-f6db6b17d972.pdf'),
  },
}
