/**
 * Psikiyatri ve nöroloji — SSRI/SNRI, atipik antipsikotikler, benzodiazepinler, antiepileptikler,
 * DEHB ilaçları, antidemansiyel, triptan.
 *
 * Two safety chains are modelled as classes so a new molecule joins them automatically:
 *   • 'Serotonerjik ilaç' — MAOİ, SSRI, SNRI, triptan, tramadol, ondansetron, linezolid → serotonin
 *     sendromu. Every entry here that raises serotonin carries the label.
 *   • 'SSS depresanı'     — benzodiazepin + opioid + antihistaminik + alkol → sedasyon, solunum
 *     depresyonu. This is what makes alprazolam + tramadol fire on the card.
 *
 * `renkliRecete` is NOT cosmetic here: alprazolam, lorazepam, pregabalin, gabapentin and
 * metilfenidat are on TİTCK's kontrole tabi lists, and a test re-derives the colour from
 * lib/doktor/receteRengi so the two can never drift.
 */
import { kub } from '../kaynak'
import type { TürkishDrug } from '../tipler'

const SEROTONERJIK = ['Serotonerjik ilaç', 'Antidepresan'] as const

const SEROTONIN_ETKILESIM = [
  { ile: 'MAO inhibitörü', siddet: 'ciddi' as const, not: 'KONTRENDİKE — serotonin sendromu (ajitasyon, tremor, hipertermi). MAOİ kesildikten sonra en az 14 gün beklenmelidir (KÜB §4.3).' },
  { ile: 'Linezolid', siddet: 'ciddi' as const, not: 'Geri dönüşlü MAO inhibitörüdür; serotonin sendromu riski — birlikte kullanımdan kaçınılmalıdır (KÜB §4.3/4.5).' },
  { ile: 'Tramadol', siddet: 'ciddi' as const, not: 'Serotonerjik yük toplanır ve nöbet eşiği düşer; serotonin sendromu riski.' },
  { ile: 'Triptan', siddet: 'ciddi' as const, not: 'Serotonin sendromu riski artar; birlikte başlanırsa hasta yakından izlenmelidir.' },
  { ile: 'Serotonerjik ilaç', siddet: 'ciddi' as const, not: 'İki serotonerjik ilacın birlikteliği serotonin sendromu riskini artırır.' },
  { ile: 'NSAİİ', siddet: 'ciddi' as const, not: 'Trombosit serotonin alımının inhibisyonu ile gastrointestinal kanama riski artar.' },
  { ile: 'Antikoagülan', siddet: 'ciddi' as const, not: 'Kanama riski artar; INR ve klinik kanama bulguları izlenmelidir.' },
  { ile: 'Antiagregan', siddet: 'ciddi' as const, not: 'Trombosit fonksiyonu üzerine sinerjik etki — kanama riski artar.' },
] as const

const SSS_DEPRESAN_ETKILESIM = [
  { ile: 'Opioid', siddet: 'ciddi' as const, not: 'Ek SSS depresyonu: sedasyon, solunum depresyonu, koma ve ölüm riski. Birlikte reçete edilecekse en düşük dozda ve kısa süreli.' },
  { ile: 'Alkol', siddet: 'ciddi' as const, not: 'Sedatif etki belirgin artar; psikomotor bozulma.' },
  { ile: 'SSS depresanı', siddet: 'ciddi' as const, not: 'Sedatif etkiler toplanır; düşme, konfüzyon ve solunum depresyonu riski.' },
  { ile: 'Antihistaminik', siddet: 'orta' as const, not: 'Birinci kuşak antihistaminiklerle sedasyon artar.' },
] as const

export const NOROPSIKIYATRI: Record<string, TürkishDrug> = {
  sertralin: {
    name: 'Sertralin',
    brand: ['Lustral', 'Selectra', 'Misol', 'Seralin', 'Zoloft'],
    dose: 'Depresyon ve OKB: 50 mg/gün ile başlanır. Panik bozukluk, TSSB, sosyal fobi: 25 mg/gün ile başlanır, bir hafta sonra 50 mg\'a çıkılır. Maksimum 200 mg/gün.',
    pediatricDose: 'OKB\'de 13–17 yaş: 50 mg/gün; 6–12 yaş: 25 mg/gün ile başlanıp bir hafta sonra 50 mg/gün',
    pediatrik: {
      min: 25, max: 50, birim: 'mg/kg/gün', gunlukBolum: 1,
      mutlakMaxMgGun: 200, enAzAy: 72,
      metin: 'KÜB §4.2 (sabit doz, mg/kg değil): etkililik ve güvenlilik 6–17 yaş arası OKB\'li pediyatrik hastalarda gösterilmiştir. 13–17 yaşta 50 mg/gün, 6–12 yaşta 25 mg/gün ile başlanır ve bir hafta sonra 50 mg/gün\'e yükseltilir. Maksimum doz 200 mg/gün.',
    },
    form: 'Film kaplı tablet',
    sgkCovered: true,
    category: 'SSRI antidepresan',
    siniflar: [...SEROTONERJIK, 'SSRI', 'Selektif serotonin geri alım inhibitörü'],
    contraindications: [
      'Sertraline aşırı duyarlılık',
      'MAO inhibitörü kullanımı (kesildikten sonra 14 gün beklenmeli)',
      'Pimozid ile birlikte kullanım',
    ],
    interactions: ['MAO inhibitörleri', 'Pimozid', 'Triptanlar', 'Tramadol', 'Varfarin', 'NSAİİ', 'Linezolid', 'Lityum'],
    etkilesimler: [...SEROTONIN_ETKILESIM, { ile: 'Pimozid', siddet: 'ciddi', not: 'KONTRENDİKE — pimozid düzeyi yükselir, QT uzaması riski (KÜB §4.3).' }],
    gebelik: { metin: 'Gebelikte yarar/risk değerlendirilir; 3. trimesterde neonatal adaptasyon sendromu ve persistan pulmoner hipertansiyon bildirilmiştir.' },
    emzirme: 'Anne sütüne az miktarda geçer; SSRI\'lar içinde emzirme döneminde en çok tercih edilenlerdendir.',
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Ani kesilmesi yoksunluk (baş dönmesi, parestezi, uyku bozukluğu) yapar — kademeli azaltılmalıdır.',
    kaynak: kub('MİSOL 100 MG FİLM KAPLI TABLET (onay 10/02/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/MSOLKBTEMZ_24_02_2026.pdf'),
  },

  essitalopram: {
    name: 'Essitalopram',
    brand: ['Cipralex', 'Medolapram', 'Escitil', 'Esram'],
    dose: 'Majör depresif bozukluk: günde bir kez 10 mg; yanıta göre maksimum 20 mg/gün. 65 yaş altı erişkinde maksimum doz 20 mg/gün.',
    pediatricDose: '18 yaş altı çocuk ve adolesanların tedavisinde kullanılmamalıdır',
    form: 'Film kaplı tablet, oral damla',
    sgkCovered: true,
    category: 'SSRI antidepresan',
    siniflar: [...SEROTONERJIK, 'SSRI', 'Selektif serotonin geri alım inhibitörü', 'QT uzatan ilaç'],
    yasKontrendikasyonAy: 216,
    contraindications: [
      'Essitaloprama aşırı duyarlılık',
      'Non-selektif irreversibl MAO inhibitörleriyle birlikte kullanım',
      'Reversibl MAO-A inhibitörleri (moklobemid) veya linezolid ile birlikte kullanım',
      '18 yaş altı',
    ],
    interactions: ['MAO inhibitörleri', 'Linezolid', 'Triptanlar', 'Tramadol', 'NSAİİ', 'Varfarin', 'QT uzatan ilaçlar', 'Simetidin', 'Omeprazol'],
    etkilesimler: [
      ...SEROTONIN_ETKILESIM,
      { ile: 'QT uzatan ilaç', siddet: 'ciddi', not: 'Essitalopram doza bağımlı QT uzatır; başka QT uzatan ilaçla birlikte aritmi riski artar.' },
      { ile: 'Omeprazol', siddet: 'orta', not: 'CYP2C19 inhibisyonu essitalopram maruziyetini artırır; doz düşürülmesi gerekebilir.' },
    ],
    gebelik: { metin: 'Gebelikte yarar/risk değerlendirilir; 3. trimesterde neonatal adaptasyon sendromu riski.' },
    emzirme: 'Anne sütüne geçer; düşük dozda emzirme sürdürülebilir, bebek izlenmelidir.',
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: '20 mg üzerindeki günlük dozlarda güvenlilik kanıtlanmamıştır (KÜB §4.2).',
    kaynak: kub('MEDOLAPRAM 10 MG FİLM KAPLI TABLET (onay 05/04/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/MEDOLAPRAMKB_06_04_2026.pdf'),
  },

  fluoksetin: {
    name: 'Fluoksetin',
    brand: ['Prozac', 'Depreks', 'Psenac', 'Zedprex', 'Fulsac'],
    dose: 'Depresyon (erişkin ve yaşlı): 20 mg/gün. Yetersizse kademeli olarak maksimum 60 mg/gün\'e çıkarılabilir. Doz 3–4 hafta sonra değerlendirilir.',
    pediatricDose: '8 yaş ve üzeri orta-şiddetli majör depresif epizodda: başlangıç 10 mg/gün, 1–2 hafta sonra 20 mg/gün',
    pediatrik: {
      min: 10, max: 20, birim: 'mg/kg/gün', gunlukBolum: 1,
      mutlakMaxMgGun: 20, enAzAy: 96,
      metin: 'KÜB §4.2 (sabit doz, mg/kg değil): 8 yaş ve üzeri çocuk ve adolesanlarda tedavi uzman gözetiminde başlatılır; başlangıç dozu 10 mg/gün, bir-iki hafta sonra 20 mg/gün\'e yükseltilebilir. 20 mg üzerindeki günlük dozlarda pediyatrik klinik veri sınırlıdır. 8 yaşın altında kullanımı önerilmez.',
    },
    form: 'Kapsül, oral çözelti',
    sgkCovered: true,
    category: 'SSRI antidepresan',
    siniflar: [...SEROTONERJIK, 'SSRI', 'Selektif serotonin geri alım inhibitörü', 'CYP2D6 inhibitörü'],
    contraindications: [
      'Fluoksetine aşırı duyarlılık',
      'İrreversibl seçici olmayan MAO inhibitörleriyle birlikte kullanım',
      'Kalp yetmezliğinde kullanılan metoprolol ile birlikte kullanım',
      'Pimozid ile birlikte kullanım',
      'Tiyoridazin ile birlikte kullanım',
    ],
    interactions: ['MAO inhibitörleri', 'Pimozid', 'Tiyoridazin', 'Metoprolol', 'Triptanlar', 'Tramadol', 'NSAİİ', 'Varfarin', 'Lityum'],
    etkilesimler: [
      ...SEROTONIN_ETKILESIM,
      { ile: 'Metoprolol', siddet: 'ciddi', not: 'KONTRENDİKE (kalp yetmezliğinde kullanılan metoprolol ile) — CYP2D6 inhibisyonu beta blokör düzeyini yükseltir (KÜB §4.3).' },
      { ile: 'Pimozid', siddet: 'ciddi', not: 'KONTRENDİKE — QT uzaması riski (KÜB §4.3).' },
    ],
    gebelik: { metin: 'Gebelikte yarar/risk değerlendirilir; geç gebelikte neonatal adaptasyon sendromu ve PPHN riski.' },
    emzirme: 'Uzun yarı ömrü nedeniyle bebekte birikebilir; emzirme döneminde sertralin tercih edilir.',
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Uzun yarı ömrü (aktif metabolit norfluoksetin) nedeniyle kesildikten sonra 5 hafta MAOİ başlanmamalıdır.',
    kaynak: kub('PSENAC 20 MG/5 ML ORAL ÇÖZELTİ (onay 04/07/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/PsenacKB_09_07_2026.pdf'),
  },

  paroksetin: {
    name: 'Paroksetin',
    brand: ['Paxil', 'Paxera', 'Seroxat', 'Parotin'],
    dose: 'Majör depresif bozukluk: 20 mg/gün; yanıta göre 10 mg\'lık artışlarla maksimum 50 mg/gün. OKB ve panik bozukluk: hedef 40 mg/gün, maksimum 60 mg/gün.',
    pediatricDose: '18 yaş altı çocuk ve adolesanlarda endike değildir',
    form: 'Film tablet',
    sgkCovered: true,
    category: 'SSRI antidepresan',
    siniflar: [...SEROTONERJIK, 'SSRI', 'Selektif serotonin geri alım inhibitörü', 'CYP2D6 inhibitörü'],
    yasKontrendikasyonAy: 216,
    contraindications: [
      'Paroksetine aşırı duyarlılık',
      'MAO inhibitörleriyle kombinasyon',
      'Tiyoridazin ile birlikte kullanım',
      'Pimozid ile birlikte kullanım',
      '18 yaş altı',
    ],
    interactions: ['MAO inhibitörleri', 'Linezolid', 'Tiyoridazin', 'Pimozid', 'Tamoksifen', 'Metoprolol', 'Triptanlar', 'Tramadol', 'NSAİİ', 'Varfarin'],
    etkilesimler: [
      ...SEROTONIN_ETKILESIM,
      { ile: 'Metoprolol', siddet: 'ciddi', not: 'Güçlü CYP2D6 inhibisyonu beta blokör maruziyetini artırır; bradikardi/hipotansiyon riski.' },
      { ile: 'Tamoksifen', siddet: 'ciddi', not: 'CYP2D6 inhibisyonu tamoksifenin aktif metabolitini azaltır; meme kanseri tedavisinde etkinlik kaybı.' },
    ],
    gebelik: { metin: 'İlk trimesterde kardiyak malformasyon riskinde küçük bir artış bildirilmiştir; gebelikte SSRI seçiminde bu göz önüne alınmalıdır.' },
    emzirme: 'Anne sütüne az miktarda geçer; emzirme döneminde kullanılabilir.',
    karacigerDozUyarisi: true,
    bobrekDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'SSRI\'lar içinde yoksunluk belirtileri en belirgin olanıdır — mutlaka kademeli azaltılmalıdır.',
    kaynak: kub('PAXERA 10 MG FİLM TABLET (onay 12/08/2024)', 'https://titck.gov.tr/storage/Archive/2024/kubKtAttachments/ONAYLIKB_93151e5a-e361-4fa0-a3f3-11db0a0acb10.pdf'),
  },

  venlafaksin: {
    name: 'Venlafaksin',
    brand: ['Efexor', 'Sulinex', 'Venegis', 'Faxiven'],
    dose: 'Majör depresyon (XR): başlangıç 75 mg/gün; yanıtsız hastalarda en fazla 375 mg/gün. Doz artışları ~2 haftalık aralıklarla.',
    pediatricDose: 'Çocuk ve ergenlerde kullanılmamalıdır (etkililik gösterilememiştir)',
    form: 'Uzatılmış salımlı kapsül/tablet',
    sgkCovered: true,
    category: 'SNRI antidepresan',
    siniflar: [...SEROTONERJIK, 'SNRI', 'Serotonin-norepinefrin geri alım inhibitörü'],
    yasKontrendikasyonAy: 216,
    contraindications: [
      'Venlafaksine aşırı duyarlılık',
      'MAO inhibitörleriyle birlikte kullanım (MAOİ kesildikten sonra 14 gün beklenmeli)',
      '18 yaş altı',
    ],
    interactions: ['MAO inhibitörleri', 'Linezolid', 'Triptanlar', 'Tramadol', 'NSAİİ', 'Varfarin', 'Antiagreganlar'],
    etkilesimler: SEROTONIN_ETKILESIM,
    gebelik: { metin: 'Gebelikte yarar/risk değerlendirilir; geç gebelikte neonatal adaptasyon sendromu riski.' },
    emzirme: 'Anne sütüne geçer; emzirme döneminde dikkatle kullanılır.',
    bobrekDozUyarisi: true,
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Doza bağlı kan basıncı artışı yapar — tedavi sırasında kan basıncı izlenmelidir. Yoksunluk belirtileri belirgindir.',
    kaynak: kub('SULİNEX XR 225 MG TABLET (onay 29/12/2025)', 'https://titck.gov.tr/storage/Archive/2025/kubKtAttachments/sulinexxr225yaynlanacakkb_31_12_2025.pdf'),
  },

  duloksetin: {
    name: 'Duloksetin',
    brand: ['Cymbalta', 'Komox', 'Duloxis', 'Dulxetin'],
    dose: 'Önerilen doz günde iki kez 40 mg (yemeklerden bağımsız). Bazı hastalarda iki hafta günde iki kez 20 mg ile başlanabilir. 2–4 haftada yeniden değerlendirilir.',
    pediatricDose: '18 yaş altı çocuk ve adolesanlarda kullanımı önerilmemektedir',
    form: 'Gastrorezistan sert kapsül',
    sgkCovered: true,
    category: 'SNRI antidepresan',
    siniflar: [...SEROTONERJIK, 'SNRI', 'Serotonin-norepinefrin geri alım inhibitörü'],
    yasKontrendikasyonAy: 216,
    contraindications: [
      'Duloksetine aşırı duyarlılık',
      'Karaciğer yetmezliği ile sonuçlanan karaciğer hastalığı',
      'Nonselektif irreversibl MAO inhibitörleriyle birlikte kullanım',
      'CYP1A2 inhibitörleri (fluvoksamin, siprofloksasin, enoksasin) ile birlikte kullanım',
      'Ağır böbrek bozukluğu',
    ],
    interactions: ['MAO inhibitörleri', 'Fluvoksamin', 'Siprofloksasin', 'Enoksasin', 'Triptanlar', 'Tramadol', 'NSAİİ', 'Varfarin'],
    etkilesimler: [
      ...SEROTONIN_ETKILESIM,
      { ile: 'Siprofloksasin', siddet: 'ciddi', not: 'KONTRENDİKE — CYP1A2 inhibisyonu duloksetin plazma konsantrasyonunu belirgin artırır (KÜB §4.3/4.5).' },
    ],
    gebelik: { metin: 'Gebelikte yarar/risk değerlendirilir; geç gebelikte neonatal adaptasyon sendromu riski.' },
    emzirme: 'Anne sütüne geçer; emzirme döneminde önerilmez.',
    bobrekDozUyarisi: true,
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Ani kesilmesinden kaçınılmalı; doz en az 1–2 haftada kademeli azaltılmalıdır (KÜB §4.2).',
    kaynak: kub('KOMOX 40 MG GASTROREZİSTAN SERT KAPSÜL (onay 29/04/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/UYGUNkbkomox40mg_30_04_2026.pdf'),
  },

  mirtazapin: {
    name: 'Mirtazapin',
    brand: ['Remeron', 'Mires', 'Mirtaron', 'Velorin'],
    dose: 'Etkili günlük doz 15–45 mg; başlangıç 15 veya 30 mg (akşam). Etki 1–2 haftada başlar; 2–4 haftada yanıt alınmazsa doz artırılır.',
    pediatricDose: 'Çocuk ve 18 yaş altı adolesanlarda kullanılmamalıdır',
    form: 'Film kaplı tablet, ağızda dağılan tablet',
    sgkCovered: true,
    category: 'Noradrenerjik ve spesifik serotonerjik antidepresan (NaSSA)',
    siniflar: [...SEROTONERJIK, 'NaSSA', 'Tetrasiklik antidepresan', 'SSS depresanı'],
    yasKontrendikasyonAy: 216,
    contraindications: ['Mirtazapine aşırı duyarlılık', 'MAO inhibitörleriyle birlikte kullanım', '18 yaş altı'],
    interactions: ['MAO inhibitörleri', 'Benzodiazepinler', 'Alkol', 'Triptanlar', 'Tramadol', 'Varfarin', 'Karbamazepin', 'Rifampisin'],
    etkilesimler: [
      ...SEROTONIN_ETKILESIM,
      ...SSS_DEPRESAN_ETKILESIM,
      { ile: 'Karbamazepin', siddet: 'orta', not: 'Enzim indüksiyonu mirtazapin plazma düzeyini düşürür; doz artırımı gerekebilir.' },
    ],
    gebelik: { metin: 'Gebelikte veri sınırlıdır; yarar/risk değerlendirilir.' },
    emzirme: 'Anne sütüne az miktarda geçer; bebek sedasyon açısından izlenmelidir.',
    bobrekDozUyarisi: true,
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'İştah artışı, kilo alımı ve sedasyon belirgindir — kaşektik/uykusuz hastada avantaj olabilir. Agranülositoz nadir ama bildirilmiştir.',
    kaynak: kub('MİRES 15 MG FİLM KAPLI TABLET (onay 18/07/2024)', 'https://titck.gov.tr/storage/Archive/2024/kubKtAttachments/kbyaymlanacak_ab82c731-3839-423a-8eb8-f4024fde053b.pdf'),
  },

  ketiapin: {
    name: 'Ketiapin',
    brand: ['Seroquel', 'Gyrex', 'Kventiax', 'Cedrina'],
    dose: 'Şizofrenide günde 2 defa: 1. gün 50 mg, 2. gün 100 mg, 3. gün 200 mg, 4. gün 300 mg toplam günlük doz. Sonraki ayarlamalarda günlük artış 200 mg\'ı aşmamalıdır.',
    pediatricDose: '18 yaş altı çocuk ve ergenlerde yeterli veri olmadığı için önerilmez',
    form: 'Film kaplı tablet, XR tablet',
    sgkCovered: true,
    sgkRestriction: 'SUT: psikiyatri uzman hekim raporu koşullarına bakınız.',
    category: 'Atipik antipsikotik',
    siniflar: ['Antipsikotik', 'Atipik antipsikotik', 'SSS depresanı', 'QT uzatan ilaç'],
    yasKontrendikasyonAy: 216,
    contraindications: ['Ketiapine aşırı duyarlılık', 'Güçlü CYP3A4 inhibitörleriyle birlikte kullanım (HIV proteaz inhibitörleri, azol antifungaller, eritromisin, klaritromisin, nefazodon)'],
    interactions: ['Klaritromisin', 'İtrakonazol', 'Karbamazepin', 'Fenitoin', 'Rifampisin', 'QT uzatan ilaçlar', 'Alkol', 'Benzodiazepinler'],
    etkilesimler: [
      ...SSS_DEPRESAN_ETKILESIM,
      { ile: 'Klaritromisin', siddet: 'ciddi', not: 'KONTRENDİKE — güçlü CYP3A4 inhibisyonu ketiapin maruziyetini belirgin artırır (KÜB §4.3).' },
      { ile: 'İtrakonazol', siddet: 'ciddi', not: 'KONTRENDİKE — güçlü CYP3A4 inhibitörü (KÜB §4.3).' },
      { ile: 'Karbamazepin', siddet: 'ciddi', not: 'Güçlü indüksiyon ketiapin düzeyini belirgin düşürür; etkinlik kaybı.' },
      { ile: 'QT uzatan ilaç', siddet: 'ciddi', not: 'Ketiapin QT uzatır; birlikte kullanımda aritmi riski artar.' },
    ],
    gebelik: { metin: 'Gebelikte yarar/risk değerlendirilir; 3. trimesterde yenidoğanda ekstrapiramidal ve yoksunluk belirtileri bildirilmiştir.' },
    emzirme: 'Anne sütüne geçer; emzirme döneminde önerilmez.',
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Metabolik izlem (kilo, açlık glukozu, lipid) zorunludur. Yaşlı demans hastalarında mortalite artışı nedeniyle endike değildir.',
    kaynak: kub('GYREX 50 MG FİLM KAPLI TABLET (onay 12/06/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/onaylkb50_17_06_2026.pdf'),
  },

  olanzapin: {
    name: 'Olanzapin',
    brand: ['Zyprexa', 'Olaxinn', 'Rexapin', 'Zolaxa'],
    dose: 'Şizofreni: başlangıç 10 mg/gün. Manik dönem: monoterapide 15 mg/gün, kombinasyonda 10 mg/gün. Bipolar reküransın önlenmesi: 10 mg/gün.',
    pediatricDose: '13–17 yaş ergenlerde 2,5–20 mg/gün aralığında çalışılmıştır; rutin pediyatrik kullanımı tavsiye edilmez',
    form: 'Ağızda dağılan tablet, film kaplı tablet, IM flakon',
    sgkCovered: true,
    sgkRestriction: 'SUT: psikiyatri uzman hekim raporu koşullarına bakınız.',
    category: 'Atipik antipsikotik',
    siniflar: ['Antipsikotik', 'Atipik antipsikotik', 'SSS depresanı'],
    contraindications: ['Olanzapine aşırı duyarlılık', 'Dar açılı glokom riski'],
    interactions: ['Karbamazepin', 'Fluvoksamin', 'Siprofloksasin', 'Alkol', 'Benzodiazepinler', 'Sigara'],
    etkilesimler: [
      ...SSS_DEPRESAN_ETKILESIM,
      { ile: 'Karbamazepin', siddet: 'orta', not: 'CYP1A2 indüksiyonu olanzapin klerensini artırır; etkinlik azalabilir.' },
      { ile: 'Siprofloksasin', siddet: 'ciddi', not: 'CYP1A2 inhibisyonu olanzapin düzeyini yükseltir; sedasyon ve yan etki riski.' },
    ],
    gebelik: { metin: 'Gebelikte yarar/risk değerlendirilir; 3. trimesterde neonatal ekstrapiramidal/yoksunluk belirtileri bildirilmiştir.' },
    emzirme: 'Anne sütüne geçer; emzirme döneminde önerilmez.',
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Kilo alımı ve metabolik sendrom riski atipikler içinde en yüksekler arasındadır — kilo, HbA1c ve lipid izlenmelidir.',
    kaynak: kub('OLAXINN 5 MG AĞIZDA DAĞILAN TABLET (onay 19/02/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/OLAXNNKBONAY_02_04_2026.pdf'),
  },

  risperidon: {
    name: 'Risperidon',
    brand: ['Risperdal', 'Rixper', 'Risperon', 'Redilin'],
    dose: 'Şizofreni (erişkin): 2 mg/gün ile başlanır, 2. gün 4 mg\'a çıkarılabilir; çoğu hastada optimal doz 4–6 mg/gün.',
    pediatricDose: '<20 kg: 0,25 mg/gün ile başlanır; ≥20 kg: 0,5 mg/gün. 4. günde aynı miktarda artırılabilir',
    pediatrik: {
      min: 0.25, max: 0.5, birim: 'mg/kg/gün', gunlukBolum: 1,
      metin: 'KÜB §4.2 (kiloya göre sabit doz, mg/kg değil): dozlamaya 20 kg\'ın altındaki hastalar için günde 0,25 mg, 20 kg ve üstündeki hastalar için günde 0,5 mg ile başlanır. 4. günde doz sırasıyla 0,25 mg / 0,5 mg artırılabilir; yanıt yaklaşık 14. günde değerlendirilir. 18 yaş altı bipolar manide veri yetersizliği nedeniyle önerilmez.',
    },
    form: 'Film kaplı tablet, ağızda dağılan tablet, oral çözelti, uzun etkili enjeksiyon',
    sgkCovered: true,
    sgkRestriction: 'SUT: psikiyatri uzman hekim raporu koşullarına bakınız.',
    category: 'Atipik antipsikotik',
    siniflar: ['Antipsikotik', 'Atipik antipsikotik', 'SSS depresanı', 'QT uzatan ilaç'],
    contraindications: ['Risperidona aşırı duyarlılık'],
    interactions: ['Karbamazepin', 'Fluoksetin', 'Paroksetin', 'Antihipertansifler', 'Levodopa', 'QT uzatan ilaçlar', 'Alkol'],
    etkilesimler: [
      ...SSS_DEPRESAN_ETKILESIM,
      { ile: 'Karbamazepin', siddet: 'ciddi', not: 'CYP3A4 indüksiyonu risperidon aktif fraksiyonunu düşürür; doz ayarı gerekir.' },
      { ile: 'Fluoksetin', siddet: 'ciddi', not: 'CYP2D6 inhibisyonu risperidon plazma düzeyini yükseltir; ekstrapiramidal yan etki riski.' },
      { ile: 'Paroksetin', siddet: 'ciddi', not: 'CYP2D6 inhibisyonu ile risperidon maruziyeti artar.' },
      { ile: 'Levodopa', siddet: 'orta', not: 'Antipsikotik dopamin antagonizması levodopanın etkisini azaltır.' },
      { ile: 'Antihipertansif', siddet: 'orta', not: 'Ortostatik hipotansiyon riski artar.' },
    ],
    gebelik: { metin: 'Gebelikte yarar/risk değerlendirilir; 3. trimesterde neonatal ekstrapiramidal/yoksunluk belirtileri.' },
    emzirme: 'Anne sütüne geçer; emzirme döneminde önerilmez.',
    bobrekDozUyarisi: true,
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Atipikler içinde prolaktin yükseltme etkisi en belirgin olanlardandır (galaktore, amenore, jinekomasti).',
    kaynak: kub('RIXPER 1 MG FİLM KAPLI TABLET (onay 06/05/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/EkEk3RXPER1mgKUBtemiz_06_05_2026.pdf'),
  },

  aripiprazol: {
    name: 'Aripiprazol',
    brand: ['Abilify', 'Madepzol', 'Arilex', 'Aribit'],
    dose: 'Şizofreni (erişkin): başlangıç 10–15 mg/gün, idame 15 mg/gün. Etkili aralık 10–30 mg/gün; günlük maksimum doz 30 mg\'ı aşmamalıdır.',
    pediatricDose: '13–17 yaş şizofrenide: 2 gün 2 mg, sonraki 2 gün 5 mg, ardından önerilen 10 mg/gün; maksimum 30 mg/gün',
    pediatrik: {
      min: 2, max: 10, birim: 'mg/kg/gün', gunlukBolum: 1,
      mutlakMaxMgGun: 30, enAzAy: 156,
      metin: 'KÜB §4.2 (sabit doz, mg/kg değil): 13–17 yaş ergenlerde şizofrenide önerilen doz günde tek doz 10 mg. Tedavi ilk 2 gün 2 mg ile başlatılır, sonraki 2 gün 5 mg\'a titre edilir ve 10 mg/gün\'e ulaşılır. Doz artışları 5 mg\'lık adımlarla, günlük maksimum 30 mg\'ı geçmeyecek şekilde yapılır.',
    },
    form: 'Tablet, ağızda dağılan tablet, oral çözelti',
    sgkCovered: true,
    sgkRestriction: 'SUT: psikiyatri uzman hekim raporu koşullarına bakınız.',
    category: 'Atipik antipsikotik (kısmi dopamin agonisti)',
    siniflar: ['Antipsikotik', 'Atipik antipsikotik', 'Dopamin kısmi agonisti'],
    contraindications: ['Aripiprazole aşırı duyarlılık'],
    interactions: ['Karbamazepin', 'Rifampisin', 'Ketokonazol', 'Kinidin', 'Fluoksetin', 'Paroksetin', 'Alkol'],
    etkilesimler: [
      ...SSS_DEPRESAN_ETKILESIM,
      { ile: 'Karbamazepin', siddet: 'ciddi', not: 'Güçlü CYP3A4 indükleyicisi aripiprazol düzeyini yarıya düşürür; doz iki katına çıkarılmalıdır.' },
      { ile: 'İtrakonazol', siddet: 'ciddi', not: 'Güçlü CYP3A4 inhibitörü — aripiprazol dozu yarıya indirilmelidir.' },
      { ile: 'Paroksetin', siddet: 'orta', not: 'CYP2D6 inhibisyonu aripiprazol maruziyetini artırır; doz azaltımı gerekebilir.' },
    ],
    gebelik: { metin: 'Gebelikte yarar/risk değerlendirilir; 3. trimesterde neonatal ekstrapiramidal/yoksunluk belirtileri.' },
    emzirme: 'Anne sütüne geçer; emzirme döneminde önerilmez.',
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Şiddetli karaciğer yetmezliğinde günlük maksimum doz 30 mg ile sınırlıdır. Akatizi ve dürtü kontrol bozukluğu (kumar, alışveriş) sorgulanmalıdır.',
    kaynak: kub('MADEPZOL 20 MG TABLET (onay 04/12/2025)', 'https://titck.gov.tr/storage/Archive/2025/kubKtAttachments/MADEPZOL20mgtabletkub_11_12_2025.pdf'),
  },

  alprazolam: {
    name: 'Alprazolam',
    brand: ['Xanax', 'Apo-Alpraz', 'Alprazolam'],
    dose: 'En düşük etkili dozda, en kısa sürede ve EN FAZLA 2–4 hafta. Doz belirtilerin şiddetine ve yanıta göre bireyselleştirilir.',
    pediatricDose: '18 yaşından küçük çocuklarda etkililik ve güvenlilik kanıtlanmamıştır',
    form: 'Tablet, XR tablet',
    sgkCovered: true,
    sgkRestriction: 'YEŞİL REÇETE ile satılır (TİTCK kontrole tabi ilaçlar).',
    category: 'Benzodiazepin (anksiyolitik)',
    siniflar: ['Benzodiazepin', 'Anksiyolitik', 'SSS depresanı', 'Sedatif'],
    yasKontrendikasyonAy: 216,
    contraindications: [
      'Benzodiazepinlere aşırı duyarlılık',
      'Miyastenia gravis',
      'Ağır solunum yetmezliği',
      'Uyku apnesi sendromu',
      'Ağır karaciğer yetmezliği',
      'Dar açılı glokom',
      '18 yaş altı',
    ],
    interactions: ['Opioidler', 'Alkol', 'Antihistaminikler', 'İtrakonazol', 'Ketokonazol', 'Klaritromisin', 'Fluvoksamin'],
    etkilesimler: [
      ...SSS_DEPRESAN_ETKILESIM,
      { ile: 'İtrakonazol', siddet: 'ciddi', not: 'Güçlü CYP3A4 inhibisyonu alprazolam düzeyini belirgin yükseltir; aşırı sedasyon riski.' },
      { ile: 'Klaritromisin', siddet: 'ciddi', not: 'CYP3A4 inhibisyonu ile alprazolam maruziyeti artar.' },
      { ile: 'Tramadol', siddet: 'ciddi', not: 'Opioid + benzodiazepin: solunum depresyonu, koma ve ölüm riski (opioid KÜB §4.5).' },
    ],
    gebelik: { metin: 'Gebelikte kullanılmamalıdır; geç gebelikte neonatal floppy infant sendromu ve yoksunluk riski.' },
    emzirme: 'Anne sütüne geçer; emzirme döneminde önerilmez.',
    karacigerDozUyarisi: true,
    renkliRecete: 'yesil',
    notes: 'Bağımlılık riski doz ve süreyle artar. Ani kesilmesi nöbet dahil ciddi yoksunluk yapar — kademeli azaltılmalıdır.',
    kaynak: kub('XANAX 0,5 MG TABLET (onay 23/06/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/1311kub_23_06_2026.pdf'),
  },

  lorazepam: {
    name: 'Lorazepam',
    brand: ['Ativan', 'Lorans', 'Loramet'],
    dose: 'Anksiyete: mümkün olduğunca kısa süre. Toplam tedavi süresi (kademeli azaltma dahil) genellikle 8–12 haftayı aşmamalıdır.',
    pediatricDose: '12 yaşından küçük çocuklarda güvenlilik ve etki saptanmamıştır, tavsiye edilmez',
    form: 'Ağızda dağılan (expidet) tablet, tablet, ampul',
    sgkCovered: true,
    sgkRestriction: 'YEŞİL REÇETE ile satılır (TİTCK kontrole tabi ilaçlar).',
    category: 'Benzodiazepin (anksiyolitik)',
    siniflar: ['Benzodiazepin', 'Anksiyolitik', 'SSS depresanı', 'Sedatif'],
    yasKontrendikasyonAy: 144,
    contraindications: [
      'Benzodiazepinlere aşırı duyarlılık',
      'Miyastenia gravis',
      'Ağır solunum yetmezliği',
      'Uyku apnesi sendromu',
      'Ağır karaciğer yetmezliği',
      'Dar açılı glokom',
      '12 yaş altı',
    ],
    interactions: ['Opioidler', 'Alkol', 'Antihistaminikler', 'Antipsikotikler', 'Valproat', 'Klozapin'],
    etkilesimler: [
      ...SSS_DEPRESAN_ETKILESIM,
      { ile: 'Valproik asit', siddet: 'orta', not: 'Lorazepam klerensini azaltır; sedasyon artabilir, doz azaltımı gerekebilir.' },
    ],
    gebelik: { metin: 'Gebelikte kullanılmamalıdır; geç gebelikte floppy infant sendromu ve neonatal yoksunluk riski.' },
    emzirme: 'Anne sütüne geçer; emzirme döneminde önerilmez.',
    karacigerDozUyarisi: true,
    renkliRecete: 'yesil',
    notes: 'Glukuronidasyonla metabolize olur — karaciğer yetmezliğinde diğer benzodiazepinlere göre daha güvenli kabul edilir.',
    kaynak: kub('ATIVAN EXPIDET 1 MG TABLET (onay 26/02/2025)', 'https://titck.gov.tr/storage/Archive/2025/kubKtAttachments/ATIVAN1mgKB_26_02_2025.pdf'),
  },

  lamotrijin: {
    name: 'Lamotrijin',
    brand: ['Lamictal', 'Pinral', 'Lamotrin', 'Lamirax'],
    dose: 'Erişkin monoterapi: ilk 2 hafta 25 mg/gün, sonraki 2 hafta 50 mg/gün; sonra 1–2 haftada bir maksimum 50–100 mg artışla idame dozuna çıkılır. Döküntü riski nedeniyle titrasyon hızı ASLA aşılmamalıdır.',
    pediatricDose: 'Tipik absans monoterapisinde ilk 2 hafta 0,3 mg/kg/gün, sonraki hafta 0,6 mg/kg/gün; sonra 1–2 haftada en fazla 0,6 mg/kg artış',
    pediatrik: {
      min: 0.3, max: 0.6, birim: 'mg/kg/gün', gunlukBolum: 2,
      metin: 'KÜB §4.2: tipik absans nöbetinde monoterapi başlangıcı ilk iki hafta için günde bir ya da iki kez toplam 0,3 mg/kg/gün, sonraki hafta 0,6 mg/kg/gün. Ardından doz her 1–2 haftada en fazla 0,6 mg/kg artırılarak optimal doza ulaşılır. Valproat ile birlikte kullanımda başlangıç dozu daha düşüktür (0,15 mg/kg/gün). Döküntü riskinden dolayı başlangıç dozu ve doz artışları AŞILMAMALIDIR.',
    },
    form: 'Çiğnenebilir/çözünebilir tablet, tablet',
    sgkCovered: true,
    category: 'Antiepileptik / duygudurum düzenleyici',
    siniflar: ['Antiepileptik', 'Duygudurum düzenleyici'],
    contraindications: ['Lamotrijine aşırı duyarlılık'],
    interactions: ['Valproik asit', 'Karbamazepin', 'Fenitoin', 'Rifampisin', 'Oral kontraseptifler'],
    etkilesimler: [
      { ile: 'Valproik asit', siddet: 'ciddi', not: 'Lamotrijin metabolizmasını yavaşlatır, düzeyi iki katına çıkarır; başlangıç dozu ve titrasyon YARIYA indirilmeli — aksi halde ciddi döküntü/SJS riski (KÜB §4.2/4.5).' },
      { ile: 'Karbamazepin', siddet: 'ciddi', not: 'Enzim indüksiyonu lamotrijin düzeyini düşürür; titrasyon şeması farklıdır.' },
      { ile: 'Oral kontraseptif', siddet: 'ciddi', not: 'Östrojen içeren kontraseptifler lamotrijin düzeyini belirgin düşürür; başlarken/bırakırken doz ayarı gerekir.' },
      { ile: 'Rifampisin', siddet: 'orta', not: 'Lamotrijin klerensini artırır; doz artırımı gerekebilir.' },
    ],
    gebelik: { metin: 'Antiepileptikler içinde gebelikte en çok tercih edilenlerdendir; ancak gebelikte klerens arttığı için düzey ve doz izlenmelidir.' },
    emzirme: 'Anne sütüne belirgin geçer; bebek döküntü ve sedasyon açısından izlenmelidir.',
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Stevens-Johnson sendromu/TEN riski titrasyon hızıyla doğrudan ilişkilidir. Herhangi bir döküntüde ilaç DERHAL kesilmelidir.',
    kaynak: kub('PİNRAL 50 MG ÇİĞNENEBİLİR/ÇÖZÜNEBİLİR TABLET (onay 09/05/2025)', 'https://titck.gov.tr/storage/Archive/2025/kubKtAttachments/PNRAL50MGKB_13_05_2025.pdf'),
  },

  levetirasetam: {
    name: 'Levetirasetam',
    brand: ['Keppra', 'Levemax', 'Epixx', 'Levetiam'],
    dose: 'Erişkin ve ≥50 kg adolesan: başlangıç günde iki kez 500 mg; günlük toplam doz iki eşit doza bölünerek verilir.',
    pediatricDose: 'Başlangıç günde iki kez 10 mg/kg; maksimum günde iki kez 30 mg/kg',
    pediatrik: {
      min: 20, max: 60, birim: 'mg/kg/gün', gunlukBolum: 2,
      maxMgKgGun: 60, mutlakMaxMgGun: 3000, enAzAy: 48,
      metin: 'KÜB §4.2: pediyatride başlangıç dozu günde iki kez 10 mg/kg; klinik yanıt ve toleransa göre günde iki kez 30 mg/kg\'a çıkarılabilir (yani 20–60 mg/kg/gün). Doz değişiklikleri her 2 haftada bir, günde iki kez 10 mg/kg\'ı geçmeyecek şekilde yapılır. Film kaplı tablet 4 yaşın altında ve 25 kg altındaki çocuklarda uygun değildir — oral çözelti kullanılır.',
    },
    form: 'Film kaplı tablet, oral çözelti, IV konsantre',
    sgkCovered: true,
    category: 'Antiepileptik',
    siniflar: ['Antiepileptik', 'SV2A ligandı'],
    contraindications: ['Levetirasetam veya diğer pirolidon türevlerine aşırı duyarlılık'],
    interactions: ['Alkol', 'Metotreksat'],
    etkilesimler: [
      { ile: 'Metotreksat', siddet: 'orta', not: 'Metotreksat klerensi azalabilir; birlikte kullanımda MTX düzeyi izlenmelidir.' },
      { ile: 'Alkol', siddet: 'orta', not: 'Santral yan etkiler artar.' },
    ],
    gebelik: { metin: 'Antiepileptikler içinde gebelikte tercih edilenlerdendir; gebelikte klerens arttığı için doz izlemi gerekir.' },
    emzirme: 'Anne sütüne belirgin geçer; bebek sedasyon ve beslenme açısından izlenmelidir.',
    bobrekDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Davranışsal yan etkiler (irritabilite, agresyon, depresyon) sıktır ve aileye anlatılmalıdır. Böbrekle atılır — doz kreatinin klerensine göre ayarlanır.',
    kaynak: kub('LEVEMAX 250 MG FİLM KAPLI TABLET (onay 02/07/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/Xek41311kubtemizkopya_03_07_2026.pdf'),
  },

  valproikAsit: {
    name: 'Valproik asit / Sodyum valproat',
    brand: ['Depakin', 'Convulex', 'Neveso', 'Valpro'],
    dose: 'Erişkinlerde 20–30 mg/kg/gün. Başlangıç genellikle 10–15 mg/kg/gün, sonra optimum doza titre edilir. Optimum doz klinik yanıta göre saptanır.',
    pediatricDose: '6–11 yaş: ~30 mg/kg/gün; ergenlerde 20–30 mg/kg/gün',
    pediatrik: {
      min: 20, max: 30, birim: 'mg/kg/gün', gunlukBolum: 2,
      maxMgKgGun: 30, enAzAy: 72,
      metin: 'KÜB §4.2: epilepside 6–11 yaş arası çocuklarda dozaj 30 mg/kg/gün civarındadır; ergenlik çağındaki çocuklarda 20–30 mg/kg (uzatılmış salımlı form tercih edilir). Başlangıç dozu genellikle 10–15 mg/kg/gün. Bu uzatılmış salımlı form 6 yaşın altındaki çocuklar için uygun değildir.',
    },
    form: 'Uzatılmış salımlı film tablet, şurup, enterik tablet, IV',
    sgkCovered: true,
    category: 'Antiepileptik / duygudurum düzenleyici',
    siniflar: ['Antiepileptik', 'Duygudurum düzenleyici', 'Enzim inhibitörü'],
    contraindications: [
      'Valproata aşırı duyarlılık',
      'Akut veya kronik hepatit, ailede ciddi hepatit öyküsü',
      'Üre döngüsü bozuklukları',
      'Mitokondriyal hastalıklar (POLG mutasyonu)',
      'Porfiri',
      'Gebelik (bipolar bozuklukta mutlak; epilepside alternatif yoksa özel koşullarla)',
      'Gebelik önleme programına uymayan doğurganlık çağındaki kadınlar',
    ],
    interactions: ['Lamotrijin', 'Karbamazepin', 'Fenitoin', 'Karbapenemler', 'Aspirin', 'Lorazepam', 'Varfarin'],
    etkilesimler: [
      { ile: 'Lamotrijin', siddet: 'ciddi', not: 'Lamotrijin düzeyini iki katına çıkarır; lamotrijin başlangıç dozu ve titrasyonu yarıya indirilmeli (ciddi döküntü riski).' },
      { ile: 'Karbamazepin', siddet: 'ciddi', not: 'Karbamazepin epoksit metaboliti artar (nörotoksisite); valproat düzeyi düşer.' },
      { ile: 'Asetilsalisilik asit', siddet: 'ciddi', not: 'Valproatı proteinden ayırarak serbest fraksiyonunu artırır; toksisite riski.' },
      { ile: 'Varfarin', siddet: 'ciddi', not: 'Protein bağlanma yarışması INR\'yi yükseltebilir.' },
      { ile: 'Lorazepam', siddet: 'orta', not: 'Benzodiazepin klerensini azaltır, sedasyon artar.' },
    ],
    gebelik: { metin: 'Gebelikte nöral tüp defekti ve nörogelişimsel bozukluk riski yüksektir — bipolar bozuklukta KONTRENDİKE, epilepside alternatif yoksa gebelik önleme programı koşullarıyla. Doğurganlık çağındaki kadında etkili kontrasepsiyon zorunludur.' },
    emzirme: 'Anne sütüne az miktarda geçer; bebek trombositopeni ve karaciğer açısından izlenmelidir.',
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Hepatotoksisite ve pankreatit riski özellikle ilk 6 ayda yüksektir; karaciğer testleri ve tam kan sayımı izlenmelidir. Hiperamonyemik ensefalopati bildirilmiştir.',
    kaynak: kub('NEVESO XR 199,8 MG/87 MG UZATILMIŞ SALIMLI FİLM KAPLI TABLET (onay 28/11/2018)', 'https://titck.gov.tr/storage/Archive/2019/kubKtAttachments/490a08ff-8a19-4b5a-ae4e-edaff327590f.pdf'),
  },

  karbamazepin: {
    name: 'Karbamazepin',
    brand: ['Tegretol', 'Karazepin', 'Karbalex', 'Temporol'],
    dose: 'Erişkin: genellikle iki veya üç bölünmüş doz halinde, yemekle veya yemek aralarında. Maksimum önerilen doz 1200 mg/gün.',
    pediatricDose: '10–20 mg/kg/gün bölünmüş dozlarda. 5–10 yaş: 400–600 mg/gün; 10–15 yaş: 600–1000 mg/gün',
    pediatrik: {
      min: 10, max: 20, birim: 'mg/kg/gün', gunlukBolum: 3,
      maxMgKgGun: 20, mutlakMaxMgGun: 1200, enAzAy: 60,
      metin: 'KÜB §4.2: çocuklarda günlük doz 10–20 mg/kg vücut ağırlığı, günlük bölünmüş dozlarda. 5–10 yaş: 400–600 mg/gün (2–3 × 200 mg); 10–15 yaş: 600–1000 mg/gün. Maksimum önerilen doz 1200 mg/gün. Tablet formu 5 yaşın altındaki çocuklarda önerilmemektedir.',
    },
    form: 'Tablet, kontrollü salım tablet, süspansiyon',
    sgkCovered: true,
    category: 'Antiepileptik / duygudurum düzenleyici',
    siniflar: ['Antiepileptik', 'Duygudurum düzenleyici', 'CYP3A4 indükleyicisi', 'Enzim indükleyicisi'],
    yasKontrendikasyonAy: 60,
    contraindications: [
      'Karbamazepin veya yapısal benzeri ilaçlara (trisiklik antidepresanlar) aşırı duyarlılık',
      'AV blok',
      'Kemik iliği depresyonu öyküsü',
      'Hepatik porfiri',
      'MAO inhibitörü kullanımı',
    ],
    interactions: ['Oral kontraseptifler', 'Varfarin', 'Lamotrijin', 'Valproik asit', 'Klaritromisin', 'Statinler', 'Ketiapin', 'Aripiprazol', 'Levotiroksin', 'Direkt oral antikoagülanlar'],
    etkilesimler: [
      { ile: 'Oral kontraseptif', siddet: 'ciddi', not: 'Güçlü enzim indüksiyonu kontraseptif etkinliği ortadan kaldırır; alternatif/ek korunma ZORUNLUDUR.' },
      { ile: 'Varfarin', siddet: 'ciddi', not: 'Varfarin metabolizmasını hızlandırır, INR düşer; tromboz riski.' },
      { ile: 'Klaritromisin', siddet: 'ciddi', not: 'CYP3A4 inhibisyonu karbamazepin düzeyini yükseltir; toksisite riski.' },
      { ile: 'Lamotrijin', siddet: 'ciddi', not: 'Lamotrijin düzeyini düşürür; titrasyon şeması farklıdır.' },
      { ile: 'Ketiapin', siddet: 'ciddi', not: 'Ketiapin düzeyini belirgin düşürür; etkinlik kaybı.' },
      { ile: 'Aripiprazol', siddet: 'ciddi', not: 'Aripiprazol düzeyini yarıya düşürür; doz iki katına çıkarılmalıdır.' },
      { ile: 'Levotiroksin', siddet: 'orta', not: 'Tiroid hormonu metabolizmasını hızlandırır; TSH izlenmelidir.' },
      { ile: 'Statin', siddet: 'orta', not: 'Statin maruziyetini düşürerek lipid kontrolünü bozabilir.' },
    ],
    gebelik: { metin: 'Nöral tüp defekti ve diğer major malformasyon riski artmıştır; gebelik planlayan kadında alternatif değerlendirilmeli, folik asit desteği verilmelidir.' },
    emzirme: 'Anne sütüne geçer; bebek sedasyon ve sarılık açısından izlenerek emzirme genellikle sürdürülebilir.',
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Han Çinli ve Tayland kökenli hastalarda tedaviye başlamadan önce HLA-B*1502 taraması önerilir (SJS riski, KÜB §4.2/4.4). Hiponatremi ve agranülositoz izlenmelidir.',
    kaynak: kub('KARAZEPİN 200 MG TABLET (onay 26/03/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/KARAZEPN200KB_30_03_2026.pdf'),
  },

  pregabalin: {
    name: 'Pregabalin',
    brand: ['Lyrica', 'Alyse', 'Pregalin', 'Nervica'],
    dose: 'Günlük doz aralığı iki veya üç bölünmüş doz halinde 150–600 mg. Nöropatik ağrıda başlangıç 150 mg/gün; 3–7 gün sonra 300 mg, bir hafta sonra maksimum 600 mg/gün.',
    pediatricDose: '12 yaş altı çocuklarda ve 12–17 yaş adolesanlarda güvenlilik/etkililik belirlenmemiştir',
    form: 'Kapsül',
    sgkCovered: true,
    sgkRestriction: 'YEŞİL REÇETE ile düzenlenir (TİTCK kontrole tabi ilaçlar). SUT: nöropatik ağrı endikasyon koşullarına bakınız.',
    category: 'Gabapentinoid (alfa-2-delta ligandı)',
    siniflar: ['Antiepileptik', 'Gabapentinoid', 'Nöropatik ağrı ilacı', 'SSS depresanı'],
    yasKontrendikasyonAy: 216,
    contraindications: ['Pregabaline aşırı duyarlılık', '18 yaş altında güvenlilik belirlenmemiştir'],
    interactions: ['Opioidler', 'Benzodiazepinler', 'Alkol', 'Antihistaminikler'],
    etkilesimler: [
      ...SSS_DEPRESAN_ETKILESIM,
      { ile: 'Tramadol', siddet: 'ciddi', not: 'Opioid ile birlikte solunum depresyonu ve ölüm bildirilmiştir; en düşük dozda ve yakın izlemle.' },
    ],
    gebelik: { metin: 'Gebelikte major konjenital malformasyon riskinde artış bildirilmiştir; etkili kontrasepsiyon önerilir, gebelikte açık gereklilik dışında kullanılmaz.' },
    emzirme: 'Anne sütüne geçer; emzirme döneminde önerilmez.',
    bobrekDozUyarisi: true,
    renkliRecete: 'yesil',
    notes: 'Kötüye kullanım ve bağımlılık potansiyeli vardır (yeşil reçete). Böbrekle atılır — doz kreatinin klerensine göre ayarlanır. Ani kesilmesinden kaçınılmalıdır.',
    kaynak: kub('ALYSE 300 MG KAPSÜL (onay 16/04/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/ALYSE300mgkapslkub_17_04_2026.pdf'),
  },

  gabapentin: {
    name: 'Gabapentin',
    brand: ['Neurontin', 'Gabateva', 'Gabapen', 'Gabalept'],
    dose: 'Erişkin: 300 mg/gün ile başlanıp 2–3 günde bir 300 mg artışla maksimum 3600 mg/gün\'e çıkarılabilir; üç bölünmüş doz, dozlar arası en fazla 12 saat.',
    pediatricDose: '6 yaş ve üzeri: başlangıç 10–15 mg/kg/gün (üç doza bölünmüş); etkili doz 25–35 mg/kg/gün',
    pediatrik: {
      min: 25, max: 35, birim: 'mg/kg/gün', gunlukBolum: 3,
      maxMgKgGun: 50, mutlakMaxMgGun: 3600, enAzAy: 72,
      metin: 'KÜB §4.2: 6 yaş ve üzeri çocuklarda başlangıç dozu günde üç defa üç eşit doza bölünerek 10–15 mg/kg; etkili doz günde üç defa bölünerek 25–35 mg/kg. Uzun süreli bir klinik çalışmada 50 mg/kg/gün\'e kadar dozlar iyi tolere edilmiştir. 6 yaşından küçük çocuklarda ek tedavi ile ilgili yeterli deneyim yoktur.',
    },
    form: 'Kapsül, film tablet',
    sgkCovered: true,
    sgkRestriction: 'TİTCK kontrole tabi olabilecek maddeler listesinde — reçete türü ürün bazında doğrulanmalıdır.',
    category: 'Gabapentinoid (alfa-2-delta ligandı)',
    siniflar: ['Antiepileptik', 'Gabapentinoid', 'Nöropatik ağrı ilacı', 'SSS depresanı'],
    contraindications: ['Gabapentine aşırı duyarlılık'],
    interactions: ['Opioidler', 'Antiasitler', 'Alkol', 'Benzodiazepinler'],
    etkilesimler: [
      ...SSS_DEPRESAN_ETKILESIM,
      { ile: 'Antiasit', siddet: 'orta', not: 'Alüminyum/magnezyum içeren antiasitler gabapentin biyoyararlanımını azaltır; en az 2 saat ara verilmelidir.' },
      { ile: 'Tramadol', siddet: 'ciddi', not: 'Opioid ile birlikte solunum depresyonu riski artar.' },
    ],
    gebelik: { metin: 'Gebelikte veri sınırlıdır; yarar/risk değerlendirilir.' },
    emzirme: 'Anne sütüne geçer; bebek sedasyon açısından izlenmelidir.',
    bobrekDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Böbrekle atılır — doz kreatinin klerensine göre ayarlanır. Kötüye kullanım potansiyeli bildirilmiştir.',
    kaynak: kub('GABATEVA 300 MG KAPSÜL (onay 11/08/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/TTCKOnaylKBGABATEVA300MG_12_08_2026.pdf'),
  },

  topiramat: {
    name: 'Topiramat',
    brand: ['Topamax', 'Epimax', 'Topiragamma', 'Topamed'],
    dose: 'Düşük dozla başlanıp yavaş titre edilir. Erişkin adjuvan tedavide tipik olarak 25 mg/gün ile başlanır, 1–2 haftalık aralıklarla artırılır.',
    pediatricDose: '2–16 yaş adjuvan tedavide ~5–9 mg/kg/gün (ikiye bölünmüş); ilk hafta gece 25 mg veya 1–3 mg/kg/gün',
    pediatrik: {
      min: 5, max: 9, birim: 'mg/kg/gün', gunlukBolum: 2,
      maxMgKgGun: 30, enAzAy: 24,
      metin: 'KÜB §4.2: 2–16 yaş arası çocuklarda adjuvan tedavi olarak önerilen toplam günlük doz ikiye bölünmüş halde yaklaşık 5–9 mg/kg/gün. Titrasyon ilk haftada geceleri 25 mg (ya da 1–3 mg/kg/gün) ile başlatılır ve 1–2 haftalık aralıklarla 1–3 mg/kg/gün ilavelerle artırılır. Günlük 30 mg/kg\'a kadar dozlar araştırılmış ve genellikle iyi tolere edilmiştir.',
    },
    form: 'Film kaplı tablet, kapsül',
    sgkCovered: true,
    category: 'Antiepileptik',
    siniflar: ['Antiepileptik', 'Karbonik anhidraz inhibitörü', 'Migren profilaktiği'],
    contraindications: ['Topiramata aşırı duyarlılık', 'Migren profilaksisinde gebelik ve etkili kontrasepsiyon kullanmayan doğurgan kadınlar'],
    interactions: ['Fenitoin', 'Karbamazepin', 'Valproik asit', 'Oral kontraseptifler', 'Metformin', 'Asetazolamid', 'Lityum'],
    etkilesimler: [
      { ile: 'Oral kontraseptif', siddet: 'ciddi', not: 'Yüksek dozda kontraseptif etkinliği azaltabilir; ek korunma önerilir.' },
      { ile: 'Karbamazepin', siddet: 'orta', not: 'Topiramat plazma düzeyini düşürür; eklenirken/çıkarılırken doz ayarı gerekir (KÜB §4.2).' },
      { ile: 'Valproik asit', siddet: 'ciddi', not: 'Birlikte hiperamonyemi ve ensefalopati bildirilmiştir.' },
      { ile: 'Asetazolamid', siddet: 'ciddi', not: 'İki karbonik anhidraz inhibitörü: metabolik asidoz ve böbrek taşı riski toplanır.' },
      { ile: 'Lityum', siddet: 'orta', not: 'Lityum düzeyi değişebilir; izlem gerekir.' },
    ],
    gebelik: { metin: 'Yarık damak/dudak ve fetal büyüme geriliği riski artmıştır; migren profilaksisinde gebelikte kontrendikedir, epilepside alternatif değerlendirilmelidir.' },
    emzirme: 'Anne sütüne belirgin geçer; bebek izlenmelidir.',
    bobrekDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Böbrek taşı, metabolik asidoz, oligohidroz/hipertermi (özellikle çocukta sıcak havada) ve akut miyopik glokom bildirilmiştir. Bilişsel yavaşlama sıktır.',
    kaynak: kub('EPİMAX 25 MG FİLM KAPLI TABLET (onay 12/08/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/Ekek7temizkub_12_08_2026.pdf'),
  },

  metilfenidat: {
    name: 'Metilfenidat',
    brand: ['Concerta', 'Ritalin', 'Konsenidat', 'Medikinet'],
    dose: 'Tedavi DEHB\'de uzmanlaşmış hekim tarafından başlatılır ve denetlenir. Adolesanlarda (13–17 yaş) uzatılmış salımlı formda maksimum günlük doz 54 mg.',
    pediatricDose: '6–12 yaş ve 13–17 yaş adolesanlarda kullanılabilir; 6 yaş altında KULLANILMAZ',
    pediatrik: {
      min: 18, max: 54, birim: 'mg/kg/gün', gunlukBolum: 1,
      mutlakMaxMgGun: 54, enAzAy: 72,
      metin: 'KÜB §4.2 (sabit doz, mg/kg değil): uzatılmış salımlı formda çocuklarda (6–12 yaş) ve adolesanlarda (13–17 yaş) kullanılabilir; adolesanlarda kullanılabilecek maksimum günlük doz 54 mg\'dır. 6 yaşın altındaki çocuklarda kontrollü çalışmalarda incelenmemiştir ve kullanılmamalıdır.',
    },
    form: 'Uzatılmış salımlı tablet, kapsül, tablet',
    sgkCovered: true,
    sgkRestriction: 'KIRMIZI REÇETE ile düzenlenir (TİTCK uyuşturucu/psikotrop madde listesi). SUT: DEHB tanısı ve uzman raporu koşullarına bakınız.',
    category: 'Santral sinir sistemi stimülanı',
    siniflar: ['Psikostimülan', 'Stimülan', 'DEHB ilacı', 'Sempatomimetik'],
    yasKontrendikasyonAy: 72,
    contraindications: [
      'Metilfenidata aşırı duyarlılık',
      'Glokom',
      'Feokromositoma',
      'MAO inhibitörü kullanımı veya son 14 gün içinde kullanım',
      'Hipertiroidizm / tirotoksikoz',
      'Ciddi kardiyovasküler hastalık (aritmi, kanal hastalıkları, ciddi hipertansiyon, kalp yetmezliği, kardiyomiyopati)',
      'Serebrovasküler hastalık',
      'Ciddi depresyon, anoreksiya nervoza, psikotik semptomlar, intihar eğilimi',
      '6 yaş altı',
    ],
    interactions: ['MAO inhibitörleri', 'Antihipertansifler', 'Varfarin', 'Antiepileptikler', 'Alkol'],
    etkilesimler: [
      { ile: 'MAO inhibitörü', siddet: 'ciddi', not: 'KONTRENDİKE — hipertansif kriz riski (KÜB §4.3).' },
      { ile: 'Antihipertansif', siddet: 'orta', not: 'Metilfenidat kan basıncını yükselterek antihipertansif etkiyi azaltabilir.' },
      { ile: 'Varfarin', siddet: 'orta', not: 'Kumarin antikoagülan metabolizmasını etkileyebilir; INR izlenmelidir.' },
    ],
    gebelik: { metin: 'Gebelikte veri sınırlıdır; yarar/risk değerlendirilir ve tercihen kullanılmaz.' },
    emzirme: 'Anne sütüne geçer; emzirme döneminde önerilmez.',
    renkliRecete: 'kirmizi',
    notes: 'Tedavi öncesi kardiyovasküler değerlendirme, boy-kilo ve kan basıncı takibi zorunludur. En az yılda bir kez ilaçsız deneme ile yarar yeniden değerlendirilmelidir (KÜB §4.2).',
    kaynak: kub('KONSENIDAT 54 MG UZATILMIŞ SALIMLI TABLET (onay 15/05/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/ek4KONSENIDAT54mgUzatlmSalmlTabletKUBtemiz_15_05_2026.pdf'),
  },

  atomoksetin: {
    name: 'Atomoksetin',
    brand: ['Strattera', 'Atominex', 'Atomax'],
    dose: '70 kg üzeri erişkin ve adolesanda başlangıç 40 mg/gün, idame 80 mg/gün. Günlük önerilen maksimum toplam doz 100 mg.',
    pediatricDose: '6 yaş ve üzeri, ≤70 kg: başlangıç 0,5 mg/kg/gün; idame ~1,2 mg/kg/gün (maksimum 100 mg/gün)',
    pediatrik: {
      min: 0.5, max: 1.2, birim: 'mg/kg/gün', gunlukBolum: 1,
      maxMgKgGun: 1.8, mutlakMaxMgGun: 100, enAzAy: 72,
      metin: 'KÜB §4.2: vücut ağırlığı 70 kg\'a kadar olan 6 yaş ve üzeri çocuk ve ergenlerde başlangıç dozu günlük toplam ~0,5 mg/kg; en az 7 gün sürdürüldükten sonra klinik yanıta göre titre edilir. Tavsiye edilen idame dozu ~1,2 mg/kg/gün. Günde 1,2 mg/kg\'dan yüksek dozların ek yararı gösterilmemiştir; 1,8 mg/kg üzerindeki dozlar sistematik olarak değerlendirilmemiştir. Günlük önerilen maksimum toplam doz 100 mg. 6 yaşın altında kullanılmamalıdır.',
    },
    form: 'Kapsül',
    sgkCovered: true,
    sgkRestriction: 'SUT: DEHB tanısı ve uzman raporu koşullarına bakınız.',
    category: 'Selektif noradrenalin geri alım inhibitörü (DEHB)',
    siniflar: ['DEHB ilacı', 'Noradrenalin geri alım inhibitörü'],
    yasKontrendikasyonAy: 72,
    contraindications: [
      'Atomoksetine aşırı duyarlılık',
      'MAO inhibitörü kullanımı veya son 14 gün içinde kullanım',
      'Dar açılı glokom',
      'Ciddi kardiyovasküler veya serebrovasküler hastalık',
      'Feokromositoma',
      '6 yaş altı',
    ],
    interactions: ['MAO inhibitörleri', 'Paroksetin', 'Fluoksetin', 'Salbutamol', 'QT uzatan ilaçlar'],
    etkilesimler: [
      { ile: 'MAO inhibitörü', siddet: 'ciddi', not: 'KONTRENDİKE — ciddi, hayatı tehdit eden reaksiyonlar (KÜB §4.3).' },
      { ile: 'Paroksetin', siddet: 'ciddi', not: 'Güçlü CYP2D6 inhibisyonu atomoksetin maruziyetini belirgin artırır; doz azaltımı gerekir.' },
      { ile: 'Fluoksetin', siddet: 'ciddi', not: 'CYP2D6 inhibisyonu ile atomoksetin düzeyi yükselir.' },
      { ile: 'Salbutamol', siddet: 'orta', not: 'Kardiyovasküler etkiler (taşikardi, kan basıncı artışı) toplanabilir.' },
    ],
    gebelik: { metin: 'Gebelikte veri sınırlıdır; yalnızca potansiyel yarar riskten fazlaysa kullanılır.' },
    emzirme: 'Anne sütüne geçer; emzirme döneminde önerilmez.',
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Stimülan değildir — kırmızı reçete gerekmez. İntihar düşüncesi, hepatotoksisite ve kan basıncı/nabız artışı izlenmelidir.',
    kaynak: kub('ATOMİNEX 18 MG KAPSÜL (onay 25/11/2025)', 'https://titck.gov.tr/storage/Archive/2025/kubKtAttachments/atominex18ek3kub_12_12_2025.pdf'),
  },

  donepezil: {
    name: 'Donepezil',
    brand: ['Aricept', 'Rewind', 'Donepex', 'Alzaid'],
    dose: 'Günde tek doz 5 mg ile başlanır ve en az bir ay sürdürülür. Klinik yanıt değerlendirmesiyle günde tek doz 10 mg\'a yükseltilebilir. Önerilen en yüksek günlük doz 10 mg.',
    pediatricDose: 'Çocuk ve 18 yaş altı adolesanlarda kullanılması önerilmemektedir',
    form: 'Film tablet, efervesan tablet, ağızda dağılan tablet',
    sgkCovered: true,
    sgkRestriction: 'SUT: Alzheimer tanısı ve uzman hekim raporu koşullarına bakınız.',
    category: 'Asetilkolinesteraz inhibitörü',
    siniflar: ['Antidemansiyel', 'Asetilkolinesteraz inhibitörü', 'Kolinerjik'],
    yasKontrendikasyonAy: 216,
    contraindications: ['Donepezil veya piperidin türevlerine aşırı duyarlılık'],
    interactions: ['Beta blokörler', 'Antikolinerjikler', 'NSAİİ', 'Süksinilkolin', 'Ketokonazol', 'Rifampisin'],
    etkilesimler: [
      { ile: 'Beta blokör', siddet: 'ciddi', not: 'Bradikardi ve senkop riski toplanır; kalp hızı izlenmelidir.' },
      { ile: 'Antikolinerjik', siddet: 'ciddi', not: 'Karşılıklı antagonizma — donepezilin etkisi kaybolur, hasta için anlamsız iki ilaç.' },
      { ile: 'NSAİİ', siddet: 'orta', not: 'Kolinerjik etki gastrik asit salgısını artırır; ülser/kanama riski artar.' },
      { ile: 'İtrakonazol', siddet: 'orta', not: 'CYP3A4 inhibisyonu donepezil düzeyini yükseltebilir.' },
    ],
    gebelik: { metin: 'Endikasyon gereği gebelikte kullanımı beklenmez; veri yoktur.' },
    emzirme: 'Emzirme döneminde kullanılmamalıdır.',
    renkliRecete: 'normal',
    notes: 'Bradikardi, sinkop, GİS kanaması ve idrar retansiyonu açısından izlenmelidir. Anestezi öncesi kolinerjik etkisi anesteziste bildirilmelidir.',
    kaynak: kub('REWİND 5 MG EFERVESAN TABLET (onay 30/10/2025)', 'https://titck.gov.tr/storage/Archive/2025/kubKtAttachments/kubrewind5_19_11_2025.pdf'),
  },

  sumatriptan: {
    name: 'Sumatriptan',
    brand: ['İmigran', 'Sumatran', 'Migranol', 'Suminat'],
    dose: 'Migren atağında oral 50 mg (bazı hastalarda 25 veya 100 mg). İlk doza yanıt yoksa aynı atak için ikinci doz ALINMAZ. 24 saatte en fazla 300 mg. Profilaktik kullanılmaz.',
    pediatricDose: '18 yaşından küçük çocuklarda kullanılmaz',
    form: 'Film tablet, subkutan enjeksiyon, nazal sprey',
    sgkCovered: true,
    sgkRestriction: 'SUT: nörolog reçetesi veya nöroloji raporu koşullarına bakınız.',
    category: 'Triptan (5-HT1B/1D agonisti)',
    siniflar: ['Triptan', 'Serotonerjik ilaç', 'Antimigren', '5-HT1 agonisti'],
    yasKontrendikasyonAy: 216,
    contraindications: [
      'Sumatriptana aşırı duyarlılık',
      'İskemik kalp hastalığı, miyokard infarktüsü öyküsü, Prinzmetal anjina',
      'İnme veya geçici iskemik atak öyküsü',
      'Periferik vasküler hastalık',
      'Kontrolsüz hipertansiyon',
      'Hemiplejik, baziler veya oftalmoplejik migren',
      'Ergotamin veya diğer triptanlarla birlikte kullanım',
      'MAO inhibitörü kullanımı (son 2 hafta)',
      'Ciddi karaciğer yetmezliği',
      '18 yaş altı',
    ],
    interactions: ['Ergotamin', 'Diğer triptanlar', 'MAO inhibitörleri', 'SSRI', 'SNRI', 'Lityum'],
    etkilesimler: [
      { ile: 'Ergotamin', siddet: 'ciddi', not: 'KONTRENDİKE — uzamış vazospazm riski; ergot alındıktan sonra 24 saat, triptandan sonra 6 saat beklenmelidir (KÜB §4.3).' },
      { ile: 'Triptan', siddet: 'ciddi', not: 'KONTRENDİKE — iki triptan birlikte kullanılmaz (KÜB §4.3).' },
      { ile: 'MAO inhibitörü', siddet: 'ciddi', not: 'KONTRENDİKE — sumatriptan metabolizması MAO-A ile olur; MAOİ kesildikten sonra 2 hafta beklenmelidir (KÜB §4.3).' },
      { ile: 'SSRI', siddet: 'ciddi', not: 'Serotonin sendromu riski artar (KÜB §4.5).' },
      { ile: 'SNRI', siddet: 'ciddi', not: 'Serotonin sendromu riski artar (KÜB §4.5).' },
    ],
    gebelik: { metin: 'Gebelikte kullanım verisi malformasyon riski artışı göstermemiştir; yine de yarar/risk değerlendirilir.' },
    emzirme: 'Anne sütüne geçer; alımdan sonra 12 saat emzirmeye ara verilmesi önerilir.',
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Migren tanısı kesinleşmeden verilmemelidir (KÜB §4.4). Ayda 10 günden fazla kullanım ilaç aşırı kullanım baş ağrısı yapar.',
    kaynak: kub('İMİGRAN 100 MG FİLM TABLET (onay 12/08/2024)', 'https://titck.gov.tr/storage/Archive/2024/kubKtAttachments/MGRAN100KB_db866a8a-9dfa-4b21-bffa-bbedee1ee6b1.pdf'),
  },
}
