/**
 * Solunum ve alerji — beta2 agonistler, inhale/nazal kortikosteroidler, antikolinerjikler,
 * lökotrien antagonisti, H1 antihistaminikler.
 *
 * Inhaled and nasal steroids share one interaction that matters in outpatient practice and is
 * therefore written as a class: güçlü CYP3A4 inhibitörleri (ritonavir, itrakonazol, ketokonazol,
 * kobisistat) sistemik kortikosteroid maruziyetini artırır — her KÜB §4.5 bunu aynı cümleyle söyler.
 *
 * `pediatrik` is filled only where the KÜB states a weight-based number. Several products here dose
 * by AGE or by PUFF, not by mg/kg; for those the field carries the KÜB's own sentence and no numbers,
 * so the card cannot compute a dose that was never expressed per kilogram.
 */
import { kub } from '../kaynak'
import type { TürkishDrug } from '../tipler'

const KORTIKOSTEROID_CYP3A = [
  { ile: 'Ritonavir', siddet: 'ciddi' as const, not: 'Sistemik kortikosteroid maruziyetini birkaç yüz kat artırır, Cushing sendromu ve adrenal baskılanma; birlikte kullanımdan kaçınılmalı (KÜB §4.5).' },
  { ile: 'İtrakonazol', siddet: 'ciddi' as const, not: 'Güçlü CYP3A inhibisyonu — sistemik kortikosteroid yan etki riski artar (KÜB §4.5).' },
  { ile: 'Klaritromisin', siddet: 'orta' as const, not: 'Orta-güçlü CYP3A inhibitörü; sistemik steroid maruziyeti artabilir, hasta izlenmeli.' },
] as const

const ANTIHISTAMIN_ETKILESIM = [
  { ile: 'Alkol', siddet: 'orta' as const, not: 'Duyarlı hastalarda santral sinir sistemi depresyonu artar (KÜB §4.5).' },
] as const

export const SOLUNUM_ALERJI: Record<string, TürkishDrug> = {
  salbutamol: {
    name: 'Salbutamol',
    brand: ['Ventolin', 'Salbutamol', 'Salbutol', 'Asthmasian'],
    dose: 'İnhaler: gerektiğinde 100–200 mcg (1–2 püskürtme). Oral (şurup) yetişkin: günde 3–4 kez 4 mg.',
    pediatricDose: 'Şurup 2–6 yaş: 3–4×1–2 mg; 6–12 yaş: 3–4×2 mg; >12 yaş: 3–4×2–4 mg',
    pediatrik: {
      min: 1, max: 4, birim: 'mg/kg/doz', gunlukBolum: 4, enAzAy: 24,
      metin: 'KÜB §4.2 (yaşa göre sabit doz, mg/kg değil): şurup formunda 2–6 yaş günde 3–4 kez 1–2 mg; 6–12 yaş günde 3–4 kez 2 mg; 12 yaş üzeri günde 3–4 kez 2–4 mg. İnhaler form dozu püskürtme sayısıyla ifade edilir.',
    },
    form: 'Ölçülü doz inhaler, nebülizasyon çözeltisi, şurup, tablet',
    sgkCovered: true,
    category: 'Kısa etkili beta-2 agonist (SABA)',
    siniflar: ['Beta-2 agonist', 'SABA', 'Bronkodilatör', 'Beta-adrenerjik agonist'],
    contraindications: ['Salbutamole aşırı duyarlılık', 'IV olmayan formlarla erken doğum/düşük tehdidi tedavisi'],
    interactions: ['Non-selektif beta blokörler', 'MAO inhibitörleri', 'Diüretikler', 'Digoksin', 'Ksantin türevleri'],
    etkilesimler: [
      { ile: 'Propranolol', siddet: 'ciddi', not: 'Non-selektif beta blokör salbutamolün bronkodilatör etkisini bloke eder; astımlıda birlikte reçete edilmemelidir (KÜB §4.5).' },
      { ile: 'Beta blokör', siddet: 'ciddi', not: 'Beta blokörler beta-2 agonist etkisini antagonize eder; astımda non-selektif olanlar kontrendike kabul edilir.' },
      { ile: 'MAO inhibitörü', siddet: 'ciddi', not: 'KÜB §4.5: MAOİ ile tedavi edilen hastalarda kontrendike kabul edilir.' },
      { ile: 'Digoksin', siddet: 'orta', not: 'Beta2 agonistin yaptığı hipokalemi dijital toksisitesi ve aritmi eğilimini artırır.' },
      { ile: 'Diüretik', siddet: 'orta', not: 'Hipokalemi riski toplanır; potasyum izlenmelidir.' },
    ],
    gebelik: { kategori: 'C', metin: 'Gerekli olmadıkça gebelik döneminde kullanılmamalıdır; yarar/risk değerlendirilir (KÜB §4.6).' },
    emzirme: 'Anne sütüne geçebilir; inhale kullanımda sistemik maruziyet düşüktür.',
    renkliRecete: 'normal',
    notes: 'Artan SABA kullanımı astımın kötüleştiğinin işaretidir — tedavi planı ve inhale kortikosteroid gözden geçirilmelidir (KÜB §4.2).',
    kaynak: kub('VENTOLIN 2 MG/5 ML ŞURUP (onay 18/05/2023)', 'https://titck.gov.tr/storage/Archive/2023/kubKtAttachments/ventolinkubtemiz_d2333d15-2a14-49c5-8300-11b5cdd862ea.pdf'),
  },

  salmeterolFlutikazon: {
    name: 'Salmeterol + Flutikazon propiyonat',
    brand: ['Seretide', 'Airtide', 'Serevent-F', 'Flutiform'],
    dose: 'Yetişkin: günde 2 kez 1 inhalasyon (50/100, 50/250 veya 50/500 mcg — astım şiddetine göre). Sadece idame tedavisi.',
    pediatricDose: '4–12 yaş: günde 2 kez 1 inhalasyon (50 mcg salmeterol + 100 mcg flutikazon)',
    pediatrik: {
      min: 50, max: 100, birim: 'mikrogram/kg/gün', gunlukBolum: 2, enAzAy: 48,
      metin: 'KÜB §4.2 (inhalasyon başına sabit doz, mg/kg değil): 4–12 yaş arası çocuklarda günde 2 kez 1 inhalasyon (50 mikrogram salmeterol + 100 mikrogram flutikazon propiyonat). 4 yaşından küçük çocuklarda kullanım bilgisi yoktur.',
    },
    form: 'İnhalasyon tozu içeren kapsül, diskus, ölçülü doz inhaler',
    sgkCovered: true,
    sgkRestriction: 'SUT: astım/KOAH tanısı ve uzman hekim raporu koşullarına bakınız.',
    category: 'LABA + inhale kortikosteroid kombinasyonu',
    siniflar: ['Beta-2 agonist', 'LABA', 'İnhale kortikosteroid', 'Kortikosteroid', 'Bronkodilatör'],
    contraindications: ['Etkin maddelere veya yardımcı maddelere aşırı duyarlılık'],
    interactions: ['Ritonavir', 'Ketokonazol', 'İtrakonazol', 'Eritromisin', 'Beta blokörler'],
    etkilesimler: [
      ...KORTIKOSTEROID_CYP3A,
      { ile: 'Ketokonazol', siddet: 'ciddi', not: 'Plazma salmeterol maruziyetini belirgin artırır (EAA 15 kat); eş zamanlı kullanımdan kaçınılmalı (KÜB §4.5).' },
      { ile: 'Eritromisin', siddet: 'orta', not: 'Orta düzeyde CYP3A4 inhibitörü — salmeterol maruziyeti artabilir (KÜB §4.5).' },
      { ile: 'Beta blokör', siddet: 'ciddi', not: 'LABA etkisini antagonize eder; astımda kaçınılmalıdır.' },
    ],
    gebelik: { kategori: 'C', metin: '1000\'den fazla gebe verisi büyük malformasyon riskinde artış göstermemiştir; yarar/risk değerlendirmesiyle kullanılır (KÜB §4.6).' },
    emzirme: 'İnhale kullanımda sistemik düzey düşüktür; yarar/risk değerlendirilir.',
    renkliRecete: 'normal',
    notes: 'Semptom giderici (kurtarıcı) olarak KULLANILMAZ — sadece idame. Ağız kandidiyazını önlemek için kullanımdan sonra ağız çalkalanmalıdır.',
    kaynak: kub('AİRTİDE 250/50 MCG İNHALASYON TOZU (onay 11/06/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/ARTDE25050KBONAY_11_06_2026.pdf'),
  },

  formoterolBudesonid: {
    name: 'Formoterol + Budesonid',
    brand: ['Symbicort', 'Foradil-Combi', 'Duoresp', 'Bufomix'],
    dose: 'Yetişkin: astım şiddetine göre günde 1–2 kez 1–2 inhalasyon. Düşük dozlu formlar "idame ve semptom giderici" (SMART) rejiminde kullanılabilir.',
    pediatricDose: '6 yaş altında önerilmez; 6–12 yaş için düşük dozlu kombinasyon formları kullanılır',
    form: 'İnhalasyon tozu, turbuhaler, sert kapsül',
    sgkCovered: true,
    sgkRestriction: 'SUT: astım/KOAH tanısı ve uzman hekim raporu koşullarına bakınız.',
    category: 'LABA + inhale kortikosteroid kombinasyonu',
    siniflar: ['Beta-2 agonist', 'LABA', 'İnhale kortikosteroid', 'Kortikosteroid', 'Bronkodilatör'],
    yasKontrendikasyonAy: 72,
    contraindications: ['Etkin maddelere veya laktoza (süt proteini) aşırı duyarlılık', '6 yaş altı çocuklarda bu form önerilmez'],
    interactions: ['Ketokonazol', 'İtrakonazol', 'Beta blokörler', 'Trisiklik antidepresanlar', 'MAO inhibitörleri', 'Digoksin', 'Halojenli anestezikler', 'QT uzatan ilaçlar'],
    etkilesimler: [
      ...KORTIKOSTEROID_CYP3A,
      { ile: 'Ketokonazol', siddet: 'ciddi', not: 'Güçlü CYP3A4 inhibitörü budesonid plazma düzeyini artırır; zorunlu değilse birlikte kullanılmamalı (KÜB §4.5).' },
      { ile: 'Beta blokör', siddet: 'ciddi', not: 'Göz damlaları dahil beta blokörlerle birlikte kullanılmamalıdır (KÜB §4.5).' },
      { ile: 'Trisiklik antidepresan', siddet: 'ciddi', not: 'QTc uzayabilir, ventriküler aritmi riski artar (KÜB §4.5).' },
      { ile: 'MAO inhibitörü', siddet: 'ciddi', not: 'Hipertansif reaksiyon riski artar (KÜB §4.5).' },
      { ile: 'Digoksin', siddet: 'orta', not: 'Hipokalemi dijital tedavisi alan hastada aritmi eğilimini artırır (KÜB §4.5).' },
    ],
    gebelik: { kategori: 'C', metin: 'Yeterli gebe verisi yoktur; ancak yarar riskten fazlaysa kullanılabilir. Kontrol altındaki astım anne ve fetüs için tedavisiz astımdan daha güvenlidir (KÜB §4.6).' },
    emzirme: 'Budesonid anne sütüne geçer; terapötik inhale dozlarda bebekte etki beklenmez.',
    renkliRecete: 'normal',
    kaynak: kub('FORADİL-COMBİ FİX 320/9 MCG İNHALASYON TOZU (onay 03/06/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/Ek2RuhsattarihvenumaraseklenenKB_25_06_2026.pdf'),
  },

  budesonidInhaler: {
    name: 'Budesonid (inhale)',
    brand: ['Pulmicort', 'Maxair', 'Budenofalk', 'Miflonide'],
    dose: 'Bronşiyal astım erişkin başlangıç: günlük toplam 1–2 mg. Astım kontrol altına alındıktan sonra en düşük idame dozuna inilir.',
    pediatricDose: '6 aylık ve daha büyük çocuklarda günlük toplam 0,25–0,5 mg',
    pediatrik: {
      min: 0.25, max: 0.5, birim: 'mg/kg/gün', gunlukBolum: 2, enAzAy: 6,
      metin: 'KÜB §4.2 (sabit günlük doz, mg/kg değil): bronşiyal astımda 6 aylık ve daha büyük çocuklarda günlük toplam doz 0,25–0,5 mg (nebülizasyon süspansiyonu). Erişkinde günlük toplam 1–2 mg. Günde tek doz uygulaması 0,25–1 mg/gün dozları içindir.',
    },
    form: 'Nebülizasyon süspansiyonu, turbuhaler, ölçülü doz inhaler',
    sgkCovered: true,
    category: 'İnhale kortikosteroid',
    siniflar: ['İnhale kortikosteroid', 'Kortikosteroid', 'Glukokortikoid'],
    contraindications: ['Budesonide aşırı duyarlılık'],
    interactions: ['Ketokonazol', 'İtrakonazol', 'Ritonavir', 'Kobisistat'],
    etkilesimler: KORTIKOSTEROID_CYP3A,
    gebelik: { kategori: 'B', metin: 'Prospektif epidemiyolojik çalışmalar ve pazarlama sonrası veriler inhale budesonid için malformasyon riski artışı göstermemiştir; gebe kadınlara verilirken tedbirli olunmalıdır (KÜB §4.6).' },
    emzirme: 'Anne sütüne geçer; terapötik inhale dozlarda bebekte etki beklenmez.',
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Uzun süreli kullanımda çocukta boy takibi önerilir.',
    kaynak: kub('MAXAİR 0,5 MG/ML NEBÜLİZASYON SÜSPANSİYONU (onay 14/03/2025)', 'https://titck.gov.tr/storage/Archive/2025/kubKtAttachments/TTCKOnaylKBMAXAR05_17_03_2025.pdf'),
  },

  flutikazonNazal: {
    name: 'Flutikazon furoat (nazal)',
    brand: ['Avamys', 'Redulan', 'Flixonase'],
    dose: 'Yetişkin ve >12 yaş: başlangıç her burun deliğine günde bir kez 2 sprey (toplam 110 mcg); idamede günde bir kez 1 sprey (55 mcg).',
    pediatricDose: '2–11 yaş: her burun deliğine günde bir kez 1 sprey (toplam 55 mcg)',
    pediatrik: {
      min: 55, max: 110, birim: 'mikrogram/kg/gün', gunlukBolum: 1, enAzAy: 24,
      metin: 'KÜB §4.2 (sprey sayısıyla ifade edilen sabit doz, mg/kg değil): 2–11 yaş arası çocuklarda başlangıç her burun deliğine günde bir kez 1 sprey (günlük toplam 55 mikrogram); yeterli yanıt alınmazsa doz artırılabilir. 2–6 yaşta yarar/zarar gözetilerek kullanılmalıdır.',
    },
    form: 'Burun spreyi, süspansiyon',
    sgkCovered: true,
    category: 'Nazal kortikosteroid',
    siniflar: ['Nazal kortikosteroid', 'Kortikosteroid', 'Glukokortikoid'],
    contraindications: ['Flutikazon furoata aşırı duyarlılık'],
    interactions: ['Ritonavir', 'Kobisistat', 'İtrakonazol', 'Ketokonazol'],
    etkilesimler: KORTIKOSTEROID_CYP3A,
    gebelik: { metin: 'Gebede yeterli veri yoktur; hayvan çalışmalarında glukokortikoidlerin yarık damak ve intrauterin gelişme geriliği yaptığı bilinmektedir (KÜB §4.6).' },
    emzirme: 'İntranazal kullanımda sistemik maruziyet düşüktür; yarar/risk değerlendirilir.',
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    kaynak: kub('REDULAN 27,5 MCG BURUN SPREYİ (onay 03/02/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/yaynlanacakredulan1311kub_11_03_2026.pdf'),
  },

  mometazonNazal: {
    name: 'Mometazon furoat (nazal)',
    brand: ['Nasonex', 'Nazoster', 'Momecon', 'Nasomet'],
    dose: 'Yetişkin: her burun deliğine günde bir kez 2 sprey (toplam 200 mcg). Kontrol sağlanamazsa günlük maksimum her burun deliğine günde iki kez 2 sprey.',
    pediatricDose: 'Çocuklarda her burun deliğine günde bir kez 1 sprey (50 mcg)',
    form: 'Burun spreyi, süspansiyon',
    sgkCovered: true,
    category: 'Nazal kortikosteroid',
    siniflar: ['Nazal kortikosteroid', 'Kortikosteroid', 'Glukokortikoid'],
    contraindications: [
      'Mometazon furoata aşırı duyarlılık',
      'Tedavi edilmemiş lokalize nazal enfeksiyon (herpes simpleks dahil)',
      'Yakın geçmişte burun ameliyatı veya travması (yara iyileşene kadar)',
    ],
    interactions: ['Ritonavir', 'Kobisistat', 'İtrakonazol', 'Ketokonazol'],
    etkilesimler: KORTIKOSTEROID_CYP3A,
    gebelik: { kategori: 'C', metin: 'Gebe verisi yok veya sınırlı; hayvan çalışmalarında üreme toksisitesi. Yarar riskleri haklı çıkarmadıkça kullanılmaz (KÜB §4.6).' },
    emzirme: 'Sistemik maruziyet düşüktür; yarar/risk değerlendirilir.',
    renkliRecete: 'normal',
    notes: 'Uzun süre nazal kortikosteroid kullanan çocuklarda boy uzunluğu düzenli takip edilmelidir (KÜB §4.2).',
    kaynak: kub('NAZOSTER %0,05 BURUN SPREYİ (onay 11/08/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/NazosterKB_12_08_2026.pdf'),
  },

  ipratropyum: {
    name: 'İpratropyum bromür',
    brand: ['Atrovent', 'Ventopium', 'İprabül', 'İpravent'],
    dose: 'Yetişkin ve >12 yaş (nebül): günde 3–4 kez 250–500 mcg. Akut bronkospazmda 500 mcg, hasta stabilize olana kadar tekrarlanabilir.',
    pediatricDose: '12 yaş ve altında sadece 250 mcg/2 mL formu kullanılır',
    pediatrik: {
      min: 250, max: 250, birim: 'mikrogram/kg/gün', gunlukBolum: 3,
      metin: 'KÜB §4.2 (flakon başına sabit doz, mg/kg değil): 12 yaşındaki veya daha küçük çocuklarda sadece 250 mcg/2 mL formu kullanılmalıdır. 12 yaşından büyük çocuk ve erişkinde günde 3–4 kez 250–500 mcg.',
    },
    form: 'Nebülizasyon çözeltisi, ölçülü doz inhaler',
    sgkCovered: true,
    category: 'Kısa etkili antikolinerjik (SAMA)',
    siniflar: ['Antikolinerjik', 'SAMA', 'Muskarinik antagonist', 'Bronkodilatör'],
    contraindications: ['İpratropyum, atropin veya türevlerine aşırı duyarlılık'],
    interactions: ['Diğer antikolinerjikler', 'Beta-adrenerjikler', 'Ksantin türevleri'],
    etkilesimler: [
      { ile: 'Antikolinerjik', siddet: 'orta', not: 'Antikolinerjik yan etkiler toplanır (idrar retansiyonu, ağız kuruluğu, akut glokom riski) — birlikte kullanım önerilmez (KÜB §4.5).' },
      { ile: 'Teofilin', siddet: 'orta', not: 'Beta-adrenerjikler ve ksantin preparatlarıyla bronkodilatör etki toplanır; yan etki şiddeti artabilir (KÜB §4.5).' },
    ],
    gebelik: { metin: 'Gebede yeterli veri yoktur; yarar/risk değerlendirmesiyle kullanılır (KÜB §4.6).' },
    emzirme: 'Anne sütüne geçişi bilinmiyor; inhale kullanımda sistemik maruziyet düşüktür.',
    renkliRecete: 'normal',
    notes: 'Nebül maskeyle uygulanırken göze kaçması akut dar açılı glokom tetikleyebilir — ağızlık tercih edilmelidir.',
    kaynak: kub('VENTOPİUM 250 MCG/2 ML NEBÜLİZASYON ÇÖZELTİSİ (onay 17/05/2022)', 'https://titck.gov.tr/storage/Archive/2022/kubKtAttachments/VENTOPUM250mcg2mLneblizasyoniininhalasyonzeltisiierentekdozlukflakonKB_c48833b3-cfc7-4659-bc69-d5d3c52d725c.pdf'),
  },

  tiotropyum: {
    name: 'Tiotropyum bromür',
    brand: ['Spiriva', 'Tioumit', 'Braltus'],
    dose: 'Yetişkin: günde bir kez bir kapsül içeriğinin inhalasyonu (18 mcg). Önerilen dozdan fazlası kullanılmamalıdır.',
    form: 'İnhalasyon için toz içeren kapsül, respimat inhaler',
    sgkCovered: true,
    sgkRestriction: 'SUT: KOAH tanısı ve uzman hekim raporu koşullarına bakınız.',
    category: 'Uzun etkili antikolinerjik (LAMA)',
    siniflar: ['Antikolinerjik', 'LAMA', 'Muskarinik antagonist', 'Bronkodilatör'],
    yasKontrendikasyonAy: 216,
    contraindications: ['Tiotropyum, atropin veya türevlerine (ipratropyum, oksitropyum) aşırı duyarlılık', '18 yaş altı KOAH endikasyonu yoktur'],
    interactions: ['Diğer antikolinerjikler'],
    etkilesimler: [
      { ile: 'Antikolinerjik', siddet: 'orta', not: 'Diğer antikolinerjiklerle birlikte kullanım çalışılmamıştır ve önerilmez (KÜB §4.5).' },
    ],
    gebelik: { kategori: 'C', metin: 'Gebede yeterli veri yoktur; olası yarar fetüs riskine üstün olmadıkça kullanılmaz (KÜB §4.6).' },
    emzirme: 'Anne sütüne geçişi bilinmiyor; yarar/risk değerlendirilir.',
    renkliRecete: 'normal',
    notes: 'Kapsüller AĞIZDAN YUTULMAZ — sadece inhaler cihazla inhale edilir (KÜB §4.2).',
    kaynak: kub('TİOUMİT 18 MCG İNHALASYON KAPSÜLÜ (onay 12/07/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/EkOnaylananKBmetni_12_08_2026.pdf'),
  },

  montelukast: {
    name: 'Montelukast',
    brand: ['Singulair', 'Onceair', 'Airfix', 'Montelas', 'Notta'],
    dose: 'Yetişkin ve >15 yaş: günde bir kez 10 mg, akşam. 6–14 yaş: 5 mg. 2–5 yaş: 4 mg.',
    pediatricDose: '12 ay–5 yaş: 4 mg/gün; 6–14 yaş: 5 mg/gün (akşam tek doz)',
    pediatrik: {
      min: 4, max: 5, birim: 'mg/kg/gün', gunlukBolum: 1, enAzAy: 6,
      metin: 'KÜB §4.2 (yaşa göre sabit doz, mg/kg değil): 12 aylık–5 yaş arası astımda günde 1 kez 4 mg saşe, akşam. Alerjik rinitte 2–5 yaş mevsimsel, 6 aylık ve üstü pereniyal alerjik rinitte günde bir kez. 2 yaşın altında mevsimsel alerjik rinitte ve 6 aydan küçükte pereniyal alerjik rinitte güvenlilik gösterilmemiştir.',
    },
    form: 'Film tablet, çiğneme tableti, granül saşe',
    sgkCovered: true,
    sgkRestriction: 'SUT: astım tanısı ve uzman hekim raporu koşullarına bakınız.',
    category: 'Lökotrien reseptör antagonisti',
    siniflar: ['Lökotrien antagonisti', 'Antiastmatik', 'Antialerjik'],
    contraindications: ['Montelukasta aşırı duyarlılık'],
    interactions: ['Fenobarbital', 'Rifampisin', 'Gemfibrozil'],
    etkilesimler: [
      { ile: 'Rifampisin', siddet: 'orta', not: 'CYP3A4/2C8/2C9 indükleyicileri montelukast maruziyetini azaltabilir; birlikte kullanımda dikkat (KÜB §4.5).' },
      { ile: 'Fenobarbital', siddet: 'orta', not: 'Enzim indüksiyonu montelukast EAA\'sını düşürür (KÜB §4.5).' },
    ],
    gebelik: { metin: 'Gebe verisi sınırlıdır; yalnızca açıkça gerekliyse kullanılır (KÜB §4.6).' },
    emzirme: 'Anne sütüne geçip geçmediği bilinmiyor; yalnızca açıkça gerekliyse.',
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Nöropsikiyatrik olaylar (ajitasyon, uyku bozukluğu, davranış değişikliği, nadiren intihar düşüncesi) bildirilmiştir — aile bilgilendirilmelidir.',
    kaynak: kub('AİRFİX 4 MG GRANÜL İÇEREN SAŞE (onay 19/03/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/TTCKOnaylKBARFIX4MGGRANL_23_03_2026.pdf'),
  },

  setirizin: {
    name: 'Setirizin',
    brand: ['Zyrtec', 'Allerset', 'Cetrin', 'Setiral', 'Hitrizin'],
    dose: 'Yetişkin ve >12 yaş: günde bir kez 10 mg.',
    pediatricDose: '2–6 yaş: günde iki kez 2,5 mg; 6–12 yaş: günde iki kez 5 mg',
    pediatrik: {
      min: 2.5, max: 5, birim: 'mg/kg/doz', gunlukBolum: 2, enAzAy: 24,
      metin: 'KÜB §4.2 (yaşa göre sabit doz, mg/kg değil): 2–6 yaş arası çocuklarda günde iki kez 2,5 mg; 6–12 yaş arası çocuklarda günde iki kez 5 mg; 12 yaş üstünde günde bir kez 10 mg.',
    },
    form: 'Film tablet, şurup, oral damla',
    sgkCovered: true,
    category: 'İkinci kuşak H1 antihistaminik',
    siniflar: ['Antihistaminik', 'H1 antagonisti', 'Piperazin türevi', 'İkinci kuşak antihistaminik'],
    contraindications: [
      'Setirizin, hidroksizin veya piperazin türevlerine aşırı duyarlılık',
      'Son dönem böbrek yetmezliği (eGFR <15 mL/dk)',
      'Kalıtımsal fruktoz intoleransı (şurup formu)',
    ],
    interactions: ['Alkol', 'Santral sinir sistemi depresanları', 'Teofilin'],
    etkilesimler: [...ANTIHISTAMIN_ETKILESIM, { ile: 'Teofilin', siddet: 'orta', not: 'Teofilin setirizin klerensini azaltır; maruziyet artar (KÜB §4.5).' }],
    gebelik: { metin: 'Prospektif veriler maternal veya embriyonal/fetal toksisite potansiyeli göstermemiştir; gebe kadınlara ancak gerekliyse verilir (KÜB §4.6).' },
    emzirme: 'Anne sütüne geçer; kısa süreli kullanımda genellikle uyumlu kabul edilir.',
    bobrekDozUyarisi: true,
    renkliRecete: 'normal',
    kaynak: kub('ALLERSET 1 MG/ML ŞURUP (onay 13/12/2024)', 'https://titck.gov.tr/storage/Archive/2025/kubKtAttachments/allerseturupkb_05_02_2025.pdf'),
  },

  levosetirizin: {
    name: 'Levosetirizin',
    brand: ['Xyzal', 'Levosetil', 'Rinosetil', 'Aerius-L'],
    dose: 'Yetişkin ve >12 yaş: günde bir kez 5 mg.',
    pediatricDose: '2–6 yaş: günde iki kez 1,25 mg (toplam 2,5 mg); 6–12 yaş: 5 mg/gün',
    pediatrik: {
      min: 1.25, max: 5, birim: 'mg/kg/doz', gunlukBolum: 2, enAzAy: 24,
      metin: 'KÜB §4.2 (yaşa göre sabit doz, mg/kg değil): 2–6 yaş arası çocuklarda günde iki defa 1,25 mg (toplam 2,5 mg/gün); 6–12 yaş ve üzerinde günlük doz 5 mg. 2 yaşından küçük çocuklarda kullanımı destekleyecek yeterli veri yoktur.',
    },
    form: 'Film tablet, oral damla, şurup',
    sgkCovered: true,
    category: 'İkinci kuşak H1 antihistaminik',
    siniflar: ['Antihistaminik', 'H1 antagonisti', 'Piperazin türevi', 'İkinci kuşak antihistaminik'],
    contraindications: [
      'Levosetirizin, setirizin, hidroksizin veya piperazin türevlerine aşırı duyarlılık',
      'Ağır böbrek yetmezliği (kreatinin klerensi <10 mL/dk)',
    ],
    interactions: ['Alkol', 'Santral sinir sistemi depresanları', 'Teofilin'],
    etkilesimler: ANTIHISTAMIN_ETKILESIM,
    gebelik: { kategori: 'B', metin: 'Rasematı setirizinin 1000\'den fazla gebelik verisi malformatif/fetal toksisite bildirmemiştir (KÜB §4.6).' },
    emzirme: 'Anne sütüne geçer; yarar/risk değerlendirilir.',
    bobrekDozUyarisi: true,
    renkliRecete: 'normal',
    kaynak: kub('LEVOSETİL 5 MG/ML ORAL DAMLA (onay 12/12/2023)', 'https://titck.gov.tr/storage/Archive/2023/kubKtAttachments/kbruhsat_7b72c922-c46e-4ccd-9f1a-14dccf73c229.pdf'),
  },

  desloratadin: {
    name: 'Desloratadin',
    brand: ['Aerius', 'Deslor', 'Dasselta', 'Lordes'],
    dose: 'Yetişkin ve >12 yaş: günde bir kez 5 mg.',
    pediatricDose: '6–11 ay: 1 mg/gün; 1–5 yaş: 1,25 mg/gün; 6–11 yaş: 2,5 mg/gün',
    pediatrik: {
      min: 1, max: 2.5, birim: 'mg/kg/gün', gunlukBolum: 1, enAzAy: 6,
      metin: 'KÜB §4.2 (yaşa göre sabit doz, mg/kg değil): şurup formunda 6–11 aylık çocuklarda 1 mg/gün, 1–5 yaş 1,25 mg/gün, 6–11 yaş 2,5 mg/gün; 12 yaş ve üzeri 5 mg/gün.',
    },
    form: 'Film tablet, şurup',
    sgkCovered: true,
    category: 'İkinci kuşak H1 antihistaminik',
    siniflar: ['Antihistaminik', 'H1 antagonisti', 'İkinci kuşak antihistaminik'],
    contraindications: ['Desloratadin veya loratadine aşırı duyarlılık'],
    interactions: ['Alkol', 'Eritromisin', 'Ketokonazol'],
    etkilesimler: ANTIHISTAMIN_ETKILESIM,
    gebelik: { kategori: 'C', metin: '1000\'den fazla gebelik sonucu malformatif veya fetal/neonatal toksisite göstermemiştir (KÜB §4.6).' },
    emzirme: 'Anne sütüne geçer; yarar/risk değerlendirilir.',
    bobrekDozUyarisi: true,
    renkliRecete: 'normal',
    kaynak: kub('AERIUS 0,5 MG/ML ŞURUP (onay 28/08/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/Ek1311temizkub_1e749b94-ba96-4f5c-bbd1-db3af130e4fb.pdf'),
  },

  loratadin: {
    name: 'Loratadin',
    brand: ['Claritine', 'Loratadin', 'Rinolan', 'Alergosan'],
    dose: 'Yetişkin ve 30 kg üstü 6 yaş üzeri çocuk: günde bir kez 10 mg.',
    pediatricDose: '30 kg üstü ve 6 yaş üzeri: 10 mg/gün. 30 kg altı için 5 mg\'lık form kullanılır',
    pediatrik: {
      min: 5, max: 10, birim: 'mg/kg/gün', gunlukBolum: 1, enAzAy: 24,
      metin: 'KÜB §4.2 (kilo/yaşa göre sabit doz, mg/kg değil): yetişkinler ve vücut ağırlığı 30 kg\'dan fazla olan 6 yaş üzeri çocuklarda günde 1 kez 10 mg. 10 mg tablet 6 yaşından küçük ve 30 kg altındaki çocuklar için uygun değildir; 2 yaşından küçükte güvenlilik/etkililik belirlenmemiştir.',
    },
    form: 'Tablet, şurup',
    sgkCovered: true,
    category: 'İkinci kuşak H1 antihistaminik',
    siniflar: ['Antihistaminik', 'H1 antagonisti', 'İkinci kuşak antihistaminik'],
    contraindications: ['Loratadin veya metabolitlerine aşırı duyarlılık'],
    interactions: ['Eritromisin', 'Ketokonazol', 'Simetidin', 'Alkol'],
    etkilesimler: [...ANTIHISTAMIN_ETKILESIM, { ile: 'Ketokonazol', siddet: 'orta', not: 'CYP3A4 inhibisyonu loratadin plazma düzeyini artırabilir.' }],
    gebelik: { kategori: 'B', metin: '1000\'den fazla maruziyet verisi malformatif veya fetal/neonatal toksisite göstermemiştir (KÜB §4.6).' },
    emzirme: 'Anne sütüne geçer; düşük düzeyde, genellikle uyumlu kabul edilir.',
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    kaynak: kub('CLARITINE 10 MG TABLET (onay 02/06/2021)', 'https://titck.gov.tr/storage/Archive/2021/kubKtAttachments/ClaritinetabletKB_db5210bf-3c68-4edb-8b64-8ea09c1f1537.pdf'),
  },

  feksofenadin: {
    name: 'Feksofenadin',
    brand: ['Telfast', 'Fexofen', 'Fexadyne', 'Allegra'],
    dose: 'Yetişkin ve >12 yaş: günde tek doz 120 mg (mevsimsel alerjik rinit) veya 180 mg (kronik ürtiker).',
    form: 'Film kaplı tablet',
    sgkCovered: true,
    category: 'İkinci kuşak H1 antihistaminik',
    siniflar: ['Antihistaminik', 'H1 antagonisti', 'İkinci kuşak antihistaminik'],
    yasKontrendikasyonAy: 144,
    contraindications: ['Feksofenadine aşırı duyarlılık', '12 yaş altı çocuklarda kontrendikedir (yeterli veri yok)'],
    interactions: ['Antiasitler', 'Eritromisin', 'Ketokonazol'],
    etkilesimler: [
      { ile: 'Antiasit', siddet: 'orta', not: 'Alüminyum/magnezyum hidroksit içeren antiasit biyoyararlanımı azaltır; 2 saat ara bırakılmalı (KÜB §4.2/4.5).' },
      { ile: 'Eritromisin', siddet: 'orta', not: 'P-glikoprotein inhibisyonu feksofenadin maruziyetini artırabilir (KÜB §4.5).' },
    ],
    gebelik: { kategori: 'C', metin: 'Klinik veri yoktur; hayvanlarda teratojenik etki gözlenmemiştir (KÜB §4.6).' },
    emzirme: 'Anne sütüne geçer; yarar/risk değerlendirilir.',
    renkliRecete: 'normal',
    notes: 'Meyve suyuyla (greyfurt, portakal, elma) alınması emilimi belirgin azaltır — su ile alınmalıdır.',
    kaynak: kub('FEXOFEN 120 MG FİLM KAPLI TABLET (onay 28/11/2025)', 'https://titck.gov.tr/storage/Archive/2025/kubKtAttachments/UYGUNFEXOFEN120mgKB_01_12_2025.pdf'),
  },

  feniramin: {
    name: 'Feniramin maleat',
    brand: ['Avil', 'Fenistil (dimetinden)'],
    dose: 'Yetişkin ve ergen: şurup günde 2–3 kez 1 ölçek. Tablet 22,7 mg günde 1–3 kez.',
    pediatricDose: '1–3 yaş: günde 2–3 kez yarım ölçek; 12 yaşa kadar: günde 2–3 kez 1 ölçek',
    pediatrik: {
      min: 0.5, max: 1, birim: 'mg/kg/doz', gunlukBolum: 3, enAzAy: 12,
      metin: 'KÜB §4.2 (ölçek sayısıyla ifade edilen sabit doz, mg/kg değil): 1–3 yaş arası çocuklarda günde 2–3 defa yarım ölçek; 12 yaşına kadar olan çocuklarda günde 2–3 defa 1 ölçek. 1 yaşın altında kontrendikedir.',
    },
    form: 'Şurup, tablet, ampul, merhem',
    sgkCovered: true,
    category: 'Birinci kuşak H1 antihistaminik',
    siniflar: ['Antihistaminik', 'H1 antagonisti', 'Alkilamin', 'Birinci kuşak antihistaminik', 'Antikolinerjik', 'SSS depresanı'],
    yasKontrendikasyonAy: 12,
    contraindications: [
      'Feniramin / alkilamin antihistaminiklerine aşırı duyarlılık',
      'Astım dahil alt solunum yolu hastalıkları',
      'Gebelik ve emzirme',
      '1 yaş altı çocuklar',
      'MAO inhibitörü tedavisi',
      'Semptomatik prostat hipertrofisi',
    ],
    interactions: ['MAO inhibitörleri', 'Alkol', 'Santral sinir sistemi depresanları', 'Antikolinerjikler', 'Trisiklik antidepresanlar'],
    etkilesimler: [
      { ile: 'MAO inhibitörü', siddet: 'ciddi', not: 'KONTRENDİKE — antikolinerjik ve SSS etkileri belirgin artar (KÜB §4.3).' },
      { ile: 'Alkol', siddet: 'ciddi', not: 'Sedasyon ve psikomotor bozulma belirgin artar.' },
      { ile: 'Benzodiazepin', siddet: 'ciddi', not: 'Ek SSS depresyonu; sedasyon ve solunum depresyonu riski.' },
      { ile: 'Trisiklik antidepresan', siddet: 'orta', not: 'Antimuskarinik etkiler toplanır (idrar retansiyonu, konfüzyon, glokom).' },
    ],
    gebelik: { kategori: 'C', metin: 'Gebelikte KONTRENDİKE (KÜB §4.3); güvenilir veri yoktur.' },
    emzirme: 'Emzirme döneminde kontrendikedir (KÜB §4.3).',
    renkliRecete: 'normal',
    notes: 'Belirgin sedasyon yapar — araç/makine kullanımı uyarısı zorunludur.',
    kaynak: kub('AVİL ŞURUP (onay 11/10/2019)', 'https://titck.gov.tr/storage/Archive/2019/kubKtAttachments/avil%20%C5%9Furup%20kub%20yay%C4%B1n.pdf_c3f5b626-07f6-458f-98b6-53fb2c1a8678.pdf'),
  },

  hidroksizin: {
    name: 'Hidroksizin',
    brand: ['Atarax', 'Validol', 'Hidroksizin'],
    dose: 'Erişkin anksiyete: günlük 50 mg, üçe bölünmüş. Kaşıntı: 25 mg akşam, gerekirse 25 mg günde 4 kez. Erişkin günlük maksimum 100 mg.',
    pediatricDose: 'Kaşıntı (12 ay ve üzeri): 1–2 mg/kg/gün bölünmüş dozlarda; 40 kg altında günlük maksimum 2 mg/kg/gün',
    pediatrik: {
      min: 1, max: 2, birim: 'mg/kg/gün', gunlukBolum: 3,
      maxMgKgGun: 2, mutlakMaxMgGun: 100, enAzAy: 12,
      metin: 'KÜB §4.2: kaşıntının semptomatik tedavisinde 12 ay ve üzerindeki çocuklarda 1–2 mg/kg/gün, bölünmüş dozlarda. 40 kg ağırlığa kadar olan çocuklarda günlük maksimum doz 2 mg/kg/gün; 40 kg üzerinde günlük maksimum 100 mg. 12 ayın altında güvenlilik ve etkinlik çalışılmamıştır.',
    },
    form: 'Film tablet, şurup, ampul',
    sgkCovered: true,
    category: 'Birinci kuşak H1 antihistaminik / anksiyolitik',
    siniflar: ['Antihistaminik', 'H1 antagonisti', 'Piperazin türevi', 'Birinci kuşak antihistaminik', 'Anksiyolitik', 'QT uzatan ilaç', 'SSS depresanı'],
    yasKontrendikasyonAy: 12,
    contraindications: [
      'Hidroksizin, setirizin, piperazin türevleri, aminofilin veya etilendiamine aşırı duyarlılık',
      'Porfiri',
      'Edinilmiş veya konjenital QT aralığı uzaması',
      'QT uzaması risk faktörü (kardiyovasküler hastalık, ailede ani kardiyak ölüm, hipokalemi, hipomagnezemi, belirgin bradikardi)',
      'QT uzatan ilaçlarla eşzamanlı kullanım',
    ],
    interactions: ['Sınıf IA antiaritmikler', 'Sınıf III antiaritmikler', 'Metadon', 'MAO inhibitörleri', 'Alkol', 'SSS depresanları', 'Betahistin', 'Antikolinesterazlar', 'Adrenalin'],
    etkilesimler: [
      { ile: 'QT uzatan ilaç', siddet: 'ciddi', not: 'KONTRENDİKE — Sınıf IA/III antiaritmik veya metadonla birlikte kardiyak aritmi riski artar (KÜB §4.3/4.5).' },
      { ile: 'MAO inhibitörü', siddet: 'ciddi', not: 'Eşzamanlı uygulanmasından kaçınılmalıdır (KÜB §4.5).' },
      { ile: 'Alkol', siddet: 'ciddi', not: 'Hidroksizinin sedatif etkisini artırır (KÜB §4.5).' },
      { ile: 'Benzodiazepin', siddet: 'ciddi', not: 'SSS depresan etkileri toplanır.' },
      { ile: 'Betahistin', siddet: 'orta', not: 'Hidroksizin betahistinin ve antikolinesteraz ilaçların etkisini antagonize eder (KÜB §4.5).' },
      { ile: 'Metoprolol', siddet: 'orta', not: 'CYP2D6 inhibisyonu — CYP2D6 substratlarının düzeyi yükselebilir (KÜB §4.5).' },
    ],
    gebelik: { metin: 'Plasentayı geçer ve fetüste anneden yüksek konsantrasyona ulaşır; geç gebelik/doğumda yenidoğanda hipotoni ve ekstrapiramidal bozukluk bildirilmiştir (KÜB §4.6).' },
    emzirme: 'Anne sütüne geçer; emzirme döneminde önerilmez.',
    bobrekDozUyarisi: true,
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Karaciğer yetmezliğinde günlük doz %33 azaltılmalıdır (KÜB §4.2).',
    kaynak: kub('ATARAX 2 MG/ML ŞURUP (onay 19/06/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/Ek21311kub_11_08_2026.pdf'),
  },
}
