/**
 * Üroloji + KBB/göz sistemikleri.
 *
 * The one interaction on this page that kills people is sildenafil + nitrat, and it is written on
 * both sides ('Nitrat' class here, 'PDE-5 inhibitörü' on the nitrate entry) so the card fires
 * whichever one the doctor is adding.
 */
import { kub } from '../kaynak'
import type { TürkishDrug } from '../tipler'

export const UROLOJI_DIGER: Record<string, TürkishDrug> = {
  tamsulosin: {
    name: 'Tamsulosin',
    brand: ['Flomax', 'Tamidra', 'Uromax', 'Prostam'],
    dose: 'Kahvaltıdan veya günün ilk öğününden sonra günde bir kapsül (0,4 mg). Kapsül bütün yutulmalı, ezilmemeli veya çiğnenmemelidir.',
    pediatricDose: 'Çocuklarda endikasyonu yoktur',
    form: 'Değiştirilmiş salımlı sert kapsül',
    sgkCovered: true,
    category: 'Alfa-1 adrenerjik reseptör blokeri',
    siniflar: ['Alfa blokör', 'Üroselektif alfa blokör', 'Antihipertansif'],
    contraindications: [
      'Tamsulosine aşırı duyarlılık (ilaca bağlı anjiyoödem dahil)',
      'Ortostatik hipotansiyon öyküsü',
      'Şiddetli karaciğer yetmezliği',
      'Güçlü CYP3A4 inhibitörleriyle (ketokonazol) birlikte kullanım',
    ],
    interactions: ['Ketokonazol', 'İtrakonazol', 'Sildenafil', 'Antihipertansifler', 'Diğer alfa blokörler'],
    etkilesimler: [
      { ile: 'İtrakonazol', siddet: 'ciddi', not: 'Güçlü CYP3A4 inhibitörü tamsulosin maruziyetini artırır; birlikte kullanılmamalıdır (KÜB §4.3/4.5).' },
      { ile: 'Sildenafil', siddet: 'ciddi', not: 'PDE-5 inhibitörü ile birlikte semptomatik hipotansiyon riski; dozlar arasında zaman bırakılmalıdır.' },
      { ile: 'Antihipertansif', siddet: 'orta', not: 'Kan basıncı düşürücü etkiler toplanır; ortostatik hipotansiyon riski.' },
      { ile: 'Alfa blokör', siddet: 'ciddi', not: 'İki alfa blokör birlikte kullanılmaz — belirgin hipotansiyon.' },
    ],
    gebelik: { metin: 'Erkek endikasyonu — gebelikte kullanımı söz konusu değildir.' },
    emzirme: 'Erkek endikasyonu — emzirmede kullanımı söz konusu değildir.',
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Katarakt/glokom cerrahisi öncesi "intraoperatif floppy iris sendromu" için göz hekimine bildirilmelidir. İlk dozda ortostatik hipotansiyon riski — akşam başlanması önerilir.',
    kaynak: kub('TAMİDRA MR 0,4 MG DEĞİŞTİRİLMİŞ SALIMLI SERT KAPSÜL (onay 12/09/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/TAMDRAMR04mgdeitirilmisalmlsertkapslkub_0591d3a4-ad54-427f-bc2c-792e36dcfb30.pdf'),
  },

  finasterid: {
    name: 'Finasterid',
    brand: ['Proscar', 'Propecia', 'Finarid', 'Prosterid'],
    dose: 'BPH: günde bir tablet (5 mg), yemeklerle birlikte veya öğün arasında. Tek başına veya alfa blokör (doksazosin) ile birlikte kullanılabilir.',
    pediatricDose: 'Pediyatrik hastalarda endike değildir',
    form: 'Film kaplı tablet (1 mg ve 5 mg)',
    sgkCovered: true,
    sgkRestriction: 'SUT: BPH endikasyonu için ödeme koşullarına bakınız (androjenetik alopesi endikasyonu ödenmez).',
    category: '5-alfa redüktaz inhibitörü',
    siniflar: ['5-alfa redüktaz inhibitörü', 'Antiandrojen', 'Hormon'],
    contraindications: [
      'Finasteride aşırı duyarlılık',
      'Kadınlarda kullanım',
      'Çocuklarda kullanım',
      'Gebelik veya gebe olma ihtimali bulunan kadınlarda kullanım/temas',
    ],
    interactions: [],
    etkilesimler: [],
    gebelik: { kategori: 'X', metin: 'Gebe veya gebe olma ihtimali olan kadınlar tablete DOKUNMAMALIDIR — erkek fetüste dış genital anomali riski (KÜB §4.3/4.6). Kırılmış/ezilmiş tabletle temas edilmemelidir.' },
    emzirme: 'Kadınlarda kullanımı endike değildir.',
    renkliRecete: 'normal',
    notes: 'Serum PSA düzeyini yaklaşık %50 düşürür — prostat kanseri taramasında PSA değeri iki katına çıkarılarak yorumlanmalıdır. Cinsel işlev bozukluğu ve depresif belirtiler bildirilmiştir.',
    kaynak: kub('PROSCAR 5 MG FİLM KAPLI TABLET (onay 07/03/2025)', 'https://titck.gov.tr/storage/Archive/2025/kubKtAttachments/1311temizkub_10_03_2025.pdf'),
  },

  dutasterid: {
    name: 'Dutasterid',
    brand: ['Avodart', 'Bepros', 'Duodart (kombinasyon)'],
    dose: 'Yetişkin erkek: günde bir kez oral bir kapsül (0,5 mg). Tatmin edici yanıtın değerlendirilmesi için en az 6 aylık tedavi gerekebilir. Tamsulosin (0,4 mg) ile kombine kullanılabilir.',
    pediatricDose: 'Çocuk ve adölesanlarda KONTRENDİKE',
    form: 'Yumuşak kapsül',
    sgkCovered: true,
    sgkRestriction: 'SUT: BPH endikasyon ve rapor koşullarına bakınız.',
    category: '5-alfa redüktaz inhibitörü',
    siniflar: ['5-alfa redüktaz inhibitörü', 'Antiandrojen', 'Hormon'],
    contraindications: [
      'Dutasteride veya diğer 5-alfa redüktaz inhibitörlerine aşırı duyarlılık',
      'Kadınlar, çocuklar ve adölesanlarda kullanım',
      'Gebelik',
      'Şiddetli karaciğer yetmezliği',
    ],
    interactions: ['Ketokonazol', 'İtrakonazol', 'Ritonavir', 'Verapamil', 'Diltiazem'],
    etkilesimler: [
      { ile: 'İtrakonazol', siddet: 'orta', not: 'Uzun süreli güçlü CYP3A4 inhibisyonu dutasterid maruziyetini artırır; doz sıklığının azaltılması düşünülebilir.' },
      { ile: 'Verapamil', siddet: 'orta', not: 'Dutasterid klerensini azaltır, maruziyeti artırır.' },
    ],
    gebelik: { kategori: 'X', metin: 'Gebelikte KONTRENDİKE — erkek fetüste dış genital anomali riski. Gebe kadın kapsüle dokunmamalıdır (kapsül içeriği ciltten emilir).' },
    emzirme: 'Kadınlarda kullanımı kontrendikedir.',
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Tedavi sırasında ve son dozdan sonra 6 ay KAN BAĞIŞI YAPILMAMALIDIR (gebe alıcıya fetal risk). PSA\'yı yaklaşık %50 düşürür.',
    kaynak: kub('BEPROS 0,5 MG YUMUŞAK KAPSÜL (onay 26/12/2024)', 'https://titck.gov.tr/storage/Archive/2025/kubKtAttachments/OnaylKBBepros05mg_28_01_2025.pdf'),
  },

  solifenasin: {
    name: 'Solifenasin',
    brand: ['Vesicare', 'Soliron', 'Solifenacin'],
    dose: 'Erişkin (yaşlı dahil): günde bir kez 5 mg; gerekli görüldüğünde günde bir kez 10 mg\'a artırılabilir. Yemeklerden bağımsız, bütün olarak yutulur.',
    pediatricDose: 'Pediyatrik doz önerisi bu üründe verilmemektedir',
    form: 'Film kaplı tablet',
    sgkCovered: true,
    sgkRestriction: 'SUT: aşırı aktif mesane endikasyon ve rapor koşullarına bakınız.',
    category: 'Muskarinik reseptör antagonisti (üroloji)',
    siniflar: ['Antikolinerjik', 'Muskarinik antagonist', 'Antimuskarinik', 'Üriner antispazmodik'],
    contraindications: [
      'Solifenasine aşırı duyarlılık',
      'İdrar retansiyonu',
      'Şiddetli gastrointestinal hastalık (toksik megakolon dahil)',
      'Miyastenia gravis',
      'Dar açılı glokom ve bu risk altındaki hastalar',
      'Hemodiyaliz hastaları',
      'Ciddi karaciğer yetmezliği',
      'Ciddi böbrek yetmezliği',
    ],
    interactions: ['Ketokonazol', 'İtrakonazol', 'Ritonavir', 'Diğer antikolinerjikler', 'Metoklopramid', 'Donepezil'],
    etkilesimler: [
      { ile: 'İtrakonazol', siddet: 'ciddi', not: 'Güçlü CYP3A4 inhibitörü solifenasin maruziyetini artırır; maksimum doz 5 mg ile sınırlanmalıdır (KÜB §4.5).' },
      { ile: 'Antikolinerjik', siddet: 'ciddi', not: 'Antikolinerjik yük toplanır: idrar retansiyonu, konstipasyon, konfüzyon, akut glokom riski.' },
      { ile: 'Donepezil', siddet: 'ciddi', not: 'Karşılıklı antagonizma — kolinesteraz inhibitörünün etkisi kaybolur.' },
      { ile: 'Metoklopramid', siddet: 'orta', not: 'Prokinetik etkiyi antagonize eder.' },
    ],
    gebelik: { metin: 'Gebelikte veri sınırlıdır; kullanımı önerilmez.' },
    emzirme: 'Emzirme döneminde önerilmez.',
    bobrekDozUyarisi: true,
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Yaşlıda antikolinerjik yük (konfüzyon, düşme, bilişsel bozulma) değerlendirilmelidir.',
    kaynak: kub('SOLİRON 5 MG FİLM KAPLI TABLET (onay 11/06/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/SOLRON5mgfilmkapltabletkub_11_06_2026.pdf'),
  },

  sildenafil: {
    name: 'Sildenafil',
    brand: ['Viagra', 'Degra', 'Sildegra', 'Revatio (pulmoner HT)'],
    dose: 'Erektil disfonksiyon: cinsel aktiviteden yaklaşık bir saat önce gerektikçe 50 mg. Etkinlik ve tolerabiliteye göre 100 mg\'a yükseltilebilir veya 25 mg\'a düşürülebilir. Önerilen en yüksek doz 100 mg, günde bir kez.',
    pediatricDose: '18 yaşından küçüklerde endike değildir',
    form: 'Film kaplı tablet',
    sgkCovered: false,
    sgkRestriction: 'Erektil disfonksiyon endikasyonunda SGK ödemesi yoktur; pulmoner arteriyel hipertansiyon endikasyonu ayrıdır.',
    category: 'Fosfodiesteraz-5 (PDE-5) inhibitörü',
    siniflar: ['PDE-5 inhibitörü', 'Vazodilatör'],
    yasKontrendikasyonAy: 216,
    contraindications: [
      'Sildenafile aşırı duyarlılık',
      'Herhangi bir formda nitrat veya nitrik oksit donörü kullanımı',
      'Riosiguat ile birlikte kullanım',
      'Cinsel aktivitenin önerilmediği kardiyovasküler durumlar (ağır kalp yetmezliği, stabil olmayan anjina)',
      'Son 6 ayda inme veya miyokard infarktüsü',
      'Ağır hipotansiyon (<90/50 mmHg)',
      'Ağır karaciğer yetmezliği',
      'Non-arteritik anterior iskemik optik nöropati (NAİON) öyküsü',
      'Retinitis pigmentoza',
      '18 yaş altı',
    ],
    interactions: ['Nitratlar', 'İzosorbid dinitrat', 'Riosiguat', 'Alfa blokörler', 'Ketokonazol', 'İtrakonazol', 'Ritonavir', 'Eritromisin', 'Greyfurt suyu'],
    etkilesimler: [
      { ile: 'Nitrat', siddet: 'ciddi', not: 'KONTRENDİKE — nitratların hipotansif etkisini şiddetle potansiyalize eder; hayatı tehdit eden hipotansiyon (KÜB §4.3).' },
      { ile: 'İzosorbid dinitrat', siddet: 'ciddi', not: 'KONTRENDİKE — ciddi hipotansiyon (KÜB §4.3).' },
      { ile: 'Alfa blokör', siddet: 'ciddi', not: 'Semptomatik hipotansiyon riski; alfa blokör dozu stabilize edilmeli ve düşük sildenafil dozuyla başlanmalıdır.' },
      { ile: 'Tamsulosin', siddet: 'ciddi', not: 'Birlikte kullanımda semptomatik hipotansiyon; dozlar arasında zaman bırakılmalıdır.' },
      { ile: 'İtrakonazol', siddet: 'ciddi', not: 'Güçlü CYP3A4 inhibisyonu sildenafil maruziyetini belirgin artırır; doz azaltılmalıdır.' },
      { ile: 'Klaritromisin', siddet: 'ciddi', not: 'CYP3A4 inhibisyonu ile sildenafil düzeyi yükselir.' },
      { ile: 'Amlodipin', siddet: 'orta', not: 'Kan basıncı düşürücü etkiler toplanabilir (KÜB §4.5).' },
    ],
    gebelik: { metin: 'Erektil disfonksiyon endikasyonunda kadınlarda kullanılmaz.' },
    emzirme: 'Erektil disfonksiyon endikasyonunda kadınlarda kullanılmaz.',
    karacigerDozUyarisi: true,
    bobrekDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Nitrat gerektiren akut koroner olayda, sildenafil alımından sonra EN AZ 24 SAAT nitrat verilmemelidir — acil servis bunu bilmelidir. Ani işitme kaybı ve NAİON bildirilmiştir.',
    kaynak: kub('DEGRA 100 MG FİLM KAPLI TABLET (onay 15/04/2026)', 'https://titck.gov.tr/storage/Archive/2026/kubKtAttachments/EkOnaylananKBmetni_17_04_2026.pdf'),
  },

  betahistin: {
    name: 'Betahistin',
    brand: ['Betaserc', 'Tinserc', 'Vertin', 'Betaver'],
    dose: '24 mg formu: günde 2 defa 1 tablet (günlük doz 48 mg), daha homojen plazma düzeyi için iki doz halinde. Doz yanıta göre bireyselleştirilir.',
    pediatricDose: '18 yaş altında yeterli veri olmadığı için önerilmez',
    form: 'Tablet',
    sgkCovered: true,
    category: 'Histamin analoğu (vertigo)',
    siniflar: ['Antivertigo', 'Histamin analoğu', 'H3 antagonisti'],
    yasKontrendikasyonAy: 216,
    contraindications: ['Betahistine aşırı duyarlılık', 'Feokromositoma'],
    interactions: ['Antihistaminikler', 'MAO inhibitörleri'],
    etkilesimler: [
      { ile: 'Antihistaminik', siddet: 'orta', not: 'H1 antihistaminikler betahistinin etkisini teorik olarak antagonize eder (hidroksizin KÜB §4.5).' },
      { ile: 'MAO inhibitörü', siddet: 'orta', not: 'Betahistin maruziyetini artırabilir.' },
    ],
    gebelik: { metin: 'Gebelikte yeterli veri yoktur; kullanımı önerilmez.' },
    emzirme: 'Emzirme döneminde önerilmez.',
    renkliRecete: 'normal',
    notes: 'Ménière hastalığında etki birkaç hafta–ay sonra görülür; erken kesilmemelidir (KÜB §4.2). Astım ve peptik ülser öyküsünde dikkatli kullanılır.',
    kaynak: kub('TINSERC BID 24 MG TABLET (onay 25/03/2025)', 'https://titck.gov.tr/storage/Archive/2025/kubKtAttachments/kb24.03_26_03_2025.pdf'),
  },

  asetazolamid: {
    name: 'Asetazolamid',
    brand: ['Diazomid', 'Diamox', 'Asetazolamid'],
    dose: 'Glokom: 24 saatte 250–1000 mg; 250 mg üzerindeki miktarlar bölünmüş dozlarda. Ödem: sabah günde bir kez 250–375 mg. Epilepside günlük doz 750 mg\'ı aşmamalıdır.',
    pediatricDose: 'Epilepsi ve glokomda doz hekim tarafından kiloya göre belirlenir; günlük doz 750 mg\'ı aşmamalıdır',
    form: 'Tablet, IV flakon',
    sgkCovered: true,
    category: 'Karbonik anhidraz inhibitörü',
    siniflar: ['Karbonik anhidraz inhibitörü', 'Diüretik', 'Antiglokom', 'Sülfonamid türevi', 'Antiepileptik'],
    alerjiSinifi: ['sulfonamid'],
    contraindications: [
      'Asetazolamide aşırı duyarlılık',
      'Sülfonamidlere aşırı duyarlılık (çapraz duyarlılık)',
      'Serum sodyum ve/veya potasyum düşüklüğü',
      'Belirgin böbrek veya karaciğer hastalığı',
      'Adrenal yetmezlik',
      'Hiperkloremik asidoz',
      'Uzun süreli kronik konjestif açılı glokom',
    ],
    interactions: ['Asetilsalisilik asit', 'Nitrofurantoin', 'Lityum', 'Topiramat', 'Digoksin', 'Kinidin'],
    etkilesimler: [
      { ile: 'Asetilsalisilik asit', siddet: 'ciddi', not: 'Yüksek doz salisilat ile birlikte ciddi metabolik asidoz ve SSS toksisitesi bildirilmiştir.' },
      { ile: 'Topiramat', siddet: 'ciddi', not: 'İki karbonik anhidraz inhibitörü: metabolik asidoz ve böbrek taşı riski toplanır.' },
      { ile: 'Nitrofurantoin', siddet: 'orta', not: 'İdrarı alkalileştirerek nitrofurantoinin antibakteriyel etkinliğini azaltır (nitrofurantoin KÜB §4.5).' },
      { ile: 'Lityum', siddet: 'orta', not: 'Lityum atılımını artırarak düzeyini düşürebilir.' },
      { ile: 'Digoksin', siddet: 'orta', not: 'Hipokalemi dijital toksisitesini kolaylaştırır.' },
    ],
    gebelik: { metin: 'Gebelikte, özellikle ilk trimesterde kullanılmaması önerilir; hayvan çalışmalarında teratojenite bildirilmiştir.' },
    emzirme: 'Anne sütüne az miktarda geçer; kısa süreli kullanımda genellikle uyumlu kabul edilir.',
    bobrekDozUyarisi: true,
    karacigerDozUyarisi: true,
    renkliRecete: 'normal',
    notes: 'Elektrolit (özellikle potasyum) ve asit-baz dengesi izlenmelidir. Parestezi, tat değişikliği ve böbrek taşı sık bildirilir.',
    kaynak: kub('DİAZOMİD 250 MG TABLET (onay 28/02/2025)', 'https://titck.gov.tr/storage/Archive/2025/kubKtAttachments/DAZOMDKB_04_03_2025.pdf'),
  },
}
