/** Loaded only under NODE_TEST_CONTEXT from index.ts — do not import from app code. */
import './schema-isolation.test'
import './pediatri-no-bleed.test'
import './sat-edd.test'
import './izlem-calendar.test'
import './test-windows.test'
import './imaging-usg.test'
import './vision-tools.test'
import './acil-obstetrik.test'
import './sources-acog.test'
