export interface Specialty {
  key: string;
  label: string;
  emoji: string;
  color: string;
  references: string[];
  soapFields: string[];
  greeting: string;
  agentIdEnvVar: string;
}

/** 30 medical specialties — each has a dedicated Ayşe-level specialist (see specialistsCatalog). */
export const SPECIALTIES: Specialty[] = [
  { key: "pediatri", label: "Pediatri", emoji: "👶", color: "#0F9B8E", references: ["T.C. SB Ulusal Çocukluk Dönemi Aşılama Takvimi (GBP) — 2025", "Türk Pediatri Kurumu (TPK) klinik kılavuzları", "ÇAYD protokolleri + SB Çocuk YBÜ kabul/taburculuk", "Türk Toraks Derneği — çocuk pnömoni / bronşiyolit", "Nelson Textbook of Pediatrics"], soapFields: ["ates", "kilo", "boy", "gelisim"], greeting: "Merhaba, ben Prof. Dr. Ayşe Kaya. Pediatri alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_PEDİATRİ" },
  { key: "kardiyoloji", label: "Kardiyoloji", emoji: "❤️", color: "#DC2626", references: ["Türk Kardiyoloji Derneği (TKD) — ESC kılavuzlarının TR yayını", "ESC/TKD 2023 AKS; 2024 AF; 2021+2024 KY odak güncelleme", "ESC/TKD 2024 HT; 2025 Dislipidemi; ESC 2023 Diyabet-KVH", "SB göğüs ağrısı / AKS acil protokolleri; SGK kardiyak rapor", "ESC klinik kılavuzları"], soapFields: ["ekg", "ef", "nyha"], greeting: "Merhaba, ben Prof. Dr. Mehmet Demir. Kardiyoloji alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_KARDİYOLOJİ" },
  { key: "noroloji", label: "Nöroloji", emoji: "🧠", color: "#7C3AED", references: ["SB + TND + TBDHD Akut İskemik İnmede Tanı ve Tedavi Rehberi", "TND Epilepsi Tanı ve Tedavi Rehberi (2021); TND Migren Klinik Protokolü", "TND Hareket Bozuklukları (2023); TND Nöromusküler (2024)", "SB Klinik Protokolleri: İnme, Alzheimer/Demans, Epilepsi"], soapFields: ["norolojik_muayene", "gcs", "kraniyal_sinirler"], greeting: "Merhaba, ben Prof. Dr. Elif Şahin. Nöroloji alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_NÖROLOJİ" },
  { key: "dahiliye", label: "Dahiliye", emoji: "🩺", color: "#0F9B8E", references: ["Türk İç Hastalıkları Uzmanlık Derneği (TİHUD) kaynakları", "TEMD DM Tanı-Tedavi-İzlem (2024/2026); TEMD HT (2022)", "TEMD Dislipidemi / Obezite kılavuzları", "SB kronik hastalık klinik protokolleri; SGK rapor kuralları", "İliçin İç Hastalıkları"], soapFields: ["sistemik_muayene"], greeting: "Merhaba, ben Prof. Dr. Zeynep Arslan. Dahiliye alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_DAHİLİYE" },
  { key: "psikiyatri", label: "Psikiyatri", emoji: "🧘", color: "#6366F1", references: ["Türkiye Psikiyatri Derneği (TPD) tedavi kılavuzları", "T.C. SB Ruh Sağlığı Eylem Planı / klinik protokoller", "DSM-5-TR tanı kriterleri (TR pratiğinde standart)", "SGK psikotrop ilaç / yeşil-turuncu reçete kuralları", "DSM-5-TR"], soapFields: ["mental_durum"], greeting: "Merhaba, ben Prof. Dr. Deniz Yılmaz. Psikiyatri alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_PSİKİYATRİ" },
  { key: "genel-cerrahi", label: "Genel Cerrahi", emoji: "🔪", color: "#EF4444", references: ["Türk Cerrahi Derneği (TCD) kılavuz ve konsensusları", "SB ameliyathane / cerrahi klinik protokolleri", "Türk Kolon ve Rektum Cerrahisi Derneği (TKRCD) ilgili rehberler", "SGK paket / ameliyat rapor kuralları", "Sabiston Textbook of Surgery"], soapFields: ["cerrahi_anamnez"], greeting: "Merhaba, ben Prof. Dr. Hakan Öztürk. Genel Cerrahi alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_GENEL_CERRAHİ" },
  { key: "ortopedi", label: "Ortopedi", emoji: "🦴", color: "#F59E0B", references: ["Türk Ortopedi ve Travmatoloji Birliği Derneği (TOTBİD) rehberleri", "SB travma / kırık klinik protokolleri", "AO / TOTBİD eğitim materyalleri (TR uygulama)", "SGK protez / ortopedik malzeme raporları", "AO Trauma principles"], soapFields: ["travma", "rom", "xray"], greeting: "Merhaba, ben Prof. Dr. Burak Şen. Ortopedi alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_ORTOPEDİ" },
  { key: "dermatoloji", label: "Dermatoloji", emoji: "🧴", color: "#EC4899", references: ["Türk Dermatoloji Derneği (TDD) kılavuzları", "SB deri kanseri / psoriazis klinik protokolleri", "TDD akne, ürtiker, atopik dermatit konsensusları", "SGK biyolojik / dermatolojik ilaç raporları", "Bolognia Dermatology"], soapFields: ["lezyon", "efflorescence"], greeting: "Merhaba, ben Prof. Dr. Selin Aksoy. Dermatoloji alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_DERMATOLOJİ" },
  { key: "kulak-burun-bogaz", label: "KBB", emoji: "👂", color: "#14B8A6", references: ["Türk Kulak Burun Boğaz ve Baş Boyun Cerrahisi Derneği kılavuzları", "SB otitis / tonsillit / sinüzit klinik protokolleri", "Türk Rinoloji Derneği ilgili konsensuslar", "SGK işitme cihazı / KBB cerrahi raporları", "Cummings Otolaryngology"], soapFields: ["kbb_muayene"], greeting: "Merhaba, ben Prof. Dr. Emre Aydın. KBB alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_KBB" },
  { key: "goz-hastaliklari", label: "Göz Hastalıkları", emoji: "👁️", color: "#3B82F6", references: ["Türk Oftalmoloji Derneği (TOD) kılavuz ve bültenleri", "SB diyabetik retinopati / glokom klinik protokolleri", "TOD retina / kornea çalışma grubu önerileri", "SGK göz içi lens / enjeksiyon raporları", "Vaughan & Asbury General Ophthalmology"], soapFields: ["goz_muayene"], greeting: "Merhaba, ben Prof. Dr. İrem Kaya. Göz Hastalıkları alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_GÖZ" },
  { key: "kadin-hastaliklari-dogum", label: "Kadın Hastalıkları ve Doğum", emoji: "🤰", color: "#BE185D", references: ["Türk Jinekoloji ve Obstetrik Derneği (TJOD) kılavuzları", "T.C. SB Doğum ve Sezaryen Yönetim Rehberi / anne ölümü protokolleri", "TJOD jinekolojik onkoloji / üreme endokrinoloji konsensusları", "SGK gebelik / IVF / jinekoloji rapor kuralları", "Williams Obstetrics"], soapFields: ["jinekolojik_anamnez"], greeting: "Merhaba, ben Prof. Dr. Fatma Çelik. Kadın Hastalıkları ve Doğum alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_KADIN_DOĞUM" },
  { key: "uroloji", label: "Üroloji", emoji: "🚽", color: "#0EA5E9", references: ["Türk Üroloji Derneği (TÜD) kılavuzları", "EAU kılavuzlarının TR uyarlaması / TÜD yorumu", "SB üriner enfeksiyon / prostat klinik protokolleri", "SGK ürolojik ilaç ve işlem raporları", "Campbell-Walsh-Wein Urology"], soapFields: ["urolojik_muayene"], greeting: "Merhaba, ben Prof. Dr. Murat Yıldız. Üroloji alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_ÜROLOJİ" },
  { key: "radyoloji", label: "Radyoloji", emoji: "📷", color: "#64748B", references: ["Türk Radyoloji Derneği (TRD) standart ve önerileri", "T.C. SB / TAEK radyasyon güvenliği mevzuatı", "TRD kontrast madde / gebelik görüntüleme protokolleri", "SGK görüntüleme tetkik rapor kuralları", "Grainger & Allison Diagnostic Radiology"], soapFields: ["goruntuleme_bulgulari"], greeting: "Merhaba, ben Prof. Dr. Caner Koç. Radyoloji alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_RADYOLOJİ" },
  { key: "anestezi", label: "Anestezi", emoji: "💉", color: "#8B5CF6", references: ["Türk Anesteziyoloji ve Reanimasyon Derneği (TARD) kılavuzları", "SB ameliyathane / sedasyon klinik protokolleri", "TARD havayolu / obstetrik anestezi önerileri", "SGK anestezi işlem kodları / rapor", "Morgan & Mikhail Clinical Anesthesiology"], soapFields: ["anestezi_riski"], greeting: "Merhaba, ben Prof. Dr. Pınar Demir. Anestezi alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_ANESTEZİ" },
  { key: "acil-tip", label: "Acil Tıp", emoji: "🚑", color: "#F97316", references: ["Türkiye Acil Tıp Derneği (TATD) protokolleri", "T.C. SB Acil Servis klinik protokolleri", "ATLS Türkiye uygulamaları; ERC/AHA resusitasyon (TR eğitim)", "SB triaj ve kritik hasta yönlendirme", "ATLS / ACLS / PALS"], soapFields: ["acil_degerlendirme"], greeting: "Merhaba, ben Prof. Dr. Oğuz Kılıç. Acil Tıp alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_ACİL" },
  { key: "fizik-tedavi", label: "Fizik Tedavi", emoji: "🏃", color: "#22C55E", references: ["Türkiye Fiziksel Tıp ve Rehabilitasyon Derneği kılavuzları", "SB rehabilitasyon / engellilik klinik protokolleri", "Türk Osteoporoz Derneği ilgili öneriler (TEMD ile örtüşen)", "SGK fizik tedavi seans / rapor kuralları", "PM&R board review sources"], soapFields: ["fiziksel_degerlendirme"], greeting: "Merhaba, ben Prof. Dr. Aylin Erdem. Fizik Tedavi alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_FİZİK" },
  { key: "enfeksiyon-hastaliklari", label: "Enfeksiyon Hastalıkları", emoji: "🦠", color: "#E11D48", references: ["KLİMİK / Türk Klinik Mikrobiyoloji ve İnfeksiyon Hastalıkları Derneği kılavuzları", "T.C. SB Akılcı Antibiyotik Kullanımı ve enfeksiyon kontrolü", "SB HIV, tüberküloz, hepatit klinik protokolleri", "SGK antibiyotik / antiviral kısıtları", "Mandell, Douglas, and Bennett Principles of Infectious Diseases"], soapFields: ["enfeksiyon_belirtileri"], greeting: "Merhaba, ben Prof. Dr. Serkan Güneş. Enfeksiyon Hastalıkları alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_ENFEKSİYON" },
  { key: "endokrinoloji", label: "Endokrinoloji", emoji: "🧬", color: "#A855F7", references: ["TEMD Diyabetes Mellitus Kılavuzu (2024/2026)", "TEMD Tiroid Hastalıkları Kılavuzu (2025)", "TEMD Osteoporoz (2025); Adrenal-Gonadal (2025); HT (2022)", "TEMD Obezite / Dislipidemi kılavuzları", "Williams Textbook of Endocrinology"], soapFields: ["endokrin_lab"], greeting: "Merhaba, ben Prof. Dr. Gülşah Tekin. Endokrinoloji alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_ENDOKRİN" },
  { key: "gastroenteroloji", label: "Gastroenteroloji", emoji: "🫁", color: "#F43F5E", references: ["Türk Gastroenteroloji Derneği (TGD) kılavuzları", "SB hepatit B/C, siroz, GIS kanama protokolleri", "TGD IBD / H. pylori / karaciğer hastalıkları konsensusları", "SGK biyolojik / endoskopi raporları", "Sleisenger and Fordtran Gastrointestinal Disease"], soapFields: ["gastro_anamnez"], greeting: "Merhaba, ben Prof. Dr. Volkan Arı. Gastroenteroloji alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_GASTRO" },
  { key: "nefroloji", label: "Nefroloji", emoji: "🫘", color: "#06B6D4", references: ["Türk Nefroloji Derneği kılavuzları", "SB kronik böbrek hastalığı / diyaliz protokolleri", "KDIGO’nun TR nefrolog pratiğindeki uyarlamaları", "SGK diyaliz / eritropoietin / fosfat bağlayıcı raporları", "Comprehensive Clinical Nephrology"], soapFields: ["bobrek_fonksiyonlari"], greeting: "Merhaba, ben Prof. Dr. Mert Özkan. Nefroloji alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_NEFRO" },
  { key: "romatoloji", label: "Romatoloji", emoji: "🦵", color: "#D97706", references: ["Türkiye Romatoloji Derneği (TRD) kılavuzları", "SB romatoid artrit / SLE klinik protokolleri", "EULAR/ACR kriterlerinin TR uygulama yorumları", "SGK biyolojik DMARD raporları", "Oxford Textbook of Rheumatology"], soapFields: ["eklem_muayenesi"], greeting: "Merhaba, ben Prof. Dr. Nazlı Kara. Romatoloji alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_ROMATO" },
  { key: "onkoloji", label: "Onkoloji", emoji: "🎗️", color: "#7C2D12", references: ["Türk Tıbbi Onkoloji Derneği (TTOD) kılavuzları", "SB kanser tarama ve tedavi protokolleri", "NCCN/ESMO’nun TR onkoloji pratiğindeki uyarlamaları", "SGK onkoloji ilaç / yeşil reçete / rapor", "DeVita, Hellman, and Rosenberg Cancer"], soapFields: ["onkolojik_degerlendirme"], greeting: "Merhaba, ben Prof. Dr. Ece Yurt. Onkoloji alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_ONKOLOJİ" },
  { key: "gogus-hastaliklari", label: "Göğüs Hastalıkları", emoji: "🫀", color: "#0D9488", references: ["Türk Toraks Derneği (TTD) kılavuzları", "GINA/GOLD’un TTD uyarlamaları; TTD astım/KOAH", "SB tüberküloz ve pnömoni klinik protokolleri", "SGK inhaler / oksijen / NIV raporları", "Fishman’s Pulmonary Diseases"], soapFields: ["solunum_fonksiyonlari"], greeting: "Merhaba, ben Prof. Dr. Barış Uysal. Göğüs Hastalıkları alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_GÖĞÜS" },
  { key: "gogus-cerrahisi", label: "Göğüs Cerrahisi", emoji: "🫁", color: "#B91C1C", references: ["Türk Göğüs Cerrahisi Derneği kılavuzları", "SB toraks travması / tüp torakostomi protokolleri", "TTD ile ortak akciğer kanseri cerrahi yaklaşımlar", "SGK torasik cerrahi paket raporları", "Pearson’s Thoracic & Esophageal Surgery"], soapFields: ["torasik_anamnez"], greeting: "Merhaba, ben Prof. Dr. Tolga Şimşek. Göğüs Cerrahisi alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_GÖĞÜS_CERRAHİ" },
  { key: "plastik-cerrahi", label: "Plastik Cerrahi", emoji: "✨", color: "#C026D3", references: ["Türk Plastik Rekonstrüktif ve Estetik Cerrahi Derneği (TPRECD) kılavuzları", "SB yanık ve yara bakımı protokolleri", "TPRECD etik / estetik cerrahi güvenlik önerileri", "SGK rekonstrüktif işlem raporları", "Plastic Surgery"], soapFields: ["plastik_degerlendirme"], greeting: "Merhaba, ben Prof. Dr. Melis Orhan. Plastik Cerrahi alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_PLASTİK" },
  { key: "beyin-cerrahisi", label: "Beyin Cerrahisi", emoji: "🧠", color: "#581C87", references: ["Türk Nöroşirürji Derneği kılavuzları", "SB kafa travması / spinal travma protokolleri", "TND (nöroloji) ile ortak inme/trombektomi cerrahi köprüsü", "SGK nöroşirürji işlem raporları", "Youmans and Winn Neurological Surgery"], soapFields: ["norocerrahi"], greeting: "Merhaba, ben Prof. Dr. Kerem Ersoy. Beyin Cerrahisi alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_BEYİN_CERRAHİ" },
  { key: "kalp-damar-cerrahisi", label: "Kalp Damar Cerrahisi", emoji: "❤️", color: "#9F1239", references: ["Türk Kalp ve Damar Cerrahisi Derneği kılavuzları", "TKD ile ortak kapak / CABG / aort yaklaşımları", "SB kardiyak cerrahi klinik protokolleri", "SGK kalp-damar cerrahi paket raporları", "Kirklin/Barratt-Boyes Cardiac Surgery"], soapFields: ["kardiyovaskuler_cerrahi"], greeting: "Merhaba, ben Prof. Dr. Sinan Acar. Kalp Damar Cerrahisi alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_KALP_DAMAR" },
  { key: "cocuk-cerrahisi", label: "Çocuk Cerrahisi", emoji: "👶", color: "#166534", references: ["Türk Çocuk Cerrahisi Derneği kılavuzları", "SB yenidoğan / çocuk cerrahi acil protokolleri", "ÇAYD ile ortak çocuk acil cerrahi yaklaşımlar", "SGK çocuk cerrahi işlem raporları", "Pediatric Surgery"], soapFields: ["cocuk_cerrahi"], greeting: "Merhaba, ben Prof. Dr. Derya Polat. Çocuk Cerrahisi alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_ÇOCUK_CERRAHİ" },
  { key: "aile-hekimligi", label: "Aile Hekimliği", emoji: "🏠", color: "#15803D", references: ["Türkiye Aile Hekimleri Uzmanlık Derneği (TAHUD) kaynakları", "T.C. SB Aile Hekimliği uygulamaları / kronik hastalık protokolleri", "SB Ulusal Aşılama Takvimi + erişkin bağışıklama", "SGK aile hekimliği performans / reçete kuralları", "Textbook of Family Medicine"], soapFields: ["aile_anamnezi"], greeting: "Merhaba, ben Prof. Dr. Yusuf Akın. Aile Hekimliği alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_AİLE" },
  { key: "spor-hekimligi", label: "Spor Hekimliği", emoji: "🏅", color: "#854D0E", references: ["Türkiye Spor Hekimliği Derneği kılavuzları", "SB sporcu sağlık kurulu / doping mevzuatı farkındalığı", "TOTBİD spor yaralanmaları ortak yaklaşımlar", "FIFA/IOC konsensuslarının TR spor hekimliği uygulaması", "ACSMs Sports Medicine"], soapFields: ["spor_yaralanma"], greeting: "Merhaba, ben Prof. Dr. Cemre Taş. Spor Hekimliği alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_SPOR" },
];

export const SPECIALTY_MAP: Record<string, Specialty> = SPECIALTIES.reduce((acc, s) => {
  acc[s.key] = s;
  return acc;
}, {} as Record<string, Specialty>);

export const SPECIALTY_COUNT = SPECIALTIES.length;
