export interface Specialty {
  key: string;
  label: string;
  emoji: string;
  color: string;
  references: string[];
  soapFields: string[];
  greeting: string;
  agentIdEnvVar: string;
}

/** 30 medical specialties — TR references match Ayşe pediatrics depth (turkishSpecialtyRefs). */
export const SPECIALTIES: Specialty[] = [
  { key: "pediatri", label: "Pediatri", emoji: "👶", color: "#0F9B8E", references: ["T.C. SB Ulusal Çocukluk Dönemi Aşılama Takvimi (GBP) — 2025", "Türk Pediatri Kurumu (TPK) klinik kılavuzları (AGE, ISPA, enürezis vb.)", "Türk Çocuk Acil Tıp ve Yoğun Bakım Derneği (ÇAYD) protokolleri", "SB Çocuk YBÜ kabul/taburculuk protokolü; Türk Toraks Derneği çocuk pnömoni/bronşiyolit", "SGK pediatrik reçete-rapor kuralları"], soapFields: ["ates", "kilo", "boy", "gelisim"], greeting: "Merhaba, ben Prof. Dr. Ayşe Kaya. Pediatri alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_PEDİATRİ" },
  { key: "kardiyoloji", label: "Kardiyoloji", emoji: "❤️", color: "#DC2626", references: ["Türk Kardiyoloji Derneği (TKD) — ESC kılavuzlarının resmi TR yayını/yorumu (tkd.org.tr)", "ESC/TKD 2023 Akut Koroner Sendrom (AKS) Kılavuzu", "ESC/TKD 2024 Atriyal Fibrilasyon; ESC 2021 KY + 2024 Odak Güncelleme", "ESC/TKD 2024 Hipertansiyon; ESC/TKD 2025 Dislipidemi; ESC 2023 Diyabet ve KVH", "T.C. SB göğüs ağrısı/AKS acil protokolleri; SGK kardiyak ilaç-stent-rapor"], soapFields: ["ekg", "ef", "nyha"], greeting: "Merhaba, ben Prof. Dr. Mehmet Demir. Kardiyoloji alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_KARDİYOLOJİ" },
  { key: "noroloji", label: "Nöroloji", emoji: "🧠", color: "#7C3AED", references: ["T.C. SB + Türk Nöroloji Derneği (TND) + Türk Beyin Damar Hastalıkları Derneği — Akut İskemik İnmede Tanı ve Tedavi Rehberi", "TND Epilepsi Tanı ve Tedavi Rehberi (2021)", "TND Migren Klinik Protokolü; TND Hareket Bozuklukları Rehberi (2023)", "TND Nöromusküler Rehber (2024); SB Klinik Protokolleri: İnme, Alzheimer/Demans, Epilepsi", "SGK nöroloji ilaç ve rapor kısıtları"], soapFields: ["norolojik_muayene", "gcs", "kraniyal_sinirler"], greeting: "Merhaba, ben Prof. Dr. Elif Şahin. Nöroloji alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_NÖROLOJİ" },
  { key: "dahiliye", label: "Dahiliye", emoji: "🩺", color: "#0F9B8E", references: ["İliçin İç Hastalıkları — Türk İç Hastalıkları Uzmanlık Derneği (TİHUD) yayını", "TİHUD klinik uygulama kaynakları ve eğitim materyalleri", "TEMD Diyabetes Mellitus Tanı-Tedavi-İzlem Kılavuzu (2024/2026)", "TEMD Hipertansiyon (2022); TEMD Dislipidemi / Obezite kılavuzları", "T.C. SB kronik hastalık klinik protokolleri; SGK dahiliye rapor/yeşil reçete"], soapFields: ["sistemik_muayene"], greeting: "Merhaba, ben Prof. Dr. Zeynep Arslan. Dahiliye alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_DAHİLİYE" },
  { key: "psikiyatri", label: "Psikiyatri", emoji: "🧘", color: "#6366F1", references: ["Türkiye Psikiyatri Derneği (TPD) tedavi kılavuzları ve çalışma birimi önerileri", "T.C. SB Ruh Sağlığı Eylem Planı / ruh sağlığı klinik protokolleri", "TPD depresyon, bipolar, şizofreni ve anksiyete tanı-tedavi yaklaşımları (TR)", "SB zorunlu yatış / kriz müdahale çerçevesi; bağımlılık tedavi protokolleri", "SGK psikotrop ilaç, yeşil-turuncu reçete ve rapor kuralları"], soapFields: ["mental_durum"], greeting: "Merhaba, ben Prof. Dr. Deniz Yılmaz. Psikiyatri alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_PSİKİYATRİ" },
  { key: "genel-cerrahi", label: "Genel Cerrahi", emoji: "🔪", color: "#EF4444", references: ["Türk Cerrahi Derneği (TCD) klinik kılavuz ve konsensusları", "T.C. SB ameliyathane güvenliği / cerrahi klinik protokolleri", "Türk Kolon ve Rektum Cerrahisi Derneği (TKRCD) ilgili rehberler", "Ulusal Travma ve Acil Cerrahi Derneği (UTACD) travma yaklaşımları (TR)", "SGK cerrahi paket, ameliyat ve rapor kuralları"], soapFields: ["cerrahi_anamnez"], greeting: "Merhaba, ben Prof. Dr. Hakan Öztürk. Genel Cerrahi alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_GENEL_CERRAHİ" },
  { key: "ortopedi", label: "Ortopedi", emoji: "🦴", color: "#F59E0B", references: ["Türk Ortopedi ve Travmatoloji Birliği Derneği (TOTBİD) klinik rehberleri", "T.C. SB travma / kırık / acil ortopedi klinik protokolleri", "TOTBİD alt grup konsensusları (diz, omuz, omurga, travma)", "AO prensiplerinin TOTBİD eğitimleri üzerinden TR uygulaması", "SGK protez, implant ve ortopedik malzeme rapor kuralları"], soapFields: ["travma", "rom", "xray"], greeting: "Merhaba, ben Prof. Dr. Burak Şen. Ortopedi alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_ORTOPEDİ" },
  { key: "dermatoloji", label: "Dermatoloji", emoji: "🧴", color: "#EC4899", references: ["Türk Dermatoloji Derneği (TDD) klinik kılavuzları", "T.C. SB deri kanseri / psoriazis klinik protokolleri", "TDD akne, ürtiker, atopik dermatit ve ilaç reaksiyonu konsensusları", "Türk Dermatoveneroloji / fototerapi çalışma grubu önerileri (TR)", "SGK biyolojik ve dermatolojik ilaç rapor kuralları"], soapFields: ["lezyon", "efflorescence"], greeting: "Merhaba, ben Prof. Dr. Selin Aksoy. Dermatoloji alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_DERMATOLOJİ" },
  { key: "kulak-burun-bogaz", label: "KBB", emoji: "👂", color: "#14B8A6", references: ["Türk Kulak Burun Boğaz ve Baş Boyun Cerrahisi Derneği klinik kılavuzları", "T.C. SB otitis media, tonsillit, sinüzit klinik protokolleri", "Türk Rinoloji Derneği sinüzit / rinoplasti konsensusları", "Türk Odyoloji / vestibüler çalışma grubu önerileri (TR KBB pratiği)", "SGK işitme cihazı, koklear implant ve KBB cerrahi raporları"], soapFields: ["kbb_muayene"], greeting: "Merhaba, ben Prof. Dr. Emre Aydın. KBB alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_KBB" },
  { key: "goz-hastaliklari", label: "Göz Hastalıkları", emoji: "👁️", color: "#3B82F6", references: ["Türk Oftalmoloji Derneği (TOD) kılavuz, bülten ve çalışma grubu önerileri", "T.C. SB diyabetik retinopati tarama ve glokom klinik protokolleri", "TOD Retina, Kornea, Glokom birimleri klinik protokolleri", "TOD pediatrik oftalmoloji / şaşılık yaklaşımları (TR)", "SGK göz içi lens, anti-VEGF enjeksiyon ve rapor kuralları"], soapFields: ["goz_muayene"], greeting: "Merhaba, ben Prof. Dr. İrem Kaya. Göz Hastalıkları alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_GÖZ" },
  { key: "kadin-hastaliklari-dogum", label: "Kadın Hastalıkları ve Doğum", emoji: "🤰", color: "#BE185D", references: ["Türk Jinekoloji ve Obstetrik Derneği (TJOD) klinik kılavuzları", "T.C. SB Doğum ve Sezaryen Yönetim Rehberi", "SB anne ölümü / obstetrik acil protokolleri; prenatal bakım rehberleri", "TJOD jinekolojik onkoloji, üreme endokrinolojisi ve ürojinekoloji konsensusları", "SGK gebelik, IVF ve jinekoloji rapor kuralları"], soapFields: ["jinekolojik_anamnez"], greeting: "Merhaba, ben Prof. Dr. Fatma Çelik. Kadın Hastalıkları ve Doğum alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_KADIN_DOĞUM" },
  { key: "uroloji", label: "Üroloji", emoji: "🚽", color: "#0EA5E9", references: ["Türk Üroloji Derneği (TÜD) klinik kılavuzları", "TÜD — EAU kılavuzlarının Türkiye pratiğine uyarlanmış yorumları", "T.C. SB üriner sistem enfeksiyonu ve prostat klinik protokolleri", "Türk Pediatrik Üroloji / endoüroloji çalışma grubu önerileri", "SGK ürolojik ilaç, ESWL, protez ve işlem raporları"], soapFields: ["urolojik_muayene"], greeting: "Merhaba, ben Prof. Dr. Murat Yıldız. Üroloji alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_ÜROLOJİ" },
  { key: "radyoloji", label: "Radyoloji", emoji: "📷", color: "#64748B", references: ["Türk Radyoloji Derneği (TRD) standartları ve kalite önerileri", "T.C. SB / TAEK radyasyon güvenliği mevzuatı ve doz sınırları", "TRD kontrast madde güvenliği ve gebelikte görüntüleme protokolleri", "TRD meme, toraks, nöro ve acil radyoloji çalışma grubu önerileri", "SGK görüntüleme tetkik endikasyon ve rapor kuralları"], soapFields: ["goruntuleme_bulgulari"], greeting: "Merhaba, ben Prof. Dr. Caner Koç. Radyoloji alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_RADYOLOJİ" },
  { key: "anestezi", label: "Anestezi", emoji: "💉", color: "#8B5CF6", references: ["Türk Anesteziyoloji ve Reanimasyon Derneği (TARD) klinik kılavuzları", "T.C. SB ameliyathane, sedasyon ve anestezi güvenlik protokolleri", "TARD zor havayolu ve obstetrik anestezi önerileri", "TARD perioperatif ağrı / ERAS uyumlu TR uygulamaları", "SGK anestezi işlem kodları ve rapor kuralları"], soapFields: ["anestezi_riski"], greeting: "Merhaba, ben Prof. Dr. Pınar Demir. Anestezi alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_ANESTEZİ" },
  { key: "acil-tip", label: "Acil Tıp", emoji: "🚑", color: "#F97316", references: ["Türkiye Acil Tıp Derneği (TATD) klinik protokolleri ve algoritmaları", "T.C. SB Acil Servis klinik protokolleri ve triaj standartları", "SB kritik hasta yönlendirme / 112 entegrasyon protokolleri", "ATLS Türkiye uygulamaları; ERC resusitasyon eğitiminin TR acil pratiği", "SGK acil işlem ve raporlama kuralları"], soapFields: ["acil_degerlendirme"], greeting: "Merhaba, ben Prof. Dr. Oğuz Kılıç. Acil Tıp alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_ACİL" },
  { key: "fizik-tedavi", label: "Fizik Tedavi", emoji: "🏃", color: "#22C55E", references: ["Türkiye Fiziksel Tıp ve Rehabilitasyon Derneği klinik kılavuzları", "T.C. SB rehabilitasyon ve engellilik değerlendirme protokolleri", "Türk Osteoporoz Derneği / TEMD ile örtüşen kemik sağlığı önerileri", "FTR ağrı, enjeksiyon ve nörorehabilitasyon çalışma grubu önerileri (TR)", "SGK fizik tedavi seans sayısı, ortez ve rapor kuralları"], soapFields: ["fiziksel_degerlendirme"], greeting: "Merhaba, ben Prof. Dr. Aylin Erdem. Fizik Tedavi alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_FİZİK" },
  { key: "enfeksiyon-hastaliklari", label: "Enfeksiyon Hastalıkları", emoji: "🦠", color: "#E11D48", references: ["KLİMİK (Türk Klinik Mikrobiyoloji ve İnfeksiyon Hastalıkları Derneği) kılavuzları", "T.C. SB Akılcı Antibiyotik Kullanımı rehberleri", "SB hastane enfeksiyon kontrolü, izolasyon ve sürveyans protokolleri", "SB HIV, tüberküloz, viral hepatit tanı-tedavi klinik protokolleri", "SGK antibiyotik, antiviral ve enfeksiyon ilaç kısıtları"], soapFields: ["enfeksiyon_belirtileri"], greeting: "Merhaba, ben Prof. Dr. Serkan Güneş. Enfeksiyon Hastalıkları alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_ENFEKSİYON" },
  { key: "endokrinoloji", label: "Endokrinoloji", emoji: "🧬", color: "#A855F7", references: ["TEMD Diyabetes Mellitus Tanı, Tedavi ve İzlem Kılavuzu (2024/2026)", "TEMD Tiroid Hastalıkları Tanı ve Tedavi Kılavuzu (2025)", "TEMD Osteoporoz ve Metabolik Kemik Hastalıkları Kılavuzu (2025)", "TEMD Adrenal-Gonadal (2025); Hipertansiyon (2022); Obezite / Dislipidemi", "SGK endokrin ilaç, insülin, GLP-1/SGLT2i ve rapor kuralları"], soapFields: ["endokrin_lab"], greeting: "Merhaba, ben Prof. Dr. Gülşah Tekin. Endokrinoloji alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_ENDOKRİN" },
  { key: "gastroenteroloji", label: "Gastroenteroloji", emoji: "🫁", color: "#F43F5E", references: ["Türk Gastroenteroloji Derneği (TGD) klinik kılavuzları", "T.C. SB hepatit B/C, siroz ve GI kanama klinik protokolleri", "TGD IBD, H. pylori eradikasyonu ve karaciğer hastalıkları konsensusları", "Türk Karaciğer Araştırmaları Derneği (TKAD) ile ortak hepatoloji yaklaşımları", "SGK biyolojik, antiviral ve endoskopi rapor kuralları"], soapFields: ["gastro_anamnez"], greeting: "Merhaba, ben Prof. Dr. Volkan Arı. Gastroenteroloji alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_GASTRO" },
  { key: "nefroloji", label: "Nefroloji", emoji: "🫘", color: "#06B6D4", references: ["Türk Nefroloji Derneği klinik kılavuzları ve konsensusları", "T.C. SB kronik böbrek hastalığı ve diyaliz klinik protokolleri", "Türk Hipertansiyon ve Böbrek Hastalıkları Derneği ilgili öneriler", "KDIGO ilkelerinin Türk Nefroloji Derneği pratiğindeki uyarlamaları", "SGK diyaliz, eritropoietin, fosfat bağlayıcı ve rapor kuralları"], soapFields: ["bobrek_fonksiyonlari"], greeting: "Merhaba, ben Prof. Dr. Mert Özkan. Nefroloji alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_NEFRO" },
  { key: "romatoloji", label: "Romatoloji", emoji: "🦵", color: "#D97706", references: ["Türkiye Romatoloji Derneği klinik kılavuzları", "T.C. SB romatoid artrit / SLE klinik protokolleri", "Türkiye Romatoloji Derneği biyolojik ajan güvenlik önerileri (TB/HBV tarama)", "EULAR/ACR kriterlerinin TR romatoloji pratiğindeki yorumu", "SGK biyolojik DMARD ve romatoloji rapor kuralları"], soapFields: ["eklem_muayenesi"], greeting: "Merhaba, ben Prof. Dr. Nazlı Kara. Romatoloji alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_ROMATO" },
  { key: "onkoloji", label: "Onkoloji", emoji: "🎗️", color: "#7C2D12", references: ["Türk Tıbbi Onkoloji Derneği (TTOD) klinik kılavuzları", "T.C. SB ulusal kanser tarama ve tedavi protokolleri", "Türk Radyasyon Onkolojisi / Hematoloji dernekleriyle ortak TR yaklaşımlar", "NCCN/ESMO’nun TTOD üzerinden Türkiye ilaç erişimine uyarlanmış uygulaması", "SGK onkoloji ilaçları, yeşil reçete ve tedavi rapor kuralları"], soapFields: ["onkolojik_degerlendirme"], greeting: "Merhaba, ben Prof. Dr. Ece Yurt. Onkoloji alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_ONKOLOJİ" },
  { key: "gogus-hastaliklari", label: "Göğüs Hastalıkları", emoji: "🫀", color: "#0D9488", references: ["Türk Toraks Derneği (TTD) astım, KOAH, pnömoni kılavuzları", "GINA/GOLD’un TTD tarafından Türkiye’ye uyarlanmış önerileri", "T.C. SB tüberküloz tanı-tedavi ve pnömoni klinik protokolleri", "TTD pulmoner emboli / uyku bozuklukları çalışma grubu önerileri", "SGK inhaler, uzun süreli oksijen, NIV ve rapor kuralları"], soapFields: ["solunum_fonksiyonlari"], greeting: "Merhaba, ben Prof. Dr. Barış Uysal. Göğüs Hastalıkları alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_GÖĞÜS" },
  { key: "gogus-cerrahisi", label: "Göğüs Cerrahisi", emoji: "🫁", color: "#B91C1C", references: ["Türk Göğüs Cerrahisi Derneği klinik kılavuzları", "T.C. SB toraks travması ve tüp torakostomi protokolleri", "TTD + Türk Göğüs Cerrahisi Derneği akciğer kanseri cerrahi yaklaşımları", "Türk Toraks Derneği / göğüs cerrahisi VATS-minimal invaziv konsensusları", "SGK torasik cerrahi paket ve rapor kuralları"], soapFields: ["torasik_anamnez"], greeting: "Merhaba, ben Prof. Dr. Tolga Şimşek. Göğüs Cerrahisi alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_GÖĞÜS_CERRAHİ" },
  { key: "plastik-cerrahi", label: "Plastik Cerrahi", emoji: "✨", color: "#C026D3", references: ["Türk Plastik Rekonstrüktif ve Estetik Cerrahi Derneği (TPRECD) kılavuzları", "T.C. SB yanık merkezi ve yara bakımı klinik protokolleri", "TPRECD etik, hasta güvenliği ve estetik cerrahi önerileri", "Türk El ve Üst Ekstremite Cerrahisi Derneği ortak yaklaşımlar (TR)", "SGK rekonstrüktif işlem ve rapor kuralları"], soapFields: ["plastik_degerlendirme"], greeting: "Merhaba, ben Prof. Dr. Melis Orhan. Plastik Cerrahi alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_PLASTİK" },
  { key: "beyin-cerrahisi", label: "Beyin Cerrahisi", emoji: "🧠", color: "#581C87", references: ["Türk Nöroşirürji Derneği klinik kılavuzları", "T.C. SB kafa travması ve spinal travma klinik protokolleri", "Türk Nöroşirürji Derneği tümör / vasküler / spinal çalışma grubu önerileri", "TND (nöroloji) + TBDHD ile ortak inme/trombektomi cerrahi köprüsü", "SGK nöroşirürji işlem ve rapor kuralları"], soapFields: ["norocerrahi"], greeting: "Merhaba, ben Prof. Dr. Kerem Ersoy. Beyin Cerrahisi alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_BEYİN_CERRAHİ" },
  { key: "kalp-damar-cerrahisi", label: "Kalp Damar Cerrahisi", emoji: "❤️", color: "#9F1239", references: ["Türk Kalp ve Damar Cerrahisi Derneği klinik kılavuzları", "TKD + Türk Kalp Damar Cerrahisi Derneği ortak kapak/CABG/aort yaklaşımları", "T.C. SB kardiyak cerrahi ve perioperatif klinik protokolleri", "Türk Damar Cerrahisi / periferik arter hastalıkları konsensusları", "SGK kalp-damar cerrahi paket, kapak ve stent-graft raporları"], soapFields: ["kardiyovaskuler_cerrahi"], greeting: "Merhaba, ben Prof. Dr. Sinan Acar. Kalp Damar Cerrahisi alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_KALP_DAMAR" },
  { key: "cocuk-cerrahisi", label: "Çocuk Cerrahisi", emoji: "👶", color: "#166534", references: ["Türk Çocuk Cerrahisi Derneği klinik kılavuzları", "T.C. SB yenidoğan ve çocuk cerrahi acil protokolleri", "ÇAYD + Türk Çocuk Cerrahisi Derneği ortak çocuk acil cerrahi yaklaşımlar", "SB çocuk yoğun bakım / cerrahi sevk protokolleri", "SGK çocuk cerrahi işlem ve rapor kuralları"], soapFields: ["cocuk_cerrahi"], greeting: "Merhaba, ben Prof. Dr. Derya Polat. Çocuk Cerrahisi alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_ÇOCUK_CERRAHİ" },
  { key: "aile-hekimligi", label: "Aile Hekimliği", emoji: "🏠", color: "#15803D", references: ["Türkiye Aile Hekimleri Uzmanlık Derneği (TAHUD) klinik kaynakları", "T.C. SB Aile Hekimliği uygulama yönetmeliği ve kronik hastalık protokolleri", "SB Ulusal Aşılama Takvimi (çocuk + erişkin bağışıklama)", "SB birinci basamak tarama, sevk ve koruyucu hekimlik rehberleri", "SGK aile hekimliği performans, reçete ve rapor kuralları"], soapFields: ["aile_anamnezi"], greeting: "Merhaba, ben Prof. Dr. Yusuf Akın. Aile Hekimliği alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_AİLE" },
  { key: "spor-hekimligi", label: "Spor Hekimliği", emoji: "🏅", color: "#854D0E", references: ["Türkiye Spor Hekimliği Derneği klinik kılavuzları", "T.C. SB sporcu sağlık kurulu mevzuatı ve muayene standartları", "TOTBİD + Spor Hekimliği Derneği spor yaralanması ortak yaklaşımları", "Türkiye Anti-Doping mevzuatı farkındalığı (hekim sorumluluğu)", "SGK spor hekimliği işlem / rapor çerçevesi (ilgili branş kodları)"], soapFields: ["spor_yaralanma"], greeting: "Merhaba, ben Prof. Dr. Cemre Taş. Spor Hekimliği alanında size yardımcı oluyorum.", agentIdEnvVar: "GROQ_AGENT_SPOR" },
];

export const SPECIALTY_MAP: Record<string, Specialty> = SPECIALTIES.reduce((acc, s) => {
  acc[s.key] = s;
  return acc;
}, {} as Record<string, Specialty>);

export const SPECIALTY_COUNT = SPECIALTIES.length;
