/**
 * HASTA-IZOLASYON-01 — every API file that can reach patient data, and how its doctor-scoping is
 * guaranteed. lib/security/hasta-izolasyon-envanter.test.ts fails when:
 *   • a file under a patient-data tree (or any app/api file that starts using patient identifiers)
 *     is missing here — a new route cannot merge unclassified;
 *   • an entry marked 'test' is not actually exercised by lib/security/hasta-izolasyon.test.ts;
 *   • an entry points at a file that no longer exists.
 *
 * 'test'      → covered by the cross-doctor regression suite (A↔B, both directions, positive control).
 * 'incelendi' → reviewed by hand; `kapsam` states the exact mechanism. Prefer promoting to 'test'.
 * Audit: docs/OPEN-COMMITMENTS.md § HASTA-IZOLASYON. Rule: .cursor/skills/hasta-izolasyon/SKILL.md.
 */
export type Siniflama = { durum: 'test' } | { durum: 'incelendi'; kapsam: string }

const T = { durum: 'test' } as const
const I = (kapsam: string): Siniflama => ({ durum: 'incelendi', kapsam })

export const HASTA_IZOLASYON_ENVANTERI: Record<string, Siniflama> = {
  // ── Hasta kaydı ──
  'app/api/doktor/hastalar/route.ts': T,
  'app/api/doktor/hastalar/[id]/route.ts': T,
  'app/api/doktor/hastalar/[id]/sessions/route.ts': T,
  'app/api/doktor/hastalar/[id]/sessions/[sessionId]/arsivle/route.ts': I('session looked up AND updated with doctor_id = user.id AND patient_id = params.id together — 404 for a foreign session or a session belonging to a different patient'),
  'app/api/doktor/hastalar/[id]/buyume-egrileri/route.ts': T,
  'app/api/doktor/hastalar/[id]/hedef-boy/route.ts': T,
  // ── Notlar / seanslar ──
  'app/api/notes/route.ts': T,
  'app/api/notes/[id]/route.ts': T,
  'app/api/notes/[id]/approve/route.ts': T,
  'app/api/notes/whatsapp/route.ts': I('note loaded by id AND doctor_id = user.id before anything is sent'),
  'app/api/notes/pdf/route.ts': I('renders only the body it is given (mali note); reads no patient table'),
  'app/api/doktor/son-notlar/route.ts': T,
  'app/api/sessions/start/route.ts': T,
  'app/api/sessions/[id]/end/route.ts': T,
  'app/api/sessions/ses-yukle/route.ts': T,
  'app/api/doktor/not-konsult/route.ts': I('note loaded by id AND doctor_id = doktorId; 404 otherwise'),
  'app/api/doktor/konsult/route.ts': I('hastaDosyasiniDerle(doktorId, patientId) returns null for a foreign patient → 404'),
  'app/api/doktor/medula/recete/route.ts': I('note by id AND doctor_id; patient read scoped by doctor_id'),
  'app/api/doktor/rrs/route.ts': I('note by id AND doctor_id, patient ownership re-checked; list/patch scoped by doctor_id'),
  'app/api/doktor/raporlar/route.ts': I('aggregates only rows with doctor_id = user.id'),
  // ── İlaç / aşı / lab / belge / görüntü / cihaz ──
  'app/api/doktor/ilaclar/route.ts': T,
  'app/api/doktor/ilaclar/[id]/route.ts': T,
  'app/api/doktor/ilaclar/doz-oner/route.ts': I('patient row fetched and doctor_id compared to user.id before any read → 404'),
  'app/api/doktor/asilar/route.ts': T,
  'app/api/doktor/asilar/[id]/route.ts': I('update/delete by id AND doktor_id = doktorId'),
  'app/api/doktor/asilar/karne/route.ts': T,
  'app/api/doktor/asilar/karne/pdf/route.ts': T,
  'app/api/doktor/asilar/hatirlatma/route.ts': T,
  'app/api/doktor/belgeler/lab/route.ts': T,
  'app/api/doktor/belgeler/analiz/route.ts': I('document via vault getDocumentMeta(doctorId) (assertPatientOwned); analyses by doctor_id'),
  'app/api/doktor/belgeler/analiz/onayla/route.ts': I('analysis by id AND doctor_id; target note by id AND doctor_id'),
  'app/api/doktor/belgeler/ingest/route.ts': T,
  // KONSULTASYON-01 — kapalı döngü konsültasyon (sevkler + Kasa belgesi + bugünkü not + Sağlığım hatırlatması)
  'app/api/doktor/konsultasyon/route.ts': T,
  // NOTYA-EYLEM — Ayşe hazırlar, hekim onaylar (core/eylemler/*)
  'app/api/doktor/eylem/route.ts': T,
  'app/api/doktor/documents/route.ts': I('vault listDocuments/uploadDocument — doctor-scoped, assertPatientOwned (lib/vault/service.acl.test.ts)'),
  'app/api/doktor/documents/[id]/route.ts': I('vault getDocumentMeta/softDeleteDocument by doctor_id (lib/vault/service.acl.test.ts)'),
  'app/api/doktor/documents/[id]/download/route.ts': I('vault downloadDocument by doctor_id (lib/vault/service.acl.test.ts)'),
  'app/api/doktor/goruntuleme/route.ts': T,
  'app/api/doktor/goruntuleme/[id]/route.ts': I('row fetched, doctor_id !== user.id → 403 before storage/DB delete'),
  'app/api/doktor/goruntuleme/yukle/route.ts': T,
  'app/api/doktor/goruntuler/route.ts': I('GET/POST: hastaSahibiMi then goruntu_calisma.eq(doctor_id); vault uploadDocument assertPatientOwned'),
  'app/api/doktor/goruntuler/[id]/route.ts': I('GET/PATCH row by id AND doctor_id; priors/seri scoped doctor_id+patient_id'),
  'app/api/doktor/cihaz-olcum/route.ts': T,
  'app/api/doktor/cihaz-olcum/dosya/route.ts': I('patient ownership check before vault upload (vault re-checks)'),
  // ── Randevu / takvim / mesaj / hatırlatma / intake ──
  'app/api/doktor/randevular/route.ts': T,
  'app/api/doktor/randevular/[id]/route.ts': T,
  'app/api/doktor/gun-programi/route.ts': T,
  'app/api/doktor/calisma-saatleri/route.ts': I('doctor working hours only (doktor_id); no patient data'),
  'app/api/doktor/mesajlar/route.ts': T,
  'app/api/doktor/mesajlar/[konuId]/route.ts': T,
  'app/api/doktor/mesajlar/unread-count/route.ts': I('count scoped by doctor_id'),
  'app/api/doktor/hatirlatma/route.ts': T,
  'app/api/doktor/intake-formlari/route.ts': T,
  'app/api/doktor/intake-formlari/[id]/route.ts': I('form by id AND doktor_id'),
  // ── Branş modülleri ──
  'app/api/doktor/mchat/route.ts': T,
  'app/api/doktor/gelisim-taramasi/route.ts': T,
  'app/api/doktor/kadin-sagligi/route.ts': T,
  // DERM-EXCEPTIONAL-01: 'goruntu-okuma' (belge_taslak / asistana_raporla) da bu dosyada — analiz ve görüntü
  // kimlikleri hastaSahibiMi() sonrası patient_id + doctor_id ile yeniden daraltılır; okuma epizoda yazılır.
  'app/api/doktor/dermatoloji/route.ts': T,
  'app/api/doktor/dermatoloji/spine/route.ts': T,
  'app/api/doktor/dermatoloji/_kohort.ts': I('patient ids drawn only from hasta_derm / derm_gorevleri / derm_ilac_guvenlik rows with doctor_id = doctorId; child tables (yama, fototerapi, lezyon) read by hasta_derm_id taken from those doctor-scoped episodes; patients read by doctor_id (read-only — dermHatirlatmaGonder lives in _kohortHatirlatma.ts, NOTYA-EYLEM-24)'),
  'app/api/doktor/dermatoloji/_kohortHatirlatma.ts': I('dermHatirlatmaGonder — split out of _kohort.ts (NOTYA-EYLEM-24, keeps the write path out of the chat/voice import graph); runs only on ids that passed dermKohortVerisi(doctorId) in kohort/route.ts'),
  'app/api/doktor/dermatoloji/kohort/route.ts': I('POST ids filtered through dermKohortVerisi(doctorId) before any message is written'),
  'app/api/doktor/gebelik/route.ts': T,
  'app/api/doktor/gebelik/dogum/route.ts': T,
  'app/api/doktor/gebelik/kohort/route.ts': T,
  'app/api/doktor/gebelik/_kohort.ts': I('patient ids drawn only from gebelikler / kadin_sagligi rows with doctor_id = doctorId; every secondary read (patients, izlem, genetik, lohusa, sessions, portal) doctor_id-scoped (read-only — kdHatirlatmaGonder lives in _kohortHatirlatma.ts, NOTYA-EYLEM-24)'),
  'app/api/doktor/gebelik/_kohortHatirlatma.ts': I('kdHatirlatmaGonder — split out of _kohort.ts (NOTYA-EYLEM-24); runs only on ids that passed kdKohortVerisi(doctorId) in kohort/route.ts'),
  'app/api/doktor/yenidogan/route.ts': I('baby card fetched by patient AND doctor_id; every derived id comes from that card; patient reads doctor-scoped'),
  'app/api/doktor/jinekoloji/route.ts': T,
  'app/api/doktor/goz/route.ts': T,
  'app/api/doktor/goz/kohort/route.ts': T,
  'app/api/doktor/goz/_ek.ts': I('gozEkAdim / gozEkVeri run only after route.ts hasta(doctorId, patientId); every read/write .eq(patient_id, h.id).eq(doctor_id); child ids (katarakt, acil, görüntü) re-scoped by patient_id + doctor_id'),
  'app/api/doktor/goz/_kohort.ts': I('patient ids drawn only from goz_* rows with doctor_id = doctorId; patients read by doctor_id (read-only — gozHatirlatmaGonder lives in _kohortHatirlatma.ts, NOTYA-EYLEM-24)'),
  'app/api/doktor/goz/_kohortHatirlatma.ts': I('gozHatirlatmaGonder — split out of _kohort.ts (NOTYA-EYLEM-24); runs only on ids that passed gozKohortVerisi(doctorId) or hasta(), called from kohort/route.ts and _ek.ts'),
  'app/api/doktor/pediatri/route.ts': T,
  'app/api/doktor/pediatri/_ortak.ts': I('pediHasta: patients by id AND doctor_id — the gate every pediatri handler passes first; pediOturum = doktorOturum + users.specialty pediatri'),
  'app/api/doktor/pediatri/tarama/route.ts': T,
  'app/api/doktor/pediatri/kohort/route.ts': T,
  'app/api/doktor/fisilti/route.ts': I('proxies exactly one branş kohort route via an internal same-origin fetch, forwarding the SAME caller bearer token unchanged -- that downstream route re-runs doktorOturum + its own doctor_id scoping independently (see its own entry above/below); this file issues no Supabase query of its own, so it cannot leak a foreign patient even if the caller supplied one, and identifies the target branş only from users.specialty of the AUTHENTICATED doctor, never from request input'),
  'app/api/doktor/pediatri/_kohort.ts': I('kohort: patients .eq(doctor_id) → ids; every source query .eq(doctor_id|doktor_id).in(patient_id, ids) (read-only — pediHatirlatmaGonder lives in _kohortHatirlatma.ts, NOTYA-EYLEM-24)'),
  'app/api/doktor/pediatri/_kohortHatirlatma.ts': I('pediHatirlatmaGonder — split out of _kohort.ts (NOTYA-EYLEM-24); runs only on ids that passed pediKohortVerisi(doktorId) in kohort/route.ts'),
  'app/api/doktor/dahiliye/route.ts': T,
  'app/api/doktor/dahiliye/_ortak.ts': I('hastaBilgi/hastaAdi: patients by id AND doctor_id — the gate every dahiliye handler passes first'),
  'app/api/doktor/dahiliye/_wow2.ts': I('runs only after hastaBilgi(); id-keyed updates scoped by doctor_id or the verified patient'),
  'app/api/doktor/dahiliye/_wow3.ts': I('runs only after hastaBilgi(); id-keyed updates scoped by doctor_id or the verified patient'),
  'app/api/doktor/dahiliye/_wow4.ts': I('runs only after hastaBilgi(); id-keyed updates scoped by doctor_id or the verified patient'),
  'app/api/doktor/dahiliye/_wow5.ts': I('runs only after hastaBilgi(); id-keyed updates scoped by doctor_id or the verified patient'),
  'app/api/doktor/dahiliye/_kohort.ts': I('patient ids drawn only from rows with doctor_id = doctorId; patients read by doctor_id'),
  'app/api/doktor/dahiliye/kohort/route.ts': I('POST ids filtered through kohortVerisi(doctorId) before any message is written'),
  'app/api/doktor/psikiyatri/_kohort.ts': I('patient ids drawn only from hasta_psik / psik_olcek / psik_risk / psik_gorevleri rows with doctor_id = doctorId; patients read by doctor_id; psikHatirlatmaGonder runs only on ids that passed that filter'),
  'app/api/doktor/psikiyatri/kohort/route.ts': I('POST ids filtered through psikKohortVerisi(doctorId) before any message is written'),
  'app/api/doktor/psikiyatri/route.ts': I('GET and POST both open with hastaSahibiMi(supabase, user.id, patientId) → 404 for a foreign patient; every psik_* read/write .eq(patient_id).eq(doctor_id), and row-id updates (gorev, kontrol) carry id + doctor_id + patient_id in the same query'),
  'app/api/doktor/kulak-burun-bogaz/_kohort.ts': I('patient ids drawn only from hasta_kbb / kbb_odyometri / kbb_risk / kbb_gorevleri rows with doctor_id = doctorId; patients read by doctor_id; kbbHatirlatmaGonder runs only on ids that passed that filter'),
  'app/api/doktor/kulak-burun-bogaz/kohort/route.ts': I('POST ids filtered through kbbKohortVerisi(doctorId) before any message is written'),
  'app/api/doktor/kulak-burun-bogaz/route.ts': I('GET and POST both open with hastaSahibiMi(supabase, user.id, patientId) → 404 for a foreign patient; every kbb_* read/write .eq(patient_id).eq(doctor_id), and row-id updates (gorev, kontrol, osas) carry id + doctor_id + patient_id in the same query'),
  'app/api/doktor/kardiyoloji/_kohort.ts': I('patient ids drawn only from hasta_kardiyoloji / kardio_score2 / kardio_izlem / kardio_risk / kardio_gorevleri rows with doctor_id = doctorId; patients read by doctor_id; kardioHatirlatmaGonder runs only on ids that passed that filter'),
  'app/api/doktor/kardiyoloji/kohort/route.ts': I('POST ids filtered through kardioKohortVerisi(doctorId) before any message is written'),
  'app/api/doktor/kardiyoloji/route.ts': I('GET and POST both open with hastaSahibiMi(supabase, user.id, patientId) → 404 for a foreign patient; every kardio_* / hasta_kardiyoloji read/write .eq(patient_id).eq(doctor_id), and row-id updates (gorev, kontrol) carry id + doctor_id + patient_id in the same query'),
  'app/api/doktor/gogus-hastaliklari/_kohort.ts': I('patient ids drawn only from hasta_gogus / gogus_skor / gogus_risk / gogus_gorevleri rows with doctor_id = doctorId; patients read by doctor_id; gogusHatirlatmaGonder runs only on ids that passed that filter'),
  'app/api/doktor/gogus-hastaliklari/kohort/route.ts': I('GET/POST use gogusKohortVerisi(doctorId); POST recall only for ids returned by that filter'),
  'app/api/doktor/gogus-hastaliklari/route.ts': I('GET and POST both open with hastaSahibiMi(supabase, user.id, patientId) → 404 for a foreign patient; every gogus_* read/write .eq(patient_id).eq(doctor_id)'),
  'app/api/doktor/noroloji/_kohort.ts': I('patient ids drawn only from hasta_noroloji / noro_migren / noro_risk / noro_gorevleri rows with doctor_id = doctorId; patients read by doctor_id; noroHatirlatmaGonder runs only on ids that passed that filter'),
  'app/api/doktor/noroloji/kohort/route.ts': I('POST ids filtered through noroKohortVerisi(doctorId) before any message is written'),
  'app/api/doktor/noroloji/route.ts': I('GET and POST both open with hastaSahibiMi(supabase, user.id, patientId) → 404 for a foreign patient; every noro_* / hasta_noroloji read/write .eq(patient_id).eq(doctor_id), and row-id updates (gorev, kontrol) carry id + doctor_id + patient_id in the same query'),
  'app/api/doktor/endokrinoloji/_kohort.ts': I('patient ids drawn only from hasta_endokrinoloji / endo_lab / endo_acil / endo_gorevleri rows with doctor_id = doctorId; patients read by doctor_id; endoHatirlatmaGonder runs only on ids that passed that filter'),
  'app/api/doktor/endokrinoloji/kohort/route.ts': I('POST ids filtered through endoKohortVerisi(doctorId) before any message is written'),
    'app/api/doktor/romatoloji/_kohort.ts': I('patient ids drawn only from hasta_romatoloji / roma_skor / roma_lab / roma_acil / roma_gorevleri / roma_eklem rows with doctor_id = doctorId; patients read by doctor_id; romaHatirlatmaGonder runs only on ids that passed that filter'),
  'app/api/doktor/romatoloji/kohort/route.ts': I('POST ids filtered through romaKohortVerisi(doctorId) before any message is written'),
  'app/api/doktor/romatoloji/route.ts': I('GET and POST both open with hastaSahibiMi(supabase, user.id, patientId) → 404 for a foreign patient; every roma_* / hasta_romatoloji read/write .eq(patient_id).eq(doctor_id), and row-id updates (gorev, kontrol) carry id + doctor_id + patient_id in the same query'),
'app/api/doktor/endokrinoloji/route.ts': I('GET and POST both open with hastaSahibiMi(supabase, user.id, patientId) → 404 for a foreign patient; every endo_* / hasta_endokrinoloji read/write .eq(patient_id).eq(doctor_id), and row-id updates (gorev, kontrol) carry id + doctor_id + patient_id in the same query'),
  'app/api/doktor/enfeksiyon-hastaliklari/_kohort.ts': I('patient ids drawn only from hasta_enfeksiyon / enfeksiyon_izolasyon / enfeksiyon_atb / enfeksiyon_viral / enfeksiyon_acil / enfeksiyon_gorevleri rows with doctor_id = doctorId; patients read by doctor_id; enfHatirlatmaGonder runs only on ids that passed that filter'),
  'app/api/doktor/enfeksiyon-hastaliklari/kohort/route.ts': I('POST ids filtered through enfKohortVerisi(doctorId) before any message is written'),
  'app/api/doktor/enfeksiyon-hastaliklari/route.ts': I('GET and POST both open with hastaSahibiMi(supabase, user.id, patientId) → 404 for a foreign patient; every enfeksiyon_* / hasta_enfeksiyon read/write .eq(patient_id).eq(doctor_id), and row-id updates (gorev, kontrol) carry id + doctor_id + patient_id in the same query'),
  'app/api/doktor/nefroloji/_kohort.ts': I('patient ids drawn only from hasta_nefroloji / nef_egfr / nef_anemi / nef_diyaliz / nef_acil / nef_gorevleri rows with doctor_id = doctorId; patients read by doctor_id; nefHatirlatmaGonder runs only on ids that passed that filter'),
  'app/api/doktor/nefroloji/kohort/route.ts': I('POST ids filtered through nefKohortVerisi(doctorId) before any message is written'),
  'app/api/doktor/nefroloji/route.ts': I('GET and POST both open with hastaSahibiMi(supabase, user.id, patientId) → 404 for a foreign patient; every nef_* / hasta_nefroloji read/write .eq(patient_id).eq(doctor_id), and row-id updates (gorev, kontrol) carry id + doctor_id + patient_id in the same query'),
  'app/api/doktor/gastroenteroloji/_kohort.ts': I('patient ids drawn only from hasta_gastro / gastro_* rows with doctor_id = doctorId; patients read by doctor_id; hatirlatma only on filtered ids'),
  'app/api/doktor/gastroenteroloji/kohort/route.ts': I('POST ids filtered through gastroKohortVerisi(doctorId) before any message is written'),
  'app/api/doktor/gastroenteroloji/route.ts': I('GET and POST both open with hastaSahibiMi(supabase, user.id, patientId) → 404 for a foreign patient; every gastro_* / hasta_gastro read/write .eq(patient_id).eq(doctor_id)'),
  'app/api/doktor/gogus-cerrahisi/_kohort.ts': I('patient ids drawn only from hasta_gogus_cerrahisi / goc_* rows with doctor_id = doctorId; patients read by doctor_id; hatirlatma only on filtered ids'),
  'app/api/doktor/gogus-cerrahisi/kohort/route.ts': I('POST ids filtered through gogusCerrahiKohortVerisi(doctorId) before any message is written'),
  'app/api/doktor/gogus-cerrahisi/route.ts': I('GET and POST both open with hastaSahibiMi(supabase, user.id, patientId) → 404 for a foreign patient; every table read/write .eq(patient_id).eq(doctor_id)'),
  'app/api/doktor/beyin-cerrahisi/_kohort.ts': I('patient ids drawn only from hasta_beyin_cerrahisi / bc_postop / bc_bilinc / bc_acil / bc_gorevleri rows with doctor_id = doctorId; patients read by doctor_id; bcHatirlatmaGonder runs only on ids that passed that filter'),
  'app/api/doktor/beyin-cerrahisi/kohort/route.ts': I('POST ids filtered through bcKohortVerisi(doctorId) before any message is written'),
  'app/api/doktor/beyin-cerrahisi/route.ts': I('GET and POST both open with hastaSahibiMi(supabase, user.id, patientId) → 404 for a foreign patient; every bc_* / hasta_beyin_cerrahisi read/write .eq(patient_id).eq(doctor_id), and row-id updates (gorev, kontrol) carry id + doctor_id + patient_id in the same query'),
  'app/api/doktor/radyoloji/_kohort.ts': I('patient ids drawn only from hasta_radyoloji / radyo_kuyruk / radyo_rapor / radyo_kritik / radyo_acil / radyo_gorevleri rows with doctor_id = doctorId; patients read by doctor_id; radyoHatirlatmaGonder runs only on ids that passed that filter'),
  'app/api/doktor/radyoloji/kohort/route.ts': I('POST ids filtered through radyoKohortVerisi(doctorId) before any message is written'),
  'app/api/doktor/radyoloji/route.ts': I('GET and POST both open with hastaSahibiMi(supabase, user.id, patientId) → 404 for a foreign patient; every radyo_* / hasta_radyoloji read/write .eq(patient_id).eq(doctor_id), and row-id updates (gorev, kontrol) carry id + doctor_id + patient_id in the same query'),
  'app/api/doktor/acil-tip/_kohort.ts': I('patient ids drawn only from hasta_acil_tip / at_esi / at_kritik_yol / at_sevk / at_risk / at_gorevleri rows with doctor_id = doctorId; patients read by doctor_id; atHatirlatmaGonder runs only on ids that passed that filter'),
  'app/api/doktor/acil-tip/kohort/route.ts': I('POST ids filtered through atKohortVerisi(doctorId) before any message is written'),
  'app/api/doktor/acil-tip/route.ts': I('GET and POST both open with hastaSahibiMi(supabase, user.id, patientId) → 404 for a foreign patient; every at_* / hasta_acil_tip read/write .eq(patient_id).eq(doctor_id), and row-id updates (gorev, kontrol) carry id + doctor_id + patient_id in the same query'),
  'app/api/doktor/kalp-damar-cerrahisi/_kohort.ts': I('patient ids drawn only from hasta_kalp_damar_cerrahisi / kdc_* rows with doctor_id = doctorId; patients read by doctor_id; hatirlatma only on filtered ids'),
  'app/api/doktor/kalp-damar-cerrahisi/kohort/route.ts': I('POST ids filtered through kdcKohortVerisi(doctorId) before any message is written'),
  'app/api/doktor/kalp-damar-cerrahisi/route.ts': I('GET and POST both open with hastaSahibiMi(supabase, user.id, patientId) → 404 for a foreign patient; every kdc_* / hasta_kalp_damar_cerrahisi read/write .eq(patient_id).eq(doctor_id)'),
  'app/api/doktor/anestezi/_kohort.ts': I('patient ids drawn only from hasta_anestezi / anestezi_asa / anestezi_hava_yolu / anestezi_agri / anestezi_acil / anestezi_gorevleri rows with doctor_id = doctorId; patients read by doctor_id; anesteziHatirlatmaGonder runs only on ids that passed that filter'),
  'app/api/doktor/anestezi/kohort/route.ts': I('POST ids filtered through anesteziKohortVerisi(doctorId) before any message is written'),
  'app/api/doktor/anestezi/route.ts': I('GET and POST both open with hastaSahibiMi(supabase, user.id, patientId) → 404 for a foreign patient; every anestezi_* / hasta_anestezi read/write .eq(patient_id).eq(doctor_id), and row-id updates (gorev, kontrol) carry id + doctor_id + patient_id in the same query'),
  'app/api/doktor/cocuk-cerrahisi/_kohort.ts': I('patient ids drawn only from hasta_cocuk_cerrahisi / cc_prepost / cc_yara_dren / cc_onam / cc_acil / cc_gorevleri rows with doctor_id = doctorId; patients read by doctor_id; ccHatirlatmaGonder runs only on ids that passed that filter'),
  'app/api/doktor/cocuk-cerrahisi/kohort/route.ts': I('POST ids filtered through ccKohortVerisi(doctorId) before any message is written'),
  'app/api/doktor/cocuk-cerrahisi/route.ts': I('GET and POST both open with hastaSahibiMi(supabase, user.id, patientId) → 404 for a foreign patient; every cc_* / hasta_cocuk_cerrahisi read/write .eq(patient_id).eq(doctor_id), and row-id updates (gorev, kontrol) carry id + doctor_id + patient_id in the same query'),
  'app/api/doktor/onkoloji/_kohort.ts': I('patient ids drawn only from hasta_onkoloji / onko_kur / onko_acil / onko_gorevleri rows with doctor_id = doctorId; patients read by doctor_id; onkoHatirlatmaGonder runs only on ids that passed that filter'),
  'app/api/doktor/onkoloji/kohort/route.ts': I('POST ids filtered through onkoKohortVerisi(doctorId) before any message is written'),
  'app/api/doktor/onkoloji/route.ts': I('GET and POST both open with hastaSahibiMi(supabase, user.id, patientId) → 404 for a foreign patient; every onko_* / hasta_onkoloji read/write .eq(patient_id).eq(doctor_id), and row-id updates (gorev, kontrol) carry id + doctor_id + patient_id in the same query'),
  'app/api/doktor/genel-cerrahi/route.ts': I('GET and POST both open with hastaSahibiMi(supabase, user.id, patientId) → 404 for a foreign patient; every gc_* / hasta_genel_cerrahi read/write .eq(patient_id).eq(doctor_id), and row-id updates (gorev, kontrol) carry id + doctor_id + patient_id in the same query'),
  'app/api/doktor/genel-cerrahi/_kohort.ts': I('patient ids drawn only from hasta_genel_cerrahi / gc_preop / gc_yara_dren / gc_patoloji / gc_acil / gc_gorevleri rows with doctor_id = doctorId; patients read by doctor_id; gcHatirlatmaGonder runs only on ids that passed that filter'),
  'app/api/doktor/genel-cerrahi/kohort/route.ts': I('POST ids filtered through gcKohortVerisi(doctorId) before any message is written'),
  'app/api/doktor/plastik-cerrahi/_kohort.ts': I('patient ids drawn only from hasta_plastik / plastik_yara / plastik_foto / plastik_acil / plastik_gorevleri rows with doctor_id = doctorId; patients read by doctor_id; plastikHatirlatmaGonder runs only on ids that passed that filter'),
  'app/api/doktor/plastik-cerrahi/kohort/route.ts': I('POST ids filtered through plastikKohortVerisi(doctorId) before any message is written'),
  'app/api/doktor/plastik-cerrahi/route.ts': I('GET and POST both open with hastaSahibiMi(supabase, user.id, patientId) → 404 for a foreign patient; every plastik_* / hasta_plastik read/write .eq(patient_id).eq(doctor_id), and row-id updates (gorev, kontrol) carry id + doctor_id + patient_id in the same query'),
  'app/api/doktor/uroloji/_kohort.ts': I('patient ids drawn only from hasta_uro / uro_ipss / uro_psa / uro_risk / uro_gorevleri rows with doctor_id = doctorId; patients read by doctor_id; uroHatirlatmaGonder runs only on ids that passed that filter'),
  'app/api/doktor/uroloji/kohort/route.ts': I('POST ids filtered through uroKohortVerisi(doctorId) before any message is written'),
  'app/api/doktor/uroloji/route.ts': I('GET and POST both open with hastaSahibiMi(supabase, user.id, patientId) → 404 for a foreign patient; every uro_* read/write .eq(patient_id).eq(doctor_id), and row-id updates (gorev, kontrol) carry id + doctor_id + patient_id in the same query'),
  'app/api/doktor/spor-hekimligi/_kohort.ts': I('patient ids drawn only from hasta_spor / spor_rtp / spor_sakatlik / spor_risk / spor_gorevleri rows with doctor_id = doctorId; patients read by doctor_id; sporHatirlatmaGonder runs only on ids that passed that filter'),
  'app/api/doktor/spor-hekimligi/kohort/route.ts': I('POST ids filtered through sporKohortVerisi(doctorId) before any message is written'),
  'app/api/doktor/spor-hekimligi/route.ts': I('GET and POST both open with hastaSahibiMi(supabase, user.id, patientId) → 404 for a foreign patient; every spor_* read/write .eq(patient_id).eq(doctor_id), and row-id updates (gorev, kontrol) carry id + doctor_id + patient_id in the same query'),
  'app/api/doktor/ortopedi/_kohort.ts': I('patient ids drawn only from hasta_ortopedi / orto_kirik_alci / orto_vas / orto_risk / orto_gorevleri rows with doctor_id = doctorId; patients read by doctor_id; ortoHatirlatmaGonder runs only on ids that passed that filter'),
  'app/api/doktor/ortopedi/kohort/route.ts': I('POST ids filtered through ortoKohortVerisi(doctorId) before any message is written'),
  'app/api/doktor/ortopedi/route.ts': I('GET and POST both open with hastaSahibiMi(supabase, user.id, patientId) → 404 for a foreign patient; every orto_* / hasta_ortopedi read/write .eq(patient_id).eq(doctor_id), and row-id updates (gorev, kontrol) carry id + doctor_id + patient_id in the same query'),
  'app/api/doktor/aile-hekimligi/_kohort.ts': I('patient ids drawn only from hasta_aile / aile_asi_tarama / aile_kronik / aile_risk / aile_gorevleri rows with doctor_id = doctorId; patients read by doctor_id; aileHatirlatmaGonder runs only on ids that passed that filter'),
  'app/api/doktor/aile-hekimligi/kohort/route.ts': I('POST ids filtered through aileKohortVerisi(doctorId) before any message is written'),
  'app/api/doktor/aile-hekimligi/route.ts': I('GET and POST both open with hastaSahibiMi(supabase, user.id, patientId) → 404 for a foreign patient; every aile_* / hasta_aile read/write .eq(patient_id).eq(doctor_id), and row-id updates (gorev, kontrol) carry id + doctor_id + patient_id in the same query'),
  'app/api/doktor/fizik-tedavi/_kohort.ts': I('patient ids drawn only from hasta_fizik_tedavi / ftr_olcek / ftr_seans / ftr_egzersiz / ftr_risk / ftr_gorevleri rows with doctor_id = doctorId; patients read by doctor_id; ftrHatirlatmaGonder runs only on ids that passed that filter'),
  'app/api/doktor/fizik-tedavi/kohort/route.ts': I('POST ids filtered through ftrKohortVerisi(doctorId) before any message is written'),
  'app/api/doktor/fizik-tedavi/route.ts': I('GET and POST both open with hastaSahibiMi(supabase, user.id, patientId) → 404 for a foreign patient; every ftr_* / hasta_fizik_tedavi read/write .eq(patient_id).eq(doctor_id), and row-id updates (gorev, kontrol) carry id + doctor_id + patient_id in the same query'),
  // ── Araçlar ──
  'app/api/doktor/araclar/epikriz/route.ts': T,
  'app/api/doktor/araclar/erecete/route.ts': I('patient ownership check (id AND doctor_id) before any read → 404'),
  'app/api/doktor/araclar/sgk-rapor/route.ts': I('patient ownership check (id AND doctor_id) before any read → 404'),
  'app/api/doktor/araclar/hasta-portali/route.ts': I('patient ownership check before token mint; share preview scoped by doctor_id'),
  'app/api/doktor/araclar/nota-ekle/route.ts': T,
  'app/api/doktor/araclar/sablonlarim/route.ts': I('doctor-only quick templates — no patient id, no patient table; every read/write .eq(doctor_id, user.id), id-keyed update/delete carry the same filter (404 otherwise)'),
  'app/api/doktor/araclar/icd10/route.ts': I('reference lookup; no patient data'),
  'app/api/doktor/araclar/ilac-interaksiyon/route.ts': I('drug names from the body only; no patient table'),
  // ── Doktor hesabı (hasta verisi yok) ──
  'app/api/doktor/erecete-ayar/route.ts': I('users row of doktorId only'),
  'app/api/doktor/recete-baslik/route.ts': I('users row of doktorId only'),
  'app/api/doktor/hafiza/route.ts': I('doktor_hafiza scoped by doctor_id; no patient data'),
  'app/api/doktor/hesap/sifre-degistir/route.ts': I('own auth account only'),
  'app/api/doktor/id-card/parse/route.ts': I('OCR of an uploaded image; stores nothing'),
  'app/api/doktor/ilac-ara/route.ts': I('drug catalogue search; no patient data'),
  'app/api/doktor/integrations/route.ts': I('doctor_integrations of user.id only'),
  'app/api/doktor/integrations/[provider]/route.ts': I('doctor_integrations of user.id only'),
  'app/api/doktor/mernis-lookup/route.ts': I('identity lookup proxy; stores nothing'),
  'app/api/doktor/personel/route.ts': I('personel scoped by doktor_id'),
  'app/api/doktor/personel/[id]/route.ts': I('personel by id AND doktor_id'),
  'app/api/doktor/profil/avatar/route.ts': I('doctor_avatars of user.id only'),
  'app/api/doktor/sgk/route.ts': I('MEDULA provision stub; reads no patient table'),
  // ── Asistan ──
  'app/api/asistan/chat/route.ts': T,
  'app/api/asistan/learn/route.ts': T,
  'app/api/asistan/hasta-bul/route.ts': I('hastaninSozunuCoz(doktorId) searches only the doctor\'s patients; file via hastaDosyaPaketiniDerle(doktorId)'),
  'app/api/asistan/ses-eylem/route.ts': I('hastaninSozunuCoz / hastaSahibiMi; eylem_onerileri doctor_id; takvim randevular.eq(doktor_id) + patients.eq(doctor_id)'),
  'app/api/asistan/signed-url/route.ts': I('voice-agent URL for the caller; no patient read'),
  'app/api/asistan/klinik-signed-url/route.ts': I('voice-agent URL for the caller; no patient read'),
  'app/api/asistan/ses-ogren/route.ts': I('NOTYA-OGRENME-03: canli sesli Ayse ogrenme kancasi — body yalniz serbest metin (doktor konusma turleri), patient_id/hasta tablosu yok; yazar doktor_hafiza/doktor_iliski, ikisi de doctor_id scoped'),
  'app/api/asistan/avukat-chat/route.ts': I('lawyer product; no patient data'),
  'app/api/asistan/avukat-learn/route.ts': I('lawyer product; no patient data'),
  'app/api/asistan/avukat-signed-url/route.ts': I('lawyer product; no patient data'),
  'app/api/asistan/mali-chat/route.ts': I('accountant product; no patient data'),
  'app/api/asistan/mali-signed-url/route.ts': I('accountant product; no patient data'),
  // ── Sağlığım portalı / intake (token = kimlik) ──
  'app/api/portal/hasta/[token]/route.ts': T,
  'app/api/portal/hasta/[token]/goruntu/route.ts': I('token → patient_id+doctor_id; vault upload as doctor; jacket kaynak=hasta_yukleme taslak'),
  'app/api/portal/hasta/[token]/goruntu/[id]/route.ts': I('token unlock; jacket id+patient_id+doctor_id; portaldaGorunurMu else 404; vault download doctor-scoped'),
  'app/api/portal/hasta/[token]/mesajlar/route.ts': T,
  'app/api/portal/hasta/[token]/asi-karnesi/pdf/route.ts': T,
  'app/api/portal/hasta/[token]/dahiliye-anket/route.ts': I('token → (patient_id, doctor_id); every read/write scoped by both'),
  'app/api/portal/hasta/[token]/unlock/route.ts': I('PIN check for the token row only'),
  'app/api/intake/[token]/route.ts': I('token → form row; patient from that row (form was created after an ownership check)'),
  // ── Entegrasyon / cron (oturumsuz, sunucu içi) ──
  'app/api/entegrasyon/fhir/isle/route.ts': I('cron-secret gated; exports notes only of doctors enrolled in that institution'),
  'app/api/entegrasyon/hl7/al/route.ts': I('per-institution inbound key; patient mapping scoped by kurum_id'),
  'app/api/entegrasyon/yonetim/route.ts': I('ADMIN_EMAILS only'),
  'app/api/cron/randevu-hatirlatma/route.ts': I('cron-secret gated; reminder only to the patient of the booking owner (doctor_id = row doktor_id)'),
  'app/api/cron/kvkk-imha/route.ts': I('cron-secret gated retention job; no cross-doctor read path'),
}
