/**
 * HASTA-IZOLASYON-01 — every API file that can reach patient data, and how its doctor-scoping is
 * guaranteed. lib/security/hasta-izolasyon-envanter.test.ts fails when:
 *   • a file under a patient-data tree (or any app/api file that starts using patient identifiers)
 *     is missing here — a new route cannot merge unclassified;
 *   • an entry marked 'test' is not actually exercised by lib/security/hasta-izolasyon.test.ts;
 *   • an entry points at a file that no longer exists.
 *
 * 'test'      → covered by the cross-doctor regression suite (A↔B, both directions, positive control).
 * 'incelendi' → reviewed by hand; `kapsam` states the exact mechanism. Prefer promoting to 'test'.
 * Audit: docs/OPEN-COMMITMENTS.md § HASTA-IZOLASYON. Rule: .cursor/skills/hasta-izolasyon/SKILL.md.
 */
export type Siniflama = { durum: 'test' } | { durum: 'incelendi'; kapsam: string }

const T = { durum: 'test' } as const
const I = (kapsam: string): Siniflama => ({ durum: 'incelendi', kapsam })

export const HASTA_IZOLASYON_ENVANTERI: Record<string, Siniflama> = {
  // ── Hasta kaydı ──
  'app/api/doktor/hastalar/route.ts': T,
  'app/api/doktor/hastalar/[id]/route.ts': T,
  'app/api/doktor/hastalar/[id]/sessions/route.ts': T,
  'app/api/doktor/hastalar/[id]/sessions/[sessionId]/arsivle/route.ts': I('session looked up AND updated with doctor_id = user.id AND patient_id = params.id together — 404 for a foreign session or a session belonging to a different patient'),
  'app/api/doktor/hastalar/[id]/sessions/[sessionId]/arsivden-cikar/route.ts': I('NOTYA-ARSIV-01 reverse of arsivle: same ownership check (session looked up with doctor_id = user.id AND patient_id = params.id together, 404 otherwise); update scoped by id + doctor_id'),
  'app/api/doktor/hastalar/[id]/sessions/[sessionId]/kalici-sil/route.ts': I('same session ownership check as arsivle (doctor_id + patient_id together, 404 otherwise), plus requires archived_at already set; every child-table delete is additionally scoped by ids derived from that owned session/note, never from raw request input'),
  'app/api/doktor/hastalar/[id]/buyume-egrileri/route.ts': T,
  'app/api/doktor/hastalar/[id]/hedef-boy/route.ts': T,
  'app/api/doktor/hastalar/[id]/klinik-ozet/route.ts': I('hastaKlinikOzetleriGuncelle: reads/writes scoped doctor_id+patient_id; foreign patient → fail'),
  // ── Notlar / seanslar ──
  'app/api/notes/route.ts': T,
  'app/api/notes/[id]/route.ts': T,
  'app/api/notes/[id]/approve/route.ts': T,
  'app/api/notes/[id]/ilac-sonlandir-geri-al/route.ts': T,
  'app/api/notes/pdf/route.ts': I('renders only the body it is given (mali note); reads no patient table'),
  'app/api/doktor/son-notlar/route.ts': T,
  'app/api/sessions/start/route.ts': T,
  'app/api/sessions/[id]/end/route.ts': T,
  'app/api/sessions/ses-yukle/route.ts': T,
  'app/api/doktor/not-konsult/route.ts': I('note loaded by id AND doctor_id = doktorId; 404 otherwise'),
  'app/api/doktor/konsult/route.ts': I('hastaDosyasiniDerle(doktorId, patientId) returns null for a foreign patient → 404; the visit-measurement evidence and the İlk-10 file-question evidence (both dosyaSorguVerisiDerle; the evidence block carries no patient name) run after that check and scopes the patient row and every child read by doktorId — lib/asistan/vizitOlcumSahne.test.ts asserts the 404'),
  'app/api/doktor/medula/recete/route.ts': I('note by id AND doctor_id; patient read scoped by doctor_id'),
  'app/api/doktor/rrs/route.ts': I('note by id AND doctor_id, patient ownership re-checked; list/patch scoped by doctor_id'),
  'app/api/doktor/raporlar/route.ts': I('aggregates only rows with doctor_id = user.id; no patient name, phone or id in the response'),
  'app/api/doktor/raporlar/pdf/route.tsx': I('same doctor-scoped aggregate as raporlar/route.ts, rendered to PDF; users.full_name read with id = user.id; no patient identity'),
  // ── İlaç / aşı / lab / belge / görüntü / cihaz ──
  'app/api/doktor/ilaclar/route.ts': T,
  'app/api/doktor/ilaclar/[id]/route.ts': T,
  'app/api/doktor/ilaclar/doz-oner/route.ts': I('patient row fetched and doctor_id compared to user.id before any read → 404'),
  'app/api/doktor/asilar/route.ts': T,
  'app/api/doktor/asilar/[id]/route.ts': I('update/delete by id AND doktor_id = doktorId'),
  'app/api/doktor/asilar/karne/route.ts': T,
  'app/api/doktor/asilar/karne/pdf/route.ts': T,
  'app/api/doktor/asilar/hatirlatma/route.ts': T,
  'app/api/doktor/belgeler/lab/route.ts': T,
  'app/api/doktor/belgeler/analiz/route.ts': I('document via vault getDocumentMeta(doctorId) (assertPatientOwned); analyses by doctor_id'),
  'app/api/doktor/belgeler/analiz/onayla/route.ts': I('analysis by id AND doctor_id; target note by id AND doctor_id'),
  'app/api/doktor/belgeler/ingest/route.ts': T,
  // KONSULTASYON-01 — kapalı döngü konsültasyon (sevkler + Kasa belgesi + bugünkü not + Sağlığım hatırlatması)
  'app/api/doktor/konsultasyon/route.ts': T,
  // NOTYA-EYLEM — Ayşe hazırlar, hekim onaylar (core/eylemler/*)
  'app/api/doktor/eylem/route.ts': T,
  'app/api/doktor/documents/route.ts': I('vault listDocuments/uploadDocument — doctor-scoped, assertPatientOwned (lib/vault/service.acl.test.ts)'),
  'app/api/doktor/documents/[id]/route.ts': I('vault getDocumentMeta/softDeleteDocument by doctor_id (lib/vault/service.acl.test.ts)'),
  'app/api/doktor/documents/[id]/download/route.ts': I('vault downloadDocument by doctor_id (lib/vault/service.acl.test.ts)'),
  'app/api/doktor/goruntuleme/route.ts': T,
  'app/api/doktor/goruntuleme/[id]/route.ts': I('row fetched, doctor_id !== user.id → 403 before storage/DB delete'),
  'app/api/doktor/goruntuleme/yukle/route.ts': T,
  'app/api/doktor/goruntuler/route.ts': I('GET/POST: hastaSahibiMi then goruntu_calisma.eq(doctor_id); vault uploadDocument assertPatientOwned'),
  'app/api/doktor/goruntuler/[id]/route.ts': I('GET/PATCH row by id AND doctor_id; priors/seri scoped doctor_id+patient_id'),
  // ── Randevu / takvim / mesaj / hatırlatma / intake ──
  'app/api/doktor/randevular/route.ts': T,
  'app/api/doktor/randevular/[id]/route.ts': T,
  'app/api/doktor/gun-programi/route.ts': T,
  'app/api/doktor/calisma-saatleri/route.ts': I('doctor working hours only (doktor_id); no patient data'),
  'app/api/doktor/randevu-portal/talepler/route.ts': T,
  'app/api/doktor/randevu-portal/ayar/route.ts': T,
  'app/api/doktor/google-takvim/route.ts': I('NOTYA-RANDEVU-V2 PR2: doktorOturum; connection row by doktor_id = user.id (token column never returned); re-title pushes resolve each randevu with id + doktor_id'),
  'app/api/doktor/google-takvim/baslat/route.ts': I('doktorOturum; returns Google consent URL with a signed state bound to user.id — reads no patient data'),
  'app/api/doktor/google-takvim/oneriler/route.ts': I('doktorOturum; proposal and appointment each resolved with id AND doktor_id = user.id (lib/randevu/v2/google/senk.ts oneriYanitla) — foreign id 404; list .eq(doktor_id)'),
  'app/api/google-takvim/donus/route.ts': I('OAuth callback: doctor id only from the HMAC-signed state + matching nonce cookie; writes that doctor\'s own connection row'),
  'app/api/google-takvim/bildirim/route.ts': I('Google push webhook: channel id must exist AND token hash match (timing-safe); imports only that connection\'s own doktor_id; returns no data'),
  'app/api/doktor/mesajlar/route.ts': T,
  'app/api/doktor/mesajlar/[konuId]/route.ts': T,
  'app/api/doktor/mesajlar/ek/[ekId]/route.ts': I('pratikOturum doktorId; ek row .eq(doctor_id); belgeye-kaydet → uploadDocument patient ownership re-check; DELETE scoped doctor_id'),
  'app/api/doktor/mesajlar/unread-count/route.ts': I('count scoped by doctor_id'),
  // NOTYA-ILETISIM-01 — tek dokunuş iletişim (hekimin kendi WhatsApp / e-postası), Hazır mesajlar, izin, kayıt
  'app/api/doktor/iletisim/hazirla/route.ts': T,
  'app/api/doktor/iletisim/kayit/route.ts': T,
  'app/api/doktor/iletisim/izin/route.ts': T,
  'app/api/doktor/iletisim/kuyruk/route.ts': T,
  // NOTYA-GELEN-BELGELER — Gelen Belgeler kutusu (lib/gelenBelgeler): liste/ekleme/hasta arama, dosyala/sil, sekreter anahtarı
  'app/api/doktor/gelen-belgeler/route.ts': T,
  'app/api/doktor/gelen-belgeler/[id]/route.ts': T,
  'app/api/doktor/gelen-belgeler/ayar/route.ts': I('users row of doktorId only (sadeceDoktor); takes no patient id and reads no patient table'),
  'app/api/doktor/iletisim/ayarlar/route.ts': I('users row of doktorId only (sadeceDoktor); takes no patient id and reads no patient table'),
  'app/api/doktor/intake-formlari/route.ts': T,
  'app/api/doktor/intake-formlari/[id]/route.ts': I('form by id AND doktor_id'),
  // ── Branş modülleri ──
  'app/api/doktor/mchat/route.ts': T,
  'app/api/doktor/gelisim-taramasi/route.ts': T,
  'app/api/doktor/kadin-sagligi/route.ts': T,
  // DERM-EXCEPTIONAL-01: 'goruntu-okuma' (belge_taslak / asistana_raporla) da bu dosyada — analiz ve görüntü
  // kimlikleri hastaSahibiMi() sonrası patient_id + doctor_id ile yeniden daraltılır; okuma epizoda yazılır.
  'app/api/doktor/dermatoloji/route.ts': T,
  'app/api/doktor/dermatoloji/spine/route.ts': T,
  'app/api/doktor/dermatoloji/_kohort.ts': I('patient ids drawn only from hasta_derm / derm_gorevleri / derm_ilac_guvenlik rows with doctor_id = doctorId; child tables (yama, fototerapi, lezyon) read by hasta_derm_id taken from those doctor-scoped episodes; patients read by doctor_id (read-only — dermHatirlatmaGonder lives in _kohortHatirlatma.ts, NOTYA-EYLEM-24)'),
  'app/api/doktor/dermatoloji/_kohortHatirlatma.ts': I('dermHatirlatmaGonder — split out of _kohort.ts (NOTYA-EYLEM-24, keeps the write path out of the chat/voice import graph); runs only on ids that passed dermKohortVerisi(doctorId) in kohort/route.ts'),
  'app/api/doktor/dermatoloji/kohort/route.ts': I('POST ids filtered through dermKohortVerisi(doctorId) before any message is written'),
  'app/api/doktor/gebelik/route.ts': T,
  'app/api/doktor/gebelik/dogum/route.ts': T,
  'app/api/doktor/gebelik/kohort/route.ts': T,
  'app/api/doktor/gebelik/_kohort.ts': I('patient ids drawn only from gebelikler / kadin_sagligi rows with doctor_id = doctorId; every secondary read (patients, izlem, genetik, lohusa, sessions, portal) doctor_id-scoped (read-only — kdHatirlatmaGonder lives in _kohortHatirlatma.ts, NOTYA-EYLEM-24)'),
  'app/api/doktor/gebelik/_kohortHatirlatma.ts': I('kdHatirlatmaGonder — split out of _kohort.ts (NOTYA-EYLEM-24); runs only on ids that passed kdKohortVerisi(doctorId) in kohort/route.ts'),
  'app/api/doktor/yenidogan/route.ts': I('baby card fetched by patient AND doctor_id; every derived id comes from that card; patient reads doctor-scoped; canli-dogum-onar goes through olusturCanliDogum which requires gebelik.patient_id = body anne AND patients.doctor_id before any name decrypt or write'),
  'app/api/doktor/jinekoloji/route.ts': T,
  'app/api/doktor/goz/route.ts': T,
  'app/api/doktor/goz/kohort/route.ts': T,
  'app/api/doktor/goz/_ek.ts': I('gozEkAdim / gozEkVeri run only after route.ts hasta(doctorId, patientId); every read/write .eq(patient_id, h.id).eq(doctor_id); child ids (katarakt, acil, görüntü) re-scoped by patient_id + doctor_id'),
  'app/api/doktor/goz/_kohort.ts': I('patient ids drawn only from goz_* rows with doctor_id = doctorId; patients read by doctor_id (read-only — gozHatirlatmaGonder lives in _kohortHatirlatma.ts, NOTYA-EYLEM-24)'),
  'app/api/doktor/goz/_kohortHatirlatma.ts': I('gozHatirlatmaGonder — split out of _kohort.ts (NOTYA-EYLEM-24); runs only on ids that passed gozKohortVerisi(doctorId) or hasta(), called from kohort/route.ts and _ek.ts'),
  'app/api/doktor/pediatri/route.ts': T,
  'app/api/doktor/pediatri/_ortak.ts': I('pediHasta: patients by id AND doctor_id — the gate every pediatri handler passes first; pediOturum = doktorOturum + users.specialty pediatri'),
  'app/api/doktor/pediatri/tarama/route.ts': T,
  'app/api/doktor/pediatri/kohort/route.ts': T,
  'app/api/doktor/fisilti/route.ts': I('via lib/doktor/fisiltiTopla: proxies exactly one branş kohort route (+ mesajlar?unread=1) via an internal same-origin fetch, forwarding the SAME caller bearer token unchanged -- that downstream route re-runs doktorOturum + its own doctor_id scoping independently (see its own entry above/below); its own Supabase reads (users by id = user.id, fisilti_sessizler and fisilti_gizlenen) are all .eq(doctor_id, user.id); takes no patient id from request input and identifies the target branş only from users.specialty of the AUTHENTICATED doctor'),
  'app/api/doktor/fisilti/gizle/route.ts': I('NOTYA-FISILTI-GIZLE-01: POST hides only an item found in the doctor\'s OWN freshly-built fisiltiOgeleri list (patient_id + facts hash taken from that item, never from the body) and inserts with doctor_id = user.id; GET lists only those items filtered by fisilti_gizlenen .eq(doctor_id, user.id); PATCH restores by id AND doctor_id = user.id (404 for a foreign row)'),
  'app/api/doktor/fisilti/kalkan/route.ts': T,
  'app/api/doktor/seans-paketi/route.ts': T,
  'app/api/doktor/seans-paketi/bugun/route.ts': T,
  'app/api/doktor/pediatri/_kohort.ts': I('kohort: patients .eq(doctor_id) → ids; every source query .eq(doctor_id|doktor_id).in(patient_id, ids) (read-only — pediHatirlatmaGonder lives in _kohortHatirlatma.ts, NOTYA-EYLEM-24)'),
  'app/api/doktor/pediatri/_kohortHatirlatma.ts': I('pediHatirlatmaGonder — split out of _kohort.ts (NOTYA-EYLEM-24); runs only on ids that passed pediKohortVerisi(doktorId) in kohort/route.ts'),
  'app/api/doktor/dahiliye/route.ts': T,
  'app/api/doktor/dahiliye/_ortak.ts': I('hastaBilgi/hastaAdi: patients by id AND doctor_id — the gate every dahiliye handler passes first'),
  'app/api/doktor/dahiliye/_wow2.ts': I('runs only after hastaBilgi(); id-keyed updates scoped by doctor_id or the verified patient'),
  'app/api/doktor/dahiliye/_wow3.ts': I('runs only after hastaBilgi(); id-keyed updates scoped by doctor_id or the verified patient'),
  'app/api/doktor/dahiliye/_wow4.ts': I('runs only after hastaBilgi(); id-keyed updates scoped by doctor_id or the verified patient'),
  'app/api/doktor/dahiliye/_wow5.ts': I('runs only after hastaBilgi(); id-keyed updates scoped by doctor_id or the verified patient'),
  'app/api/doktor/dahiliye/_kohort.ts': I('patient ids drawn only from rows with doctor_id = doctorId; patients read by doctor_id'),
  'app/api/doktor/dahiliye/kohort/route.ts': I('POST ids filtered through kohortVerisi(doctorId) before any message is written'),
  'app/api/doktor/psikiyatri/_kohort.ts': I('patient ids drawn only from hasta_psik / psik_olcek / psik_risk / psik_gorevleri rows with doctor_id = doctorId; patients read by doctor_id; psikHatirlatmaGonder runs only on ids that passed that filter'),
  'app/api/doktor/psikiyatri/kohort/route.ts': I('POST ids filtered through psikKohortVerisi(doctorId) before any message is written'),
  'app/api/doktor/psikiyatri/route.ts': I('GET and POST both open with hastaSahibiMi(supabase, user.id, patientId) → 404 for a foreign patient; every psik_* read/write .eq(patient_id).eq(doctor_id), and row-id updates (gorev, kontrol) carry id + doctor_id + patient_id in the same query'),
  'app/api/doktor/kulak-burun-bogaz/_kohort.ts': I('patient ids drawn only from hasta_kbb / kbb_odyometri / kbb_risk / kbb_gorevleri rows with doctor_id = doctorId; patients read by doctor_id; kbbHatirlatmaGonder runs only on ids that passed that filter'),
  'app/api/doktor/kulak-burun-bogaz/kohort/route.ts': I('POST ids filtered through kbbKohortVerisi(doctorId) before any message is written'),
  'app/api/doktor/kulak-burun-bogaz/route.ts': I('GET and POST both open with hastaSahibiMi(supabase, user.id, patientId) → 404 for a foreign patient; every kbb_* read/write .eq(patient_id).eq(doctor_id), and row-id updates (gorev, kontrol, osas) carry id + doctor_id + patient_id in the same query'),
  'app/api/doktor/kardiyoloji/_kohort.ts': I('patient ids drawn only from hasta_kardiyoloji / kardio_score2 / kardio_izlem / kardio_risk / kardio_gorevleri rows with doctor_id = doctorId; patients read by doctor_id; kardioHatirlatmaGonder runs only on ids that passed that filter'),
  'app/api/doktor/kardiyoloji/kohort/route.ts': I('POST ids filtered through kardioKohortVerisi(doctorId) before any message is written'),
  'app/api/doktor/kardiyoloji/route.ts': I('GET and POST both open with hastaSahibiMi(supabase, user.id, patientId) → 404 for a foreign patient; every kardio_* / hasta_kardiyoloji read/write .eq(patient_id).eq(doctor_id), and row-id updates (gorev, kontrol) carry id + doctor_id + patient_id in the same query'),
  'app/api/doktor/gogus-hastaliklari/_kohort.ts': I('patient ids drawn only from hasta_gogus / gogus_skor / gogus_risk / gogus_gorevleri rows with doctor_id = doctorId; patients read by doctor_id; gogusHatirlatmaGonder runs only on ids that passed that filter'),
  'app/api/doktor/gogus-hastaliklari/kohort/route.ts': I('GET/POST use gogusKohortVerisi(doctorId); POST recall only for ids returned by that filter'),
  'app/api/doktor/gogus-hastaliklari/route.ts': I('GET and POST both open with hastaSahibiMi(supabase, user.id, patientId) → 404 for a foreign patient; every gogus_* read/write .eq(patient_id).eq(doctor_id)'),
  'app/api/doktor/noroloji/_kohort.ts': I('patient ids drawn only from hasta_noroloji / noro_migren / noro_risk / noro_gorevleri rows with doctor_id = doctorId; patients read by doctor_id; noroHatirlatmaGonder runs only on ids that passed that filter'),
  'app/api/doktor/noroloji/kohort/route.ts': I('POST ids filtered through noroKohortVerisi(doctorId) before any message is written'),
  'app/api/doktor/noroloji/route.ts': I('GET and POST both open with hastaSahibiMi(supabase, user.id, patientId) → 404 for a foreign patient; every noro_* / hasta_noroloji read/write .eq(patient_id).eq(doctor_id), and row-id updates (gorev, kontrol) carry id + doctor_id + patient_id in the same query'),
  'app/api/doktor/endokrinoloji/_kohort.ts': I('patient ids drawn only from hasta_endokrinoloji / endo_lab / endo_acil / endo_gorevleri rows with doctor_id = doctorId; patients read by doctor_id; endoHatirlatmaGonder runs only on ids that passed that filter'),
  'app/api/doktor/endokrinoloji/kohort/route.ts': I('POST ids filtered through endoKohortVerisi(doctorId) before any message is written'),
    'app/api/doktor/romatoloji/_kohort.ts': I('patient ids drawn only from hasta_romatoloji / roma_skor / roma_lab / roma_acil / roma_gorevleri / roma_eklem rows with doctor_id = doctorId; patients read by doctor_id; romaHatirlatmaGonder runs only on ids that passed that filter'),
  'app/api/doktor/romatoloji/kohort/route.ts': I('POST ids filtered through romaKohortVerisi(doctorId) before any message is written'),
  'app/api/doktor/romatoloji/route.ts': I('GET and POST both open with hastaSahibiMi(supabase, user.id, patientId) → 404 for a foreign patient; every roma_* / hasta_romatoloji read/write .eq(patient_id).eq(doctor_id), and row-id updates (gorev, kontrol) carry id + doctor_id + patient_id in the same query'),
'app/api/doktor/endokrinoloji/route.ts': I('GET and POST both open with hastaSahibiMi(supabase, user.id, patientId) → 404 for a foreign patient; every endo_* / hasta_endokrinoloji read/write .eq(patient_id).eq(doctor_id), and row-id updates (gorev, kontrol) carry id + doctor_id + patient_id in the same query'),
  'app/api/doktor/enfeksiyon-hastaliklari/_kohort.ts': I('patient ids drawn only from hasta_enfeksiyon / enfeksiyon_izolasyon / enfeksiyon_atb / enfeksiyon_viral / enfeksiyon_acil / enfeksiyon_gorevleri rows with doctor_id = doctorId; patients read by doctor_id; enfHatirlatmaGonder runs only on ids that passed that filter'),
  'app/api/doktor/enfeksiyon-hastaliklari/kohort/route.ts': I('POST ids filtered through enfKohortVerisi(doctorId) before any message is written'),
  'app/api/doktor/enfeksiyon-hastaliklari/route.ts': I('GET and POST both open with hastaSahibiMi(supabase, user.id, patientId) → 404 for a foreign patient; every enfeksiyon_* / hasta_enfeksiyon read/write .eq(patient_id).eq(doctor_id), and row-id updates (gorev, kontrol) carry id + doctor_id + patient_id in the same query'),
  'app/api/doktor/nefroloji/_kohort.ts': I('patient ids drawn only from hasta_nefroloji / nef_egfr / nef_anemi / nef_diyaliz / nef_acil / nef_gorevleri rows with doctor_id = doctorId; patients read by doctor_id; nefHatirlatmaGonder runs only on ids that passed that filter'),
  'app/api/doktor/nefroloji/kohort/route.ts': I('POST ids filtered through nefKohortVerisi(doctorId) before any message is written'),
  'app/api/doktor/nefroloji/route.ts': I('GET and POST both open with hastaSahibiMi(supabase, user.id, patientId) → 404 for a foreign patient; every nef_* / hasta_nefroloji read/write .eq(patient_id).eq(doctor_id), and row-id updates (gorev, kontrol) carry id + doctor_id + patient_id in the same query'),
  'app/api/doktor/gastroenteroloji/_kohort.ts': I('patient ids drawn only from hasta_gastro / gastro_* rows with doctor_id = doctorId; patients read by doctor_id; hatirlatma only on filtered ids'),
  'app/api/doktor/gastroenteroloji/kohort/route.ts': I('POST ids filtered through gastroKohortVerisi(doctorId) before any message is written'),
  'app/api/doktor/gastroenteroloji/route.ts': I('GET and POST both open with hastaSahibiMi(supabase, user.id, patientId) → 404 for a foreign patient; every gastro_* / hasta_gastro read/write .eq(patient_id).eq(doctor_id)'),
  'app/api/doktor/gogus-cerrahisi/_kohort.ts': I('patient ids drawn only from hasta_gogus_cerrahisi / goc_* rows with doctor_id = doctorId; patients read by doctor_id; hatirlatma only on filtered ids'),
  'app/api/doktor/gogus-cerrahisi/kohort/route.ts': I('POST ids filtered through gogusCerrahiKohortVerisi(doctorId) before any message is written'),
  'app/api/doktor/gogus-cerrahisi/route.ts': I('GET and POST both open with hastaSahibiMi(supabase, user.id, patientId) → 404 for a foreign patient; every table read/write .eq(patient_id).eq(doctor_id)'),
  'app/api/doktor/beyin-cerrahisi/_kohort.ts': I('patient ids drawn only from hasta_beyin_cerrahisi / bc_postop / bc_bilinc / bc_acil / bc_gorevleri rows with doctor_id = doctorId; patients read by doctor_id; bcHatirlatmaGonder runs only on ids that passed that filter'),
  'app/api/doktor/beyin-cerrahisi/kohort/route.ts': I('POST ids filtered through bcKohortVerisi(doctorId) before any message is written'),
  'app/api/doktor/beyin-cerrahisi/route.ts': I('GET and POST both open with hastaSahibiMi(supabase, user.id, patientId) → 404 for a foreign patient; every bc_* / hasta_beyin_cerrahisi read/write .eq(patient_id).eq(doctor_id), and row-id updates (gorev, kontrol) carry id + doctor_id + patient_id in the same query'),
  'app/api/doktor/radyoloji/_kohort.ts': I('patient ids drawn only from hasta_radyoloji / radyo_kuyruk / radyo_rapor / radyo_kritik / radyo_acil / radyo_gorevleri rows with doctor_id = doctorId; patients read by doctor_id; radyoHatirlatmaGonder runs only on ids that passed that filter'),
  'app/api/doktor/radyoloji/kohort/route.ts': I('POST ids filtered through radyoKohortVerisi(doctorId) before any message is written'),
  'app/api/doktor/radyoloji/route.ts': I('GET and POST both open with hastaSahibiMi(supabase, user.id, patientId) → 404 for a foreign patient; every radyo_* / hasta_radyoloji read/write .eq(patient_id).eq(doctor_id), and row-id updates (gorev, kontrol) carry id + doctor_id + patient_id in the same query'),
  'app/api/doktor/acil-tip/_kohort.ts': I('patient ids drawn only from hasta_acil_tip / at_esi / at_kritik_yol / at_sevk / at_risk / at_gorevleri rows with doctor_id = doctorId; patients read by doctor_id; atHatirlatmaGonder runs only on ids that passed that filter'),
  'app/api/doktor/acil-tip/kohort/route.ts': I('POST ids filtered through atKohortVerisi(doctorId) before any message is written'),
  'app/api/doktor/acil-tip/route.ts': I('GET and POST both open with hastaSahibiMi(supabase, user.id, patientId) → 404 for a foreign patient; every at_* / hasta_acil_tip read/write .eq(patient_id).eq(doctor_id), and row-id updates (gorev, kontrol) carry id + doctor_id + patient_id in the same query'),
  'app/api/doktor/kalp-damar-cerrahisi/_kohort.ts': I('patient ids drawn only from hasta_kalp_damar_cerrahisi / kdc_* rows with doctor_id = doctorId; patients read by doctor_id; hatirlatma only on filtered ids'),
  'app/api/doktor/kalp-damar-cerrahisi/kohort/route.ts': I('POST ids filtered through kdcKohortVerisi(doctorId) before any message is written'),
  'app/api/doktor/kalp-damar-cerrahisi/route.ts': I('GET and POST both open with hastaSahibiMi(supabase, user.id, patientId) → 404 for a foreign patient; every kdc_* / hasta_kalp_damar_cerrahisi read/write .eq(patient_id).eq(doctor_id)'),
  'app/api/doktor/anestezi/_kohort.ts': I('patient ids drawn only from hasta_anestezi / anestezi_asa / anestezi_hava_yolu / anestezi_agri / anestezi_acil / anestezi_gorevleri rows with doctor_id = doctorId; patients read by doctor_id; anesteziHatirlatmaGonder runs only on ids that passed that filter'),
  'app/api/doktor/anestezi/kohort/route.ts': I('POST ids filtered through anesteziKohortVerisi(doctorId) before any message is written'),
  'app/api/doktor/anestezi/route.ts': I('GET and POST both open with hastaSahibiMi(supabase, user.id, patientId) → 404 for a foreign patient; every anestezi_* / hasta_anestezi read/write .eq(patient_id).eq(doctor_id), and row-id updates (gorev, kontrol) carry id + doctor_id + patient_id in the same query'),
  'app/api/doktor/cocuk-cerrahisi/_kohort.ts': I('patient ids drawn only from hasta_cocuk_cerrahisi / cc_prepost / cc_yara_dren / cc_onam / cc_acil / cc_gorevleri rows with doctor_id = doctorId; patients read by doctor_id; ccHatirlatmaGonder runs only on ids that passed that filter'),
  'app/api/doktor/cocuk-cerrahisi/kohort/route.ts': I('POST ids filtered through ccKohortVerisi(doctorId) before any message is written'),
  'app/api/doktor/cocuk-cerrahisi/route.ts': I('GET and POST both open with hastaSahibiMi(supabase, user.id, patientId) → 404 for a foreign patient; every cc_* / hasta_cocuk_cerrahisi read/write .eq(patient_id).eq(doctor_id), and row-id updates (gorev, kontrol) carry id + doctor_id + patient_id in the same query'),
  'app/api/doktor/onkoloji/_kohort.ts': I('patient ids drawn only from hasta_onkoloji / onko_kur / onko_acil / onko_gorevleri rows with doctor_id = doctorId; patients read by doctor_id; onkoHatirlatmaGonder runs only on ids that passed that filter'),
  'app/api/doktor/onkoloji/kohort/route.ts': I('POST ids filtered through onkoKohortVerisi(doctorId) before any message is written'),
  'app/api/doktor/onkoloji/route.ts': I('GET and POST both open with hastaSahibiMi(supabase, user.id, patientId) → 404 for a foreign patient; every onko_* / hasta_onkoloji read/write .eq(patient_id).eq(doctor_id), and row-id updates (gorev, kontrol) carry id + doctor_id + patient_id in the same query'),
  'app/api/doktor/genel-cerrahi/route.ts': I('GET and POST both open with hastaSahibiMi(supabase, user.id, patientId) → 404 for a foreign patient; every gc_* / hasta_genel_cerrahi read/write .eq(patient_id).eq(doctor_id), and row-id updates (gorev, kontrol) carry id + doctor_id + patient_id in the same query'),
  'app/api/doktor/genel-cerrahi/_kohort.ts': I('patient ids drawn only from hasta_genel_cerrahi / gc_preop / gc_yara_dren / gc_patoloji / gc_acil / gc_gorevleri rows with doctor_id = doctorId; patients read by doctor_id; gcHatirlatmaGonder runs only on ids that passed that filter'),
  'app/api/doktor/genel-cerrahi/kohort/route.ts': I('POST ids filtered through gcKohortVerisi(doctorId) before any message is written'),
  'app/api/doktor/plastik-cerrahi/_kohort.ts': I('patient ids drawn only from hasta_plastik / plastik_yara / plastik_foto / plastik_acil / plastik_gorevleri rows with doctor_id = doctorId; patients read by doctor_id; plastikHatirlatmaGonder runs only on ids that passed that filter'),
  'app/api/doktor/plastik-cerrahi/kohort/route.ts': I('POST ids filtered through plastikKohortVerisi(doctorId) before any message is written'),
  'app/api/doktor/plastik-cerrahi/route.ts': I('GET and POST both open with hastaSahibiMi(supabase, user.id, patientId) → 404 for a foreign patient; every plastik_* / hasta_plastik read/write .eq(patient_id).eq(doctor_id), and row-id updates (gorev, kontrol) carry id + doctor_id + patient_id in the same query'),
  'app/api/doktor/uroloji/_kohort.ts': I('patient ids drawn only from hasta_uro / uro_ipss / uro_psa / uro_risk / uro_gorevleri rows with doctor_id = doctorId; patients read by doctor_id; uroHatirlatmaGonder runs only on ids that passed that filter'),
  'app/api/doktor/uroloji/kohort/route.ts': I('POST ids filtered through uroKohortVerisi(doctorId) before any message is written'),
  'app/api/doktor/uroloji/route.ts': I('GET and POST both open with hastaSahibiMi(supabase, user.id, patientId) → 404 for a foreign patient; every uro_* read/write .eq(patient_id).eq(doctor_id), and row-id updates (gorev, kontrol) carry id + doctor_id + patient_id in the same query'),
  'app/api/doktor/spor-hekimligi/_kohort.ts': I('patient ids drawn only from hasta_spor / spor_rtp / spor_sakatlik / spor_risk / spor_gorevleri rows with doctor_id = doctorId; patients read by doctor_id; sporHatirlatmaGonder runs only on ids that passed that filter'),
  'app/api/doktor/spor-hekimligi/kohort/route.ts': I('POST ids filtered through sporKohortVerisi(doctorId) before any message is written'),
  'app/api/doktor/spor-hekimligi/route.ts': I('GET and POST both open with hastaSahibiMi(supabase, user.id, patientId) → 404 for a foreign patient; every spor_* read/write .eq(patient_id).eq(doctor_id), and row-id updates (gorev, kontrol) carry id + doctor_id + patient_id in the same query'),
  'app/api/doktor/ortopedi/_kohort.ts': I('patient ids drawn only from hasta_ortopedi / orto_kirik_alci / orto_vas / orto_risk / orto_gorevleri rows with doctor_id = doctorId; patients read by doctor_id; ortoHatirlatmaGonder runs only on ids that passed that filter'),
  'app/api/doktor/ortopedi/kohort/route.ts': I('POST ids filtered through ortoKohortVerisi(doctorId) before any message is written'),
  'app/api/doktor/ortopedi/route.ts': I('GET and POST both open with hastaSahibiMi(supabase, user.id, patientId) → 404 for a foreign patient; every orto_* / hasta_ortopedi read/write .eq(patient_id).eq(doctor_id), and row-id updates (gorev, kontrol) carry id + doctor_id + patient_id in the same query'),
  'app/api/doktor/aile-hekimligi/_kohort.ts': I('patient ids drawn only from hasta_aile / aile_asi_tarama / aile_kronik / aile_risk / aile_gorevleri rows with doctor_id = doctorId; patients read by doctor_id; aileHatirlatmaGonder runs only on ids that passed that filter'),
  'app/api/doktor/aile-hekimligi/kohort/route.ts': I('POST ids filtered through aileKohortVerisi(doctorId) before any message is written'),
  'app/api/doktor/aile-hekimligi/route.ts': I('GET and POST both open with hastaSahibiMi(supabase, user.id, patientId) → 404 for a foreign patient; every aile_* / hasta_aile read/write .eq(patient_id).eq(doctor_id), and row-id updates (gorev, kontrol) carry id + doctor_id + patient_id in the same query'),
  'app/api/doktor/fizik-tedavi/_kohort.ts': I('patient ids drawn only from hasta_fizik_tedavi / ftr_olcek / ftr_seans / ftr_egzersiz / ftr_risk / ftr_gorevleri rows with doctor_id = doctorId; patients read by doctor_id; ftrHatirlatmaGonder runs only on ids that passed that filter'),
  'app/api/doktor/fizik-tedavi/kohort/route.ts': I('POST ids filtered through ftrKohortVerisi(doctorId) before any message is written'),
  'app/api/doktor/fizik-tedavi/route.ts': I('GET and POST both open with hastaSahibiMi(supabase, user.id, patientId) → 404 for a foreign patient; every ftr_* / hasta_fizik_tedavi read/write .eq(patient_id).eq(doctor_id), and row-id updates (gorev, kontrol) carry id + doctor_id + patient_id in the same query'),
  // ── Araçlar ──
  'app/api/doktor/araclar/epikriz/route.ts': T,
  'app/api/doktor/araclar/enabiz/route.ts': T,
  'app/api/doktor/araclar/enabiz/mbys/route.ts': T,
  'app/api/doktor/araclar/erecete/route.ts': I('patient ownership check (id AND doctor_id) before any read → 404'),
  'app/api/doktor/araclar/sgk-rapor/route.ts': I('patient ownership check (id AND doctor_id) before any read → 404'),
  'app/api/doktor/araclar/hasta-portali/route.ts': I('patient ownership check before token mint; share preview scoped by doctor_id'),
  'app/api/doktor/araclar/nota-ekle/route.ts': T,
  'app/api/doktor/araclar/sablonlarim/route.ts': I('doctor-only quick templates — no patient id, no patient table; every read/write .eq(doctor_id, user.id), id-keyed update/delete carry the same filter (404 otherwise)'),
  'app/api/doktor/araclar/icd10/route.ts': I('reference lookup; no patient data'),
  'app/api/doktor/araclar/ilac-interaksiyon/route.ts': I('drug names from the body only; no patient table'),
  // ── Doktor hesabı (hasta verisi yok) ──
  'app/api/doktor/erecete-ayar/route.ts': I('users row of doktorId only'),
  'app/api/doktor/recete-baslik/route.ts': I('GET/POST users row of doktorId only — letterhead, no patient id'),
  'app/api/doktor/hafiza/route.ts': I('doktor_hafiza scoped by doctor_id; no patient data'),
  'app/api/doktor/kullanim/route.ts': I('usage events only: sayfa_tipi/eylem; no patient id; insert scoped by pratikOturum doktorId'),
  'app/api/doktor/rutin/route.ts': I('doktor_rutin / kullanim olaylari scoped by doktorId; no patient table'),
  'app/api/doktor/onbellek-isin/route.ts': I('hastaSahibiMi before patientId; randevu list .eq(doktor_id); onbellek key doctor_id+patient_id'),
  'app/api/doktor/hesap/sifre-degistir/route.ts': I('own auth account only'),
  'app/api/doktor/id-card/parse/route.ts': I('OCR of an uploaded image; stores nothing'),
  'app/api/doktor/ilac-ara/route.ts': I('drug catalogue search; no patient data'),
  'app/api/doktor/integrations/route.ts': I('doctor_integrations of user.id only'),
  'app/api/doktor/integrations/[provider]/route.ts': I('doctor_integrations of user.id only'),
  'app/api/doktor/mernis-lookup/route.ts': I('identity lookup proxy; stores nothing'),
  'app/api/doktor/personel/route.ts': I('personel scoped by doktor_id'),
  'app/api/doktor/personel/[id]/route.ts': I('personel by id AND doktor_id'),
  'app/api/doktor/profil/avatar/route.ts': I('doctor_avatars of user.id only'),
  'app/api/doktor/sgk/route.ts': I('MEDULA provision stub; reads no patient table'),
  // ── Asistan ──
  // NOTYA-AYSE-ARAC-PARITE (2026-10-02): chat, fish-tur and ses-llm all run ayseCevapla, which now executes Ayşe's read
  // tools (hasta_bul, randevu_takvim — lib/asistan/okumaAraclari.ts) IN PROCESS. No new route. The tools take text and a
  // date from the model, never an id; every executor gets the authenticated doctor's id and scopes by it
  // (hastaninSozunuCoz / kimlikSorusunuCevapla / dosyaPaketOnbellekli by doctor_id, doktorunGununuOku and
  // doktorCalismaGunu by doktor_id); the session's open patient is re-checked with hastaSahibiMi before it is used.
  // Covered both ways (A→B, B→A, positive control) on chat and fish-tur by the "Ayşe okuma araçları" block of
  // hasta-izolasyon.test.ts and by lib/asistan/aracPariteKabul.test.ts.
  // NOTYA-AYSE-ALAN-01 (2026-10-02): a third read tool, hasta_alan(alan, hasta_adi?) — lib/asistan/hastaAlan.ts. It takes
  // a field key and a NAME, never an id: the name is resolved with hastaninSozunuCoz(doktorId), the open patient is
  // re-checked with hastaSahibiMi, the record is read with kimlikKaydiOku(doktorId). It returns a placeholder, never a
  // value; a name that is another doctor's patient gets the same sentence as a name nobody has and no placeholder.
  // The value is put into the final answer by alanlariYerineKoy(doktorId) — in ayseCevapla for the written answer and
  // in ses-ekran for the screen form of a voice turn, where the patient id comes from the session row (id + doctor_id)
  // and the record is read again with the authenticated doctor's id (a reference to a foreign patient reads nothing).
  // Covered by the same "Ayşe okuma araçları" block (positive control, A→B, B→A, chat and fish-tur) and by
  // lib/asistan/alanSizinti.test.ts (forged reference in ses-ekran, other doctor's session → 404).
  // NOTYA-AYSE-ANALIZ-01 (2026-10-02): three more read tools — muayene_ara(terim, hasta_adi?),
  // muayeneleri_oku(adet | tarihler | tur, hasta_adi?), eksikler(hasta_adi?) — lib/asistan/muayeneAnaliz.ts. They take a
  // term, dates and a NAME, never an id. The patient is resolved by the same helper as hasta_alan (aracHastasi:
  // hastaninSozunuCoz(doktorId), or the open patient after hastaSahibiMi); the chart is dosyaPaketOnbellekli(doktorId).
  // eksikler also calls the branch's kohort function in process (lib/doktor/fisiltiHasta.ts → app/api/doktor/<rota>/
  // _kohort.ts, the function the kohort route itself calls; five branches whose engine file is read-only) with the
  // authenticated doctor's id and that ONE resolved patient id; every kohort function scopes its reads by the doctor
  // id it is given. No new route. Covered by the same
  // "Ayşe okuma araçları" block (the three tools are called with the victim's patient name: five "not found" results,
  // no chart read; positive control reads the doctor's own patient) and by lib/asistan/analizKabul.test.ts.
  'app/api/asistan/chat/route.ts': T,
  'app/api/asistan/learn/route.ts': T,
  'app/api/asistan/hasta-bul/route.ts': I('hastaninSozunuCoz(doktorId) searches only the doctor\'s patients; file via hastaDosyaPaketiniDerle(doktorId). Client-tool endpoint of the ElevenLabs path only; the single brain runs the same logic in process (lib/asistan/okumaAraclari.ts)'),
  'app/api/asistan/ses-eylem/route.ts': I('hastaninSozunuCoz / hastaSahibiMi; eylem_onerileri doctor_id; takvim randevular.eq(doktor_id) + patients.eq(doctor_id)'),
  'app/api/asistan/ses-profili-sayac/route.ts': I('NOTYA-SES-PROFILI-01 anonymous verdict counters; signed-in doctor required (pratikOturum + sadeceDoktor); stores daily totals only, no doctor id, no patient id, no audio/text'),
  'app/api/doktor/ses-profili/route.ts': I('NOTYA-SES-PROFILI-01 the doctor\'s own voice-profile row only; every read/write/delete .eq(doctor_id, doktorId) from pratikOturum + sadeceDoktor; accepts no patient or row id from the request'),
  'app/api/asistan/fish-ses/route.ts': I('any authenticated doctor; free-text body synthesized by Fish TTS, no Supabase read, no patient identifier ever touches this route'),
  'app/api/asistan/fish-stt/route.ts': I('any authenticated doctor; uploaded audio forwarded to Fish ASR; no patient id, no Supabase patient read'),
  'app/api/asistan/fish-tur/route.ts': I('ayseCevapla(doktorId from auth); asistanSessionId reused only when id + doctor_id match (404 otherwise); optional patientId enters only after hastaSahibiMi; optional audio is Fish ASR only (no patient id on the clip); spoken Evet / Hayır → sesliKarariUygula (session id + doctor_id, eylem_onerileri doctor_id, hastaSahibiMi before eylemOnayla); sesDevam read / cleared by session id + doctor_id; NOTYA-AYSE-ARAC-PARITE: the read tools the model may call inside ayseCevapla (hasta_bul, randevu_takvim) take text / a date only and run with doktorId from auth — cross-doctor cases for this route are in hasta-izolasyon.test.ts ("Ayşe okuma araçları")'),
  'app/api/asistan/signed-url/route.ts': I('voice-agent URL for the caller; NOTYA-TEK-BEYIN: optional patientId enters the signed token only after hastaSahibiMi(doktorId), optional asistanSessionId reused only when id + doctor_id match'),
  'app/api/asistan/ses-llm/v1/chat/completions/route.ts': T,
  'app/api/asistan/ses-llm/v1/route.ts': I('same handler as ses-llm/v1/chat/completions (lib/asistan/sesLlm.ts), covered there'),
  'app/api/asistan/ses-ekran/route.ts': T,
  'app/api/asistan/oturum-hasta/route.ts': T,
  'app/api/asistan/klinik-signed-url/route.ts': I('voice-agent URL for the caller; no patient read'),
  'app/api/asistan/ses-ogren/route.ts': I('NOTYA-OGRENME-03: canli sesli Ayse ogrenme kancasi — body yalniz serbest metin (doktor konusma turleri), patient_id/hasta tablosu yok; yazar doktor_hafiza/doktor_iliski, ikisi de doctor_id scoped'),
  'app/api/asistan/avukat-chat/route.ts': I('lawyer product; no patient data'),
  'app/api/asistan/avukat-learn/route.ts': I('lawyer product; no patient data'),
  'app/api/asistan/avukat-signed-url/route.ts': I('lawyer product; no patient data'),
  'app/api/asistan/mali-chat/route.ts': I('accountant product; no patient data'),
  'app/api/asistan/mali-signed-url/route.ts': I('accountant product; no patient data'),
  // ── Sağlığım portalı / intake (token = kimlik) ──
  'app/api/portal/hasta/[token]/route.ts': T,
  'app/api/portal/hasta/[token]/goruntu/route.ts': I('410 — patient cannot upload to belgeler; redirects to Mesajlar (no vault write)'),
  'app/api/portal/hasta/[token]/goruntu/[id]/route.ts': I('token unlock; jacket id+patient_id+doctor_id; portaldaGorunurMu else 404; vault download doctor-scoped'),
  'app/api/portal/hasta/[token]/mesajlar/route.ts': T,
  'app/api/portal/hasta/[token]/mesajlar/ek/[ekId]/route.ts': I('token → patient_id+doctor_id; mesajEkOku filters both; no foreign patient bytes'),
  'app/api/portal/hasta/[token]/randevu/route.ts': T,
  'app/api/randevu/eylem/route.ts': I('NOTYA-RANDEVU-V2 e-mail links: HMAC-signed token (PORTAL_TOKEN_SECRET) names one randevu id + one action; that row\'s own doktor_id + patient_id scope every further read/write (hastaIslem re-resolves id + doktor_id + patient_id); response carries time, doctor name and state only — no patient name, phone, e-mail or clinical field'),
  'app/api/portal/hasta/[token]/asi-karnesi/pdf/route.ts': T,
  'app/api/portal/hasta/[token]/dahiliye-anket/route.ts': I('token → (patient_id, doctor_id); every read/write scoped by both'),
  'app/api/portal/hasta/[token]/unlock/route.ts': I('PIN check for the token row only'),
  'app/api/intake/[token]/route.ts': I('token → form row; patient from that row (form was created after an ownership check); NOTYA-ILETISIM-01 / NOTYA-GELEN-BELGELER consent writes scoped by that row\'s patient_id AND doktor_id'),
  // ── Entegrasyon / cron (oturumsuz, sunucu içi) ──
  'app/api/entegrasyon/fhir/isle/route.ts': I('cron-secret gated; exports notes only of doctors enrolled in that institution'),
  'app/api/entegrasyon/hl7/al/route.ts': I('per-institution inbound key; patient mapping scoped by kurum_id'),
  'app/api/entegrasyon/yonetim/route.ts': I('ADMIN_EMAILS only'),
  'app/api/cron/randevu-v2/route.ts': I('cron-secret gated; NOTYA-RANDEVU-V2 jobs: each randevu_isleri row is re-resolved as randevular.id + the job\'s own doktor_id, the patient via hastaIletisimi(doktor_id, patient_id), mail leaves only from that doctor\'s own account, every write .eq(doktor_id)'),
  'app/api/cron/randevu-hatirlatma/route.ts': I('cron-secret gated; enqueues tomorrow\'s reminder into the booking owner\'s queue only when patients.id is re-found with doctor_id = the row\'s doktor_id; then (NOTYA-ILETISIM-04) the dispatcher sends from each item\'s own doctor\'s account — see iletisim-otomatik'),
  'app/api/cron/iletisim-otomatik/route.ts': I('cron-secret gated; NOTYA-ILETISIM-04 dispatcher (lib/iletisim/otomatikGonderim.ts): every queue item is re-read via iletisimHazirla with the item\'s own doctor_id (queue row, appointment and patient each resolved with doctor_id), sent only from that doctor\'s own connected account, every write .eq(doctor_id)'),
  'app/api/cron/kvkk-imha/route.ts': I('cron-secret gated retention job; no cross-doctor read path (NOTYA-GELEN-BELGELER: deletes unfiled inbox rows + their files by age only, returns counts)'),
  'app/api/cron/meslektas-rutin/route.ts': I('cron-secret gated; 30-day usage purge + per-doctor rutinTuret on that doctor_id only; no patient ids'),
  'app/api/cron/meslektas-onbellek/route.ts': I('cron-secret gated; builds hasta_dosya_onbellek per randevu row doctor_id+patient_id; no cross-doctor key'),
  // ── NOTYA-UZ-MUAYENE-01: routes of a country build (*.ulke.*). Not part of a Türkiye build. Their cross-doctor
  //    tests (positive control, A→B, B→A, "every query carries the doctor") live with the country pack, on its own
  //    stand-in database: countries/uz/uygulama/uygulama.test.ts and countries/uz/uygulama/muayene.test.ts. ──
  'app/api/ulke/hastalar/route.ulke.ts': I('doctor = the authenticated account only; the body cannot name a doctor and no patient id is accepted; list reads patients + hasta_ulke_bilgisi by doctor_id'),
  'app/api/ulke/hasta/route.ulke.ts': I('hastaGetir: patient id from the address matched with doctor_id in the same query BEFORE anything else is read; foreign id → 404, identical to a missing id'),
  'app/api/ulke/bugun/route.ulke.ts': I('takes no id from the request; sessions, notes and patient names are each read by doctor_id (lib/ulke/uygulama/muayeneler.ts)'),
  'app/api/ulke/muayene/route.ulke.ts': I('muayeneKaydet: patient id proven the caller\'s (hastaGetir) and the recording path proven to lie in the caller\'s own folder BEFORE storage is read; muayeneGetir: visit id + doctor_id in one query, foreign id → 404'),
  'app/api/ulke/not/route.ulke.ts': I('notYaz: visit id + doctor_id in one query (muayeneGetir), patient re-read by doctor_id; notGetir / notKaydet: note id + doctor_id in one query, every later read or write carries doctor_id; foreign id → 404'),
  'app/api/ulke/not/yeniden-yaz/route.ulke.ts': I('notYenidenYaz: note id + doctor_id in one query; the second draft is written to not_dil_kaydi by note_id AND doctor_id; target language is not taken from the request'),
  'app/api/ulke/not/onayla/route.ulke.ts': I('notOnayla: note id + doctor_id in one query; the approving update carries id, doctor_id and approved_at IS NULL in the same statement; foreign id → 404'),
  // NOTYA-UZ-RANDEVU-01: appointments of a country build. Tested in countries/uz/uygulama/randevu.test.ts (A→B and B→A).
  'app/api/ulke/calisma-duzeni/route.ulke.ts': I('takes no id from the request; the working pattern is read and written by the authenticated account\'s own id; no patient data'),
  'app/api/ulke/randevu/route.ulke.ts': I('randevuOlustur: patient id proven the caller\'s (hastaGetir) before anything is written; randevuGetir / randevuTasi / randevuDurumDegistir: appointment id + doctor_id in the same statement, the patient re-read by doctor_id; foreign id → 404, identical to a missing id'),
  'app/api/ulke/randevular/route.ulke.ts': I('the list is read by doctor_id; a patient id from the address is proven the caller\'s (hastaGetir) before anything is read with it; patient names are read by doctor_id AND patient id'),
}
