/** Tools the dahiliye-locked prompt may call (W0.1). Keep in sync with /api/doktor/dahiliye adımları. */
export const DAHILIYE_TOOLS = [
  { name: 'dahiliye.serit', description: 'Bugünkü vizit şeridi: KB / HbA1c Δ / LDL / eGFR / gecikmiş görevler / plan taslağı' },
  { name: 'dahiliye.kb', description: 'Ofis KB kaydet → Uzlaşı 2025 evre taslağı + HT planı' },
  { name: 'dahiliye.dm', description: 'DM kartı: HbA1c trend, yıllık tarama görevleri, sınıf önerisi' },
  { name: 'dahiliye.lipid', description: 'Lipid kartı: LDL hedef (hekim), statin/ALT izlem' },
  { name: 'dahiliye.kvr', description: 'KVR: kural kovası (ASKVH/DM+TOD/KBH) → SCORE2 / SCORE2-Diabetes / SCORE2-OP (yalnız ONAYLI motor) → LDL hedef + statin açığı' },
  { name: 'dahiliye.ckd', description: 'KDIGO G×A ısı haritası, plan, nefro sevk paketi' },
  { name: 'dahiliye.evkayit', description: 'Ev KB/glukoz/kilo kaydı ve özeti (beyaz önlük / maskeli)' },
  { name: 'dahiliye.ilacizlem', description: 'İlaç izlem takvimi: hasta_ilaclar → lab izlem görevleri' },
  { name: 'dahiliye.kilit', description: 'Hekim kilidi: kart alanını kilitle (tanı/evre/hedef/kategori)' },
  { name: 'dahiliye.sgkrapor', description: 'SGK ilaç kullanım raporu taslağı (HT/DM/statin/DOAK) kartlardan; hekim kilitler, Medula e-imza ile' },
  { name: 'dahiliye.dmdongu', description: 'DM kapalı döngü: FIB-4, ayak foto görevi, SGLT2/GLP-1 kardiyo-renal bayrak, hipoglisemi riski' },
  { name: 'dahiliye.anemi', description: 'Anemi merdiveni: morfoloji → sonraki test → olası neden (onaylı lab)' },
  { name: 'dahiliye.obezite', description: 'VKİ + TEMD basamakları, farmakoterapi sınıfı, bariatrik değerlendirme sevki, gerekçe metni' },
  { name: 'dahiliye.tarama', description: 'KETEM kolon/meme/serviks due; GGK pozitif → gastro sevk' },
  { name: 'dahiliye.asi', description: 'Erişkin aşı takvimi (HYP): grip, pnömokok, zona, Td, HBV, COVID-19' },
  { name: 'dahiliye.htpanel', description: 'HT başlangıç paneli istemi + 14 gün sonuçlanmayan lab takibi' },
  { name: 'dahiliye.anketsoap', description: 'Portal ön anketini bugünkü muayenenin Subjektif bölümüne ekle' },
  { name: 'dahiliye.hf', description: 'KY: EF kategorisi, GDMT 4 sütun kontrol listesi, kardiyoloji sevk tetikleyicileri' },
  { name: 'dahiliye.antikoagulan', description: 'Antikoagülan: INR + TTR, DOAK uygunluk (KrKl/yaş/kilo), HAS-BLED maddeleri kontrol listesi' },
  { name: 'dahiliye.pulm', description: 'KOAH/astım: spirometri, GOLD + ABE, astım kontrolü, inhaler sınıfı + teknik' },
  { name: 'dahiliye.gi', description: 'GÖRH, İBS Roma IV, MASLD FIB-4, H. pylori eradikasyon + kontrol testi zamanı' },
  { name: 'dahiliye.ekg', description: 'EKG 1-tap Türkçe rapor; acil bulgu kırmızı bayrak kapısı' },
  { name: 'dahiliye.nodul', description: 'Tiroid nodül TI-RADS tarzı tarif, izlem görevi, endokrin sevki' },
  { name: 'dahiliye.ramazan', description: 'Ramazan DM/HT risk kademesi, ilaç zamanlaması (doz yok), hasta yaprağı' },
  { name: 'dahiliye.checkup', description: 'Check-up paket defteri (kendi ödemeli) + birleşik rapor' },
  { name: 'dahiliye.kohort', description: 'Kronik kohort paneli: bayraklı hastalar + klinik değer içermeyen hatırlatma mesajı' },
  { name: 'dahiliye.nudge', description: 'Bakım kalitesi: KB ölçüm tekniği, FRAIL, düşme, PHQ-2 taramaları' },
  { name: 'dahiliye.polifarmasi_karar', description: '≥65 polifarmasi (STOPP/START v3 esinli): öneri başına hekim kararı; engelleyici öneride override gerekçesi ≥15 karakter; ilaç asla otomatik kesilmez' },
  { name: 'dahiliye.hedefkart', description: 'Hasta hedef kartı (yalnız kilitli HT/DM/LDL/KVR hedefleri) + Türkçe eğitim yaprakları; hekim onayıyla yazdırılır' },
  { name: 'dahiliye.sigara', description: 'Sigara bırakma: paket-yıl, HSI, değişim evresi, 5A, ALO 171, farmakoterapi sınıfı (doz yok), izlem görevleri' },
  { name: 'dahiliye.vitamin', description: 'D vitamini / B12 eksikliği (onaylı lab): sonraki test, replasman sınıfı (doz hekim), SGK vitd/b12 şablonu' },
  { name: 'dahiliye.gut', description: 'Gut / ürik asit: atak sınıfları, ULT endikasyonu ve hedef, diyet danışmanlığı, sevk' },
  { name: 'dahiliye.osteo', description: 'Osteoporoz: DXA T-skoru (belge/hekim), sınıf, risk bayrakları (FRAX hesaplanmaz), tedavi sınıfı, DXA aralığı' },
  { name: 'dahiliye.sevk', description: 'Sevk oluştur (son onaylı panel eklenir)' },
] as const
export type DahiliyeToolName = (typeof DAHILIYE_TOOLS)[number]['name']
