export const DILEKCE_TURLERI: Record<string,{baslik:string;mahkeme_turu:string;kanun_dayanagi:string;zorunlu_alanlar:string[];sablon:string}> = {
  itiraz_dilekce:{baslik:'Itiraz Dilekcesi',mahkeme_turu:'Asliye Hukuk Mahkemesi',kanun_dayanagi:'HMK 346',zorunlu_alanlar:['muvekkil_adi','konu','itiraz_gerekce'],sablon:'{{mahkeme}} BASKANLIGINA | Davaci: {{muvekkil_adi}} | Konu: {{konu}} | ACIKLAMA: {{itiraz_gerekce}} | HUKUKI DAYANAK: HMK 346 | SONUC: Itirazimizin kabulunu arz ederiz.'},
  dava_acilis:{baslik:'Dava Acilis Dilekcesi',mahkeme_turu:'Asliye Hukuk Mahkemesi',kanun_dayanagi:'HMK 119',zorunlu_alanlar:['muvekkil_adi','davali_adi','dava_konusu','talep_miktari'],sablon:'{{mahkeme}} BASKANLIGINA | Davaci: {{muvekkil_adi}} | Davali: {{davali_adi}} | Talep: {{talep_miktari}} TL | ACIKLAMA: {{dava_konusu}} | HUKUKI DAYANAK: HMK 119 | SONUC: Tahsiline karar verilmesini arz ederiz.'},
  nafaka_talebi:{baslik:'Nafaka Talebi',mahkeme_turu:'Aile Mahkemesi',kanun_dayanagi:'TMK 182',zorunlu_alanlar:['muvekkil_adi','karsi_taraf','nafaka_miktari'],sablon:'{{mahkeme}} BASKANLIGINA | Davaci: {{muvekkil_adi}} | Davali: {{karsi_taraf}} | Konu: Nafaka Talebi | HUKUKI DAYANAK: TMK 182 | SONUC: Aylik {{nafaka_miktari}} TL nafakaya hukmedilmesini arz ederiz.'},
  bosanma_davasi:{baslik:'Bosanma Davasi',mahkeme_turu:'Aile Mahkemesi',kanun_dayanagi:'TMK 166',zorunlu_alanlar:['muvekkil_adi','es_adi','evlilik_tarihi','bosanma_gerekce'],sablon:'{{mahkeme}} BASKANLIGINA | Davaci: {{muvekkil_adi}} | Davali: {{es_adi}} | Evlilik: {{evlilik_tarihi}} | ACIKLAMA: {{bosanma_gerekce}} | HUKUKI DAYANAK: TMK 166 | SONUC: Bosanmaya karar verilmesini arz ederiz.'},
  is_akdi_feshi:{baslik:'Haksiz Fesih Dilekcesi',mahkeme_turu:'Is Mahkemesi',kanun_dayanagi:'Is K. 17-18',zorunlu_alanlar:['muvekkil_adi','fesih_tarihi','fesih_gerekce'],sablon:'{{mahkeme}} BASKANLIGINA | Davaci: {{muvekkil_adi}} | Fesih: {{fesih_tarihi}} | ACIKLAMA: {{fesih_gerekce}} | HUKUKI DAYANAK: Is K. 17-18-19 | SONUC: Tazminat tahsiline karar verilmesini arz ederiz.'},
  icra_itiraz:{baslik:'Icra Itiraz',mahkeme_turu:'Icra Hukuk Mahkemesi',kanun_dayanagi:'IIK 62',zorunlu_alanlar:['muvekkil_adi','alacakli_adi','takip_no','itiraz_gerekce'],sablon:'{{mahkeme}} BASKANLIGINA | Borclu: {{muvekkil_adi}} | Alacakli: {{alacakli_adi}} | Takip: {{takip_no}} | ACIKLAMA: {{itiraz_gerekce}} | HUKUKI DAYANAK: IIK 62 | SONUC: Itirazimizin kabulune karar verilmesini arz ederiz.'},
  idari_itiraz:{baslik:'Idari Islem Iptali',mahkeme_turu:'Idare Mahkemesi',kanun_dayanagi:'IYUK 7',zorunlu_alanlar:['muvekkil_adi','idare_adi','islem_tarihi','iptal_gerekce'],sablon:'{{mahkeme}} BASKANLIGINA | Davaci: {{muvekkil_adi}} | Davali: {{idare_adi}} | Islem: {{islem_tarihi}} | ACIKLAMA: {{iptal_gerekce}} | HUKUKI DAYANAK: IYUK 7 | SONUC: Islemin iptaline karar verilmesini arz ederiz.'},
  tespit_talebi:{baslik:'Tespit Dilekcesi',mahkeme_turu:'Asliye Hukuk Mahkemesi',kanun_dayanagi:'HMK 106',zorunlu_alanlar:['muvekkil_adi','tespit_konusu'],sablon:'{{mahkeme}} BASKANLIGINA | Davaci: {{muvekkil_adi}} | Konu: {{tespit_konusu}} | HUKUKI DAYANAK: HMK 106 | SONUC: Tespitine karar verilmesini arz ederiz.'},
  kvkk_veri_ihlali_bildirimi:{baslik:'KVKK Veri Ihlali Bildirimi',mahkeme_turu:'Kisisel Verileri Koruma Kurumu',kanun_dayanagi:'KVKK 12, Kurul Karari 2019/10',zorunlu_alanlar:['veri_sorumlusu_adi','ihlal_tarihi','etkilenen_kisi_sayisi','ihlal_konusu_veri','alinan_onlemler'],sablon:'KISISEL VERILERI KORUMA KURULU BASKANLIGINA | Veri Sorumlusu: {{veri_sorumlusu_adi}} | Ihlal Tarihi: {{ihlal_tarihi}} | Etkilenen Kisi Sayisi: {{etkilenen_kisi_sayisi}} | ACIKLAMA: {{ihlal_konusu_veri}} konusunda veri ihlali tespit edilmistir. | ALINAN ONLEMLER: {{alinan_onlemler}} | HUKUKI DAYANAK: KVKK m.12, Kurulun 2019/10 sayili karari geregi ihlalin ogrenilmesinden itibaren en gec 72 saat icinde bildirim yapilmaktadir. | SONUC: Bilgilerinize arz ederiz.'},
  kvkk_kurula_sikayet:{baslik:'KVKK Kurula Sikayet Basvurusu',mahkeme_turu:'Kisisel Verileri Koruma Kurumu',kanun_dayanagi:'KVKK 13-14',zorunlu_alanlar:['basvuran_adi','veri_sorumlusu_adi','onceki_basvuru_tarihi','sikayet_konusu'],sablon:'KISISEL VERILERI KORUMA KURULU BASKANLIGINA | Basvuran: {{basvuran_adi}} | Sikayet Edilen (Veri Sorumlusu): {{veri_sorumlusu_adi}} | Veri Sorumlusuna Onceki Basvuru Tarihi: {{onceki_basvuru_tarihi}} | ACIKLAMA: {{sikayet_konusu}} | HUKUKI DAYANAK: KVKK m.13-14 -- veri sorumlusuna yapilan basvurunun reddedilmesi, cevabin yetersiz bulunmasi veya suresinde cevap verilmemesi halinde, basvuru sonucunun ogrenilmesinden itibaren 30 gun ve her halde basvuru tarihinden itibaren 60 gun icinde Kurula sikayet hakki dogar. | SONUC: Sikayetimizin kabulu ile geregi kararin verilmesini arz ederiz.'},
}

export function buildDilekceSystemPrompt(turId:string,avukat:{name:string;baro:string},muvekkil:Record<string,unknown>|null):string{
  const tur=DILEKCE_TURLERI[turId]
  if(!tur) return 'Gecersiz tur'
  const muvStr=muvekkil?'Muvekkil: '+JSON.stringify(muvekkil):''
  return 'Sen deneyimli bir Turk avukatinin yazisma asistanisin. '+tur.baslik+' olusturacaksin. Mahkeme: '+tur.mahkeme_turu+'. Kanun: '+tur.kanun_dayanagi+'. Avukat: '+avukat.name+' Baro: '+avukat.baro+'. '+muvStr+' Sablon referans: '+tur.sablon+' Yaniti SADECE su JSON formatinda ver (baska hicbir sey yazma): {"dilekce_metni":"tam dilekce metni","eksik_bilgiler":["varsa"],"uyarilar":["varsa"]}'
}
